# Harmony best - scib_sim1

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR

In [1]:
import gc
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import harmonypy as hm
import numpy as np
import pandas as pd
import scanpy as sc

from scib.metrics.metrics import metrics

In [2]:
DATASET_NAME = 'scib_sim1'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'Batch'
LABEL_KEY = 'Group'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_PCS = 50
N_NEIGHBORS = 15
N_TOP_HVG = 2000

EMBED_KEY = "X_harmony"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "harmony_metric_batch"
METRIC_LABEL_KEY = "harmony_metric_label"

assert DATASET_NAME == 'scib_sim1'
assert BATCH_KEY == 'Batch'
assert LABEL_KEY == 'Group'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
    },
    name="configuration",
)

dataset                                              scib_sim1
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                Batch
label_key                                                Group
metrics      [BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR]
seeds                           [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Name: configuration, dtype: object

In [3]:
def validate_dataset_contents():
    adata_backed = ad.read_h5ad(DATA_PATH, backed="r")
    try:
        required_keys = (BATCH_KEY, LABEL_KEY)
        missing_keys = [
            key for key in required_keys if key not in adata_backed.obs
        ]
        if missing_keys:
            raise ValueError(
                f"Missing obs keys {missing_keys}. "
                f"Available keys: {list(adata_backed.obs.columns)}"
            )

        obs = adata_backed.obs[[BATCH_KEY, LABEL_KEY]].copy()
        pseudotime = None
        if "TRAJ" in SELECTED_METRICS:
            if "dpt_pseudotime" not in adata_backed.obs:
                raise ValueError(
                    "TRAJ requires adata.obs['dpt_pseudotime']."
                )
            pseudotime = adata_backed.obs["dpt_pseudotime"].copy()

        n_obs = int(adata_backed.n_obs)
        n_vars = int(adata_backed.n_vars)
    finally:
        adata_backed.file.close()

    if obs.isna().any().any():
        raise ValueError(
            "Missing batch/label values: "
            f"{obs.isna().sum().to_dict()}"
        )

    n_batches = int(obs[BATCH_KEY].nunique())
    n_labels = int(obs[LABEL_KEY].nunique())
    if n_batches < 2:
        raise ValueError(
            f"Batch metrics require at least 2 batches; found {n_batches}."
        )

    batch_coverage = obs.groupby(
        LABEL_KEY,
        observed=True,
    )[BATCH_KEY].nunique()
    label_counts = obs.groupby(LABEL_KEY, observed=True).size()

    if "TRAJ" in SELECTED_METRICS:
        finite_pseudotime = pseudotime.dropna()
        if (
            len(finite_pseudotime) < 2
            or finite_pseudotime.nunique() < 2
        ):
            raise ValueError(
                "TRAJ requires at least 2 usable pseudotime values."
            )

    if "ISOLISI" in SELECTED_METRICS:
        min_batch_coverage = int(batch_coverage.min())
        if min_batch_coverage >= n_batches:
            raise ValueError(
                "ISOLISI is enabled, but every label appears in all batches."
            )

    eligible_cpcr_labels = [
        str(label)
        for label in label_counts.index
        if int(label_counts.loc[label]) >= 100
        and int(batch_coverage.loc[label]) >= 2
    ]
    if "CPCR" in SELECTED_METRICS and not eligible_cpcr_labels:
        raise ValueError(
            "CPCR requires a label with at least 100 cells across "
            "at least 2 batches."
        )

    return {
        "n_obs": n_obs,
        "n_vars": n_vars,
        "n_batches": n_batches,
        "n_labels": n_labels,
        "cpcr_eligible_labels": len(eligible_cpcr_labels),
    }


validate_dataset_contents()

{'n_obs': 12097,
 'n_vars': 9979,
 'n_batches': 6,
 'n_labels': 7,
 'cpcr_eligible_labels': 7}

In [4]:
OPTUNA_STUDY_NAME = 'harmony_scib_sim1_joint_expanded_metrics_scgraphm_v2'
OPTUNA_BEST_TRIAL = 235
OPTUNA_BEST_VALUE = 0.830879655778088
OPTUNA_BEST_PARAMS = {'theta': 3.783617747447166, 'sigma': 0.13207747589467475, 'lamb_mode': 'auto', 'tau': 1.0453750899155032, 'nclust': 177}

if OPTUNA_BEST_PARAMS["lamb_mode"] == "auto":
    resolved_lamb = -1
else:
    resolved_lamb = OPTUNA_BEST_PARAMS["lamb"]

HARMONY_BEST_ARGS = {
    "theta": OPTUNA_BEST_PARAMS["theta"],
    "lamb": resolved_lamb,
    "sigma": OPTUNA_BEST_PARAMS["sigma"],
    "nclust": OPTUNA_BEST_PARAMS["nclust"],
    "tau": OPTUNA_BEST_PARAMS["tau"],
    "block_size": 0.05,
    "max_iter_harmony": 10,
    "max_iter_kmeans": 20,
    "epsilon_cluster": 1e-5,
    "epsilon_harmony": 1e-4,
    "alpha": 0.2,
}


def run_harmony_best(adata, seed):
    adata_int = adata.copy()

    if "highly_variable" in adata_int.var:
        adata_int = adata_int[:, adata_int.var["highly_variable"]].copy()
    else:
        sc.pp.highly_variable_genes(
            adata_int,
            flavor="seurat",
            n_top_genes=N_TOP_HVG,
        )
        adata_int = adata_int[:, adata_int.var["highly_variable"]].copy()

    sc.tl.pca(
        adata_int,
        n_comps=N_PCS,
        svd_solver="arpack",
    )
    x_pca = np.asarray(adata_int.obsm["X_pca"], dtype=np.float32)

    harmony_result = hm.run_harmony(
        x_pca,
        adata_int.obs,
        BATCH_KEY,
        **HARMONY_BEST_ARGS,
        verbose=False,
        random_state=seed,
        device="cpu",
    )

    x_harmony = np.asarray(harmony_result.Z_corr)
    if (
        x_harmony.shape[0] != adata_int.n_obs
        and x_harmony.shape[1] == adata_int.n_obs
    ):
        x_harmony = x_harmony.T
    if x_harmony.shape[0] != adata_int.n_obs:
        raise ValueError(
            f"Harmony output shape {x_harmony.shape} is incompatible "
            f"with n_obs={adata_int.n_obs}."
        )
    if not np.all(np.isfinite(x_harmony)):
        raise ValueError("Harmony produced NaN or Inf in X_harmony.")

    adata_int.obsm[EMBED_KEY] = x_harmony
    return adata_int


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **HARMONY_BEST_ARGS,
    },
    name="best_setting",
)

study               harmony_scib_sim1_joint_expanded_metrics_scgra...
best_trial                                                        235
best_value                                                    0.83088
theta                                                        3.783618
lamb                                                               -1
sigma                                                        0.132077
nclust                                                            177
tau                                                          1.045375
block_size                                                       0.05
max_iter_harmony                                                   10
max_iter_kmeans                                                    20
epsilon_cluster                                               0.00001
epsilon_harmony                                                0.0001
alpha                                                             0.2
Name: best_setting, dtype: object

In [5]:
def metric_value(metric_series, key):
    if key not in metric_series.index:
        raise KeyError(
            f"Metric {key} not found. "
            f"Available metrics: {list(metric_series.index)}"
        )

    value = metric_series[key]
    if isinstance(value, (list, tuple, np.ndarray)):
        values = np.asarray(value, dtype=float)
        if values.size == 0 or not np.all(np.isfinite(values)):
            raise ValueError(
                f"Metric {key} returned non-finite values: {values}"
            )
        return float(np.mean(values))

    value = float(value)
    if not np.isfinite(value):
        raise ValueError(
            f"Metric {key} returned a non-finite value: {value}"
        )
    return value


def compute_joint_metrics(adata_raw, adata_int):
    sc.pp.neighbors(
        adata_int,
        use_rep=EMBED_KEY,
        n_neighbors=N_NEIGHBORS,
        random_state=0,
    )

    metric_key_map = {
        METRIC_BATCH_KEY: BATCH_KEY,
        METRIC_LABEL_KEY: LABEL_KEY,
    }
    for adata_name, adata_obj in (
        ("adata_raw", adata_raw),
        ("adata_int", adata_int),
    ):
        existing_aliases = [
            alias for alias in metric_key_map if alias in adata_obj.obs
        ]
        if existing_aliases:
            raise ValueError(
                f"Reserved metric obs keys already exist in {adata_name}: "
                f"{existing_aliases}"
            )
        for alias, source_key in metric_key_map.items():
            adata_obj.obs[alias] = adata_obj.obs[source_key].copy()

    metric_df = metrics(
        adata=adata_raw,
        adata_int=adata_int,
        batch_key=METRIC_BATCH_KEY,
        label_key=METRIC_LABEL_KEY,
        embed=EMBED_KEY,
        cluster_key=CLUSTER_KEY,
        verbose=False,
        bami_="BAMI" in SELECTED_METRICS,
        casw_="CASW" in SELECTED_METRICS,
        scgraphm_="SCGRAPHM" in SELECTED_METRICS,
        traj_="TRAJ" in SELECTED_METRICS,
        isolisi_="ISOLISI" in SELECTED_METRICS,
        bras_="BRAS" in SELECTED_METRICS,
        kbet_="KBET" in SELECTED_METRICS,
        cpcr_="CPCR" in SELECTED_METRICS,
    )
    metric_series = metric_df.iloc[:, 0]

    result = {
        key: metric_value(metric_series, key)
        for key in SELECTED_METRICS
    }
    bio_score = float(
        np.mean([result[key] for key in SELECTED_BIO_METRICS])
    )
    batch_score = float(
        np.mean([result[key] for key in SELECTED_BATCH_METRICS])
    )
    joint_score = float(0.6 * bio_score + 0.4 * batch_score)

    if not np.all(np.isfinite([bio_score, batch_score, joint_score])):
        raise ValueError(
            "Aggregation produced a non-finite score: "
            f"bio={bio_score}, batch={batch_score}, "
            f"joint={joint_score}"
        )

    result["bio_score"] = bio_score
    result["batch_score"] = batch_score
    result["joint_score"] = joint_score
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_harmony_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

2026-07-23 10:56:18,357 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 10:56:18,731 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:00,  9.80it/s]

 33%|███▎      | 2/6 [00:00<00:00,  8.30it/s]

 50%|█████     | 3/6 [00:00<00:00,  8.79it/s]

 83%|████████▎ | 5/6 [00:00<00:00, 10.22it/s]

100%|██████████| 6/6 [00:00<00:00, 10.17it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9902457514196407

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9801874172827572

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9800881749097491

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9798916354700288

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9700692727002725

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9697441509765099

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9695615487531285

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9484685405722206

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-07-23 10:57:03,982:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

seed           0.000000
BAMI           0.994917
CASW           0.687632
SCGRAPHM       0.979210
ISOLISI        1.000000
BRAS           0.926793
KBET           0.260556
CPCR           0.924747
bio_score      0.915440
batch_score    0.704032
joint_score    0.830877
dtype: float64

===== seed 1 =====

2026-07-23 10:57:22,284 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 10:57:22,881 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:00,  9.74it/s]

 33%|███▎      | 2/6 [00:00<00:00,  9.18it/s]

 50%|█████     | 3/6 [00:00<00:00,  8.24it/s]

 83%|████████▎ | 5/6 [00:00<00:00, 11.75it/s]

100%|██████████| 6/6 [00:00<00:00, 11.43it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9902457514196407

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9801874172827572

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9799405297909853

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9702583341595232

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9700692727002725

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9698826092426465

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9694668216047599

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9339436018737804

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           1.000000
BAMI           0.994917
CASW           0.687464
SCGRAPHM       0.970957
ISOLISI        1.000000
BRAS           0.926805
KBET           0.260268
CPCR           0.924725
bio_score      0.913334
batch_score    0.703933
joint_score    0.829574
dtype: float64

===== seed 2 =====

2026-07-23 10:58:05,206 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 10:58:05,552 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 33%|███▎      | 2/6 [00:00<00:00, 10.09it/s]

 67%|██████▋   | 4/6 [00:00<00:00, 10.10it/s]

100%|██████████| 6/6 [00:00<00:00, 12.54it/s]

100%|██████████| 6/6 [00:00<00:00, 11.75it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9902457514196407

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9803593480003091

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9801874172827572

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9798916354700288

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9703578478450904

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9697937710252296

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.969475662721174

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9300458224145242

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           2.000000
BAMI           0.994917
CASW           0.687651
SCGRAPHM       0.970489
ISOLISI        1.000000
BRAS           0.926716
KBET           0.260722
CPCR           0.924728
bio_score      0.913264
batch_score    0.704055
joint_score    0.829581
dtype: float64

===== seed 3 =====

2026-07-23 10:58:48,471 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 10:58:48,991 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 33%|███▎      | 2/6 [00:00<00:00,  9.59it/s]

 50%|█████     | 3/6 [00:00<00:00,  8.76it/s]

 83%|████████▎ | 5/6 [00:00<00:00, 11.94it/s]

100%|██████████| 6/6 [00:00<00:00, 11.62it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9902457514196407

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9901722775004832

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9800387984722145

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.979794321781574

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.970072032830676

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.969790158856687

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9695162514566972

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9307602063798468

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           3.000000
BAMI           0.994917
CASW           0.687520
SCGRAPHM       0.969022
ISOLISI        1.000000
BRAS           0.926771
KBET           0.260062
CPCR           0.924707
bio_score      0.912865
batch_score    0.703847
joint_score    0.829257
dtype: float64

===== seed 4 =====

2026-07-23 10:59:27,547 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 10:59:28,569 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:00,  9.84it/s]

 33%|███▎      | 2/6 [00:00<00:00,  9.20it/s]

 50%|█████     | 3/6 [00:00<00:00,  8.32it/s]

 83%|████████▎ | 5/6 [00:00<00:00, 11.73it/s]

100%|██████████| 6/6 [00:00<00:00, 11.29it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9902457514196407

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9803593480003091

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.980259431020205

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9798916354700288

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9702605085834012

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9700252885965291

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9695162514566972

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9293951626155315

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           4.000000
BAMI           0.994917
CASW           0.687611
SCGRAPHM       0.970740
ISOLISI        1.000000
BRAS           0.926733
KBET           0.260704
CPCR           0.924719
bio_score      0.913317
batch_score    0.704052
joint_score    0.829611
dtype: float64

===== seed 5 =====

2026-07-23 11:00:08,905 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:00:09,447 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 33%|███▎      | 2/6 [00:00<00:00,  9.42it/s]

 50%|█████     | 3/6 [00:00<00:00,  8.60it/s]

 83%|████████▎ | 5/6 [00:00<00:00, 11.79it/s]

100%|██████████| 6/6 [00:00<00:00, 11.51it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9902457514196407

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9801107903552779

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9800615684280549

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9797459004214286

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.969923587233458

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9696914090965496

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9694137414283326

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9306192787386295

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           5.000000
BAMI           0.994917
CASW           0.687740
SCGRAPHM       0.977000
ISOLISI        1.000000
BRAS           0.926806
KBET           0.260539
CPCR           0.924781
bio_score      0.914914
batch_score    0.704042
joint_score    0.830565
dtype: float64

===== seed 6 =====

2026-07-23 11:01:08,823 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:01:09,338 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 33%|███▎      | 2/6 [00:00<00:00, 10.05it/s]

 67%|██████▋   | 4/6 [00:00<00:00, 10.65it/s]

100%|██████████| 6/6 [00:00<00:00, 13.05it/s]

100%|██████████| 6/6 [00:00<00:00, 12.19it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9901722775004832

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9901722775004832

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9901722775004832

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.97030800685292

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9700252885965291

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9699322434646288

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9695658481809944

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9327137552186883

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           6.000000
BAMI           0.994917
CASW           0.687651
SCGRAPHM       0.971945
ISOLISI        1.000000
BRAS           0.926715
KBET           0.260021
CPCR           0.924727
bio_score      0.913628
batch_score    0.703821
joint_score    0.829705
dtype: float64

===== seed 7 =====

2026-07-23 11:01:46,531 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:01:47,038 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 33%|███▎      | 2/6 [00:00<00:00, 12.66it/s]

 67%|██████▋   | 4/6 [00:00<00:00, 10.91it/s]

100%|██████████| 6/6 [00:00<00:00, 13.39it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9902457514196407

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9902457514196407

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9801107903552779

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9703578478450904

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9702157955096711

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9698435591915785

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9696609195260815

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9334437240672306

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           7.000000
BAMI           0.994917
CASW           0.687606
SCGRAPHM       0.971004
ISOLISI        1.000000
BRAS           0.926783
KBET           0.260268
CPCR           0.924748
bio_score      0.913382
batch_score    0.703933
joint_score    0.829602
dtype: float64

===== seed 8 =====

2026-07-23 11:02:24,558 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:02:24,803 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 33%|███▎      | 2/6 [00:00<00:00, 11.88it/s]

 67%|██████▋   | 4/6 [00:00<00:00, 10.19it/s]

100%|██████████| 6/6 [00:00<00:00, 12.55it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9902457514196407

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9902457514196407

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9902457514196407

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9798662777217284

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9701189260332946

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9698397836147691

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9694710938732417

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9302940864032356

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           8.000000
BAMI           0.994917
CASW           0.687664
SCGRAPHM       0.971065
ISOLISI        1.000000
BRAS           0.926765
KBET           0.260300
CPCR           0.924751
bio_score      0.913411
batch_score    0.703939
joint_score    0.829622
dtype: float64

===== seed 9 =====

2026-07-23 11:03:04,463 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:03:04,712 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:373: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common_type = np.find_common_type(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/algorithms.py:522: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  common = np.find_common_type([values.dtype, comps_array.dtype], [])
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Chunk 12049 does not have enough neighbors. Skipping...
Chunk 12050 does not have enough neighbors. Skipping...
Chunk 12051 does not have enough neighbors. Skipping...
Chunk 12052 does not have enough neighbors. Skipping...
Chunk 12053 does not have enough neighbors. Skipping...
Chunk 12054 does not have enough neighbors. Skipping...
Chunk 12055 does not have enough neighbors. Skipping...
Chunk 12056 does not have enough neighbors. Skipping...
Chunk 12057 does not have enough neighbors. Skipping...
Chunk 12058 does not have enough neighbors. Skipping...
Chunk 12059 does not have enough neighbors. Skipping...
Chunk 12060 does not have enough neighbors. Skipping...
Chunk 12061 does not have enough neighbors. Skipping...
Chunk 12062 does not have enough neighbors. Skipping...
Chunk 12063 does not have enough neighbors. Skipping...
Chunk 12064 does not have enough neighbors. Skipping...
Chunk 12065 does not have enough neighbors. Skipping...
Chunk 12066 does not have enough neighbors. Skipping...
Chunk 12067 does not have enough neighbors. Skipping...
Chunk 12068 does not have enough neighbors. Skipping...
Chunk 12069 does not have enough neighbors. Skipping...
Chunk 12070 does not have enough neighbors. Skipping...
Chunk 12071 does not have enough neighbors. Skipping...
Chunk 12072 does not have enough neighbors. Skipping...
Chunk 12073 does not have enough neighbors. Skipping...
Chunk 12074 does not have enough neighbors. Skipping...
Chunk 12075 does not have enough neighbors. Skipping...
Chunk 12076 does not have enough neighbors. Skipping...
Chunk 12077 does not have enough neighbors. Skipping...
Chunk 12078 does not have enough neighbors. Skipping...
Chunk 12079 does not have enough neighbors. Skipping...
Chunk 12080 does not have enough neighbors. Skipping...
Chunk 12081 does not have enough neighbors. Skipping...
Chunk 12082 does not have enough neighbors. Skipping...
Chunk 12083 does not have enough neighbors. Skipping...
Chunk 12084 does not have enough neighbors. Skipping...
Chunk 12085 does not have enough neighbors. Skipping...
Chunk 12086 does not have enough neighbors. Skipping...
Chunk 12087 does not have enough neighbors. Skipping...
Chunk 12088 does not have enough neighbors. Skipping...
Chunk 12089 does not have enough neighbors. Skipping...
Chunk 12090 does not have enough neighbors. Skipping...
Chunk 12091 does not have enough neighbors. Skipping...
Chunk 12092 does not have enough neighbors. Skipping...
Chunk 12093 does not have enough neighbors. Skipping...
Chunk 12094 does not have enough neighbors. Skipping...
Chunk 12095 does not have enough neighbors. Skipping...
Chunk 12096 does not have enough neighbors. Skipping...
Chunk 12097 does not have enough neighbors. Skipping...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 33%|███▎      | 2/6 [00:00<00:00, 11.45it/s]

 67%|██████▋   | 4/6 [00:00<00:00, 10.20it/s]

100%|██████████| 6/6 [00:00<00:00, 12.52it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9949167136994327

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9901722775004832

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9901722775004832

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9801377141546215

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9705478222182214

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9702131629842946

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.969747902203586

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.969336451664739

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9303499409934506

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9949167136994327
BRAS...

seed           9.000000
BAMI           0.994917
CASW           0.687370
SCGRAPHM       0.968591
ISOLISI        1.000000
BRAS           0.926832
KBET           0.259518
CPCR           0.924702
bio_score      0.912719
batch_score    0.703684
joint_score    0.829105
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,ISOLISI,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.994917,0.687632,0.979210,1.0,0.926793,0.260556,0.924747,0.915440,0.704032,0.830877
1,1,0.994917,0.687464,0.970957,1.0,0.926805,0.260268,0.924725,0.913334,0.703933,0.829574
2,2,0.994917,0.687651,0.970489,1.0,0.926716,0.260722,0.924728,0.913264,0.704055,0.829581
3,3,0.994917,0.687520,0.969022,1.0,0.926771,0.260062,0.924707,0.912865,0.703847,0.829257
4,4,0.994917,0.687611,0.970740,1.0,0.926733,0.260704,0.924719,0.913317,0.704052,0.829611
5,5,0.994917,0.687740,0.977000,1.0,0.926806,0.260539,0.924781,0.914914,0.704042,0.830565
6,6,0.994917,0.687651,0.971945,1.0,0.926715,0.260021,0.924727,0.913628,0.703821,0.829705
7,7,0.994917,0.687606,0.971004,1.0,0.926783,0.260268,0.924748,0.913382,0.703933,0.829602
8,8,0.994917,0.687664,0.971065,1.0,0.926765,0.260300,0.924751,0.913411,0.703939,0.829622
9,9,0.994917,0.687370,0.968591,1.0,0.926832,0.259518,0.924702,0.912719,0.703684,0.829105

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean           std       min       max
BAMI         0.994917  1.110223e-16  0.994917  0.994917
CASW         0.687591  1.033472e-04  0.687370  0.687740
SCGRAPHM     0.972002  3.229572e-03  0.968591  0.979210
ISOLISI      1.000000  0.000000e+00  1.000000  1.000000
BRAS         0.926772  3.798222e-05  0.926715  0.926832
KBET         0.260296  3.480080e-04  0.259518  0.260722
CPCR         0.924734  2.233576e-05  0.924702  0.924781
bio_score    0.913628  8.226199e-04  0.912719  0.915440
batch_score  0.703934  1.152388e-04  0.703684  0.704055
joint_score  0.829750  5.206898e-04  0.829105  0.830877