# LIGER default - mouse_mammary

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'mouse_mammary'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'BATCH'
LABEL_KEY = 'celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'mouse_mammary'
assert BATCH_KEY == 'BATCH'
assert LABEL_KEY == 'celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                          mouse_mammary
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                BATCH
label_key                                             celltype
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=9288 n_batches=3 n_labels=3
CPCR preflight: eligible_labels=3

In [4]:
LIGER_DEFAULT_ARGS = {
    "k": 20,
    "value_lambda": 5.0,
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_default(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_DEFAULT_ARGS["k"],
        lam=LIGER_DEFAULT_ARGS["value_lambda"],
        max_iterations=LIGER_DEFAULT_ARGS["max_iters"],
        mode=LIGER_DEFAULT_ARGS["mode"],
        layer=LIGER_DEFAULT_ARGS["layer"],
        seed=seed,
    )


pd.Series(LIGER_DEFAULT_ARGS, name="default_setting")

k                   20
value_lambda       5.0
max_iters           30
mode              core
layer           counts
Name: default_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_default(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:41,  1.41s/it]

  7%|▋         | 2/30 [00:02<00:40,  1.43s/it]

 10%|█         | 3/30 [00:04<00:39,  1.45s/it]

 13%|█▎        | 4/30 [00:05<00:36,  1.42s/it]

 17%|█▋        | 5/30 [00:07<00:36,  1.44s/it]

 20%|██        | 6/30 [00:08<00:34,  1.43s/it]

 23%|██▎       | 7/30 [00:09<00:31,  1.39s/it]

 27%|██▋       | 8/30 [00:11<00:29,  1.36s/it]

 30%|███       | 9/30 [00:12<00:28,  1.36s/it]

 33%|███▎      | 10/30 [00:13<00:27,  1.37s/it]

 37%|███▋      | 11/30 [00:15<00:25,  1.36s/it]

 40%|████      | 12/30 [00:16<00:24,  1.36s/it]

 43%|████▎     | 13/30 [00:18<00:23,  1.38s/it]

 47%|████▋     | 14/30 [00:19<00:22,  1.38s/it]

 50%|█████     | 15/30 [00:20<00:20,  1.37s/it]

 53%|█████▎    | 16/30 [00:22<00:19,  1.37s/it]

 57%|█████▋    | 17/30 [00:23<00:17,  1.38s/it]

 60%|██████    | 18/30 [00:24<00:16,  1.36s/it]

 63%|██████▎   | 19/30 [00:26<00:14,  1.36s/it]

 67%|██████▋   | 20/30 [00:27<00:13,  1.37s/it]

 70%|███████   | 21/30 [00:28<00:12,  1.37s/it]

 73%|███████▎  | 22/30 [00:30<00:11,  1.38s/it]

 77%|███████▋  | 23/30 [00:31<00:09,  1.39s/it]

 80%|████████  | 24/30 [00:33<00:08,  1.39s/it]

 83%|████████▎ | 25/30 [00:34<00:06,  1.38s/it]

 87%|████████▋ | 26/30 [00:35<00:05,  1.39s/it]

 90%|█████████ | 27/30 [00:37<00:04,  1.37s/it]

 93%|█████████▎| 28/30 [00:38<00:02,  1.36s/it]

 97%|█████████▋| 29/30 [00:39<00:01,  1.34s/it]

100%|██████████| 30/30 [00:41<00:00,  1.34s/it]

100%|██████████| 30/30 [00:41<00:00,  1.38s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 31.15it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.8297459580884675

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7295175488828459

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6044795226303036

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5648639363806595

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5365927579193457

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5221748710507709

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.497598497132832

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4830993237011241

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.47898042784664024

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4700055356265691

WARNING:2026-07-23 16:00:13,161:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8297459580884675
BRAS...

seed           1.000000
BAMI           0.829746
CASW           0.668905
SCGRAPHM       0.431156
BRAS           0.908539
KBET           0.362542
CPCR           0.933324
bio_score      0.643269
batch_score    0.734802
joint_score    0.679882
dtype: float64

===== seed 2 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:37,  1.30s/it]

  7%|▋         | 2/30 [00:02<00:36,  1.30s/it]

 10%|█         | 3/30 [00:03<00:34,  1.28s/it]

 13%|█▎        | 4/30 [00:05<00:32,  1.26s/it]

 17%|█▋        | 5/30 [00:06<00:31,  1.26s/it]

 20%|██        | 6/30 [00:07<00:30,  1.25s/it]

 23%|██▎       | 7/30 [00:08<00:28,  1.25s/it]

 27%|██▋       | 8/30 [00:10<00:27,  1.24s/it]

 30%|███       | 9/30 [00:10<00:24,  1.14s/it]

 33%|███▎      | 10/30 [00:11<00:21,  1.07s/it]

 37%|███▋      | 11/30 [00:12<00:19,  1.02s/it]

 40%|████      | 12/30 [00:13<00:17,  1.02it/s]

 43%|████▎     | 13/30 [00:14<00:16,  1.04it/s]

 47%|████▋     | 14/30 [00:15<00:15,  1.05it/s]

 50%|█████     | 15/30 [00:16<00:14,  1.07it/s]

 53%|█████▎    | 16/30 [00:17<00:12,  1.08it/s]

 57%|█████▋    | 17/30 [00:18<00:11,  1.08it/s]

 60%|██████    | 18/30 [00:19<00:11,  1.09it/s]

 63%|██████▎   | 19/30 [00:20<00:10,  1.09it/s]

 67%|██████▋   | 20/30 [00:20<00:09,  1.09it/s]

 70%|███████   | 21/30 [00:21<00:08,  1.09it/s]

 73%|███████▎  | 22/30 [00:22<00:07,  1.09it/s]

 77%|███████▋  | 23/30 [00:23<00:06,  1.09it/s]

 80%|████████  | 24/30 [00:24<00:05,  1.09it/s]

 83%|████████▎ | 25/30 [00:25<00:04,  1.10it/s]

 87%|████████▋ | 26/30 [00:26<00:03,  1.10it/s]

 90%|█████████ | 27/30 [00:27<00:02,  1.09it/s]

 93%|█████████▎| 28/30 [00:28<00:01,  1.09it/s]

 97%|█████████▋| 29/30 [00:29<00:00,  1.09it/s]

100%|██████████| 30/30 [00:30<00:00,  1.09it/s]

100%|██████████| 30/30 [00:30<00:00,  1.00s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 34.97it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8399379934347664

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7395542787971644

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6018381625942183

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5805486775898171

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5607009630300729

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5349335843245658

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5145668678656938

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5193556413786716

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5192889839193521

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5046427908356769

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8399379934347664
BRAS...

seed           2.000000
BAMI           0.839938
CASW           0.674772
SCGRAPHM       0.440970
BRAS           0.900498
KBET           0.317002
CPCR           0.897817
bio_score      0.651893
batch_score    0.705106
joint_score    0.673178
dtype: float64

===== seed 3 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:00<00:26,  1.11it/s]

  7%|▋         | 2/30 [00:01<00:27,  1.03it/s]

 10%|█         | 3/30 [00:02<00:25,  1.04it/s]

 13%|█▎        | 4/30 [00:03<00:24,  1.05it/s]

 17%|█▋        | 5/30 [00:04<00:23,  1.07it/s]

 20%|██        | 6/30 [00:05<00:22,  1.08it/s]

 23%|██▎       | 7/30 [00:06<00:21,  1.09it/s]

 27%|██▋       | 8/30 [00:07<00:20,  1.09it/s]

 30%|███       | 9/30 [00:08<00:19,  1.10it/s]

 33%|███▎      | 10/30 [00:09<00:18,  1.10it/s]

 37%|███▋      | 11/30 [00:10<00:17,  1.11it/s]

 40%|████      | 12/30 [00:11<00:16,  1.11it/s]

 43%|████▎     | 13/30 [00:11<00:15,  1.11it/s]

 47%|████▋     | 14/30 [00:12<00:14,  1.11it/s]

 50%|█████     | 15/30 [00:13<00:13,  1.11it/s]

 53%|█████▎    | 16/30 [00:14<00:12,  1.11it/s]

 57%|█████▋    | 17/30 [00:15<00:11,  1.11it/s]

 60%|██████    | 18/30 [00:16<00:10,  1.11it/s]

 63%|██████▎   | 19/30 [00:17<00:09,  1.11it/s]

 67%|██████▋   | 20/30 [00:18<00:09,  1.11it/s]

 70%|███████   | 21/30 [00:19<00:08,  1.10it/s]

 73%|███████▎  | 22/30 [00:20<00:07,  1.10it/s]

 77%|███████▋  | 23/30 [00:20<00:06,  1.11it/s]

 80%|████████  | 24/30 [00:21<00:05,  1.11it/s]

 83%|████████▎ | 25/30 [00:22<00:04,  1.11it/s]

 87%|████████▋ | 26/30 [00:23<00:03,  1.11it/s]

 90%|█████████ | 27/30 [00:24<00:02,  1.10it/s]

 93%|█████████▎| 28/30 [00:25<00:01,  1.11it/s]

 97%|█████████▋| 29/30 [00:26<00:00,  1.11it/s]

100%|██████████| 30/30 [00:27<00:00,  1.11it/s]

100%|██████████| 30/30 [00:27<00:00,  1.10it/s]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 34.57it/s]

kBET...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7560748627105547

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7184327718891393

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.569644805204908

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5463505774666206

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5063316525381354

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5077427286115926

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.47726638966562573

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.47273057926512785

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4639537974782414

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4528740678642003

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7560748627105547
BRAS...

seed           3.000000
BAMI           0.756075
CASW           0.655398
SCGRAPHM       0.431671
BRAS           0.877006
KBET           0.277962
CPCR           0.889830
bio_score      0.614381
batch_score    0.681600
joint_score    0.641269
dtype: float64

===== seed 4 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:00<00:25,  1.12it/s]

  7%|▋         | 2/30 [00:01<00:26,  1.05it/s]

 10%|█         | 3/30 [00:02<00:26,  1.04it/s]

 13%|█▎        | 4/30 [00:03<00:24,  1.04it/s]

 17%|█▋        | 5/30 [00:04<00:23,  1.05it/s]

 20%|██        | 6/30 [00:05<00:22,  1.06it/s]

 23%|██▎       | 7/30 [00:06<00:21,  1.07it/s]

 27%|██▋       | 8/30 [00:07<00:20,  1.07it/s]

 30%|███       | 9/30 [00:08<00:19,  1.08it/s]

 33%|███▎      | 10/30 [00:09<00:18,  1.08it/s]

 37%|███▋      | 11/30 [00:10<00:17,  1.08it/s]

 40%|████      | 12/30 [00:11<00:16,  1.09it/s]

 43%|████▎     | 13/30 [00:12<00:15,  1.10it/s]

 47%|████▋     | 14/30 [00:12<00:14,  1.10it/s]

 50%|█████     | 15/30 [00:13<00:13,  1.11it/s]

 53%|█████▎    | 16/30 [00:14<00:12,  1.11it/s]

 57%|█████▋    | 17/30 [00:15<00:11,  1.11it/s]

 60%|██████    | 18/30 [00:16<00:10,  1.10it/s]

 63%|██████▎   | 19/30 [00:17<00:09,  1.10it/s]

 67%|██████▋   | 20/30 [00:18<00:09,  1.10it/s]

 70%|███████   | 21/30 [00:19<00:08,  1.10it/s]

 73%|███████▎  | 22/30 [00:20<00:07,  1.10it/s]

 77%|███████▋  | 23/30 [00:21<00:06,  1.10it/s]

 80%|████████  | 24/30 [00:22<00:05,  1.10it/s]

 83%|████████▎ | 25/30 [00:22<00:04,  1.10it/s]

 87%|████████▋ | 26/30 [00:23<00:03,  1.10it/s]

 90%|█████████ | 27/30 [00:24<00:02,  1.10it/s]

 93%|█████████▎| 28/30 [00:25<00:01,  1.10it/s]

 97%|█████████▋| 29/30 [00:26<00:00,  1.10it/s]

100%|██████████| 30/30 [00:27<00:00,  1.10it/s]

100%|██████████| 30/30 [00:27<00:00,  1.09it/s]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 30.36it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8717134340411041

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7629627705482676

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6368790528526385

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5976107578783808

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5726774927073427

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.529022636155505

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5143744388895231

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5092022153281824

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4893372984549334

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4975643883892009

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8717134340411041
BRAS...

seed           4.000000
BAMI           0.871713
CASW           0.676591
SCGRAPHM       0.440257
BRAS           0.903975
KBET           0.307460
CPCR           0.914301
bio_score      0.662854
batch_score    0.708578
joint_score    0.681144
dtype: float64

===== seed 5 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:00<00:25,  1.13it/s]

  7%|▋         | 2/30 [00:01<00:26,  1.07it/s]

 10%|█         | 3/30 [00:02<00:25,  1.05it/s]

 13%|█▎        | 4/30 [00:03<00:24,  1.05it/s]

 17%|█▋        | 5/30 [00:04<00:23,  1.06it/s]

 20%|██        | 6/30 [00:05<00:22,  1.08it/s]

 23%|██▎       | 7/30 [00:06<00:21,  1.08it/s]

 27%|██▋       | 8/30 [00:07<00:20,  1.09it/s]

 30%|███       | 9/30 [00:08<00:19,  1.10it/s]

 33%|███▎      | 10/30 [00:09<00:18,  1.10it/s]

 37%|███▋      | 11/30 [00:10<00:17,  1.10it/s]

 40%|████      | 12/30 [00:11<00:16,  1.10it/s]

 43%|████▎     | 13/30 [00:11<00:15,  1.11it/s]

 47%|████▋     | 14/30 [00:12<00:14,  1.11it/s]

 50%|█████     | 15/30 [00:13<00:13,  1.11it/s]

 53%|█████▎    | 16/30 [00:14<00:12,  1.12it/s]

 57%|█████▋    | 17/30 [00:15<00:11,  1.13it/s]

 60%|██████    | 18/30 [00:16<00:10,  1.14it/s]

 63%|██████▎   | 19/30 [00:17<00:09,  1.14it/s]

 67%|██████▋   | 20/30 [00:18<00:08,  1.14it/s]

 70%|███████   | 21/30 [00:18<00:07,  1.15it/s]

 73%|███████▎  | 22/30 [00:19<00:06,  1.15it/s]

 77%|███████▋  | 23/30 [00:20<00:06,  1.15it/s]

 80%|████████  | 24/30 [00:21<00:05,  1.15it/s]

 83%|████████▎ | 25/30 [00:22<00:04,  1.15it/s]

 87%|████████▋ | 26/30 [00:23<00:03,  1.15it/s]

 90%|█████████ | 27/30 [00:24<00:02,  1.15it/s]

 93%|█████████▎| 28/30 [00:25<00:01,  1.15it/s]

 97%|█████████▋| 29/30 [00:25<00:00,  1.15it/s]

100%|██████████| 30/30 [00:26<00:00,  1.15it/s]

100%|██████████| 30/30 [00:26<00:00,  1.12it/s]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 36.92it/s]

kBET...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7922973868118327

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7347067647285687

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6353318146925936

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5813617060765697

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5687050834166866

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5577927391319499

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5164302801703775

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.49355241214524515

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.49753559449072177

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.47381971535859013

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7922973868118327
BRAS...

seed           5.000000
BAMI           0.792297
CASW           0.677961
SCGRAPHM       0.718914
BRAS           0.884115
KBET           0.299790
CPCR           0.881478
bio_score      0.729724
batch_score    0.688461
joint_score    0.713219
dtype: float64

===== seed 6 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:00<00:28,  1.01it/s]

  7%|▋         | 2/30 [00:01<00:27,  1.02it/s]

 10%|█         | 3/30 [00:02<00:26,  1.03it/s]

 13%|█▎        | 4/30 [00:03<00:24,  1.04it/s]

 17%|█▋        | 5/30 [00:04<00:23,  1.05it/s]

 20%|██        | 6/30 [00:05<00:22,  1.07it/s]

 23%|██▎       | 7/30 [00:06<00:21,  1.08it/s]

 27%|██▋       | 8/30 [00:07<00:20,  1.08it/s]

 30%|███       | 9/30 [00:08<00:19,  1.09it/s]

 33%|███▎      | 10/30 [00:09<00:18,  1.09it/s]

 37%|███▋      | 11/30 [00:10<00:17,  1.09it/s]

 40%|████      | 12/30 [00:11<00:16,  1.10it/s]

 43%|████▎     | 13/30 [00:12<00:15,  1.10it/s]

 47%|████▋     | 14/30 [00:12<00:14,  1.10it/s]

 50%|█████     | 15/30 [00:13<00:13,  1.10it/s]

 53%|█████▎    | 16/30 [00:14<00:12,  1.10it/s]

 57%|█████▋    | 17/30 [00:15<00:11,  1.10it/s]

 60%|██████    | 18/30 [00:16<00:10,  1.10it/s]

 63%|██████▎   | 19/30 [00:17<00:09,  1.10it/s]

 67%|██████▋   | 20/30 [00:18<00:09,  1.10it/s]

 70%|███████   | 21/30 [00:19<00:08,  1.10it/s]

 73%|███████▎  | 22/30 [00:20<00:07,  1.10it/s]

 77%|███████▋  | 23/30 [00:21<00:06,  1.10it/s]

 80%|████████  | 24/30 [00:22<00:05,  1.10it/s]

 83%|████████▎ | 25/30 [00:22<00:04,  1.10it/s]

 87%|████████▋ | 26/30 [00:23<00:03,  1.10it/s]

 90%|█████████ | 27/30 [00:24<00:02,  1.11it/s]

 93%|█████████▎| 28/30 [00:25<00:01,  1.10it/s]

 97%|█████████▋| 29/30 [00:26<00:00,  1.10it/s]

100%|██████████| 30/30 [00:27<00:00,  1.10it/s]

100%|██████████| 30/30 [00:27<00:00,  1.09it/s]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 33.30it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.810874504604539

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6945637872893908

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6238473165857698

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5848793007707797

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5600307440543312

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5400603560468602

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5164580419831906

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.505913982391839

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.49249418990158916

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4926735999528847

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.810874504604539
BRAS...

seed           6.000000
BAMI           0.810875
CASW           0.662758
SCGRAPHM       0.435163
BRAS           0.897644
KBET           0.306951
CPCR           0.907250
bio_score      0.636265
batch_score    0.703948
joint_score    0.663338
dtype: float64

===== seed 7 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:00<00:26,  1.10it/s]

  7%|▋         | 2/30 [00:01<00:26,  1.05it/s]

 10%|█         | 3/30 [00:02<00:25,  1.04it/s]

 13%|█▎        | 4/30 [00:03<00:25,  1.04it/s]

 17%|█▋        | 5/30 [00:04<00:23,  1.05it/s]

 20%|██        | 6/30 [00:05<00:22,  1.07it/s]

 23%|██▎       | 7/30 [00:06<00:21,  1.08it/s]

 27%|██▋       | 8/30 [00:07<00:20,  1.09it/s]

 30%|███       | 9/30 [00:08<00:19,  1.09it/s]

 33%|███▎      | 10/30 [00:09<00:18,  1.09it/s]

 37%|███▋      | 11/30 [00:10<00:17,  1.10it/s]

 40%|████      | 12/30 [00:11<00:16,  1.09it/s]

 43%|████▎     | 13/30 [00:12<00:15,  1.10it/s]

 47%|████▋     | 14/30 [00:12<00:14,  1.10it/s]

 50%|█████     | 15/30 [00:13<00:13,  1.10it/s]

 53%|█████▎    | 16/30 [00:14<00:12,  1.11it/s]

 57%|█████▋    | 17/30 [00:15<00:11,  1.12it/s]

 60%|██████    | 18/30 [00:16<00:10,  1.13it/s]

 63%|██████▎   | 19/30 [00:17<00:09,  1.14it/s]

 67%|██████▋   | 20/30 [00:18<00:08,  1.15it/s]

 70%|███████   | 21/30 [00:19<00:07,  1.15it/s]

 73%|███████▎  | 22/30 [00:19<00:06,  1.15it/s]

 77%|███████▋  | 23/30 [00:20<00:06,  1.15it/s]

 80%|████████  | 24/30 [00:21<00:05,  1.16it/s]

 83%|████████▎ | 25/30 [00:22<00:04,  1.16it/s]

 87%|████████▋ | 26/30 [00:23<00:03,  1.16it/s]

 90%|█████████ | 27/30 [00:24<00:02,  1.16it/s]

 93%|█████████▎| 28/30 [00:25<00:01,  1.16it/s]

 97%|█████████▋| 29/30 [00:25<00:00,  1.16it/s]

100%|██████████| 30/30 [00:26<00:00,  1.16it/s]

100%|██████████| 30/30 [00:26<00:00,  1.12it/s]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 39.78it/s]

kBET...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8044612322222611

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7009334090298224

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6613529579897415

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5746854743247368

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5520484662021528

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5132743950857895

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5036565299333933

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5051047944141024

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4867729284672839

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4691924370370511

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8044612322222611
BRAS...
seed           7.000000
BAMI           0.804461
CASW           0.658319
SCGRAPHM       0.716243
BRAS           0.892950
KBET           0.299030
CPCR           0.893891
bio_score      0.726341
batch_score    0.695290
joint_score    0.713921
dtype: float64

===== seed 8 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:40,  1.39s/it]

  7%|▋         | 2/30 [00:02<00:33,  1.21s/it]

 10%|█         | 3/30 [00:03<00:29,  1.10s/it]

 13%|█▎        | 4/30 [00:04<00:27,  1.04s/it]

 17%|█▋        | 5/30 [00:05<00:24,  1.00it/s]

 20%|██        | 6/30 [00:06<00:23,  1.03it/s]

 23%|██▎       | 7/30 [00:07<00:21,  1.05it/s]

 27%|██▋       | 8/30 [00:08<00:20,  1.07it/s]

 30%|███       | 9/30 [00:08<00:19,  1.07it/s]

 33%|███▎      | 10/30 [00:09<00:18,  1.08it/s]

 37%|███▋      | 11/30 [00:10<00:17,  1.09it/s]

 40%|████      | 12/30 [00:11<00:16,  1.09it/s]

 43%|████▎     | 13/30 [00:12<00:15,  1.09it/s]

 47%|████▋     | 14/30 [00:13<00:14,  1.10it/s]

 50%|█████     | 15/30 [00:14<00:13,  1.09it/s]

 53%|█████▎    | 16/30 [00:15<00:12,  1.10it/s]

 57%|█████▋    | 17/30 [00:16<00:11,  1.11it/s]

 60%|██████    | 18/30 [00:17<00:10,  1.13it/s]

 63%|██████▎   | 19/30 [00:17<00:09,  1.13it/s]

 67%|██████▋   | 20/30 [00:18<00:08,  1.14it/s]

 70%|███████   | 21/30 [00:19<00:07,  1.14it/s]

 73%|███████▎  | 22/30 [00:20<00:06,  1.14it/s]

 77%|███████▋  | 23/30 [00:21<00:06,  1.15it/s]

 80%|████████  | 24/30 [00:22<00:05,  1.15it/s]

 83%|████████▎ | 25/30 [00:23<00:04,  1.15it/s]

 87%|████████▋ | 26/30 [00:24<00:03,  1.15it/s]

 90%|█████████ | 27/30 [00:24<00:02,  1.14it/s]

 93%|█████████▎| 28/30 [00:25<00:01,  1.15it/s]

 97%|█████████▋| 29/30 [00:26<00:00,  1.15it/s]

100%|██████████| 30/30 [00:27<00:00,  1.15it/s]

100%|██████████| 30/30 [00:27<00:00,  1.09it/s]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 38.92it/s]

kBET...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8089734940213255

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.696195054559986

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.617782367100362

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5883233025451826

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5477337478180803

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5406921054612642

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5121202430088876

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5018648856303148

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4910171325741862

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4820358306269442

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8089734940213255
BRAS...

seed           8.000000
BAMI           0.808973
CASW           0.671161
SCGRAPHM       0.716280
BRAS           0.898379
KBET           0.366190
CPCR           0.913409
bio_score      0.732138
batch_score    0.725993
joint_score    0.729680
dtype: float64

===== seed 9 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:00<00:25,  1.14it/s]

  7%|▋         | 2/30 [00:01<00:26,  1.06it/s]

 10%|█         | 3/30 [00:02<00:26,  1.04it/s]

 13%|█▎        | 4/30 [00:03<00:24,  1.04it/s]

 17%|█▋        | 5/30 [00:04<00:23,  1.06it/s]

 20%|██        | 6/30 [00:05<00:22,  1.07it/s]

 23%|██▎       | 7/30 [00:06<00:21,  1.08it/s]

 27%|██▋       | 8/30 [00:07<00:20,  1.08it/s]

 30%|███       | 9/30 [00:08<00:19,  1.09it/s]

 33%|███▎      | 10/30 [00:09<00:18,  1.09it/s]

 37%|███▋      | 11/30 [00:10<00:17,  1.10it/s]

 40%|████      | 12/30 [00:11<00:16,  1.10it/s]

 43%|████▎     | 13/30 [00:12<00:15,  1.10it/s]

 47%|████▋     | 14/30 [00:12<00:14,  1.10it/s]

 50%|█████     | 15/30 [00:13<00:13,  1.10it/s]

 53%|█████▎    | 16/30 [00:14<00:12,  1.10it/s]

 57%|█████▋    | 17/30 [00:15<00:11,  1.12it/s]

 60%|██████    | 18/30 [00:16<00:10,  1.13it/s]

 63%|██████▎   | 19/30 [00:17<00:09,  1.13it/s]

 67%|██████▋   | 20/30 [00:18<00:08,  1.14it/s]

 70%|███████   | 21/30 [00:19<00:07,  1.15it/s]

 73%|███████▎  | 22/30 [00:19<00:06,  1.15it/s]

 77%|███████▋  | 23/30 [00:20<00:06,  1.16it/s]

 80%|████████  | 24/30 [00:21<00:05,  1.16it/s]

 83%|████████▎ | 25/30 [00:22<00:04,  1.16it/s]

 87%|████████▋ | 26/30 [00:23<00:03,  1.16it/s]

 90%|█████████ | 27/30 [00:24<00:02,  1.16it/s]

 93%|█████████▎| 28/30 [00:25<00:01,  1.16it/s]

 97%|█████████▋| 29/30 [00:25<00:00,  1.16it/s]

100%|██████████| 30/30 [00:26<00:00,  1.15it/s]

100%|██████████| 30/30 [00:26<00:00,  1.12it/s]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 35.92it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8132203070476275

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.667607569044556

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6088519094769705

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5752398905576329

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5265425487031714

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.509428081238743

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.499224469481417

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.49178597126953005

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4769691250096102

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4661894586737861

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8132203070476275
BRAS...

seed           9.000000
BAMI           0.813220
CASW           0.670168
SCGRAPHM       0.710949
BRAS           0.888294
KBET           0.301139
CPCR           0.888032
bio_score      0.731446
batch_score    0.692488
joint_score    0.715863
dtype: float64

===== seed 10 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:00<00:26,  1.11it/s]

  7%|▋         | 2/30 [00:01<00:26,  1.07it/s]

 10%|█         | 3/30 [00:02<00:25,  1.06it/s]

 13%|█▎        | 4/30 [00:03<00:24,  1.07it/s]

 17%|█▋        | 5/30 [00:04<00:23,  1.08it/s]

 20%|██        | 6/30 [00:05<00:22,  1.09it/s]

 23%|██▎       | 7/30 [00:06<00:21,  1.09it/s]

 27%|██▋       | 8/30 [00:07<00:20,  1.10it/s]

 30%|███       | 9/30 [00:08<00:19,  1.10it/s]

 33%|███▎      | 10/30 [00:09<00:18,  1.10it/s]

 37%|███▋      | 11/30 [00:10<00:17,  1.10it/s]

 40%|████      | 12/30 [00:10<00:16,  1.10it/s]

 43%|████▎     | 13/30 [00:11<00:15,  1.10it/s]

 47%|████▋     | 14/30 [00:12<00:14,  1.10it/s]

 50%|█████     | 15/30 [00:13<00:13,  1.10it/s]

 53%|█████▎    | 16/30 [00:14<00:12,  1.10it/s]

 57%|█████▋    | 17/30 [00:15<00:11,  1.11it/s]

 60%|██████    | 18/30 [00:16<00:10,  1.11it/s]

 63%|██████▎   | 19/30 [00:17<00:09,  1.11it/s]

 67%|██████▋   | 20/30 [00:18<00:09,  1.11it/s]

 70%|███████   | 21/30 [00:19<00:08,  1.11it/s]

 73%|███████▎  | 22/30 [00:20<00:07,  1.10it/s]

 77%|███████▋  | 23/30 [00:20<00:06,  1.10it/s]

 80%|████████  | 24/30 [00:21<00:05,  1.10it/s]

 83%|████████▎ | 25/30 [00:22<00:04,  1.10it/s]

 87%|████████▋ | 26/30 [00:23<00:03,  1.10it/s]

 90%|█████████ | 27/30 [00:24<00:02,  1.10it/s]

 93%|█████████▎| 28/30 [00:25<00:01,  1.10it/s]

 97%|█████████▋| 29/30 [00:26<00:00,  1.10it/s]

100%|██████████| 30/30 [00:27<00:00,  1.10it/s]

100%|██████████| 30/30 [00:27<00:00,  1.10it/s]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 34.34it/s]

kBET...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8457558871964223

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.771200021128888

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6663302803998833

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6015580688450404

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5731510807936988

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5386088735173439

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5217334202528052

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.49606172320203834

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4976342676637432

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4857449883893377

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8457558871964223
BRAS...

seed           10.000000
BAMI            0.845756
CASW            0.670772
SCGRAPHM        0.438579
BRAS            0.909345
KBET            0.367298
CPCR            0.922088
bio_score       0.651702
batch_score     0.732910
joint_score     0.684186
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.829746,0.668905,0.431156,0.908539,0.362542,0.933324,0.643269,0.734802,0.679882
1,2,0.839938,0.674772,0.440970,0.900498,0.317002,0.897817,0.651893,0.705106,0.673178
2,3,0.756075,0.655398,0.431671,0.877006,0.277962,0.889830,0.614381,0.681600,0.641269
3,4,0.871713,0.676591,0.440257,0.903975,0.307460,0.914301,0.662854,0.708578,0.681144
4,5,0.792297,0.677961,0.718914,0.884115,0.299790,0.881478,0.729724,0.688461,0.713219
5,6,0.810875,0.662758,0.435163,0.897644,0.306951,0.907250,0.636265,0.703948,0.663338
6,7,0.804461,0.658319,0.716243,0.892950,0.299030,0.893891,0.726341,0.695290,0.713921
7,8,0.808973,0.671161,0.716280,0.898379,0.366190,0.913409,0.732138,0.725993,0.729680
8,9,0.813220,0.670168,0.710949,0.888294,0.301139,0.888032,0.731446,0.692488,0.715863
9,10,0.845756,0.670772,0.438579,0.909345,0.367298,0.922088,0.651702,0.732910,0.684186

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.817306  0.030172  0.756075  0.871713
CASW         0.668681  0.007193  0.655398  0.677961
SCGRAPHM     0.548018  0.136873  0.431156  0.718914
BRAS         0.896074  0.009991  0.877006  0.909345
KBET         0.320536  0.030798  0.277962  0.367298
CPCR         0.904142  0.015797  0.881478  0.933324
bio_score    0.678001  0.044043  0.614381  0.732138
batch_score  0.706918  0.017768  0.681600  0.734802
joint_score  0.689568  0.026336  0.641269  0.729680