# LIGER best - mouse_mammary

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'mouse_mammary'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'BATCH'
LABEL_KEY = 'celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'mouse_mammary'
assert BATCH_KEY == 'BATCH'
assert LABEL_KEY == 'celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                          mouse_mammary
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                BATCH
label_key                                             celltype
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=9288 n_batches=3 n_labels=3
CPCR preflight: eligible_labels=3

In [4]:
OPTUNA_STUDY_NAME = 'liger_mouse_mammary_joint_expanded_metrics_scgraphm_v1'
OPTUNA_BEST_TRIAL = 81
OPTUNA_BEST_VALUE = 0.7309488589758968
OPTUNA_BEST_PARAMS = {'k': 23, 'value_lambda': 8.412025368174445}

LIGER_BEST_ARGS = {
    "k": OPTUNA_BEST_PARAMS["k"],
    "value_lambda": OPTUNA_BEST_PARAMS["value_lambda"],
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_best(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_BEST_ARGS["k"],
        lam=LIGER_BEST_ARGS["value_lambda"],
        max_iterations=LIGER_BEST_ARGS["max_iters"],
        mode=LIGER_BEST_ARGS["mode"],
        layer=LIGER_BEST_ARGS["layer"],
        seed=seed,
    )


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **LIGER_BEST_ARGS,
    },
    name="best_setting",
)

study           liger_mouse_mammary_joint_expanded_metrics_scg...
best_trial                                                     81
best_value                                               0.730949
k                                                              23
value_lambda                                             8.412025
max_iters                                                      30
mode                                                         core
layer                                                      counts
Name: best_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:34,  1.18s/it]

  7%|▋         | 2/30 [00:02<00:33,  1.19s/it]

 10%|█         | 3/30 [00:03<00:31,  1.17s/it]

 13%|█▎        | 4/30 [00:04<00:29,  1.14s/it]

 17%|█▋        | 5/30 [00:05<00:28,  1.12s/it]

 20%|██        | 6/30 [00:06<00:26,  1.11s/it]

 23%|██▎       | 7/30 [00:07<00:25,  1.11s/it]

 27%|██▋       | 8/30 [00:09<00:24,  1.12s/it]

 30%|███       | 9/30 [00:10<00:23,  1.11s/it]

 33%|███▎      | 10/30 [00:11<00:21,  1.09s/it]

 37%|███▋      | 11/30 [00:12<00:20,  1.09s/it]

 40%|████      | 12/30 [00:13<00:19,  1.09s/it]

 43%|████▎     | 13/30 [00:14<00:18,  1.09s/it]

 47%|████▋     | 14/30 [00:15<00:17,  1.08s/it]

 50%|█████     | 15/30 [00:16<00:16,  1.08s/it]

 53%|█████▎    | 16/30 [00:17<00:15,  1.08s/it]

 57%|█████▋    | 17/30 [00:18<00:14,  1.10s/it]

 60%|██████    | 18/30 [00:20<00:14,  1.22s/it]

 63%|██████▎   | 19/30 [00:21<00:14,  1.32s/it]

 67%|██████▋   | 20/30 [00:23<00:13,  1.40s/it]

 70%|███████   | 21/30 [00:25<00:13,  1.47s/it]

 73%|███████▎  | 22/30 [00:26<00:11,  1.50s/it]

 77%|███████▋  | 23/30 [00:28<00:10,  1.54s/it]

 80%|████████  | 24/30 [00:29<00:09,  1.55s/it]

 83%|████████▎ | 25/30 [00:31<00:07,  1.56s/it]

 87%|████████▋ | 26/30 [00:33<00:06,  1.61s/it]

 90%|█████████ | 27/30 [00:34<00:04,  1.57s/it]

 93%|█████████▎| 28/30 [00:36<00:03,  1.54s/it]

 97%|█████████▋| 29/30 [00:37<00:01,  1.51s/it]

100%|██████████| 30/30 [00:39<00:00,  1.55s/it]

100%|██████████| 30/30 [00:39<00:00,  1.31s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 28.05it/s]

100%|██████████| 3/3 [00:00<00:00, 26.64it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.8206688369682326

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7545207469913504

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6715324078276927

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5951597878829694

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5634112292220577

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5424976810555344

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5336064341129383

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4978477479716214

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.49670827822432345

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49667348891046015

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8206688369682326
BRAS...

WARNING:2026-07-23 16:00:36,022:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

seed           1.000000
BAMI           0.820669
CASW           0.658471
SCGRAPHM       0.717308
BRAS           0.906884
KBET           0.368430
CPCR           0.912131
bio_score      0.732149
batch_score    0.729148
joint_score    0.730949
dtype: float64

===== seed 2 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:36,  1.25s/it]

  7%|▋         | 2/30 [00:02<00:42,  1.51s/it]

 10%|█         | 3/30 [00:04<00:38,  1.41s/it]

 13%|█▎        | 4/30 [00:05<00:33,  1.30s/it]

 17%|█▋        | 5/30 [00:06<00:31,  1.26s/it]

 20%|██        | 6/30 [00:07<00:29,  1.22s/it]

 23%|██▎       | 7/30 [00:08<00:27,  1.17s/it]

 27%|██▋       | 8/30 [00:09<00:25,  1.14s/it]

 30%|███       | 9/30 [00:10<00:23,  1.12s/it]

 33%|███▎      | 10/30 [00:11<00:21,  1.10s/it]

 37%|███▋      | 11/30 [00:12<00:20,  1.08s/it]

 40%|████      | 12/30 [00:14<00:21,  1.19s/it]

 43%|████▎     | 13/30 [00:15<00:21,  1.29s/it]

 47%|████▋     | 14/30 [00:17<00:19,  1.24s/it]

 50%|█████     | 15/30 [00:18<00:17,  1.20s/it]

 53%|█████▎    | 16/30 [00:19<00:16,  1.15s/it]

 57%|█████▋    | 17/30 [00:20<00:14,  1.14s/it]

 60%|██████    | 18/30 [00:21<00:13,  1.14s/it]

 63%|██████▎   | 19/30 [00:22<00:12,  1.12s/it]

 67%|██████▋   | 20/30 [00:23<00:10,  1.08s/it]

 70%|███████   | 21/30 [00:24<00:09,  1.06s/it]

 73%|███████▎  | 22/30 [00:25<00:08,  1.05s/it]

 77%|███████▋  | 23/30 [00:27<00:08,  1.22s/it]

 80%|████████  | 24/30 [00:29<00:08,  1.42s/it]

 83%|████████▎ | 25/30 [00:30<00:07,  1.50s/it]

 87%|████████▋ | 26/30 [00:32<00:06,  1.56s/it]

 90%|█████████ | 27/30 [00:34<00:04,  1.57s/it]

 93%|█████████▎| 28/30 [00:35<00:02,  1.43s/it]

 97%|█████████▋| 29/30 [00:36<00:01,  1.43s/it]

100%|██████████| 30/30 [00:38<00:00,  1.47s/it]

100%|██████████| 30/30 [00:38<00:00,  1.27s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 29.06it/s]

100%|██████████| 3/3 [00:00<00:00, 28.90it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7535101846244883

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7001825021789131

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6489317564799381

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6017960645427539

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.579566977642164

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5344847072325728

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5186489979489254

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5091785869823767

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.503999206356299

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.48687188348925553

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7535101846244883
BRAS...
seed           2.000000
BAMI           0.753510
CASW           0.656338
SCGRAPHM       0.164387
BRAS           0.879372
KBET           0.315398
CPCR           0.865594
bio_score      0.524745
batch_score    0.686788
joint_score    0.589562
dtype: float64

===== seed 3 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:32,  1.12s/it]

  7%|▋         | 2/30 [00:02<00:33,  1.20s/it]

 10%|█         | 3/30 [00:03<00:32,  1.21s/it]

 13%|█▎        | 4/30 [00:04<00:31,  1.21s/it]

 17%|█▋        | 5/30 [00:05<00:29,  1.18s/it]

 20%|██        | 6/30 [00:07<00:28,  1.19s/it]

 23%|██▎       | 7/30 [00:08<00:27,  1.18s/it]

 27%|██▋       | 8/30 [00:09<00:25,  1.17s/it]

 30%|███       | 9/30 [00:10<00:24,  1.16s/it]

 33%|███▎      | 10/30 [00:11<00:22,  1.14s/it]

 37%|███▋      | 11/30 [00:12<00:21,  1.15s/it]

 40%|████      | 12/30 [00:13<00:20,  1.13s/it]

 43%|████▎     | 13/30 [00:15<00:19,  1.13s/it]

 47%|████▋     | 14/30 [00:16<00:17,  1.12s/it]

 50%|█████     | 15/30 [00:17<00:16,  1.13s/it]

 53%|█████▎    | 16/30 [00:18<00:15,  1.10s/it]

 57%|█████▋    | 17/30 [00:19<00:14,  1.09s/it]

 60%|██████    | 18/30 [00:20<00:12,  1.06s/it]

 63%|██████▎   | 19/30 [00:21<00:11,  1.06s/it]

 67%|██████▋   | 20/30 [00:22<00:10,  1.05s/it]

 70%|███████   | 21/30 [00:23<00:09,  1.05s/it]

 73%|███████▎  | 22/30 [00:24<00:08,  1.05s/it]

 77%|███████▋  | 23/30 [00:25<00:07,  1.03s/it]

 80%|████████  | 24/30 [00:26<00:06,  1.03s/it]

 83%|████████▎ | 25/30 [00:27<00:05,  1.02s/it]

 87%|████████▋ | 26/30 [00:28<00:04,  1.01s/it]

 90%|█████████ | 27/30 [00:29<00:02,  1.01it/s]

 93%|█████████▎| 28/30 [00:30<00:01,  1.01it/s]

 97%|█████████▋| 29/30 [00:31<00:01,  1.00s/it]

100%|██████████| 30/30 [00:32<00:00,  1.01it/s]

100%|██████████| 30/30 [00:32<00:00,  1.08s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 26.71it/s]

100%|██████████| 3/3 [00:00<00:00, 25.87it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.806402206420021

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7342852934639006

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6797450611856807

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5877782436576728

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.550372670107663

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5478138199616926

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5135470020536422

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5133622891513082

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.48855987801708056

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4812853103097453

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.806402206420021
BRAS...
seed           3.000000
BAMI           0.806402
CASW           0.661560
SCGRAPHM       0.437540
BRAS           0.898405
KBET           0.347926
CPCR           0.892503
bio_score      0.635167
batch_score    0.712944
joint_score    0.666278
dtype: float64

===== seed 4 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:44,  1.53s/it]

  7%|▋         | 2/30 [00:02<00:37,  1.35s/it]

 10%|█         | 3/30 [00:03<00:33,  1.23s/it]

 13%|█▎        | 4/30 [00:04<00:30,  1.16s/it]

 17%|█▋        | 5/30 [00:05<00:27,  1.12s/it]

 20%|██        | 6/30 [00:06<00:26,  1.09s/it]

 23%|██▎       | 7/30 [00:07<00:24,  1.06s/it]

 27%|██▋       | 8/30 [00:09<00:23,  1.06s/it]

 30%|███       | 9/30 [00:10<00:22,  1.05s/it]

 33%|███▎      | 10/30 [00:11<00:21,  1.07s/it]

 37%|███▋      | 11/30 [00:12<00:20,  1.06s/it]

 40%|████      | 12/30 [00:13<00:18,  1.05s/it]

 43%|████▎     | 13/30 [00:14<00:18,  1.06s/it]

 47%|████▋     | 14/30 [00:15<00:16,  1.05s/it]

 50%|█████     | 15/30 [00:16<00:15,  1.05s/it]

 53%|█████▎    | 16/30 [00:17<00:14,  1.07s/it]

 57%|█████▋    | 17/30 [00:18<00:14,  1.10s/it]

 60%|██████    | 18/30 [00:19<00:13,  1.10s/it]

 63%|██████▎   | 19/30 [00:20<00:12,  1.11s/it]

 67%|██████▋   | 20/30 [00:22<00:11,  1.10s/it]

 70%|███████   | 21/30 [00:23<00:09,  1.09s/it]

 73%|███████▎  | 22/30 [00:24<00:08,  1.09s/it]

 77%|███████▋  | 23/30 [00:25<00:07,  1.08s/it]

 80%|████████  | 24/30 [00:26<00:06,  1.07s/it]

 83%|████████▎ | 25/30 [00:27<00:05,  1.07s/it]

 87%|████████▋ | 26/30 [00:28<00:04,  1.06s/it]

 90%|█████████ | 27/30 [00:29<00:03,  1.07s/it]

 93%|█████████▎| 28/30 [00:30<00:02,  1.06s/it]

 97%|█████████▋| 29/30 [00:31<00:01,  1.07s/it]

100%|██████████| 30/30 [00:32<00:00,  1.06s/it]

100%|██████████| 30/30 [00:32<00:00,  1.09s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 31.71it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8202159467787677

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7836260114861902

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6913951922107774

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5794040052700853

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5776615404299814

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5550537006209841

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5248988544542685

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5188568070001541

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.499895306190873

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.48981178709343726

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8202159467787677
BRAS...
seed           4.000000
BAMI           0.820216
CASW           0.664911
SCGRAPHM       0.439251
BRAS           0.848555
KBET           0.296876
CPCR           0.855727
bio_score      0.641459
batch_score    0.667053
joint_score    0.651697
dtype: float64

===== seed 5 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:30,  1.05s/it]

  7%|▋         | 2/30 [00:02<00:31,  1.12s/it]

 10%|█         | 3/30 [00:03<00:30,  1.12s/it]

 13%|█▎        | 4/30 [00:04<00:29,  1.15s/it]

 17%|█▋        | 5/30 [00:05<00:28,  1.13s/it]

 20%|██        | 6/30 [00:06<00:26,  1.12s/it]

 23%|██▎       | 7/30 [00:07<00:25,  1.11s/it]

 27%|██▋       | 8/30 [00:08<00:24,  1.11s/it]

 30%|███       | 9/30 [00:10<00:23,  1.10s/it]

 33%|███▎      | 10/30 [00:11<00:21,  1.09s/it]

 37%|███▋      | 11/30 [00:12<00:21,  1.11s/it]

 40%|████      | 12/30 [00:13<00:19,  1.10s/it]

 43%|████▎     | 13/30 [00:14<00:19,  1.12s/it]

 47%|████▋     | 14/30 [00:15<00:17,  1.11s/it]

 50%|█████     | 15/30 [00:16<00:16,  1.10s/it]

 53%|█████▎    | 16/30 [00:17<00:15,  1.10s/it]

 57%|█████▋    | 17/30 [00:18<00:13,  1.07s/it]

 60%|██████    | 18/30 [00:19<00:12,  1.06s/it]

 63%|██████▎   | 19/30 [00:20<00:11,  1.06s/it]

 67%|██████▋   | 20/30 [00:21<00:10,  1.06s/it]

 70%|███████   | 21/30 [00:22<00:09,  1.05s/it]

 73%|███████▎  | 22/30 [00:24<00:08,  1.06s/it]

 77%|███████▋  | 23/30 [00:25<00:07,  1.05s/it]

 80%|████████  | 24/30 [00:26<00:06,  1.04s/it]

 83%|████████▎ | 25/30 [00:27<00:05,  1.04s/it]

 87%|████████▋ | 26/30 [00:28<00:04,  1.04s/it]

 90%|█████████ | 27/30 [00:29<00:03,  1.04s/it]

 93%|█████████▎| 28/30 [00:30<00:02,  1.05s/it]

 97%|█████████▋| 29/30 [00:31<00:01,  1.06s/it]

100%|██████████| 30/30 [00:32<00:00,  1.06s/it]

100%|██████████| 30/30 [00:32<00:00,  1.08s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 35.08it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8454945174903652

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7371184759533103

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6704477559472385

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6020331584067053

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.566436720367068

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5455255705832457

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5394385713979158

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.518572656830235

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5027187390838374

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.48859603628230996

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8454945174903652
BRAS...
seed           5.000000
BAMI           0.845495
CASW           0.679792
SCGRAPHM       0.439712
BRAS           0.918325
KBET           0.392720
CPCR           0.920418
bio_score      0.654999
batch_score    0.743821
joint_score    0.690528
dtype: float64

===== seed 6 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:00<00:28,  1.00it/s]

  7%|▋         | 2/30 [00:02<00:30,  1.10s/it]

 10%|█         | 3/30 [00:03<00:29,  1.09s/it]

 13%|█▎        | 4/30 [00:04<00:28,  1.09s/it]

 17%|█▋        | 5/30 [00:05<00:26,  1.06s/it]

 20%|██        | 6/30 [00:06<00:25,  1.05s/it]

 23%|██▎       | 7/30 [00:07<00:24,  1.07s/it]

 27%|██▋       | 8/30 [00:08<00:26,  1.19s/it]

 30%|███       | 9/30 [00:09<00:24,  1.14s/it]

 33%|███▎      | 10/30 [00:10<00:22,  1.10s/it]

 37%|███▋      | 11/30 [00:12<00:20,  1.08s/it]

 40%|████      | 12/30 [00:13<00:19,  1.10s/it]

 43%|████▎     | 13/30 [00:14<00:18,  1.09s/it]

 47%|████▋     | 14/30 [00:15<00:17,  1.07s/it]

 50%|█████     | 15/30 [00:16<00:15,  1.04s/it]

 53%|█████▎    | 16/30 [00:17<00:14,  1.02s/it]

 57%|█████▋    | 17/30 [00:18<00:13,  1.02s/it]

 60%|██████    | 18/30 [00:19<00:12,  1.01s/it]

 63%|██████▎   | 19/30 [00:20<00:11,  1.02s/it]

 67%|██████▋   | 20/30 [00:21<00:10,  1.03s/it]

 70%|███████   | 21/30 [00:22<00:09,  1.04s/it]

 73%|███████▎  | 22/30 [00:23<00:08,  1.04s/it]

 77%|███████▋  | 23/30 [00:24<00:07,  1.07s/it]

 80%|████████  | 24/30 [00:25<00:06,  1.06s/it]

 83%|████████▎ | 25/30 [00:26<00:05,  1.06s/it]

 87%|████████▋ | 26/30 [00:27<00:04,  1.07s/it]

 90%|█████████ | 27/30 [00:28<00:03,  1.07s/it]

 93%|█████████▎| 28/30 [00:29<00:02,  1.05s/it]

 97%|█████████▋| 29/30 [00:30<00:01,  1.04s/it]

100%|██████████| 30/30 [00:31<00:00,  1.04s/it]

100%|██████████| 30/30 [00:31<00:00,  1.06s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 36.47it/s]

kBET...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.792212762563217

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7236356152515352

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6442958837277778

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5735643688058503

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5310466741425954

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5162345704519873

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.4987844881084348

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4944764576948001

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4797095966420589

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4712642664610423

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.792212762563217
BRAS...
seed           6.000000
BAMI           0.792213
CASW           0.653341
SCGRAPHM       0.437454
BRAS           0.892976
KBET           0.284677
CPCR           0.888621
bio_score      0.627669
batch_score    0.688758
joint_score    0.652105
dtype: float64

===== seed 7 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:30,  1.06s/it]

  7%|▋         | 2/30 [00:02<00:30,  1.07s/it]

 10%|█         | 3/30 [00:03<00:28,  1.06s/it]

 13%|█▎        | 4/30 [00:04<00:27,  1.05s/it]

 17%|█▋        | 5/30 [00:05<00:25,  1.03s/it]

 20%|██        | 6/30 [00:06<00:24,  1.02s/it]

 23%|██▎       | 7/30 [00:07<00:23,  1.01s/it]

 27%|██▋       | 8/30 [00:08<00:22,  1.01s/it]

 30%|███       | 9/30 [00:09<00:21,  1.01s/it]

 33%|███▎      | 10/30 [00:10<00:20,  1.03s/it]

 37%|███▋      | 11/30 [00:11<00:19,  1.03s/it]

 40%|████      | 12/30 [00:12<00:18,  1.02s/it]

 43%|████▎     | 13/30 [00:13<00:17,  1.03s/it]

 47%|████▋     | 14/30 [00:14<00:16,  1.02s/it]

 50%|█████     | 15/30 [00:15<00:15,  1.02s/it]

 53%|█████▎    | 16/30 [00:16<00:14,  1.02s/it]

 57%|█████▋    | 17/30 [00:17<00:13,  1.05s/it]

 60%|██████    | 18/30 [00:18<00:12,  1.05s/it]

 63%|██████▎   | 19/30 [00:19<00:11,  1.04s/it]

 67%|██████▋   | 20/30 [00:20<00:10,  1.03s/it]

 70%|███████   | 21/30 [00:21<00:09,  1.04s/it]

 73%|███████▎  | 22/30 [00:22<00:08,  1.07s/it]

 77%|███████▋  | 23/30 [00:23<00:07,  1.07s/it]

 80%|████████  | 24/30 [00:24<00:06,  1.06s/it]

 83%|████████▎ | 25/30 [00:25<00:05,  1.06s/it]

 87%|████████▋ | 26/30 [00:27<00:04,  1.08s/it]

 90%|█████████ | 27/30 [00:28<00:03,  1.09s/it]

 93%|█████████▎| 28/30 [00:29<00:02,  1.07s/it]

 97%|█████████▋| 29/30 [00:30<00:01,  1.06s/it]

100%|██████████| 30/30 [00:31<00:00,  1.06s/it]

100%|██████████| 30/30 [00:31<00:00,  1.05s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 34.39it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7832378988904756

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.712070837718741

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6418378564983788

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.593921859776962

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5439221553782381

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.536229679880852

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5163549882725297

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4980439672467066

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5017734073695137

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4886679117783895

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7832378988904756
BRAS...
seed           7.000000
BAMI           0.783238
CASW           0.651031
SCGRAPHM       0.430715
BRAS           0.911311
KBET           0.320853
CPCR           0.904218
bio_score      0.621661
batch_score    0.712127
joint_score    0.657848
dtype: float64

===== seed 8 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:31,  1.08s/it]

  7%|▋         | 2/30 [00:02<00:33,  1.18s/it]

 10%|█         | 3/30 [00:03<00:30,  1.13s/it]

 13%|█▎        | 4/30 [00:04<00:28,  1.10s/it]

 17%|█▋        | 5/30 [00:05<00:27,  1.08s/it]

 20%|██        | 6/30 [00:06<00:25,  1.07s/it]

 23%|██▎       | 7/30 [00:07<00:24,  1.05s/it]

 27%|██▋       | 8/30 [00:08<00:23,  1.05s/it]

 30%|███       | 9/30 [00:09<00:21,  1.04s/it]

 33%|███▎      | 10/30 [00:10<00:20,  1.03s/it]

 37%|███▋      | 11/30 [00:11<00:19,  1.04s/it]

 40%|████      | 12/30 [00:12<00:19,  1.07s/it]

 43%|████▎     | 13/30 [00:14<00:20,  1.21s/it]

 47%|████▋     | 14/30 [00:15<00:18,  1.19s/it]

 50%|█████     | 15/30 [00:16<00:17,  1.17s/it]

 53%|█████▎    | 16/30 [00:17<00:16,  1.15s/it]

 57%|█████▋    | 17/30 [00:18<00:14,  1.13s/it]

 60%|██████    | 18/30 [00:19<00:13,  1.12s/it]

 63%|██████▎   | 19/30 [00:20<00:11,  1.09s/it]

 67%|██████▋   | 20/30 [00:21<00:10,  1.07s/it]

 70%|███████   | 21/30 [00:22<00:09,  1.06s/it]

 73%|███████▎  | 22/30 [00:24<00:08,  1.05s/it]

 77%|███████▋  | 23/30 [00:25<00:07,  1.04s/it]

 80%|████████  | 24/30 [00:26<00:06,  1.04s/it]

 83%|████████▎ | 25/30 [00:27<00:05,  1.05s/it]

 87%|████████▋ | 26/30 [00:28<00:04,  1.05s/it]

 90%|█████████ | 27/30 [00:29<00:03,  1.04s/it]

 93%|█████████▎| 28/30 [00:30<00:02,  1.03s/it]

 97%|█████████▋| 29/30 [00:31<00:01,  1.01s/it]

100%|██████████| 30/30 [00:32<00:00,  1.01s/it]

100%|██████████| 30/30 [00:32<00:00,  1.07s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 33.30it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.782302207623223

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7301622857403278

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5941440360947224

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5599232612482375

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5275128641670623

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5185442183844976

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5129011965845938

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.506031907219113

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.49568313242036827

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4873018607148214

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.782302207623223
BRAS...
seed           8.000000
BAMI           0.782302
CASW           0.663244
SCGRAPHM       0.441043
BRAS           0.891567
KBET           0.290392
CPCR           0.897934
bio_score      0.628863
batch_score    0.693298
joint_score    0.654637
dtype: float64

===== seed 9 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:31,  1.10s/it]

  7%|▋         | 2/30 [00:02<00:31,  1.13s/it]

 10%|█         | 3/30 [00:03<00:30,  1.12s/it]

 13%|█▎        | 4/30 [00:04<00:29,  1.12s/it]

 17%|█▋        | 5/30 [00:05<00:27,  1.10s/it]

 20%|██        | 6/30 [00:06<00:26,  1.09s/it]

 23%|██▎       | 7/30 [00:07<00:24,  1.08s/it]

 27%|██▋       | 8/30 [00:08<00:23,  1.07s/it]

 30%|███       | 9/30 [00:09<00:22,  1.05s/it]

 33%|███▎      | 10/30 [00:10<00:20,  1.04s/it]

 37%|███▋      | 11/30 [00:11<00:19,  1.04s/it]

 40%|████      | 12/30 [00:12<00:18,  1.05s/it]

 43%|████▎     | 13/30 [00:14<00:21,  1.25s/it]

 47%|████▋     | 14/30 [00:15<00:19,  1.23s/it]

 50%|█████     | 15/30 [00:16<00:17,  1.16s/it]

 53%|█████▎    | 16/30 [00:17<00:15,  1.12s/it]

 57%|█████▋    | 17/30 [00:18<00:14,  1.08s/it]

 60%|██████    | 18/30 [00:19<00:12,  1.04s/it]

 63%|██████▎   | 19/30 [00:20<00:11,  1.03s/it]

 67%|██████▋   | 20/30 [00:21<00:10,  1.01s/it]

 70%|███████   | 21/30 [00:22<00:09,  1.03s/it]

 73%|███████▎  | 22/30 [00:23<00:08,  1.04s/it]

 77%|███████▋  | 23/30 [00:24<00:07,  1.04s/it]

 80%|████████  | 24/30 [00:25<00:06,  1.04s/it]

 83%|████████▎ | 25/30 [00:26<00:05,  1.02s/it]

 87%|████████▋ | 26/30 [00:27<00:04,  1.01s/it]

 90%|█████████ | 27/30 [00:28<00:03,  1.02s/it]

 93%|█████████▎| 28/30 [00:30<00:02,  1.15s/it]

 97%|█████████▋| 29/30 [00:31<00:01,  1.24s/it]

100%|██████████| 30/30 [00:33<00:00,  1.30s/it]

100%|██████████| 30/30 [00:33<00:00,  1.11s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 28.51it/s]

100%|██████████| 3/3 [00:00<00:00, 28.30it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8327287681005751

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7609541874222289

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6464648094511548

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5912303529175971

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5597903414825521

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5429797211042345

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5362977418537951

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5060420064662301

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5141557375286406

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.48721224550684644

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8327287681005751
BRAS...
seed           9.000000
BAMI           0.832729
CASW           0.658338
SCGRAPHM       0.438328
BRAS           0.900305
KBET           0.317725
CPCR           0.899385
bio_score      0.643132
batch_score    0.705805
joint_score    0.668201
dtype: float64

===== seed 10 =====

[LIGER PARAMS] function=optimize_ALS k=23 value_lambda=8.412025368174445 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:01<00:29,  1.01s/it]

  7%|▋         | 2/30 [00:02<00:30,  1.10s/it]

 10%|█         | 3/30 [00:03<00:30,  1.11s/it]

 13%|█▎        | 4/30 [00:04<00:28,  1.10s/it]

 17%|█▋        | 5/30 [00:05<00:27,  1.08s/it]

 20%|██        | 6/30 [00:06<00:25,  1.08s/it]

 23%|██▎       | 7/30 [00:07<00:24,  1.06s/it]

 27%|██▋       | 8/30 [00:08<00:23,  1.05s/it]

 30%|███       | 9/30 [00:09<00:22,  1.05s/it]

 33%|███▎      | 10/30 [00:10<00:20,  1.04s/it]

 37%|███▋      | 11/30 [00:11<00:19,  1.03s/it]

 40%|████      | 12/30 [00:12<00:18,  1.02s/it]

 43%|████▎     | 13/30 [00:13<00:17,  1.02s/it]

 47%|████▋     | 14/30 [00:14<00:16,  1.01s/it]

 50%|█████     | 15/30 [00:15<00:15,  1.03s/it]

 53%|█████▎    | 16/30 [00:16<00:14,  1.04s/it]

 57%|█████▋    | 17/30 [00:17<00:13,  1.03s/it]

 60%|██████    | 18/30 [00:18<00:12,  1.02s/it]

 63%|██████▎   | 19/30 [00:19<00:11,  1.03s/it]

 67%|██████▋   | 20/30 [00:20<00:10,  1.02s/it]

 70%|███████   | 21/30 [00:21<00:09,  1.02s/it]

 73%|███████▎  | 22/30 [00:22<00:08,  1.02s/it]

 77%|███████▋  | 23/30 [00:23<00:07,  1.02s/it]

 80%|████████  | 24/30 [00:24<00:06,  1.01s/it]

 83%|████████▎ | 25/30 [00:25<00:05,  1.01s/it]

 87%|████████▋ | 26/30 [00:26<00:04,  1.01s/it]

 90%|█████████ | 27/30 [00:27<00:03,  1.03s/it]

 93%|█████████▎| 28/30 [00:28<00:02,  1.02s/it]

 97%|█████████▋| 29/30 [00:29<00:01,  1.02s/it]

100%|██████████| 30/30 [00:31<00:00,  1.03s/it]

100%|██████████| 30/30 [00:31<00:00,  1.03s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 35.41it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.795542986919163

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7408949290448696

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6567888976083605

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6100139468657322

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5574412693674142

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.547271416534907

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5270853643532581

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5214983397860895

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5087134885739264

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5044348466106723

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.795542986919163
BRAS...
seed           10.000000
BAMI            0.795543
CASW            0.654031
SCGRAPHM        0.440908
BRAS            0.889951
KBET            0.291042
CPCR            0.895684
bio_score       0.630160
batch_score     0.692226
joint_score     0.654986
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.820669,0.658471,0.717308,0.906884,0.368430,0.912131,0.732149,0.729148,0.730949
1,2,0.753510,0.656338,0.164387,0.879372,0.315398,0.865594,0.524745,0.686788,0.589562
2,3,0.806402,0.661560,0.437540,0.898405,0.347926,0.892503,0.635167,0.712944,0.666278
3,4,0.820216,0.664911,0.439251,0.848555,0.296876,0.855727,0.641459,0.667053,0.651697
4,5,0.845495,0.679792,0.439712,0.918325,0.392720,0.920418,0.654999,0.743821,0.690528
5,6,0.792213,0.653341,0.437454,0.892976,0.284677,0.888621,0.627669,0.688758,0.652105
6,7,0.783238,0.651031,0.430715,0.911311,0.320853,0.904218,0.621661,0.712127,0.657848
7,8,0.782302,0.663244,0.441043,0.891567,0.290392,0.897934,0.628863,0.693298,0.654637
8,9,0.832729,0.658338,0.438328,0.900305,0.317725,0.899385,0.643132,0.705805,0.668201
9,10,0.795543,0.654031,0.440908,0.889951,0.291042,0.895684,0.630160,0.692226,0.654986

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.803232  0.025980  0.753510  0.845495
CASW         0.660106  0.007795  0.651031  0.679792
SCGRAPHM     0.438664  0.123672  0.164387  0.717308
BRAS         0.893765  0.018489  0.848555  0.918325
KBET         0.322604  0.034453  0.284677  0.392720
CPCR         0.893221  0.018642  0.855727  0.920418
bio_score    0.634001  0.047313  0.524745  0.732149
batch_score  0.703197  0.021232  0.667053  0.743821
joint_score  0.661679  0.033460  0.589562  0.730949