# Harmony best - mouse_mammary

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import harmonypy as hm
import numpy as np
import pandas as pd
import scanpy as sc

from scib.metrics.metrics import metrics

In [2]:
DATASET_NAME = 'mouse_mammary'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'BATCH'
LABEL_KEY = 'celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_PCS = 50
N_NEIGHBORS = 15
N_TOP_HVG = 2000

EMBED_KEY = "X_harmony"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "harmony_metric_batch"
METRIC_LABEL_KEY = "harmony_metric_label"

assert DATASET_NAME == 'mouse_mammary'
assert BATCH_KEY == 'BATCH'
assert LABEL_KEY == 'celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
    },
    name="configuration",
)

dataset                                          mouse_mammary
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                BATCH
label_key                                             celltype
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                           [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Name: configuration, dtype: object

In [3]:
def validate_dataset_contents():
    adata_backed = ad.read_h5ad(DATA_PATH, backed="r")
    try:
        required_keys = (BATCH_KEY, LABEL_KEY)
        missing_keys = [
            key for key in required_keys if key not in adata_backed.obs
        ]
        if missing_keys:
            raise ValueError(
                f"Missing obs keys {missing_keys}. "
                f"Available keys: {list(adata_backed.obs.columns)}"
            )

        obs = adata_backed.obs[[BATCH_KEY, LABEL_KEY]].copy()
        pseudotime = None
        if "TRAJ" in SELECTED_METRICS:
            if "dpt_pseudotime" not in adata_backed.obs:
                raise ValueError(
                    "TRAJ requires adata.obs['dpt_pseudotime']."
                )
            pseudotime = adata_backed.obs["dpt_pseudotime"].copy()

        n_obs = int(adata_backed.n_obs)
        n_vars = int(adata_backed.n_vars)
    finally:
        adata_backed.file.close()

    if obs.isna().any().any():
        raise ValueError(
            "Missing batch/label values: "
            f"{obs.isna().sum().to_dict()}"
        )

    n_batches = int(obs[BATCH_KEY].nunique())
    n_labels = int(obs[LABEL_KEY].nunique())
    if n_batches < 2:
        raise ValueError(
            f"Batch metrics require at least 2 batches; found {n_batches}."
        )

    batch_coverage = obs.groupby(
        LABEL_KEY,
        observed=True,
    )[BATCH_KEY].nunique()
    label_counts = obs.groupby(LABEL_KEY, observed=True).size()

    if "TRAJ" in SELECTED_METRICS:
        finite_pseudotime = pseudotime.dropna()
        if (
            len(finite_pseudotime) < 2
            or finite_pseudotime.nunique() < 2
        ):
            raise ValueError(
                "TRAJ requires at least 2 usable pseudotime values."
            )

    if "ISOLISI" in SELECTED_METRICS:
        min_batch_coverage = int(batch_coverage.min())
        if min_batch_coverage >= n_batches:
            raise ValueError(
                "ISOLISI is enabled, but every label appears in all batches."
            )

    eligible_cpcr_labels = [
        str(label)
        for label in label_counts.index
        if int(label_counts.loc[label]) >= 100
        and int(batch_coverage.loc[label]) >= 2
    ]
    if "CPCR" in SELECTED_METRICS and not eligible_cpcr_labels:
        raise ValueError(
            "CPCR requires a label with at least 100 cells across "
            "at least 2 batches."
        )

    return {
        "n_obs": n_obs,
        "n_vars": n_vars,
        "n_batches": n_batches,
        "n_labels": n_labels,
        "cpcr_eligible_labels": len(eligible_cpcr_labels),
    }


validate_dataset_contents()

{'n_obs': 9288,
 'n_vars': 1222,
 'n_batches': 3,
 'n_labels': 3,
 'cpcr_eligible_labels': 3}

In [4]:
OPTUNA_STUDY_NAME = 'harmony_mouse_mammary_joint_expanded_metrics_scgraphm_v2'
OPTUNA_BEST_TRIAL = 211
OPTUNA_BEST_VALUE = 0.7408612866966899
OPTUNA_BEST_PARAMS = {'theta': 7.865984153384493, 'sigma': 0.036031182713343934, 'lamb_mode': 'fixed', 'lamb': 0.11607743221159703, 'tau': 1.387709132344425, 'nclust': 193}

if OPTUNA_BEST_PARAMS["lamb_mode"] == "auto":
    resolved_lamb = -1
else:
    resolved_lamb = OPTUNA_BEST_PARAMS["lamb"]

HARMONY_BEST_ARGS = {
    "theta": OPTUNA_BEST_PARAMS["theta"],
    "lamb": resolved_lamb,
    "sigma": OPTUNA_BEST_PARAMS["sigma"],
    "nclust": OPTUNA_BEST_PARAMS["nclust"],
    "tau": OPTUNA_BEST_PARAMS["tau"],
    "block_size": 0.05,
    "max_iter_harmony": 10,
    "max_iter_kmeans": 20,
    "epsilon_cluster": 1e-5,
    "epsilon_harmony": 1e-4,
    "alpha": 0.2,
}


def run_harmony_best(adata, seed):
    adata_int = adata.copy()

    if "highly_variable" in adata_int.var:
        adata_int = adata_int[:, adata_int.var["highly_variable"]].copy()
    else:
        sc.pp.highly_variable_genes(
            adata_int,
            flavor="seurat",
            n_top_genes=N_TOP_HVG,
        )
        adata_int = adata_int[:, adata_int.var["highly_variable"]].copy()

    sc.tl.pca(
        adata_int,
        n_comps=N_PCS,
        svd_solver="arpack",
    )
    x_pca = np.asarray(adata_int.obsm["X_pca"], dtype=np.float32)

    harmony_result = hm.run_harmony(
        x_pca,
        adata_int.obs,
        BATCH_KEY,
        **HARMONY_BEST_ARGS,
        verbose=False,
        random_state=seed,
        device="cpu",
    )

    x_harmony = np.asarray(harmony_result.Z_corr)
    if (
        x_harmony.shape[0] != adata_int.n_obs
        and x_harmony.shape[1] == adata_int.n_obs
    ):
        x_harmony = x_harmony.T
    if x_harmony.shape[0] != adata_int.n_obs:
        raise ValueError(
            f"Harmony output shape {x_harmony.shape} is incompatible "
            f"with n_obs={adata_int.n_obs}."
        )
    if not np.all(np.isfinite(x_harmony)):
        raise ValueError("Harmony produced NaN or Inf in X_harmony.")

    adata_int.obsm[EMBED_KEY] = x_harmony
    return adata_int


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **HARMONY_BEST_ARGS,
    },
    name="best_setting",
)

study               harmony_mouse_mammary_joint_expanded_metrics_s...
best_trial                                                        211
best_value                                                   0.740861
theta                                                        7.865984
lamb                                                         0.116077
sigma                                                        0.036031
nclust                                                            193
tau                                                          1.387709
block_size                                                       0.05
max_iter_harmony                                                   10
max_iter_kmeans                                                    20
epsilon_cluster                                               0.00001
epsilon_harmony                                                0.0001
alpha                                                             0.2
Name: best_setting, dtype: object

In [5]:
def metric_value(metric_series, key):
    if key not in metric_series.index:
        raise KeyError(
            f"Metric {key} not found. "
            f"Available metrics: {list(metric_series.index)}"
        )

    value = metric_series[key]
    if isinstance(value, (list, tuple, np.ndarray)):
        values = np.asarray(value, dtype=float)
        if values.size == 0 or not np.all(np.isfinite(values)):
            raise ValueError(
                f"Metric {key} returned non-finite values: {values}"
            )
        return float(np.mean(values))

    value = float(value)
    if not np.isfinite(value):
        raise ValueError(
            f"Metric {key} returned a non-finite value: {value}"
        )
    return value


def compute_joint_metrics(adata_raw, adata_int):
    sc.pp.neighbors(
        adata_int,
        use_rep=EMBED_KEY,
        n_neighbors=N_NEIGHBORS,
        random_state=0,
    )

    metric_key_map = {
        METRIC_BATCH_KEY: BATCH_KEY,
        METRIC_LABEL_KEY: LABEL_KEY,
    }
    for adata_name, adata_obj in (
        ("adata_raw", adata_raw),
        ("adata_int", adata_int),
    ):
        existing_aliases = [
            alias for alias in metric_key_map if alias in adata_obj.obs
        ]
        if existing_aliases:
            raise ValueError(
                f"Reserved metric obs keys already exist in {adata_name}: "
                f"{existing_aliases}"
            )
        for alias, source_key in metric_key_map.items():
            adata_obj.obs[alias] = adata_obj.obs[source_key].copy()

    metric_df = metrics(
        adata=adata_raw,
        adata_int=adata_int,
        batch_key=METRIC_BATCH_KEY,
        label_key=METRIC_LABEL_KEY,
        embed=EMBED_KEY,
        cluster_key=CLUSTER_KEY,
        verbose=False,
        bami_="BAMI" in SELECTED_METRICS,
        casw_="CASW" in SELECTED_METRICS,
        scgraphm_="SCGRAPHM" in SELECTED_METRICS,
        traj_="TRAJ" in SELECTED_METRICS,
        isolisi_="ISOLISI" in SELECTED_METRICS,
        bras_="BRAS" in SELECTED_METRICS,
        kbet_="KBET" in SELECTED_METRICS,
        cpcr_="CPCR" in SELECTED_METRICS,
    )
    metric_series = metric_df.iloc[:, 0]

    result = {
        key: metric_value(metric_series, key)
        for key in SELECTED_METRICS
    }
    bio_score = float(
        np.mean([result[key] for key in SELECTED_BIO_METRICS])
    )
    batch_score = float(
        np.mean([result[key] for key in SELECTED_BATCH_METRICS])
    )
    joint_score = float(0.6 * bio_score + 0.4 * batch_score)

    if not np.all(np.isfinite([bio_score, batch_score, joint_score])):
        raise ValueError(
            "Aggregation produced a non-finite score: "
            f"bio={bio_score}, batch={batch_score}, "
            f"joint={joint_score}"
        )

    result["bio_score"] = bio_score
    result["batch_score"] = batch_score
    result["joint_score"] = joint_score
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_harmony_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

2026-07-23 11:03:43,903 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:03:44,153 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 31.85it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.9676866296153307

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9605569277882776

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9537866356182322

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8875929736067669

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8037678783397754

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6859965695602808

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.664988207880023

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.611988253863341

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.584085939169236

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5664293324646724

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-07-23 11:04:18,981:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9676866296153307
BRAS...

seed           0.000000
BAMI           0.967687
CASW           0.658212
SCGRAPHM       0.718138
BRAS           0.950214
KBET           0.091073
CPCR           0.998457
bio_score      0.781346
batch_score    0.679915
joint_score    0.740773
dtype: float64

===== seed 1 =====

2026-07-23 11:04:21,873 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:04:22,252 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 30.26it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9553247930048626

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9554873721827162

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9551901892265241

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8794009988583222

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7388282759350072

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.667842904123574

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6422472078241523

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5944854845299831

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5857461864861752

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5598189264771105

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.9554873721827162
BRAS...

seed           1.000000
BAMI           0.955487
CASW           0.658591
SCGRAPHM       0.718179
BRAS           0.949722
KBET           0.089610
CPCR           0.998508
bio_score      0.777419
batch_score    0.679280
joint_score    0.738164
dtype: float64

===== seed 2 =====

2026-07-23 11:04:40,400 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:04:40,626 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 30.41it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9604339860320636

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9604339860320636

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9616990530651126

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8714274042441161

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.86291980047352

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6644031317957507

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6512790535274019

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6028311109027396

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5905287331912901

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5879746951619719

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.9616990530651126
BRAS...

seed           2.000000
BAMI           0.961699
CASW           0.658335
SCGRAPHM       0.718122
BRAS           0.949838
KBET           0.093574
CPCR           0.998382
bio_score      0.779385
batch_score    0.680598
joint_score    0.739870
dtype: float64

===== seed 3 =====

2026-07-23 11:04:57,430 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:04:57,664 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 51.95it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9577986384715481

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9583272948395095

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9591735065451973

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.892306117176201

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7970628947208992

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6629156949631947

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6324273469006279

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6259997636345158

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5916208770179429

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.575570211440212

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.9591735065451973
BRAS...

seed           3.000000
BAMI           0.959174
CASW           0.658469
SCGRAPHM       0.718175
BRAS           0.949024
KBET           0.094994
CPCR           0.998485
bio_score      0.778606
batch_score    0.680835
joint_score    0.739497
dtype: float64

===== seed 4 =====

2026-07-23 11:05:14,229 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:05:14,454 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 41.42it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9604369489229176

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9604369489229176

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9568706683389238

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8970775934058933

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7959286344083344

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6766145998282466

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6400789244462121

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6292355376687258

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5872056756202741

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5778066809468416

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9604369489229176
BRAS...

seed           4.000000
BAMI           0.960437
CASW           0.658298
SCGRAPHM       0.718147
BRAS           0.949132
KBET           0.093952
CPCR           0.998359
bio_score      0.778960
batch_score    0.680481
joint_score    0.739569
dtype: float64

===== seed 5 =====

2026-07-23 11:05:31,068 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:05:31,290 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 40.79it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9576797358421106

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9576797358421106

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9576797358421106

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8820261163077785

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7374293589035134

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6702585162403367

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6360848501313805

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6206431138096298

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5928485666415662

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5802047562180763

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9576797358421106
BRAS...

seed           5.000000
BAMI           0.957680
CASW           0.658327
SCGRAPHM       0.718147
BRAS           0.949458
KBET           0.090536
CPCR           0.998241
bio_score      0.778051
batch_score    0.679412
joint_score    0.738595
dtype: float64

===== seed 6 =====

2026-07-23 11:05:47,791 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:05:48,012 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 39.47it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9589694023872314

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9589694023872314

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9592403848267824

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8685199843303385

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7555494030829836

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6982070456475988

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6289339772983469

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.610454859673623

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5852408503446505

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5836423571855645

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.9592403848267824
BRAS...

seed           6.000000
BAMI           0.959240
CASW           0.658202
SCGRAPHM       0.718121
BRAS           0.948827
KBET           0.089529
CPCR           0.998065
bio_score      0.778521
batch_score    0.678807
joint_score    0.738635
dtype: float64

===== seed 7 =====

2026-07-23 11:06:04,311 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:06:04,549 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 36.46it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9578004531676269

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9578004531676269

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9598105920748421

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8436123593702791

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7348803109958689

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6670076810457467

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6426230556238236

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5981652952497156

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5769796430107792

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5655546018445463

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.9598105920748421
BRAS...

seed           7.000000
BAMI           0.959811
CASW           0.658285
SCGRAPHM       0.718115
BRAS           0.949632
KBET           0.093778
CPCR           0.998469
bio_score      0.778737
batch_score    0.680626
joint_score    0.739493
dtype: float64

===== seed 8 =====

2026-07-23 11:06:23,912 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:06:24,124 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 34.65it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.957799404318757

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9594921976657445

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9594921976657445

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8731905036203581

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7624192543059237

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6884673723610739

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6279893232556182

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5962089381416962

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.587986493495837

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5699154905541971

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.9594921976657445
BRAS...

seed           8.000000
BAMI           0.959492
CASW           0.658337
SCGRAPHM       0.718141
BRAS           0.949305
KBET           0.099075
CPCR           0.998377
bio_score      0.778657
batch_score    0.682253
joint_score    0.740095
dtype: float64

===== seed 9 =====

2026-07-23 11:06:42,186 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:06:42,573 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Per cell type PC regression...
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 33.81it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9577420021438637

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9577420021438637

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9579792802576879

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8383338864500313

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7908659285229864

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.685033675137256

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6352971083679003

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6036131870095848

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5735601529092629

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5713429226752323

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.9579792802576879
BRAS...

seed           9.000000
BAMI           0.957979
CASW           0.658303
SCGRAPHM       0.718106
BRAS           0.949727
KBET           0.097713
CPCR           0.998299
bio_score      0.778129
batch_score    0.681913
joint_score    0.739643
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.967687,0.658212,0.718138,0.950214,0.091073,0.998457,0.781346,0.679915,0.740773
1,1,0.955487,0.658591,0.718179,0.949722,0.089610,0.998508,0.777419,0.679280,0.738164
2,2,0.961699,0.658335,0.718122,0.949838,0.093574,0.998382,0.779385,0.680598,0.739870
3,3,0.959174,0.658469,0.718175,0.949024,0.094994,0.998485,0.778606,0.680835,0.739497
4,4,0.960437,0.658298,0.718147,0.949132,0.093952,0.998359,0.778960,0.680481,0.739569
5,5,0.957680,0.658327,0.718147,0.949458,0.090536,0.998241,0.778051,0.679412,0.738595
6,6,0.959240,0.658202,0.718121,0.948827,0.089529,0.998065,0.778521,0.678807,0.738635
7,7,0.959811,0.658285,0.718115,0.949632,0.093778,0.998469,0.778737,0.680626,0.739493
8,8,0.959492,0.658337,0.718141,0.949305,0.099075,0.998377,0.778657,0.682253,0.740095
9,9,0.957979,0.658303,0.718106,0.949727,0.097713,0.998299,0.778129,0.681913,0.739643

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.959869  0.003056  0.955487  0.967687
CASW         0.658336  0.000110  0.658202  0.658591
SCGRAPHM     0.718139  0.000023  0.718106  0.718179
BRAS         0.949488  0.000400  0.948827  0.950214
KBET         0.093383  0.003111  0.089529  0.099075
CPCR         0.998364  0.000128  0.998065  0.998508
bio_score    0.778781  0.000995  0.777419  0.781346
batch_score  0.680412  0.001049  0.678807  0.682253
joint_score  0.739433  0.000738  0.738164  0.740773