# Harmony default - mouse_regulatory_T

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import harmonypy as hm
import numpy as np
import pandas as pd
import scanpy as sc

from scib.metrics.metrics import metrics

In [2]:
DATASET_NAME = 'mouse_regulatory_T'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'method'
LABEL_KEY = 'cell.type'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_PCS = 50
N_NEIGHBORS = 15
N_TOP_HVG = 2000

EMBED_KEY = "X_harmony"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "harmony_metric_batch"
METRIC_LABEL_KEY = "harmony_metric_label"

assert DATASET_NAME == 'mouse_regulatory_T'
assert BATCH_KEY == 'method'
assert LABEL_KEY == 'cell.type'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
    },
    name="configuration",
)

dataset                                     mouse_regulatory_T
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                               method
label_key                                            cell.type
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                           [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Name: configuration, dtype: object

In [3]:
def validate_dataset_contents():
    adata_backed = ad.read_h5ad(DATA_PATH, backed="r")
    try:
        required_keys = (BATCH_KEY, LABEL_KEY)
        missing_keys = [
            key for key in required_keys if key not in adata_backed.obs
        ]
        if missing_keys:
            raise ValueError(
                f"Missing obs keys {missing_keys}. "
                f"Available keys: {list(adata_backed.obs.columns)}"
            )

        obs = adata_backed.obs[[BATCH_KEY, LABEL_KEY]].copy()
        pseudotime = None
        if "TRAJ" in SELECTED_METRICS:
            if "dpt_pseudotime" not in adata_backed.obs:
                raise ValueError(
                    "TRAJ requires adata.obs['dpt_pseudotime']."
                )
            pseudotime = adata_backed.obs["dpt_pseudotime"].copy()

        n_obs = int(adata_backed.n_obs)
        n_vars = int(adata_backed.n_vars)
    finally:
        adata_backed.file.close()

    if obs.isna().any().any():
        raise ValueError(
            "Missing batch/label values: "
            f"{obs.isna().sum().to_dict()}"
        )

    n_batches = int(obs[BATCH_KEY].nunique())
    n_labels = int(obs[LABEL_KEY].nunique())
    if n_batches < 2:
        raise ValueError(
            f"Batch metrics require at least 2 batches; found {n_batches}."
        )

    batch_coverage = obs.groupby(
        LABEL_KEY,
        observed=True,
    )[BATCH_KEY].nunique()
    label_counts = obs.groupby(LABEL_KEY, observed=True).size()

    if "TRAJ" in SELECTED_METRICS:
        finite_pseudotime = pseudotime.dropna()
        if (
            len(finite_pseudotime) < 2
            or finite_pseudotime.nunique() < 2
        ):
            raise ValueError(
                "TRAJ requires at least 2 usable pseudotime values."
            )

    if "ISOLISI" in SELECTED_METRICS:
        min_batch_coverage = int(batch_coverage.min())
        if min_batch_coverage >= n_batches:
            raise ValueError(
                "ISOLISI is enabled, but every label appears in all batches."
            )

    eligible_cpcr_labels = [
        str(label)
        for label in label_counts.index
        if int(label_counts.loc[label]) >= 100
        and int(batch_coverage.loc[label]) >= 2
    ]
    if "CPCR" in SELECTED_METRICS and not eligible_cpcr_labels:
        raise ValueError(
            "CPCR requires a label with at least 100 cells across "
            "at least 2 batches."
        )

    return {
        "n_obs": n_obs,
        "n_vars": n_vars,
        "n_batches": n_batches,
        "n_labels": n_labels,
        "cpcr_eligible_labels": len(eligible_cpcr_labels),
    }


validate_dataset_contents()

{'n_obs': 34697,
 'n_vars': 11765,
 'n_batches': 2,
 'n_labels': 3,
 'cpcr_eligible_labels': 2}

In [4]:
HARMONY_DEFAULTS = {
    "theta": None,
    "lamb": None,
    "sigma": 0.1,
    "nclust": None,
    "tau": 0.0,
    "block_size": 0.05,
    "max_iter_harmony": 10,
    "max_iter_kmeans": 20,
    "epsilon_cluster": 1e-5,
    "epsilon_harmony": 1e-4,
    "alpha": 0.2,
}


def run_harmony_default(adata, seed):
    adata_int = adata.copy()

    if "highly_variable" in adata_int.var:
        adata_int = adata_int[:, adata_int.var["highly_variable"]].copy()
    else:
        sc.pp.highly_variable_genes(
            adata_int,
            flavor="seurat",
            n_top_genes=N_TOP_HVG,
        )
        adata_int = adata_int[:, adata_int.var["highly_variable"]].copy()

    sc.tl.pca(
        adata_int,
        n_comps=N_PCS,
        svd_solver="arpack",
    )
    x_pca = np.asarray(adata_int.obsm["X_pca"], dtype=np.float32)

    harmony_result = hm.run_harmony(
        x_pca,
        adata_int.obs,
        BATCH_KEY,
        **HARMONY_DEFAULTS,
        verbose=False,
        random_state=seed,
        device="cpu",
    )

    x_harmony = np.asarray(harmony_result.Z_corr)
    if (
        x_harmony.shape[0] != adata_int.n_obs
        and x_harmony.shape[1] == adata_int.n_obs
    ):
        x_harmony = x_harmony.T
    if x_harmony.shape[0] != adata_int.n_obs:
        raise ValueError(
            f"Harmony output shape {x_harmony.shape} is incompatible "
            f"with n_obs={adata_int.n_obs}."
        )
    if not np.all(np.isfinite(x_harmony)):
        raise ValueError("Harmony produced NaN or Inf in X_harmony.")

    adata_int.obsm[EMBED_KEY] = x_harmony
    return adata_int


pd.Series(HARMONY_DEFAULTS, name="upstream_default_argument")

theta                    NaN
lamb                     NaN
sigma                0.10000
nclust                   NaN
tau                  0.00000
block_size           0.05000
max_iter_harmony    10.00000
max_iter_kmeans     20.00000
epsilon_cluster      0.00001
epsilon_harmony      0.00010
alpha                0.20000
Name: upstream_default_argument, dtype: float64

In [5]:
def metric_value(metric_series, key):
    if key not in metric_series.index:
        raise KeyError(
            f"Metric {key} not found. "
            f"Available metrics: {list(metric_series.index)}"
        )

    value = metric_series[key]
    if isinstance(value, (list, tuple, np.ndarray)):
        values = np.asarray(value, dtype=float)
        if values.size == 0 or not np.all(np.isfinite(values)):
            raise ValueError(
                f"Metric {key} returned non-finite values: {values}"
            )
        return float(np.mean(values))

    value = float(value)
    if not np.isfinite(value):
        raise ValueError(
            f"Metric {key} returned a non-finite value: {value}"
        )
    return value


def compute_joint_metrics(adata_raw, adata_int):
    sc.pp.neighbors(
        adata_int,
        use_rep=EMBED_KEY,
        n_neighbors=N_NEIGHBORS,
        random_state=0,
    )

    metric_key_map = {
        METRIC_BATCH_KEY: BATCH_KEY,
        METRIC_LABEL_KEY: LABEL_KEY,
    }
    for adata_name, adata_obj in (
        ("adata_raw", adata_raw),
        ("adata_int", adata_int),
    ):
        existing_aliases = [
            alias for alias in metric_key_map if alias in adata_obj.obs
        ]
        if existing_aliases:
            raise ValueError(
                f"Reserved metric obs keys already exist in {adata_name}: "
                f"{existing_aliases}"
            )
        for alias, source_key in metric_key_map.items():
            adata_obj.obs[alias] = adata_obj.obs[source_key].copy()

    metric_df = metrics(
        adata=adata_raw,
        adata_int=adata_int,
        batch_key=METRIC_BATCH_KEY,
        label_key=METRIC_LABEL_KEY,
        embed=EMBED_KEY,
        cluster_key=CLUSTER_KEY,
        verbose=False,
        bami_="BAMI" in SELECTED_METRICS,
        casw_="CASW" in SELECTED_METRICS,
        scgraphm_="SCGRAPHM" in SELECTED_METRICS,
        traj_="TRAJ" in SELECTED_METRICS,
        isolisi_="ISOLISI" in SELECTED_METRICS,
        bras_="BRAS" in SELECTED_METRICS,
        kbet_="KBET" in SELECTED_METRICS,
        cpcr_="CPCR" in SELECTED_METRICS,
    )
    metric_series = metric_df.iloc[:, 0]

    result = {
        key: metric_value(metric_series, key)
        for key in SELECTED_METRICS
    }
    bio_score = float(
        np.mean([result[key] for key in SELECTED_BIO_METRICS])
    )
    batch_score = float(
        np.mean([result[key] for key in SELECTED_BATCH_METRICS])
    )
    joint_score = float(0.6 * bio_score + 0.4 * batch_score)

    if not np.all(np.isfinite([bio_score, batch_score, joint_score])):
        raise ValueError(
            "Aggregation produced a non-finite score: "
            f"bio={bio_score}, batch={batch_score}, "
            f"joint={joint_score}"
        )

    result["bio_score"] = bio_score
    result["batch_score"] = batch_score
    result["joint_score"] = joint_score
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_harmony_default(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

2026-07-21 15:17:23,023 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:17:23,413 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.77it/s]

100%|██████████| 2/2 [00:00<00:00,  3.33it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.5619922429104436

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6762286417454111

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6304067845411001

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6065015272841888

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5581192327526717

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5412292381970406

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5276805034816675

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5236721990181338

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5121132509478872

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5009097900035241

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-07-21 15:18:55,148:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6762286417454111
BRAS...

seed           0.000000
BAMI           0.676229
CASW           0.501950
SCGRAPHM       0.995542
BRAS           0.847538
KBET           0.565251
CPCR           0.957841
bio_score      0.724573
batch_score    0.790210
joint_score    0.750828
dtype: float64

===== seed 1 =====

2026-07-21 15:19:06,031 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:19:06,392 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.80it/s]

100%|██████████| 2/2 [00:00<00:00,  3.45it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6311276279456625

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6360349323475158

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6316552170626211

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.611637802256718

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5872813191242886

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5428236306050175

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5205564327222453

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5082522664796008

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.496142150006527

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4902002066242486

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6360349323475158
BRAS...

seed           1.000000
BAMI           0.636035
CASW           0.501230
SCGRAPHM       0.995538
BRAS           0.850265
KBET           0.566509
CPCR           0.959932
bio_score      0.710935
batch_score    0.792235
joint_score    0.743455
dtype: float64

===== seed 2 =====

2026-07-21 15:20:35,314 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:20:35,672 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.84it/s]

100%|██████████| 2/2 [00:00<00:00,  3.52it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.5765297851049392

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5568876511249007

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6299004775606643

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5550805807222184

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5532854758113301

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5392259146323347

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5238690505664941

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.521260853546037

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5101316752568236

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4949475106563169

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6299004775606643
BRAS...

seed           2.000000
BAMI           0.629900
CASW           0.501215
SCGRAPHM       0.995618
BRAS           0.848162
KBET           0.565759
CPCR           0.958235
bio_score      0.708911
batch_score    0.790718
joint_score    0.741634
dtype: float64

===== seed 3 =====

2026-07-21 15:21:58,813 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:21:59,167 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.78it/s]

100%|██████████| 2/2 [00:00<00:00,  3.41it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.547299051702046

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5737460170963

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6055451957168544

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5882966365629517

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.541099526294515

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.524391358139894

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5202306481938364

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.512158648775664

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5036051160793646

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5024851847847572

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6055451957168544
BRAS...

seed           3.000000
BAMI           0.605545
CASW           0.500425
SCGRAPHM       0.995345
BRAS           0.857762
KBET           0.567893
CPCR           0.966295
bio_score      0.700438
batch_score    0.797317
joint_score    0.739190
dtype: float64

===== seed 4 =====

2026-07-21 15:23:17,702 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:23:18,084 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.77it/s]

100%|██████████| 2/2 [00:00<00:00,  3.36it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.5772646940822463

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5585626561475038

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6500669203609019

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6047464957610695

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5383730766926186

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5339504139586184

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5196851168912396

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5119620997705652

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5110719079465826

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49693175927088956

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6500669203609019
BRAS...

seed           4.000000
BAMI           0.650067
CASW           0.500528
SCGRAPHM       0.995717
BRAS           0.849111
KBET           0.566151
CPCR           0.958877
bio_score      0.715437
batch_score    0.791380
joint_score    0.745814
dtype: float64

===== seed 5 =====

2026-07-21 15:24:41,399 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:24:41,765 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.74it/s]

100%|██████████| 2/2 [00:00<00:00,  3.33it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.5616249956136177

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5550251086123564

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6267726874112379

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6023762717044995

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5575354685372372

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5300784697185512

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.529041277561706

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5167030344407738

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5080684081981668

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5015302339280735

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6267726874112379
BRAS...

seed           5.000000
BAMI           0.626773
CASW           0.501187
SCGRAPHM       0.995555
BRAS           0.851121
KBET           0.566529
CPCR           0.960705
bio_score      0.707838
batch_score    0.792785
joint_score    0.741817
dtype: float64

===== seed 6 =====

2026-07-21 15:26:13,572 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:26:13,953 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.83it/s]

100%|██████████| 2/2 [00:00<00:00,  3.50it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.5544572762324534

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6479581396593114

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6289528152134243

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5990101105461841

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5481070552029257

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5273731208087422

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5166627729221689

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5072727895354583

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.50581195969383

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49906298335047133

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6479581396593114
BRAS...

seed           6.000000
BAMI           0.647958
CASW           0.500392
SCGRAPHM       0.995342
BRAS           0.856569
KBET           0.567414
CPCR           0.965288
bio_score      0.714564
batch_score    0.796424
joint_score    0.747308
dtype: float64

===== seed 7 =====

2026-07-21 15:27:39,439 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:27:39,796 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.70it/s]

100%|██████████| 2/2 [00:00<00:00,  3.23it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.5278661213815234

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5924640116395534

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6572521029247197

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6276217690177662

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5882341633175023

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5331286387690309

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5207501867139627

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5188493858107843

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5067452981923187

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5049953696346453

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6572521029247197
BRAS...

seed           7.000000
BAMI           0.657252
CASW           0.501824
SCGRAPHM       0.995403
BRAS           0.850253
KBET           0.566146
CPCR           0.959718
bio_score      0.718160
batch_score    0.792039
joint_score    0.747711
dtype: float64

===== seed 8 =====

2026-07-21 15:29:03,388 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:29:03,754 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.76it/s]

100%|██████████| 2/2 [00:00<00:00,  3.35it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.5794496043515572

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6790633238119809

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.629758774423064

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5933794798921594

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5422614672499493

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5341753258325214

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.524011134792032

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5221608130429688

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.517380400523521

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4979834984082502

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6790633238119809
BRAS...

seed           8.000000
BAMI           0.679063
CASW           0.501318
SCGRAPHM       0.995541
BRAS           0.850669
KBET           0.566442
CPCR           0.960366
bio_score      0.725307
batch_score    0.792492
joint_score    0.752181
dtype: float64

===== seed 9 =====

2026-07-21 15:30:29,725 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-21 15:30:30,122 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.75it/s]

100%|██████████| 2/2 [00:00<00:00,  3.33it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6345171962022483

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5555635876211874

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5495658803659947

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5305044192981306

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5310919666964082

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.541322238700072

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5124261449736864

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4953707583315668

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5018322562945323

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5033162003539242

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6345171962022483
BRAS...

seed           9.000000
BAMI           0.634517
CASW           0.501225
SCGRAPHM       0.995593
BRAS           0.849716
KBET           0.565914
CPCR           0.959601
bio_score      0.710445
batch_score    0.791744
joint_score    0.742965
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.676229,0.501950,0.995542,0.847538,0.565251,0.957841,0.724573,0.790210,0.750828
1,1,0.636035,0.501230,0.995538,0.850265,0.566509,0.959932,0.710935,0.792235,0.743455
2,2,0.629900,0.501215,0.995618,0.848162,0.565759,0.958235,0.708911,0.790718,0.741634
3,3,0.605545,0.500425,0.995345,0.857762,0.567893,0.966295,0.700438,0.797317,0.739190
4,4,0.650067,0.500528,0.995717,0.849111,0.566151,0.958877,0.715437,0.791380,0.745814
5,5,0.626773,0.501187,0.995555,0.851121,0.566529,0.960705,0.707838,0.792785,0.741817
6,6,0.647958,0.500392,0.995342,0.856569,0.567414,0.965288,0.714564,0.796424,0.747308
7,7,0.657252,0.501824,0.995403,0.850253,0.566146,0.959718,0.718160,0.792039,0.747711
8,8,0.679063,0.501318,0.995541,0.850669,0.566442,0.960366,0.725307,0.792492,0.752181
9,9,0.634517,0.501225,0.995593,0.849716,0.565914,0.959601,0.710445,0.791744,0.742965

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.644334  0.021501  0.605545  0.679063
CASW         0.501129  0.000512  0.500392  0.501950
SCGRAPHM     0.995519  0.000115  0.995342  0.995717
BRAS         0.851116  0.003211  0.847538  0.857762
KBET         0.566401  0.000734  0.565251  0.567893
CPCR         0.960686  0.002698  0.957841  0.966295
bio_score    0.713661  0.007266  0.700438  0.725307
batch_score  0.792734  0.002206  0.790210  0.797317
joint_score  0.745290  0.003997  0.739190  0.752181