# Harmony best - mouse_regulatory_T

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import harmonypy as hm
import numpy as np
import pandas as pd
import scanpy as sc

from scib.metrics.metrics import metrics

In [2]:
DATASET_NAME = 'mouse_regulatory_T'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'method'
LABEL_KEY = 'cell.type'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_PCS = 50
N_NEIGHBORS = 15
N_TOP_HVG = 2000

EMBED_KEY = "X_harmony"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "harmony_metric_batch"
METRIC_LABEL_KEY = "harmony_metric_label"

assert DATASET_NAME == 'mouse_regulatory_T'
assert BATCH_KEY == 'method'
assert LABEL_KEY == 'cell.type'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
    },
    name="configuration",
)

dataset                                     mouse_regulatory_T
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                               method
label_key                                            cell.type
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                           [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Name: configuration, dtype: object

In [3]:
def validate_dataset_contents():
    adata_backed = ad.read_h5ad(DATA_PATH, backed="r")
    try:
        required_keys = (BATCH_KEY, LABEL_KEY)
        missing_keys = [
            key for key in required_keys if key not in adata_backed.obs
        ]
        if missing_keys:
            raise ValueError(
                f"Missing obs keys {missing_keys}. "
                f"Available keys: {list(adata_backed.obs.columns)}"
            )

        obs = adata_backed.obs[[BATCH_KEY, LABEL_KEY]].copy()
        pseudotime = None
        if "TRAJ" in SELECTED_METRICS:
            if "dpt_pseudotime" not in adata_backed.obs:
                raise ValueError(
                    "TRAJ requires adata.obs['dpt_pseudotime']."
                )
            pseudotime = adata_backed.obs["dpt_pseudotime"].copy()

        n_obs = int(adata_backed.n_obs)
        n_vars = int(adata_backed.n_vars)
    finally:
        adata_backed.file.close()

    if obs.isna().any().any():
        raise ValueError(
            "Missing batch/label values: "
            f"{obs.isna().sum().to_dict()}"
        )

    n_batches = int(obs[BATCH_KEY].nunique())
    n_labels = int(obs[LABEL_KEY].nunique())
    if n_batches < 2:
        raise ValueError(
            f"Batch metrics require at least 2 batches; found {n_batches}."
        )

    batch_coverage = obs.groupby(
        LABEL_KEY,
        observed=True,
    )[BATCH_KEY].nunique()
    label_counts = obs.groupby(LABEL_KEY, observed=True).size()

    if "TRAJ" in SELECTED_METRICS:
        finite_pseudotime = pseudotime.dropna()
        if (
            len(finite_pseudotime) < 2
            or finite_pseudotime.nunique() < 2
        ):
            raise ValueError(
                "TRAJ requires at least 2 usable pseudotime values."
            )

    if "ISOLISI" in SELECTED_METRICS:
        min_batch_coverage = int(batch_coverage.min())
        if min_batch_coverage >= n_batches:
            raise ValueError(
                "ISOLISI is enabled, but every label appears in all batches."
            )

    eligible_cpcr_labels = [
        str(label)
        for label in label_counts.index
        if int(label_counts.loc[label]) >= 100
        and int(batch_coverage.loc[label]) >= 2
    ]
    if "CPCR" in SELECTED_METRICS and not eligible_cpcr_labels:
        raise ValueError(
            "CPCR requires a label with at least 100 cells across "
            "at least 2 batches."
        )

    return {
        "n_obs": n_obs,
        "n_vars": n_vars,
        "n_batches": n_batches,
        "n_labels": n_labels,
        "cpcr_eligible_labels": len(eligible_cpcr_labels),
    }


validate_dataset_contents()

{'n_obs': 34697,
 'n_vars': 11765,
 'n_batches': 2,
 'n_labels': 3,
 'cpcr_eligible_labels': 2}

In [4]:
OPTUNA_STUDY_NAME = 'harmony_mouse_regulatory_T_joint_expanded_metrics_scgraphm_v2'
OPTUNA_BEST_TRIAL = 194
OPTUNA_BEST_VALUE = 0.7705248028607997
OPTUNA_BEST_PARAMS = {'theta': 8.40362236809307, 'sigma': 1.8289185665622578, 'lamb_mode': 'fixed', 'lamb': 3.050817430617729, 'tau': 0.4544509783817766, 'nclust': 141}

if OPTUNA_BEST_PARAMS["lamb_mode"] == "auto":
    resolved_lamb = -1
else:
    resolved_lamb = OPTUNA_BEST_PARAMS["lamb"]

HARMONY_BEST_ARGS = {
    "theta": OPTUNA_BEST_PARAMS["theta"],
    "lamb": resolved_lamb,
    "sigma": OPTUNA_BEST_PARAMS["sigma"],
    "nclust": OPTUNA_BEST_PARAMS["nclust"],
    "tau": OPTUNA_BEST_PARAMS["tau"],
    "block_size": 0.05,
    "max_iter_harmony": 10,
    "max_iter_kmeans": 20,
    "epsilon_cluster": 1e-5,
    "epsilon_harmony": 1e-4,
    "alpha": 0.2,
}


def run_harmony_best(adata, seed):
    adata_int = adata.copy()

    if "highly_variable" in adata_int.var:
        adata_int = adata_int[:, adata_int.var["highly_variable"]].copy()
    else:
        sc.pp.highly_variable_genes(
            adata_int,
            flavor="seurat",
            n_top_genes=N_TOP_HVG,
        )
        adata_int = adata_int[:, adata_int.var["highly_variable"]].copy()

    sc.tl.pca(
        adata_int,
        n_comps=N_PCS,
        svd_solver="arpack",
    )
    x_pca = np.asarray(adata_int.obsm["X_pca"], dtype=np.float32)

    harmony_result = hm.run_harmony(
        x_pca,
        adata_int.obs,
        BATCH_KEY,
        **HARMONY_BEST_ARGS,
        verbose=False,
        random_state=seed,
        device="cpu",
    )

    x_harmony = np.asarray(harmony_result.Z_corr)
    if (
        x_harmony.shape[0] != adata_int.n_obs
        and x_harmony.shape[1] == adata_int.n_obs
    ):
        x_harmony = x_harmony.T
    if x_harmony.shape[0] != adata_int.n_obs:
        raise ValueError(
            f"Harmony output shape {x_harmony.shape} is incompatible "
            f"with n_obs={adata_int.n_obs}."
        )
    if not np.all(np.isfinite(x_harmony)):
        raise ValueError("Harmony produced NaN or Inf in X_harmony.")

    adata_int.obsm[EMBED_KEY] = x_harmony
    return adata_int


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **HARMONY_BEST_ARGS,
    },
    name="best_setting",
)

study               harmony_mouse_regulatory_T_joint_expanded_metr...
best_trial                                                        194
best_value                                                   0.770525
theta                                                        8.403622
lamb                                                         3.050817
sigma                                                        1.828919
nclust                                                            141
tau                                                          0.454451
block_size                                                       0.05
max_iter_harmony                                                   10
max_iter_kmeans                                                    20
epsilon_cluster                                               0.00001
epsilon_harmony                                                0.0001
alpha                                                             0.2
Name: best_setting, dtype: object

In [5]:
def metric_value(metric_series, key):
    if key not in metric_series.index:
        raise KeyError(
            f"Metric {key} not found. "
            f"Available metrics: {list(metric_series.index)}"
        )

    value = metric_series[key]
    if isinstance(value, (list, tuple, np.ndarray)):
        values = np.asarray(value, dtype=float)
        if values.size == 0 or not np.all(np.isfinite(values)):
            raise ValueError(
                f"Metric {key} returned non-finite values: {values}"
            )
        return float(np.mean(values))

    value = float(value)
    if not np.isfinite(value):
        raise ValueError(
            f"Metric {key} returned a non-finite value: {value}"
        )
    return value


def compute_joint_metrics(adata_raw, adata_int):
    sc.pp.neighbors(
        adata_int,
        use_rep=EMBED_KEY,
        n_neighbors=N_NEIGHBORS,
        random_state=0,
    )

    metric_key_map = {
        METRIC_BATCH_KEY: BATCH_KEY,
        METRIC_LABEL_KEY: LABEL_KEY,
    }
    for adata_name, adata_obj in (
        ("adata_raw", adata_raw),
        ("adata_int", adata_int),
    ):
        existing_aliases = [
            alias for alias in metric_key_map if alias in adata_obj.obs
        ]
        if existing_aliases:
            raise ValueError(
                f"Reserved metric obs keys already exist in {adata_name}: "
                f"{existing_aliases}"
            )
        for alias, source_key in metric_key_map.items():
            adata_obj.obs[alias] = adata_obj.obs[source_key].copy()

    metric_df = metrics(
        adata=adata_raw,
        adata_int=adata_int,
        batch_key=METRIC_BATCH_KEY,
        label_key=METRIC_LABEL_KEY,
        embed=EMBED_KEY,
        cluster_key=CLUSTER_KEY,
        verbose=False,
        bami_="BAMI" in SELECTED_METRICS,
        casw_="CASW" in SELECTED_METRICS,
        scgraphm_="SCGRAPHM" in SELECTED_METRICS,
        traj_="TRAJ" in SELECTED_METRICS,
        isolisi_="ISOLISI" in SELECTED_METRICS,
        bras_="BRAS" in SELECTED_METRICS,
        kbet_="KBET" in SELECTED_METRICS,
        cpcr_="CPCR" in SELECTED_METRICS,
    )
    metric_series = metric_df.iloc[:, 0]

    result = {
        key: metric_value(metric_series, key)
        for key in SELECTED_METRICS
    }
    bio_score = float(
        np.mean([result[key] for key in SELECTED_BIO_METRICS])
    )
    batch_score = float(
        np.mean([result[key] for key in SELECTED_BATCH_METRICS])
    )
    joint_score = float(0.6 * bio_score + 0.4 * batch_score)

    if not np.all(np.isfinite([bio_score, batch_score, joint_score])):
        raise ValueError(
            "Aggregation produced a non-finite score: "
            f"bio={bio_score}, batch={batch_score}, "
            f"joint={joint_score}"
        )

    result["bio_score"] = bio_score
    result["batch_score"] = batch_score
    result["joint_score"] = joint_score
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_harmony_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

2026-07-23 11:07:53,968 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:07:54,695 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.65it/s]

100%|██████████| 2/2 [00:00<00:00,  3.10it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.644597244679255

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5603273128757278

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6247369685632987

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6017714935702275

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.593828398354706

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5422372423544238

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5307968805715794

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5150365032135797

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4988592575347296

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5046615631156958

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-07-23 11:09:49,544:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.644597244679255
BRAS...

seed           0.000000
BAMI           0.644597
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944497
KBET           0.506832
CPCR           0.975821
bio_score      0.715714
batch_score    0.809050
joint_score    0.753048
dtype: float64

===== seed 1 =====

2026-07-23 11:10:25,768 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:10:26,653 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.49it/s]

100%|██████████| 2/2 [00:00<00:00,  2.84it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.5705833723225459

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.560396954061014

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6229060720857812

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5969555701547367

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5556063226722583

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5340126847933553

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5264701763775419

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5128798099901082

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5037399101126785

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4987514344592455

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6229060720857812
BRAS...

seed           1.000000
BAMI           0.622906
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944497
KBET           0.506832
CPCR           0.975821
bio_score      0.708484
batch_score    0.809050
joint_score    0.748710
dtype: float64

===== seed 2 =====

2026-07-23 11:12:42,932 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:12:43,821 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.43it/s]

100%|██████████| 2/2 [00:00<00:00,  2.73it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6444454318700108

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7236462828447787

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.637959727266605

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6209744959877402

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.565426783136706

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5554567466642167

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.540746093123316

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5255774556305245

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4987702426743984

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4879372158969875

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7236462828447787
BRAS...

seed           2.000000
BAMI           0.723646
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944497
KBET           0.506832
CPCR           0.975820
bio_score      0.742064
batch_score    0.809050
joint_score    0.768858
dtype: float64

===== seed 3 =====

2026-07-23 11:15:06,887 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:15:07,780 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.50it/s]

100%|██████████| 2/2 [00:00<00:00,  2.87it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6044523267063642

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6307851847940593

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6227702365396183

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6073291710351846

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5893203915439886

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5358749531241531

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5266076328099356

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5169485172844197

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5004568985414146

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5005500918658427

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6307851847940593
BRAS...

seed           3.000000
BAMI           0.630785
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944497
KBET           0.506832
CPCR           0.975820
bio_score      0.711110
batch_score    0.809050
joint_score    0.750286
dtype: float64

===== seed 4 =====

2026-07-23 11:17:46,232 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:17:47,065 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.55it/s]

100%|██████████| 2/2 [00:00<00:00,  2.96it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6462269542889622

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6233041241587848

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6337977612223419

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6172313663334651

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5601187575738914

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5551175177332991

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.542683622899889

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5065245983426782

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5102602412811996

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49492296077824866

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6462269542889622
BRAS...

seed           4.000000
BAMI           0.646227
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944496
KBET           0.506832
CPCR           0.975820
bio_score      0.716257
batch_score    0.809050
joint_score    0.753374
dtype: float64

===== seed 5 =====

2026-07-23 11:19:55,067 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:19:55,707 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.55it/s]

100%|██████████| 2/2 [00:00<00:00,  2.94it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6029340601945666

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5560749712987143

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6304257507190321

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6120513748651006

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5694105165304649

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5466887637347138

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5276906250402128

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.526528632559638

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5178230638442253

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5047986748165627

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6304257507190321
BRAS...

seed           5.000000
BAMI           0.630426
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944497
KBET           0.506832
CPCR           0.975820
bio_score      0.710990
batch_score    0.809050
joint_score    0.750214
dtype: float64

===== seed 6 =====

2026-07-23 11:22:18,098 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:22:18,698 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.59it/s]

100%|██████████| 2/2 [00:00<00:00,  3.02it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.646120523105546

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6796062418325848

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6396584916187683

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.604565580259444

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5871515417361419

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5549588479996717

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5515920846360474

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5217878092376982

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.49406017810251396

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49691530443541043

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6796062418325848
BRAS...

seed           6.000000
BAMI           0.679606
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944497
KBET           0.506832
CPCR           0.975821
bio_score      0.727384
batch_score    0.809050
joint_score    0.760050
dtype: float64

===== seed 7 =====

2026-07-23 11:24:23,109 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:24:23,954 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.72it/s]

100%|██████████| 2/2 [00:00<00:00,  3.28it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6074556577483207

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5608668790861752

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6278883274052343

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6001666599437314

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5675093270408648

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.554284485339026

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5482196461895394

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5187972434008763

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5033946300177022

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49894781798666266

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6278883274052343
BRAS...

seed           7.000000
BAMI           0.627888
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944497
KBET           0.506832
CPCR           0.975820
bio_score      0.710144
batch_score    0.809050
joint_score    0.749706
dtype: float64

===== seed 8 =====

2026-07-23 11:26:31,107 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:26:31,615 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.69it/s]

100%|██████████| 2/2 [00:00<00:00,  3.19it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6467109684523287

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5606214271379513

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6239573261291717

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5996942315940312

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.587108751898409

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5402761982780973

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5267923040321111

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5129857603506065

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4962631002465292

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49123388962987735

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6467109684523287
BRAS...

seed           8.000000
BAMI           0.646711
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944496
KBET           0.506832
CPCR           0.975820
bio_score      0.716418
batch_score    0.809050
joint_score    0.753471
dtype: float64

===== seed 9 =====

2026-07-23 11:28:33,232 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...

2026-07-23 11:28:33,914 - harmonypy - INFO - KMeans initialization complete.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.49it/s]

100%|██████████| 2/2 [00:00<00:00,  2.85it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6078064054913553

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6308283160592364

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6255764378873728

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6045230715980994

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5941983400094525

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5607961914101764

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5426970915349238

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5237562901231947

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5121384406836466

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5047058475330951

optimised clustering against harmony_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6308283160592364
BRAS...

seed           9.000000
BAMI           0.630828
CASW           0.507840
SCGRAPHM       0.994704
BRAS           0.944497
KBET           0.506832
CPCR           0.975821
bio_score      0.711124
batch_score    0.809050
joint_score    0.750294
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.644597,0.50784,0.994704,0.944497,0.506832,0.975821,0.715714,0.80905,0.753048
1,1,0.622906,0.50784,0.994704,0.944497,0.506832,0.975821,0.708484,0.80905,0.748710
2,2,0.723646,0.50784,0.994704,0.944497,0.506832,0.975820,0.742064,0.80905,0.768858
3,3,0.630785,0.50784,0.994704,0.944497,0.506832,0.975820,0.711110,0.80905,0.750286
4,4,0.646227,0.50784,0.994704,0.944496,0.506832,0.975820,0.716257,0.80905,0.753374
5,5,0.630426,0.50784,0.994704,0.944497,0.506832,0.975820,0.710990,0.80905,0.750214
6,6,0.679606,0.50784,0.994704,0.944497,0.506832,0.975821,0.727384,0.80905,0.760050
7,7,0.627888,0.50784,0.994704,0.944497,0.506832,0.975820,0.710144,0.80905,0.749706
8,8,0.646711,0.50784,0.994704,0.944496,0.506832,0.975820,0.716418,0.80905,0.753471
9,9,0.630828,0.50784,0.994704,0.944497,0.506832,0.975821,0.711124,0.80905,0.750294

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean           std       min       max
BAMI         0.648362  2.944596e-02  0.622906  0.723646
CASW         0.507840  9.607079e-09  0.507840  0.507840
SCGRAPHM     0.994704  1.832373e-09  0.994704  0.994704
BRAS         0.944497  3.209808e-08  0.944496  0.944497
KBET         0.506832  0.000000e+00  0.506832  0.506832
CPCR         0.975821  1.088084e-07  0.975820  0.975821
bio_score    0.716969  9.815317e-03  0.708484  0.742064
batch_score  0.809050  3.862765e-08  0.809050  0.809050
joint_score  0.753801  5.889187e-03  0.748710  0.768858