# LIGER default - mouse_regulatory_T

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'mouse_regulatory_T'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'method'
LABEL_KEY = 'cell.type'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'mouse_regulatory_T'
assert BATCH_KEY == 'method'
assert LABEL_KEY == 'cell.type'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                     mouse_regulatory_T
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                               method
label_key                                            cell.type
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=34697 n_batches=2 n_labels=3
CPCR preflight: eligible_labels=2

In [4]:
LIGER_DEFAULT_ARGS = {
    "k": 20,
    "value_lambda": 5.0,
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_default(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_DEFAULT_ARGS["k"],
        lam=LIGER_DEFAULT_ARGS["value_lambda"],
        max_iterations=LIGER_DEFAULT_ARGS["max_iters"],
        mode=LIGER_DEFAULT_ARGS["mode"],
        layer=LIGER_DEFAULT_ARGS["layer"],
        seed=seed,
    )


pd.Series(LIGER_DEFAULT_ARGS, name="default_setting")

k                   20
value_lambda       5.0
max_iters           30
mode              core
layer           counts
Name: default_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_default(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:09<04:32,  9.38s/it]

  7%|▋         | 2/30 [00:19<04:37,  9.90s/it]

 10%|█         | 3/30 [00:30<04:33, 10.13s/it]

 13%|█▎        | 4/30 [00:39<04:21, 10.06s/it]

 17%|█▋        | 5/30 [00:49<04:09,  9.99s/it]

 20%|██        | 6/30 [01:00<04:01, 10.05s/it]

 23%|██▎       | 7/30 [01:10<03:51, 10.07s/it]

 27%|██▋       | 8/30 [01:20<03:44, 10.21s/it]

 30%|███       | 9/30 [01:30<03:32, 10.10s/it]

 33%|███▎      | 10/30 [01:40<03:20, 10.03s/it]

 37%|███▋      | 11/30 [01:50<03:09,  9.97s/it]

 40%|████      | 12/30 [02:01<03:05, 10.29s/it]

 43%|████▎     | 13/30 [02:11<02:53, 10.18s/it]

 47%|████▋     | 14/30 [02:21<02:41, 10.09s/it]

 50%|█████     | 15/30 [02:32<02:35, 10.38s/it]

 53%|█████▎    | 16/30 [02:43<02:27, 10.54s/it]

 57%|█████▋    | 17/30 [02:52<02:14, 10.35s/it]

 60%|██████    | 18/30 [03:02<02:02, 10.25s/it]

 63%|██████▎   | 19/30 [03:12<01:51, 10.15s/it]

 67%|██████▋   | 20/30 [03:22<01:40, 10.10s/it]

 70%|███████   | 21/30 [03:32<01:30, 10.11s/it]

 73%|███████▎  | 22/30 [03:42<01:20, 10.07s/it]

 77%|███████▋  | 23/30 [03:52<01:10, 10.03s/it]

 80%|████████  | 24/30 [04:02<01:00, 10.02s/it]

 83%|████████▎ | 25/30 [04:12<00:50, 10.01s/it]

 87%|████████▋ | 26/30 [04:22<00:39,  9.99s/it]

 90%|█████████ | 27/30 [04:32<00:29, 10.00s/it]

 93%|█████████▎| 28/30 [04:44<00:20, 10.36s/it]

 97%|█████████▋| 29/30 [04:54<00:10, 10.52s/it]

100%|██████████| 30/30 [05:04<00:00, 10.34s/it]

100%|██████████| 30/30 [05:04<00:00, 10.16s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.46s/it]

100%|██████████| 2/2 [00:01<00:00,  1.31it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.725294592196696

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6485826400166507

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6147925620141752

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5659931692664416

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5598045278047452

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5050874664233873

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.4832860868884636

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4791353373717075

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4755481490228604

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4685075611688508

WARNING:2026-07-23 16:42:10,796:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.725294592196696
BRAS...

seed           1.000000
BAMI           0.725295
CASW           0.565275
SCGRAPHM       0.983208
BRAS           0.851868
KBET           0.869567
CPCR           0.969215
bio_score      0.757926
batch_score    0.896883
joint_score    0.813509
dtype: float64

===== seed 2 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:11<05:25, 11.21s/it]

  7%|▋         | 2/30 [00:23<05:26, 11.66s/it]

 10%|█         | 3/30 [00:33<05:00, 11.12s/it]

 13%|█▎        | 4/30 [00:43<04:37, 10.68s/it]

 17%|█▋        | 5/30 [00:53<04:19, 10.39s/it]

 20%|██        | 6/30 [01:03<04:05, 10.22s/it]

 23%|██▎       | 7/30 [01:13<03:52, 10.10s/it]

 27%|██▋       | 8/30 [01:23<03:40, 10.02s/it]

 30%|███       | 9/30 [01:33<03:29,  9.98s/it]

 33%|███▎      | 10/30 [01:42<03:18,  9.94s/it]

 37%|███▋      | 11/30 [01:52<03:08,  9.93s/it]

 40%|████      | 12/30 [02:02<02:58,  9.92s/it]

 43%|████▎     | 13/30 [02:12<02:48,  9.91s/it]

 47%|████▋     | 14/30 [02:22<02:38,  9.89s/it]

 50%|█████     | 15/30 [02:32<02:28,  9.88s/it]

 53%|█████▎    | 16/30 [02:42<02:18,  9.87s/it]

 57%|█████▋    | 17/30 [02:52<02:08,  9.87s/it]

 60%|██████    | 18/30 [03:03<02:02, 10.21s/it]

 63%|██████▎   | 19/30 [03:14<01:55, 10.46s/it]

 67%|██████▋   | 20/30 [03:23<01:42, 10.29s/it]

 70%|███████   | 21/30 [03:33<01:31, 10.18s/it]

 73%|███████▎  | 22/30 [03:43<01:20, 10.09s/it]

 77%|███████▋  | 23/30 [03:53<01:10, 10.04s/it]

 80%|████████  | 24/30 [04:03<01:00, 10.04s/it]

 83%|████████▎ | 25/30 [04:13<00:50, 10.02s/it]

 87%|████████▋ | 26/30 [04:23<00:39,  9.98s/it]

 90%|█████████ | 27/30 [04:33<00:29,  9.94s/it]

 93%|█████████▎| 28/30 [04:43<00:19,  9.96s/it]

 97%|█████████▋| 29/30 [04:55<00:10, 10.50s/it]

100%|██████████| 30/30 [05:06<00:00, 10.67s/it]

100%|██████████| 30/30 [05:06<00:00, 10.21s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.40s/it]

100%|██████████| 2/2 [00:01<00:00,  1.37it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.73665949622184

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6698960782116095

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6022488559530795

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5889163726637217

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5450133477556325

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5202984441331553

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5000194919255321

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4868243497121311

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.47981441185472506

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4759786864126641

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.73665949622184
BRAS...

seed           2.000000
BAMI           0.736659
CASW           0.570709
SCGRAPHM       0.988152
BRAS           0.852437
KBET           0.867677
CPCR           0.970659
bio_score      0.765174
batch_score    0.896924
joint_score    0.817874
dtype: float64

===== seed 3 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:10<04:53, 10.11s/it]

  7%|▋         | 2/30 [00:20<04:41, 10.05s/it]

 10%|█         | 3/30 [00:30<04:31, 10.04s/it]

 13%|█▎        | 4/30 [00:40<04:20, 10.01s/it]

 17%|█▋        | 5/30 [00:49<04:08,  9.95s/it]

 20%|██        | 6/30 [00:59<03:57,  9.91s/it]

 23%|██▎       | 7/30 [01:09<03:47,  9.89s/it]

 27%|██▋       | 8/30 [01:19<03:39,  9.98s/it]

 30%|███       | 9/30 [01:29<03:29,  9.99s/it]

 33%|███▎      | 10/30 [01:39<03:19,  9.96s/it]

 37%|███▋      | 11/30 [01:49<03:08,  9.93s/it]

 40%|████      | 12/30 [01:59<02:59, 10.00s/it]

 43%|████▎     | 13/30 [02:09<02:49,  9.99s/it]

 47%|████▋     | 14/30 [02:19<02:38,  9.94s/it]

 50%|█████     | 15/30 [02:29<02:28,  9.88s/it]

 53%|█████▎    | 16/30 [02:39<02:18,  9.91s/it]

 57%|█████▋    | 17/30 [02:49<02:12, 10.16s/it]

 60%|██████    | 18/30 [03:00<02:04, 10.39s/it]

 63%|██████▎   | 19/30 [03:10<01:52, 10.23s/it]

 67%|██████▋   | 20/30 [03:20<01:41, 10.10s/it]

 70%|███████   | 21/30 [03:30<01:30, 10.02s/it]

 73%|███████▎  | 22/30 [03:40<01:19,  9.96s/it]

 77%|███████▋  | 23/30 [03:50<01:09,  9.92s/it]

 80%|████████  | 24/30 [03:59<00:59,  9.90s/it]

 83%|████████▎ | 25/30 [04:09<00:49,  9.88s/it]

 87%|████████▋ | 26/30 [04:19<00:39,  9.87s/it]

 90%|█████████ | 27/30 [04:29<00:29,  9.86s/it]

 93%|█████████▎| 28/30 [04:39<00:19,  9.92s/it]

 97%|█████████▋| 29/30 [04:49<00:10, 10.01s/it]

100%|██████████| 30/30 [04:59<00:00,  9.97s/it]

100%|██████████| 30/30 [04:59<00:00,  9.99s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.47s/it]

100%|██████████| 2/2 [00:01<00:00,  1.31it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7493703070026617

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6824965926458574

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6286818496937828

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5933651348520111

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5619800135620417

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5163425872707224

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5016398555047583

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5067213855926007

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4826314110908839

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.47702069224725563

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7493703070026617
BRAS...

seed           3.000000
BAMI           0.749370
CASW           0.568537
SCGRAPHM       0.983976
BRAS           0.859013
KBET           0.871411
CPCR           0.972471
bio_score      0.767294
batch_score    0.900965
joint_score    0.820763
dtype: float64

===== seed 4 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:09<04:36,  9.52s/it]

  7%|▋         | 2/30 [00:20<04:51, 10.41s/it]

 10%|█         | 3/30 [00:30<04:38, 10.31s/it]

 13%|█▎        | 4/30 [00:40<04:25, 10.21s/it]

 17%|█▋        | 5/30 [00:51<04:21, 10.46s/it]

 20%|██        | 6/30 [01:01<04:06, 10.26s/it]

 23%|██▎       | 7/30 [01:11<03:52, 10.13s/it]

 27%|██▋       | 8/30 [01:21<03:41, 10.05s/it]

 30%|███       | 9/30 [01:31<03:32, 10.10s/it]

 33%|███▎      | 10/30 [01:41<03:21, 10.07s/it]

 37%|███▋      | 11/30 [01:51<03:10, 10.01s/it]

 40%|████      | 12/30 [02:01<03:01, 10.07s/it]

 43%|████▎     | 13/30 [02:11<02:50, 10.01s/it]

 47%|████▋     | 14/30 [02:21<02:39,  9.96s/it]

 50%|█████     | 15/30 [02:31<02:32, 10.14s/it]

 53%|█████▎    | 16/30 [02:41<02:20, 10.04s/it]

 57%|█████▋    | 17/30 [02:51<02:09,  9.98s/it]

 60%|██████    | 18/30 [03:01<01:59,  9.93s/it]

 63%|██████▎   | 19/30 [03:11<01:48,  9.91s/it]

 67%|██████▋   | 20/30 [03:21<01:39,  9.95s/it]

 70%|███████   | 21/30 [03:31<01:29,  9.95s/it]

 73%|███████▎  | 22/30 [03:41<01:20, 10.01s/it]

 77%|███████▋  | 23/30 [03:51<01:09,  9.97s/it]

 80%|████████  | 24/30 [04:01<01:00, 10.13s/it]

 83%|████████▎ | 25/30 [04:11<00:50, 10.14s/it]

 87%|████████▋ | 26/30 [04:21<00:40, 10.07s/it]

 90%|█████████ | 27/30 [04:31<00:30, 10.01s/it]

 93%|█████████▎| 28/30 [04:41<00:19,  9.98s/it]

 97%|█████████▋| 29/30 [04:51<00:10, 10.00s/it]

100%|██████████| 30/30 [05:01<00:00, 10.00s/it]

100%|██████████| 30/30 [05:01<00:00, 10.05s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.43s/it]

100%|██████████| 2/2 [00:01<00:00,  1.33it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7347221999656409

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6334477265820417

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6114021125826158

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5718998022763293

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5457479912304972

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5437878557833665

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5212077740580146

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4895521893829076

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.47646181201710774

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.48043675659768365

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7347221999656409
BRAS...

seed           4.000000
BAMI           0.734722
CASW           0.566437
SCGRAPHM       0.989795
BRAS           0.857476
KBET           0.882073
CPCR           0.973888
bio_score      0.763651
batch_score    0.904479
joint_score    0.819982
dtype: float64

===== seed 5 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:11<05:28, 11.33s/it]

  7%|▋         | 2/30 [00:21<04:59, 10.68s/it]

 10%|█         | 3/30 [00:31<04:45, 10.57s/it]

 13%|█▎        | 4/30 [00:41<04:27, 10.30s/it]

 17%|█▋        | 5/30 [00:51<04:13, 10.13s/it]

 20%|██        | 6/30 [01:01<04:03, 10.15s/it]

 23%|██▎       | 7/30 [01:11<03:51, 10.05s/it]

 27%|██▋       | 8/30 [01:21<03:39,  9.96s/it]

 30%|███       | 9/30 [01:31<03:27,  9.89s/it]

 33%|███▎      | 10/30 [01:41<03:17,  9.86s/it]

 37%|███▋      | 11/30 [01:50<03:06,  9.83s/it]

 40%|████      | 12/30 [02:00<02:56,  9.82s/it]

 43%|████▎     | 13/30 [02:10<02:46,  9.81s/it]

 47%|████▋     | 14/30 [02:20<02:36,  9.81s/it]

 50%|█████     | 15/30 [02:30<02:27,  9.81s/it]

 53%|█████▎    | 16/30 [02:39<02:17,  9.81s/it]

 57%|█████▋    | 17/30 [02:49<02:07,  9.82s/it]

 60%|██████    | 18/30 [02:59<01:58,  9.85s/it]

 63%|██████▎   | 19/30 [03:09<01:48,  9.87s/it]

 67%|██████▋   | 20/30 [03:19<01:38,  9.88s/it]

 70%|███████   | 21/30 [03:29<01:28,  9.87s/it]

 73%|███████▎  | 22/30 [03:39<01:18,  9.87s/it]

 77%|███████▋  | 23/30 [03:49<01:09,  9.90s/it]

 80%|████████  | 24/30 [03:58<00:59,  9.89s/it]

 83%|████████▎ | 25/30 [04:08<00:49,  9.88s/it]

 87%|████████▋ | 26/30 [04:18<00:39,  9.89s/it]

 90%|█████████ | 27/30 [04:28<00:29,  9.88s/it]

 93%|█████████▎| 28/30 [04:38<00:19,  9.88s/it]

 97%|█████████▋| 29/30 [04:48<00:09,  9.89s/it]

100%|██████████| 30/30 [04:58<00:00,  9.94s/it]

100%|██████████| 30/30 [04:58<00:00,  9.95s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.41s/it]

100%|██████████| 2/2 [00:01<00:00,  1.35it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7353764260190698

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.647512098584154

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5988607798826167

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5739076488069957

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5541834264177173

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5402484538040061

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5090761809861731

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5061795715249208

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4781885694804757

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.47776814433664877

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7353764260190698
BRAS...

seed           5.000000
BAMI           0.735376
CASW           0.566905
SCGRAPHM       0.987668
BRAS           0.873411
KBET           0.871267
CPCR           0.977484
bio_score      0.763317
batch_score    0.907387
joint_score    0.820945
dtype: float64

===== seed 6 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:09<04:31,  9.37s/it]

  7%|▋         | 2/30 [00:19<04:32,  9.73s/it]

 10%|█         | 3/30 [00:29<04:27,  9.90s/it]

 13%|█▎        | 4/30 [00:39<04:17,  9.92s/it]

 17%|█▋        | 5/30 [00:49<04:07,  9.90s/it]

 20%|██        | 6/30 [00:59<03:56,  9.86s/it]

 23%|██▎       | 7/30 [01:08<03:46,  9.84s/it]

 27%|██▋       | 8/30 [01:18<03:36,  9.83s/it]

 30%|███       | 9/30 [01:28<03:26,  9.83s/it]

 33%|███▎      | 10/30 [01:38<03:16,  9.83s/it]

 37%|███▋      | 11/30 [01:48<03:06,  9.84s/it]

 40%|████      | 12/30 [01:57<02:56,  9.83s/it]

 43%|████▎     | 13/30 [02:07<02:46,  9.82s/it]

 47%|████▋     | 14/30 [02:17<02:37,  9.82s/it]

 50%|█████     | 15/30 [02:27<02:27,  9.83s/it]

 53%|█████▎    | 16/30 [02:38<02:22, 10.19s/it]

 57%|█████▋    | 17/30 [02:49<02:17, 10.58s/it]

 60%|██████    | 18/30 [03:00<02:05, 10.44s/it]

 63%|██████▎   | 19/30 [03:09<01:52, 10.26s/it]

 67%|██████▋   | 20/30 [03:19<01:41, 10.13s/it]

 70%|███████   | 21/30 [03:29<01:31, 10.15s/it]

 73%|███████▎  | 22/30 [03:39<01:20, 10.12s/it]

 77%|███████▋  | 23/30 [03:49<01:10, 10.05s/it]

 80%|████████  | 24/30 [03:59<00:59,  9.99s/it]

 83%|████████▎ | 25/30 [04:09<00:49,  9.96s/it]

 87%|████████▋ | 26/30 [04:19<00:39,  9.94s/it]

 90%|█████████ | 27/30 [04:29<00:30, 10.04s/it]

 93%|█████████▎| 28/30 [04:39<00:20, 10.08s/it]

 97%|█████████▋| 29/30 [04:50<00:10, 10.14s/it]

100%|██████████| 30/30 [05:00<00:00, 10.05s/it]

100%|██████████| 30/30 [05:00<00:00, 10.00s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.44s/it]

100%|██████████| 2/2 [00:01<00:00,  1.33it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7192195271402042

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6234820878579923

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5998042573846621

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5676689432917698

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.517711263695049

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5030986321911269

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.48444953882659464

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4759864206305308

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4732188900051904

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4668133446092211

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7192195271402042
BRAS...

seed           6.000000
BAMI           0.719220
CASW           0.572192
SCGRAPHM       0.984167
BRAS           0.846313
KBET           0.880140
CPCR           0.965308
bio_score      0.758526
batch_score    0.897254
joint_score    0.814017
dtype: float64

===== seed 7 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:09<04:36,  9.54s/it]

  7%|▋         | 2/30 [00:19<04:40, 10.03s/it]

 10%|█         | 3/30 [00:30<04:35, 10.19s/it]

 13%|█▎        | 4/30 [00:40<04:23, 10.13s/it]

 17%|█▋        | 5/30 [00:50<04:11, 10.05s/it]

 20%|██        | 6/30 [01:00<03:59,  9.99s/it]

 23%|██▎       | 7/30 [01:10<03:49,  9.96s/it]

 27%|██▋       | 8/30 [01:19<03:38,  9.94s/it]

 30%|███       | 9/30 [01:29<03:28,  9.92s/it]

 33%|███▎      | 10/30 [01:39<03:19,  9.97s/it]

 37%|███▋      | 11/30 [01:50<03:11, 10.05s/it]

 40%|████      | 12/30 [01:59<03:00, 10.00s/it]

 43%|████▎     | 13/30 [02:09<02:49,  9.97s/it]

 47%|████▋     | 14/30 [02:19<02:39,  9.95s/it]

 50%|█████     | 15/30 [02:29<02:28,  9.93s/it]

 53%|█████▎    | 16/30 [02:39<02:18,  9.92s/it]

 57%|█████▋    | 17/30 [02:49<02:08,  9.92s/it]

 60%|██████    | 18/30 [02:59<01:59,  9.92s/it]

 63%|██████▎   | 19/30 [03:09<01:49,  9.92s/it]

 67%|██████▋   | 20/30 [03:19<01:39,  9.93s/it]

 70%|███████   | 21/30 [03:29<01:29,  9.93s/it]

 73%|███████▎  | 22/30 [03:39<01:19,  9.93s/it]

 77%|███████▋  | 23/30 [03:49<01:09,  9.93s/it]

 80%|████████  | 24/30 [03:59<00:59,  9.94s/it]

 83%|████████▎ | 25/30 [04:09<00:50, 10.01s/it]

 87%|████████▋ | 26/30 [04:19<00:40, 10.06s/it]

 90%|█████████ | 27/30 [04:29<00:30, 10.02s/it]

 93%|█████████▎| 28/30 [04:39<00:19,  9.98s/it]

 97%|█████████▋| 29/30 [04:49<00:09,  9.95s/it]

100%|██████████| 30/30 [04:58<00:00,  9.93s/it]

100%|██████████| 30/30 [04:58<00:00,  9.97s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.42s/it]

100%|██████████| 2/2 [00:01<00:00,  1.35it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7091198930539075

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6791031301828123

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6014951530601417

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5826807345986617

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5554387933521101

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5431462122497056

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5002555545619044

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.49498638764862934

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.48359562557274327

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4786809153101609

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7091198930539075
BRAS...

seed           7.000000
BAMI           0.709120
CASW           0.571073
SCGRAPHM       0.987358
BRAS           0.857380
KBET           0.843073
CPCR           0.974712
bio_score      0.755850
batch_score    0.891722
joint_score    0.810199
dtype: float64

===== seed 8 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:09<04:49,  9.97s/it]

  7%|▋         | 2/30 [00:20<04:46, 10.23s/it]

 10%|█         | 3/30 [00:31<04:43, 10.51s/it]

 13%|█▎        | 4/30 [00:41<04:29, 10.35s/it]

 17%|█▋        | 5/30 [00:51<04:15, 10.23s/it]

 20%|██        | 6/30 [01:01<04:03, 10.13s/it]

 23%|██▎       | 7/30 [01:11<03:52, 10.09s/it]

 27%|██▋       | 8/30 [01:21<03:44, 10.18s/it]

 30%|███       | 9/30 [01:31<03:32, 10.10s/it]

 33%|███▎      | 10/30 [01:41<03:20, 10.04s/it]

 37%|███▋      | 11/30 [01:52<03:16, 10.34s/it]

 40%|████      | 12/30 [02:03<03:08, 10.49s/it]

 43%|████▎     | 13/30 [02:13<02:55, 10.33s/it]

 47%|████▋     | 14/30 [02:23<02:44, 10.25s/it]

 50%|█████     | 15/30 [02:33<02:32, 10.16s/it]

 53%|█████▎    | 16/30 [02:43<02:21, 10.10s/it]

 57%|█████▋    | 17/30 [02:53<02:10, 10.07s/it]

 60%|██████    | 18/30 [03:03<02:02, 10.17s/it]

 63%|██████▎   | 19/30 [03:13<01:51, 10.18s/it]

 67%|██████▋   | 20/30 [03:24<01:42, 10.27s/it]

 70%|███████   | 21/30 [03:34<01:31, 10.19s/it]

 73%|███████▎  | 22/30 [03:44<01:21, 10.13s/it]

 77%|███████▋  | 23/30 [03:54<01:10, 10.14s/it]

 80%|████████  | 24/30 [04:04<01:01, 10.22s/it]

 83%|████████▎ | 25/30 [04:14<00:50, 10.15s/it]

 87%|████████▋ | 26/30 [04:24<00:40, 10.11s/it]

 90%|█████████ | 27/30 [04:34<00:30, 10.09s/it]

 93%|█████████▎| 28/30 [04:45<00:20, 10.15s/it]

 97%|█████████▋| 29/30 [04:55<00:10, 10.18s/it]

100%|██████████| 30/30 [05:05<00:00, 10.12s/it]

100%|██████████| 30/30 [05:05<00:00, 10.18s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.41s/it]

100%|██████████| 2/2 [00:01<00:00,  1.35it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7271944339355043

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6667626600086982

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6005441125250374

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5765913956833951

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5316370236451716

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5214277142531635

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5062202713858099

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5009730814113676

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.48746816336762855

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.47337309848652365

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7271944339355043
BRAS...

seed           8.000000
BAMI           0.727194
CASW           0.571432
SCGRAPHM       0.983226
BRAS           0.860783
KBET           0.874571
CPCR           0.975286
bio_score      0.760617
batch_score    0.903547
joint_score    0.817789
dtype: float64

===== seed 9 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:10<05:06, 10.56s/it]

  7%|▋         | 2/30 [00:21<05:08, 11.01s/it]

 10%|█         | 3/30 [00:32<04:50, 10.74s/it]

 13%|█▎        | 4/30 [00:42<04:32, 10.50s/it]

 17%|█▋        | 5/30 [00:52<04:17, 10.28s/it]

 20%|██        | 6/30 [01:02<04:04, 10.20s/it]

 23%|██▎       | 7/30 [01:12<03:54, 10.20s/it]

 27%|██▋       | 8/30 [01:23<03:51, 10.53s/it]

 30%|███       | 9/30 [01:33<03:36, 10.30s/it]

 33%|███▎      | 10/30 [01:43<03:23, 10.15s/it]

 37%|███▋      | 11/30 [01:53<03:11, 10.07s/it]

 40%|████      | 12/30 [02:03<03:00, 10.02s/it]

 43%|████▎     | 13/30 [02:14<02:55, 10.34s/it]

 47%|████▋     | 14/30 [02:25<02:49, 10.58s/it]

 50%|█████     | 15/30 [02:36<02:42, 10.83s/it]

 53%|█████▎    | 16/30 [02:47<02:32, 10.91s/it]

 57%|█████▋    | 17/30 [02:59<02:23, 11.02s/it]

 60%|██████    | 18/30 [03:10<02:14, 11.20s/it]

 63%|██████▎   | 19/30 [03:21<02:01, 11.04s/it]

 67%|██████▋   | 20/30 [03:31<01:46, 10.69s/it]

 70%|███████   | 21/30 [03:41<01:34, 10.51s/it]

 73%|███████▎  | 22/30 [03:51<01:22, 10.32s/it]

 77%|███████▋  | 23/30 [04:01<01:11, 10.19s/it]

 80%|████████  | 24/30 [04:11<01:00, 10.09s/it]

 83%|████████▎ | 25/30 [04:20<00:50, 10.03s/it]

 87%|████████▋ | 26/30 [04:31<00:40, 10.08s/it]

 90%|█████████ | 27/30 [04:41<00:30, 10.03s/it]

 93%|█████████▎| 28/30 [04:51<00:19, 10.00s/it]

 97%|█████████▋| 29/30 [05:00<00:09,  9.97s/it]

100%|██████████| 30/30 [05:10<00:00,  9.96s/it]

100%|██████████| 30/30 [05:10<00:00, 10.36s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.41s/it]

100%|██████████| 2/2 [00:01<00:00,  1.36it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7223481588006427

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6359825808120408

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5959980009451733

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5704320067368237

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5533134588413302

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5185706591952335

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.4860875156475873

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4820572200959569

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4738372650671637

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4649521392565097

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7223481588006427
BRAS...

seed           9.000000
BAMI           0.722348
CASW           0.559778
SCGRAPHM       0.993031
BRAS           0.866644
KBET           0.837906
CPCR           0.974898
bio_score      0.758386
batch_score    0.893149
joint_score    0.812291
dtype: float64

===== seed 10 =====

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:10<05:04, 10.51s/it]

  7%|▋         | 2/30 [00:20<04:45, 10.21s/it]

 10%|█         | 3/30 [00:30<04:34, 10.16s/it]

 13%|█▎        | 4/30 [00:40<04:22, 10.10s/it]

 17%|█▋        | 5/30 [00:50<04:11, 10.04s/it]

 20%|██        | 6/30 [01:00<03:59,  9.99s/it]

 23%|██▎       | 7/30 [01:10<03:49,  9.98s/it]

 27%|██▋       | 8/30 [01:20<03:42, 10.11s/it]

 30%|███       | 9/30 [01:30<03:30, 10.05s/it]

 33%|███▎      | 10/30 [01:40<03:21, 10.08s/it]

 37%|███▋      | 11/30 [01:50<03:10, 10.03s/it]

 40%|████      | 12/30 [02:00<02:59,  9.99s/it]

 43%|████▎     | 13/30 [02:10<02:49,  9.96s/it]

 47%|████▋     | 14/30 [02:20<02:39,  9.94s/it]

 50%|█████     | 15/30 [02:30<02:29,  9.93s/it]

 53%|█████▎    | 16/30 [02:40<02:18,  9.93s/it]

 57%|█████▋    | 17/30 [02:50<02:11, 10.10s/it]

 60%|██████    | 18/30 [03:00<02:00, 10.05s/it]

 63%|██████▎   | 19/30 [03:10<01:50, 10.01s/it]

 67%|██████▋   | 20/30 [03:20<01:40, 10.02s/it]

 70%|███████   | 21/30 [03:30<01:29,  9.99s/it]

 73%|███████▎  | 22/30 [03:40<01:19,  9.96s/it]

 77%|███████▋  | 23/30 [03:50<01:09,  9.95s/it]

 80%|████████  | 24/30 [04:00<00:59,  9.94s/it]

 83%|████████▎ | 25/30 [04:10<00:49,  9.94s/it]

 87%|████████▋ | 26/30 [04:20<00:39,  9.95s/it]

 90%|█████████ | 27/30 [04:30<00:29,  9.94s/it]

 93%|█████████▎| 28/30 [04:40<00:20, 10.06s/it]

 97%|█████████▋| 29/30 [04:50<00:10, 10.07s/it]

100%|██████████| 30/30 [05:00<00:00, 10.02s/it]

100%|██████████| 30/30 [05:00<00:00, 10.02s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.44s/it]

100%|██████████| 2/2 [00:01<00:00,  1.33it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7401027698054399

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6412358612096102

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5927074521745598

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5634329996561257

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5614718311318392

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5341738772691798

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.49593079418331015

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4885023706478423

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4828614638238926

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4756214613716338

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7401027698054399
BRAS...

seed           10.000000
BAMI            0.740103
CASW            0.566226
SCGRAPHM        0.989024
BRAS            0.864643
KBET            0.880683
CPCR            0.974968
bio_score       0.765117
batch_score     0.906765
joint_score     0.821776
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.725295,0.565275,0.983208,0.851868,0.869567,0.969215,0.757926,0.896883,0.813509
1,2,0.736659,0.570709,0.988152,0.852437,0.867677,0.970659,0.765174,0.896924,0.817874
2,3,0.749370,0.568537,0.983976,0.859013,0.871411,0.972471,0.767294,0.900965,0.820763
3,4,0.734722,0.566437,0.989795,0.857476,0.882073,0.973888,0.763651,0.904479,0.819982
4,5,0.735376,0.566905,0.987668,0.873411,0.871267,0.977484,0.763317,0.907387,0.820945
5,6,0.719220,0.572192,0.984167,0.846313,0.880140,0.965308,0.758526,0.897254,0.814017
6,7,0.709120,0.571073,0.987358,0.857380,0.843073,0.974712,0.755850,0.891722,0.810199
7,8,0.727194,0.571432,0.983226,0.860783,0.874571,0.975286,0.760617,0.903547,0.817789
8,9,0.722348,0.559778,0.993031,0.866644,0.837906,0.974898,0.758386,0.893149,0.812291
9,10,0.740103,0.566226,0.989024,0.864643,0.880683,0.974968,0.765117,0.906765,0.821776

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.729941  0.011016  0.709120  0.749370
CASW         0.567856  0.003578  0.559778  0.572192
SCGRAPHM     0.986961  0.003098  0.983208  0.993031
BRAS         0.858997  0.007490  0.846313  0.873411
KBET         0.867837  0.014495  0.837906  0.882073
CPCR         0.972889  0.003401  0.965308  0.977484
bio_score    0.761586  0.003633  0.755850  0.767294
batch_score  0.899908  0.005254  0.891722  0.907387
joint_score  0.816915  0.003902  0.810199  0.821776