# LIGER best - mouse_regulatory_T

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'mouse_regulatory_T'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'method'
LABEL_KEY = 'cell.type'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'mouse_regulatory_T'
assert BATCH_KEY == 'method'
assert LABEL_KEY == 'cell.type'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                     mouse_regulatory_T
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                               method
label_key                                            cell.type
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=34697 n_batches=2 n_labels=3
CPCR preflight: eligible_labels=2

In [4]:
OPTUNA_STUDY_NAME = 'liger_mouse_regulatory_T_joint_expanded_metrics_scgraphm_v1'
OPTUNA_BEST_TRIAL = 75
OPTUNA_BEST_VALUE = 0.8252295205914444
OPTUNA_BEST_PARAMS = {'k': 28, 'value_lambda': 6.020912011962021}

LIGER_BEST_ARGS = {
    "k": OPTUNA_BEST_PARAMS["k"],
    "value_lambda": OPTUNA_BEST_PARAMS["value_lambda"],
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_best(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_BEST_ARGS["k"],
        lam=LIGER_BEST_ARGS["value_lambda"],
        max_iterations=LIGER_BEST_ARGS["max_iters"],
        mode=LIGER_BEST_ARGS["mode"],
        layer=LIGER_BEST_ARGS["layer"],
        seed=seed,
    )


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **LIGER_BEST_ARGS,
    },
    name="best_setting",
)

study           liger_mouse_regulatory_T_joint_expanded_metric...
best_trial                                                     75
best_value                                                0.82523
k                                                              28
value_lambda                                             6.020912
max_iters                                                      30
mode                                                         core
layer                                                      counts
Name: best_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:14<06:57, 14.41s/it]

  7%|▋         | 2/30 [00:29<06:55, 14.83s/it]

 10%|█         | 3/30 [00:45<06:51, 15.24s/it]

 13%|█▎        | 4/30 [01:00<06:39, 15.37s/it]

 17%|█▋        | 5/30 [01:13<06:02, 14.48s/it]

 20%|██        | 6/30 [01:25<05:24, 13.54s/it]

 23%|██▎       | 7/30 [01:36<04:54, 12.80s/it]

 27%|██▋       | 8/30 [01:51<04:56, 13.50s/it]

 30%|███       | 9/30 [02:06<04:54, 14.04s/it]

 33%|███▎      | 10/30 [02:21<04:44, 14.21s/it]

 37%|███▋      | 11/30 [02:37<04:38, 14.63s/it]

 40%|████      | 12/30 [02:53<04:32, 15.16s/it]

 43%|████▎     | 13/30 [03:10<04:25, 15.59s/it]

 47%|████▋     | 14/30 [03:25<04:10, 15.64s/it]

 50%|█████     | 15/30 [03:42<03:57, 15.84s/it]

 53%|█████▎    | 16/30 [03:58<03:43, 15.96s/it]

 57%|█████▋    | 17/30 [04:15<03:30, 16.22s/it]

 60%|██████    | 18/30 [04:48<04:15, 21.29s/it]

 63%|██████▎   | 19/30 [05:05<03:40, 20.01s/it]

 67%|██████▋   | 20/30 [05:20<03:05, 18.55s/it]

 70%|███████   | 21/30 [05:36<02:40, 17.81s/it]

 73%|███████▎  | 22/30 [05:51<02:15, 16.98s/it]

 77%|███████▋  | 23/30 [06:07<01:57, 16.74s/it]

 80%|████████  | 24/30 [06:24<01:40, 16.73s/it]

 83%|████████▎ | 25/30 [06:47<01:33, 18.76s/it]

 87%|████████▋ | 26/30 [07:03<01:11, 17.89s/it]

 90%|█████████ | 27/30 [07:27<00:58, 19.65s/it]

 93%|█████████▎| 28/30 [07:44<00:37, 18.90s/it]

 97%|█████████▋| 29/30 [07:57<00:17, 17.07s/it]

100%|██████████| 30/30 [08:19<00:00, 18.46s/it]

100%|██████████| 30/30 [08:19<00:00, 16.64s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.74s/it]

100%|██████████| 2/2 [00:01<00:00,  1.11it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.7527503644487935

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6761289906826862

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.620339939403933

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6080782808578552

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.56455686913085

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5175388363567666

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.49669261092041067

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.48043739883781494

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.48554780278386056

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.47104649810033394

WARNING:2026-07-23 16:52:46,450:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7527503644487935
BRAS...

seed           1.000000
BAMI           0.752750
CASW           0.555196
SCGRAPHM       0.989067
BRAS           0.885035
KBET           0.877779
CPCR           0.980886
bio_score      0.765671
batch_score    0.914567
joint_score    0.825230
dtype: float64

===== seed 2 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:32<15:29, 32.05s/it]

  7%|▋         | 2/30 [00:45<09:53, 21.21s/it]

 10%|█         | 3/30 [01:00<08:07, 18.07s/it]

 13%|█▎        | 4/30 [01:12<06:57, 16.05s/it]

 17%|█▋        | 5/30 [01:25<06:11, 14.85s/it]

 20%|██        | 6/30 [01:38<05:40, 14.19s/it]

 23%|██▎       | 7/30 [01:51<05:19, 13.90s/it]

 27%|██▋       | 8/30 [02:04<04:59, 13.63s/it]

 30%|███       | 9/30 [02:18<04:45, 13.61s/it]

 33%|███▎      | 10/30 [02:31<04:28, 13.42s/it]

 37%|███▋      | 11/30 [02:44<04:15, 13.44s/it]

 40%|████      | 12/30 [02:58<03:59, 13.31s/it]

 43%|████▎     | 13/30 [03:11<03:44, 13.22s/it]

 47%|████▋     | 14/30 [03:23<03:29, 13.11s/it]

 50%|█████     | 15/30 [03:37<03:17, 13.14s/it]

 53%|█████▎    | 16/30 [03:50<03:05, 13.22s/it]

 57%|█████▋    | 17/30 [04:03<02:51, 13.19s/it]

 60%|██████    | 18/30 [04:17<02:42, 13.52s/it]

 63%|██████▎   | 19/30 [04:31<02:30, 13.64s/it]

 67%|██████▋   | 20/30 [04:45<02:16, 13.66s/it]

 70%|███████   | 21/30 [04:58<02:01, 13.53s/it]

 73%|███████▎  | 22/30 [05:11<01:47, 13.38s/it]

 77%|███████▋  | 23/30 [05:25<01:33, 13.36s/it]

 80%|████████  | 24/30 [05:38<01:19, 13.28s/it]

 83%|████████▎ | 25/30 [05:51<01:06, 13.25s/it]

 87%|████████▋ | 26/30 [06:04<00:52, 13.18s/it]

 90%|█████████ | 27/30 [06:17<00:39, 13.16s/it]

 93%|█████████▎| 28/30 [06:30<00:26, 13.24s/it]

 97%|█████████▋| 29/30 [06:43<00:13, 13.13s/it]

100%|██████████| 30/30 [06:57<00:00, 13.18s/it]

100%|██████████| 30/30 [06:57<00:00, 13.90s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.69s/it]

100%|██████████| 2/2 [00:01<00:00,  1.13it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7286703165732797

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6755890964240986

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6126065945085014

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5796476760454664

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.561907873189298

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.542631363200696

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5302481760437031

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.49480128276160135

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4872941543042426

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4794147329194787

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7286703165732797
BRAS...

seed           2.000000
BAMI           0.728670
CASW           0.556463
SCGRAPHM       0.980612
BRAS           0.883763
KBET           0.843039
CPCR           0.975185
bio_score      0.755248
batch_score    0.900662
joint_score    0.813414
dtype: float64

===== seed 3 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:12<06:07, 12.66s/it]

  7%|▋         | 2/30 [00:26<06:17, 13.48s/it]

 10%|█         | 3/30 [00:45<07:14, 16.11s/it]

 13%|█▎        | 4/30 [01:01<06:52, 15.86s/it]

 17%|█▋        | 5/30 [01:18<06:43, 16.13s/it]

 20%|██        | 6/30 [01:31<06:06, 15.25s/it]

 23%|██▎       | 7/30 [01:45<05:37, 14.68s/it]

 27%|██▋       | 8/30 [01:58<05:12, 14.18s/it]

 30%|███       | 9/30 [02:11<04:50, 13.81s/it]

 33%|███▎      | 10/30 [02:24<04:35, 13.78s/it]

 37%|███▋      | 11/30 [02:37<04:15, 13.47s/it]

 40%|████      | 12/30 [02:50<03:58, 13.25s/it]

 43%|████▎     | 13/30 [03:03<03:41, 13.06s/it]

 47%|████▋     | 14/30 [03:15<03:27, 12.99s/it]

 50%|█████     | 15/30 [03:29<03:15, 13.04s/it]

 53%|█████▎    | 16/30 [03:41<03:02, 13.02s/it]

 57%|█████▋    | 17/30 [03:54<02:48, 12.98s/it]

 60%|██████    | 18/30 [04:07<02:35, 12.93s/it]

 63%|██████▎   | 19/30 [04:20<02:23, 13.00s/it]

 67%|██████▋   | 20/30 [04:33<02:08, 12.87s/it]

 70%|███████   | 21/30 [04:46<01:55, 12.81s/it]

 73%|███████▎  | 22/30 [04:58<01:41, 12.73s/it]

 77%|███████▋  | 23/30 [05:11<01:28, 12.70s/it]

 80%|████████  | 24/30 [05:23<01:15, 12.66s/it]

 83%|████████▎ | 25/30 [05:36<01:03, 12.72s/it]

 87%|████████▋ | 26/30 [05:49<00:51, 12.83s/it]

 90%|█████████ | 27/30 [06:02<00:38, 12.76s/it]

 93%|█████████▎| 28/30 [06:15<00:25, 12.94s/it]

 97%|█████████▋| 29/30 [06:29<00:13, 13.08s/it]

100%|██████████| 30/30 [06:42<00:00, 13.27s/it]

100%|██████████| 30/30 [06:42<00:00, 13.43s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.77s/it]

100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.732936152366687

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6652353634474848

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.620982419990189

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5985482929798978

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5721502134683671

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5219566636342766

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5068871038703172

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4892824654317354

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.47482860078127975

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4669538018742725

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.732936152366687
BRAS...

seed           3.000000
BAMI           0.732936
CASW           0.557551
SCGRAPHM       0.973672
BRAS           0.882574
KBET           0.845848
CPCR           0.978575
bio_score      0.754720
batch_score    0.902333
joint_score    0.813765
dtype: float64

===== seed 4 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:12<05:57, 12.33s/it]

  7%|▋         | 2/30 [00:25<05:59, 12.83s/it]

 10%|█         | 3/30 [00:39<06:00, 13.35s/it]

 13%|█▎        | 4/30 [00:52<05:46, 13.31s/it]

 17%|█▋        | 5/30 [01:05<05:28, 13.16s/it]

 20%|██        | 6/30 [01:18<05:15, 13.13s/it]

 23%|██▎       | 7/30 [01:32<05:03, 13.19s/it]

 27%|██▋       | 8/30 [01:44<04:47, 13.07s/it]

 30%|███       | 9/30 [01:57<04:32, 12.99s/it]

 33%|███▎      | 10/30 [02:10<04:20, 13.03s/it]

 37%|███▋      | 11/30 [02:23<04:03, 12.84s/it]

 40%|████      | 12/30 [02:36<03:51, 12.86s/it]

 43%|████▎     | 13/30 [02:49<03:40, 12.94s/it]

 47%|████▋     | 14/30 [03:17<04:39, 17.45s/it]

 50%|█████     | 15/30 [03:30<04:04, 16.29s/it]

 53%|█████▎    | 16/30 [03:44<03:36, 15.47s/it]

 57%|█████▋    | 17/30 [03:57<03:13, 14.88s/it]

 60%|██████    | 18/30 [04:11<02:53, 14.48s/it]

 63%|██████▎   | 19/30 [04:26<02:40, 14.60s/it]

 67%|██████▋   | 20/30 [04:39<02:23, 14.33s/it]

 70%|███████   | 21/30 [04:56<02:15, 15.07s/it]

 73%|███████▎  | 22/30 [05:09<01:56, 14.53s/it]

 77%|███████▋  | 23/30 [05:23<01:39, 14.21s/it]

 80%|████████  | 24/30 [05:36<01:23, 13.99s/it]

 83%|████████▎ | 25/30 [05:50<01:09, 13.83s/it]

 87%|████████▋ | 26/30 [06:04<00:55, 13.79s/it]

 90%|█████████ | 27/30 [06:17<00:40, 13.65s/it]

 93%|█████████▎| 28/30 [06:32<00:28, 14.06s/it]

 97%|█████████▋| 29/30 [06:47<00:14, 14.28s/it]

100%|██████████| 30/30 [07:00<00:00, 13.99s/it]

100%|██████████| 30/30 [07:00<00:00, 14.02s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.67s/it]

100%|██████████| 2/2 [00:01<00:00,  1.14it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7325136767067838

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6724525872589208

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6256367827700903

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5941963523903939

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5597389260786573

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.54384421006959

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.528299355912129

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.48888982688053595

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.485750637245903

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4817269991681798

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7325136767067838
BRAS...

seed           4.000000
BAMI           0.732514
CASW           0.557882
SCGRAPHM       0.979604
BRAS           0.879313
KBET           0.839701
CPCR           0.980020
bio_score      0.756667
batch_score    0.899678
joint_score    0.813871
dtype: float64

===== seed 5 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:13<06:19, 13.09s/it]

  7%|▋         | 2/30 [00:26<06:12, 13.29s/it]

 10%|█         | 3/30 [00:39<05:59, 13.31s/it]

 13%|█▎        | 4/30 [00:52<05:44, 13.24s/it]

 17%|█▋        | 5/30 [01:06<05:32, 13.30s/it]

 20%|██        | 6/30 [01:19<05:15, 13.14s/it]

 23%|██▎       | 7/30 [01:33<05:08, 13.40s/it]

 27%|██▋       | 8/30 [01:46<04:51, 13.24s/it]

 30%|███       | 9/30 [01:59<04:36, 13.19s/it]

 33%|███▎      | 10/30 [02:14<04:34, 13.71s/it]

 37%|███▋      | 11/30 [02:26<04:16, 13.48s/it]

 40%|████      | 12/30 [02:42<04:14, 14.16s/it]

 43%|████▎     | 13/30 [02:56<03:58, 14.04s/it]

 47%|████▋     | 14/30 [03:09<03:40, 13.79s/it]

 50%|█████     | 15/30 [03:23<03:28, 13.89s/it]

 53%|█████▎    | 16/30 [03:37<03:14, 13.88s/it]

 57%|█████▋    | 17/30 [03:51<03:00, 13.86s/it]

 60%|██████    | 18/30 [04:05<02:46, 13.89s/it]

 63%|██████▎   | 19/30 [04:20<02:35, 14.13s/it]

 67%|██████▋   | 20/30 [04:34<02:21, 14.15s/it]

 70%|███████   | 21/30 [04:48<02:06, 14.09s/it]

 73%|███████▎  | 22/30 [05:02<01:52, 14.06s/it]

 77%|███████▋  | 23/30 [05:16<01:38, 14.02s/it]

 80%|████████  | 24/30 [05:30<01:23, 14.00s/it]

 83%|████████▎ | 25/30 [05:43<01:09, 13.85s/it]

 87%|████████▋ | 26/30 [05:57<00:55, 13.79s/it]

 90%|█████████ | 27/30 [06:11<00:41, 13.96s/it]

 93%|█████████▎| 28/30 [06:25<00:27, 13.89s/it]

 97%|█████████▋| 29/30 [06:39<00:13, 13.90s/it]

100%|██████████| 30/30 [06:52<00:00, 13.75s/it]

100%|██████████| 30/30 [06:52<00:00, 13.76s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.65s/it]

100%|██████████| 2/2 [00:01<00:00,  1.15it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7440846345151747

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6606007416291414

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6241136449778852

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5923940491631872

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5704857880109885

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5271871496495384

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5152354722663078

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5066860490120155

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.49184024601873494

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.48457517257181704

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7440846345151747
BRAS...

seed           5.000000
BAMI           0.744085
CASW           0.558989
SCGRAPHM       0.983123
BRAS           0.883002
KBET           0.866875
CPCR           0.978297
bio_score      0.762066
batch_score    0.909392
joint_score    0.820996
dtype: float64

===== seed 6 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:13<06:38, 13.74s/it]

  7%|▋         | 2/30 [00:28<06:41, 14.33s/it]

 10%|█         | 3/30 [00:43<06:30, 14.47s/it]

 13%|█▎        | 4/30 [00:56<06:06, 14.08s/it]

 17%|█▋        | 5/30 [01:10<05:48, 13.95s/it]

 20%|██        | 6/30 [01:24<05:34, 13.95s/it]

 23%|██▎       | 7/30 [01:38<05:22, 14.02s/it]

 27%|██▋       | 8/30 [01:51<05:03, 13.78s/it]

 30%|███       | 9/30 [02:04<04:46, 13.62s/it]

 33%|███▎      | 10/30 [02:18<04:32, 13.61s/it]

 37%|███▋      | 11/30 [02:31<04:16, 13.50s/it]

 40%|████      | 12/30 [02:45<04:02, 13.48s/it]

 43%|████▎     | 13/30 [02:58<03:48, 13.45s/it]

 47%|████▋     | 14/30 [03:12<03:38, 13.64s/it]

 50%|█████     | 15/30 [03:26<03:25, 13.72s/it]

 53%|█████▎    | 16/30 [03:40<03:13, 13.81s/it]

 57%|█████▋    | 17/30 [03:55<03:03, 14.08s/it]

 60%|██████    | 18/30 [04:09<02:47, 14.00s/it]

 63%|██████▎   | 19/30 [04:22<02:31, 13.81s/it]

 67%|██████▋   | 20/30 [04:36<02:17, 13.73s/it]

 70%|███████   | 21/30 [04:49<02:03, 13.75s/it]

 73%|███████▎  | 22/30 [05:03<01:48, 13.59s/it]

 77%|███████▋  | 23/30 [05:16<01:34, 13.56s/it]

 80%|████████  | 24/30 [05:30<01:22, 13.69s/it]

 83%|████████▎ | 25/30 [05:44<01:09, 13.81s/it]

 87%|████████▋ | 26/30 [05:58<00:55, 13.76s/it]

 90%|█████████ | 27/30 [06:12<00:41, 13.93s/it]

 93%|█████████▎| 28/30 [06:25<00:27, 13.74s/it]

 97%|█████████▋| 29/30 [06:38<00:13, 13.47s/it]

100%|██████████| 30/30 [06:51<00:00, 13.31s/it]

100%|██████████| 30/30 [06:51<00:00, 13.72s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.71s/it]

100%|██████████| 2/2 [00:01<00:00,  1.12it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7357535926658966

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6761795420109702

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6297191811510553

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5807018945175003

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5596751195087102

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5468972530242866

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5151133293939774

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.49422546552452606

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4870257753440055

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.48020735178953905

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7357535926658966
BRAS...

seed           6.000000
BAMI           0.735754
CASW           0.562457
SCGRAPHM       0.980462
BRAS           0.880950
KBET           0.846049
CPCR           0.978420
bio_score      0.759558
batch_score    0.901806
joint_score    0.816457
dtype: float64

===== seed 7 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:12<06:15, 12.94s/it]

  7%|▋         | 2/30 [00:26<06:19, 13.56s/it]

 10%|█         | 3/30 [00:40<06:05, 13.55s/it]

 13%|█▎        | 4/30 [00:53<05:49, 13.44s/it]

 17%|█▋        | 5/30 [01:06<05:32, 13.32s/it]

 20%|██        | 6/30 [01:19<05:17, 13.24s/it]

 23%|██▎       | 7/30 [01:33<05:10, 13.50s/it]

 27%|██▋       | 8/30 [01:47<04:58, 13.56s/it]

 30%|███       | 9/30 [02:01<04:43, 13.52s/it]

 33%|███▎      | 10/30 [02:14<04:30, 13.55s/it]

 37%|███▋      | 11/30 [02:28<04:18, 13.62s/it]

 40%|████      | 12/30 [02:42<04:04, 13.59s/it]

 43%|████▎     | 13/30 [02:54<03:47, 13.39s/it]

 47%|████▋     | 14/30 [03:08<03:35, 13.45s/it]

 50%|█████     | 15/30 [03:22<03:24, 13.65s/it]

 53%|█████▎    | 16/30 [03:35<03:08, 13.46s/it]

 57%|█████▋    | 17/30 [03:48<02:53, 13.35s/it]

 60%|██████    | 18/30 [04:01<02:38, 13.24s/it]

 63%|██████▎   | 19/30 [04:15<02:28, 13.48s/it]

 67%|██████▋   | 20/30 [04:29<02:15, 13.53s/it]

 70%|███████   | 21/30 [04:45<02:07, 14.16s/it]

 73%|███████▎  | 22/30 [05:01<01:58, 14.83s/it]

 77%|███████▋  | 23/30 [05:15<01:43, 14.74s/it]

 80%|████████  | 24/30 [05:31<01:29, 14.85s/it]

 83%|████████▎ | 25/30 [05:46<01:15, 15.14s/it]

 87%|████████▋ | 26/30 [06:02<01:01, 15.31s/it]

 90%|█████████ | 27/30 [06:17<00:45, 15.33s/it]

 93%|█████████▎| 28/30 [06:31<00:29, 14.89s/it]

 97%|█████████▋| 29/30 [06:47<00:15, 15.08s/it]

100%|██████████| 30/30 [07:01<00:00, 14.86s/it]

100%|██████████| 30/30 [07:01<00:00, 14.06s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.69s/it]

100%|██████████| 2/2 [00:01<00:00,  1.13it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7374294122416105

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6691951366387521

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5997047819478347

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5670372307662817

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5304627498018328

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.522797239154846

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5178696681379107

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4973110753144511

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.48462712005673364

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.47628080480415524

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7374294122416105
BRAS...

seed           7.000000
BAMI           0.737429
CASW           0.555420
SCGRAPHM       0.984230
BRAS           0.869574
KBET           0.828903
CPCR           0.955661
bio_score      0.759027
batch_score    0.884713
joint_score    0.809301
dtype: float64

===== seed 8 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:13<06:36, 13.66s/it]

  7%|▋         | 2/30 [00:29<06:57, 14.92s/it]

 10%|█         | 3/30 [00:44<06:44, 14.98s/it]

 13%|█▎        | 4/30 [00:58<06:20, 14.64s/it]

 17%|█▋        | 5/30 [01:11<05:54, 14.17s/it]

 20%|██        | 6/30 [01:25<05:32, 13.87s/it]

 23%|██▎       | 7/30 [01:38<05:17, 13.82s/it]

 27%|██▋       | 8/30 [01:53<05:09, 14.06s/it]

 30%|███       | 9/30 [02:06<04:50, 13.85s/it]

 33%|███▎      | 10/30 [02:20<04:34, 13.71s/it]

 37%|███▋      | 11/30 [02:34<04:22, 13.81s/it]

 40%|████      | 12/30 [02:48<04:10, 13.90s/it]

 43%|████▎     | 13/30 [03:03<04:02, 14.28s/it]

 47%|████▋     | 14/30 [03:18<03:48, 14.31s/it]

 50%|█████     | 15/30 [03:31<03:33, 14.20s/it]

 53%|█████▎    | 16/30 [03:46<03:19, 14.26s/it]

 57%|█████▋    | 17/30 [04:01<03:08, 14.51s/it]

 60%|██████    | 18/30 [04:17<02:59, 14.96s/it]

 63%|██████▎   | 19/30 [04:33<02:47, 15.24s/it]

 67%|██████▋   | 20/30 [04:49<02:34, 15.42s/it]

 70%|███████   | 21/30 [05:02<02:13, 14.82s/it]

 73%|███████▎  | 22/30 [05:16<01:55, 14.42s/it]

 77%|███████▋  | 23/30 [05:29<01:38, 14.06s/it]

 80%|████████  | 24/30 [05:42<01:22, 13.75s/it]

 83%|████████▎ | 25/30 [05:56<01:09, 13.87s/it]

 87%|████████▋ | 26/30 [06:10<00:55, 13.88s/it]

 90%|█████████ | 27/30 [06:25<00:42, 14.20s/it]

 93%|█████████▎| 28/30 [06:40<00:28, 14.40s/it]

 97%|█████████▋| 29/30 [06:54<00:14, 14.30s/it]

100%|██████████| 30/30 [07:08<00:00, 14.41s/it]

100%|██████████| 30/30 [07:08<00:00, 14.30s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.74s/it]

100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7342840391513924

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6699388631079198

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6060362793905438

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5719134411330591

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5603755645457219

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5136426490155613

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.49818573790885

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.4911399481271185

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4763686968417608

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.47536863431063503

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7342840391513924
BRAS...

seed           8.000000
BAMI           0.734284
CASW           0.555074
SCGRAPHM       0.980149
BRAS           0.884211
KBET           0.881055
CPCR           0.978454
bio_score      0.756502
batch_score    0.914574
joint_score    0.819731
dtype: float64

===== seed 9 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:14<07:06, 14.69s/it]

  7%|▋         | 2/30 [00:28<06:36, 14.15s/it]

 10%|█         | 3/30 [00:42<06:14, 13.89s/it]

 13%|█▎        | 4/30 [00:55<05:58, 13.80s/it]

 17%|█▋        | 5/30 [01:08<05:39, 13.57s/it]

 20%|██        | 6/30 [01:23<05:30, 13.77s/it]

 23%|██▎       | 7/30 [01:37<05:25, 14.13s/it]

 27%|██▋       | 8/30 [01:51<05:09, 14.09s/it]

 30%|███       | 9/30 [02:06<04:56, 14.10s/it]

 33%|███▎      | 10/30 [02:19<04:38, 13.94s/it]

 37%|███▋      | 11/30 [02:33<04:22, 13.79s/it]

 40%|████      | 12/30 [02:47<04:12, 14.01s/it]

 43%|████▎     | 13/30 [03:00<03:54, 13.80s/it]

 47%|████▋     | 14/30 [03:14<03:39, 13.71s/it]

 50%|█████     | 15/30 [03:27<03:24, 13.65s/it]

 53%|█████▎    | 16/30 [03:40<03:05, 13.27s/it]

 57%|█████▋    | 17/30 [03:53<02:50, 13.14s/it]

 60%|██████    | 18/30 [04:06<02:37, 13.13s/it]

 63%|██████▎   | 19/30 [04:20<02:26, 13.34s/it]

 67%|██████▋   | 20/30 [04:34<02:17, 13.76s/it]

 70%|███████   | 21/30 [04:48<02:05, 13.89s/it]

 73%|███████▎  | 22/30 [05:03<01:52, 14.11s/it]

 77%|███████▋  | 23/30 [05:17<01:38, 14.11s/it]

 80%|████████  | 24/30 [05:31<01:23, 13.98s/it]

 83%|████████▎ | 25/30 [05:44<01:09, 13.84s/it]

 87%|████████▋ | 26/30 [05:57<00:53, 13.39s/it]

 90%|█████████ | 27/30 [06:13<00:42, 14.15s/it]

 93%|█████████▎| 28/30 [06:31<00:30, 15.45s/it]

 97%|█████████▋| 29/30 [06:52<00:17, 17.04s/it]

100%|██████████| 30/30 [07:11<00:00, 17.77s/it]

100%|██████████| 30/30 [07:11<00:00, 14.40s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.78s/it]

100%|██████████| 2/2 [00:03<00:00,  1.64s/it]

100%|██████████| 2/2 [00:03<00:00,  1.96s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7254957137471192

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.649819050915394

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5964208074759842

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5822559364958247

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5606253804870517

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5252537471030305

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5057761397997032

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5028270328767613

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4725614071899413

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.47257974366970734

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7254957137471192
BRAS...

seed           9.000000
BAMI           0.725496
CASW           0.556906
SCGRAPHM       0.978609
BRAS           0.913028
KBET           0.833749
CPCR           0.985141
bio_score      0.753670
batch_score    0.910639
joint_score    0.816458
dtype: float64

===== seed 10 =====

[LIGER PARAMS] function=optimize_ALS k=28 value_lambda=6.020912011962021 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:18<09:05, 18.81s/it]

  7%|▋         | 2/30 [00:33<07:45, 16.63s/it]

 10%|█         | 3/30 [00:56<08:41, 19.33s/it]

 13%|█▎        | 4/30 [01:14<08:11, 18.90s/it]

 17%|█▋        | 5/30 [01:32<07:45, 18.61s/it]

 20%|██        | 6/30 [01:52<07:32, 18.84s/it]

 23%|██▎       | 7/30 [02:07<06:51, 17.88s/it]

 27%|██▋       | 8/30 [02:22<06:08, 16.74s/it]

 30%|███       | 9/30 [02:36<05:34, 15.93s/it]

 33%|███▎      | 10/30 [02:49<05:01, 15.08s/it]

 37%|███▋      | 11/30 [03:02<04:35, 14.48s/it]

 40%|████      | 12/30 [03:16<04:14, 14.13s/it]

 43%|████▎     | 13/30 [03:28<03:53, 13.72s/it]

 47%|████▋     | 14/30 [03:42<03:39, 13.72s/it]

 50%|█████     | 15/30 [03:56<03:26, 13.78s/it]

 53%|█████▎    | 16/30 [04:10<03:14, 13.93s/it]

 57%|█████▋    | 17/30 [04:25<03:04, 14.20s/it]

 60%|██████    | 18/30 [04:39<02:49, 14.12s/it]

 63%|██████▎   | 19/30 [04:56<02:45, 15.03s/it]

 67%|██████▋   | 20/30 [05:13<02:35, 15.59s/it]

 70%|███████   | 21/30 [05:27<02:14, 14.96s/it]

 73%|███████▎  | 22/30 [05:39<01:52, 14.07s/it]

 77%|███████▋  | 23/30 [05:51<01:35, 13.71s/it]

 80%|████████  | 24/30 [06:10<01:31, 15.25s/it]

 83%|████████▎ | 25/30 [06:29<01:20, 16.16s/it]

 87%|████████▋ | 26/30 [06:46<01:05, 16.46s/it]

 90%|█████████ | 27/30 [07:03<00:50, 16.79s/it]

 93%|█████████▎| 28/30 [07:19<00:33, 16.52s/it]

 97%|█████████▋| 29/30 [07:32<00:15, 15.53s/it]

100%|██████████| 30/30 [07:45<00:00, 14.74s/it]

100%|██████████| 30/30 [07:45<00:00, 15.53s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.75s/it]

100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7325007985921806

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6407269702299739

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5982186884393311

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5772278397357434

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5551928053435083

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5396677462877226

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5042432293224461

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.479588611732878

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.4755021193480945

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4721213459709601

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7325007985921806
BRAS...

seed           10.000000
BAMI            0.732501
CASW            0.543293
SCGRAPHM        0.990735
BRAS            0.883155
KBET            0.839153
CPCR            0.978195
bio_score       0.755510
batch_score     0.900168
joint_score     0.813373
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.752750,0.555196,0.989067,0.885035,0.877779,0.980886,0.765671,0.914567,0.825230
1,2,0.728670,0.556463,0.980612,0.883763,0.843039,0.975185,0.755248,0.900662,0.813414
2,3,0.732936,0.557551,0.973672,0.882574,0.845848,0.978575,0.754720,0.902333,0.813765
3,4,0.732514,0.557882,0.979604,0.879313,0.839701,0.980020,0.756667,0.899678,0.813871
4,5,0.744085,0.558989,0.983123,0.883002,0.866875,0.978297,0.762066,0.909392,0.820996
5,6,0.735754,0.562457,0.980462,0.880950,0.846049,0.978420,0.759558,0.901806,0.816457
6,7,0.737429,0.555420,0.984230,0.869574,0.828903,0.955661,0.759027,0.884713,0.809301
7,8,0.734284,0.555074,0.980149,0.884211,0.881055,0.978454,0.756502,0.914574,0.819731
8,9,0.725496,0.556906,0.978609,0.913028,0.833749,0.985141,0.753670,0.910639,0.816458
9,10,0.732501,0.543293,0.990735,0.883155,0.839153,0.978195,0.755510,0.900168,0.813373

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.735642  0.007400  0.725496  0.752750
CASW         0.555923  0.004700  0.543293  0.562457
SCGRAPHM     0.982026  0.004762  0.973672  0.990735
BRAS         0.884461  0.010415  0.869574  0.913028
KBET         0.850215  0.017420  0.828903  0.881055
CPCR         0.976883  0.007475  0.955661  0.985141
bio_score    0.757864  0.003549  0.753670  0.765671
batch_score  0.903853  0.008488  0.884713  0.914574
joint_score  0.816260  0.004380  0.809301  0.825230