# LIGER best - nph_cerebellum

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'nph_cerebellum'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'Sample'
LABEL_KEY = 'Celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'nph_cerebellum'
assert BATCH_KEY == 'Sample'
assert LABEL_KEY == 'Celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                         nph_cerebellum
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                               Sample
label_key                                             Celltype
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=84619 n_batches=2 n_labels=8
CPCR preflight: eligible_labels=8

In [4]:
OPTUNA_STUDY_NAME = 'liger_nph_cerebellum_joint_expanded_metrics_scgraphm_v1'
OPTUNA_BEST_TRIAL = 15
OPTUNA_BEST_VALUE = 0.7457946872944343
OPTUNA_BEST_PARAMS = {'k': 32, 'value_lambda': 0.5033965087804688}

LIGER_BEST_ARGS = {
    "k": OPTUNA_BEST_PARAMS["k"],
    "value_lambda": OPTUNA_BEST_PARAMS["value_lambda"],
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_best(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_BEST_ARGS["k"],
        lam=LIGER_BEST_ARGS["value_lambda"],
        max_iterations=LIGER_BEST_ARGS["max_iters"],
        mode=LIGER_BEST_ARGS["mode"],
        layer=LIGER_BEST_ARGS["layer"],
        seed=seed,
    )


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **LIGER_BEST_ARGS,
    },
    name="best_setting",
)

study           liger_nph_cerebellum_joint_expanded_metrics_sc...
best_trial                                                     15
best_value                                               0.745795
k                                                              32
value_lambda                                             0.503397
max_iters                                                      30
mode                                                         core
layer                                                      counts
Name: best_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:13<06:31, 13.51s/it]

  7%|▋         | 2/30 [00:27<06:23, 13.71s/it]

 10%|█         | 3/30 [00:41<06:14, 13.88s/it]

 13%|█▎        | 4/30 [00:52<05:33, 12.82s/it]

 17%|█▋        | 5/30 [01:04<05:08, 12.34s/it]

 20%|██        | 6/30 [01:14<04:39, 11.64s/it]

 23%|██▎       | 7/30 [01:24<04:18, 11.25s/it]

 27%|██▋       | 8/30 [01:35<04:01, 10.96s/it]

 30%|███       | 9/30 [01:45<03:47, 10.81s/it]

 33%|███▎      | 10/30 [01:56<03:37, 10.85s/it]

 37%|███▋      | 11/30 [02:06<03:19, 10.51s/it]

 40%|████      | 12/30 [02:17<03:14, 10.82s/it]

 43%|████▎     | 13/30 [02:29<03:06, 10.96s/it]

 47%|████▋     | 14/30 [02:39<02:53, 10.82s/it]

 50%|█████     | 15/30 [02:50<02:40, 10.71s/it]

 53%|█████▎    | 16/30 [03:01<02:32, 10.86s/it]

 57%|█████▋    | 17/30 [03:12<02:23, 11.05s/it]

 60%|██████    | 18/30 [03:23<02:10, 10.86s/it]

 63%|██████▎   | 19/30 [03:35<02:05, 11.40s/it]

 67%|██████▋   | 20/30 [03:46<01:50, 11.07s/it]

 70%|███████   | 21/30 [03:57<01:38, 11.00s/it]

 73%|███████▎  | 22/30 [04:07<01:26, 10.84s/it]

 77%|███████▋  | 23/30 [04:17<01:14, 10.65s/it]

 80%|████████  | 24/30 [04:29<01:05, 10.98s/it]

 83%|████████▎ | 25/30 [04:42<00:58, 11.69s/it]

 87%|████████▋ | 26/30 [04:55<00:48, 12.00s/it]

 90%|█████████ | 27/30 [05:05<00:34, 11.41s/it]

 93%|█████████▎| 28/30 [05:16<00:22, 11.31s/it]

 97%|█████████▋| 29/30 [05:28<00:11, 11.56s/it]

100%|██████████| 30/30 [05:41<00:00, 11.80s/it]

100%|██████████| 30/30 [05:41<00:00, 11.37s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.93s/it]

100%|██████████| 2/2 [00:03<00:00,  1.49s/it]

100%|██████████| 2/2 [00:03<00:00,  1.55s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.7972084448944451

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.758380687342956

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7680460861351692

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.762406914965508

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7476336877326065

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.74410021571982

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.736179268448413

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7294835513715664

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7261621792836715

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7224687101274418

WARNING:2026-07-23 20:44:01,219:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7972084448944451
BRAS...

seed           1.000000
BAMI           0.797208
CASW           0.827366
SCGRAPHM       0.548570
BRAS           0.866577
KBET           0.678643
CPCR           0.788522
bio_score      0.724382
batch_score    0.777914
joint_score    0.745795
dtype: float64

===== seed 2 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:12<06:07, 12.66s/it]

  7%|▋         | 2/30 [00:23<05:17, 11.34s/it]

 10%|█         | 3/30 [00:35<05:22, 11.96s/it]

 13%|█▎        | 4/30 [00:47<05:11, 11.99s/it]

 17%|█▋        | 5/30 [00:59<04:55, 11.82s/it]

 20%|██        | 6/30 [01:09<04:27, 11.14s/it]

 23%|██▎       | 7/30 [01:21<04:28, 11.66s/it]

 27%|██▋       | 8/30 [01:34<04:26, 12.12s/it]

 30%|███       | 9/30 [01:48<04:21, 12.45s/it]

 33%|███▎      | 10/30 [02:02<04:18, 12.95s/it]

 37%|███▋      | 11/30 [02:15<04:06, 13.00s/it]

 40%|████      | 12/30 [02:27<03:48, 12.68s/it]

 43%|████▎     | 13/30 [02:40<03:39, 12.89s/it]

 47%|████▋     | 14/30 [02:54<03:28, 13.04s/it]

 50%|█████     | 15/30 [03:07<03:17, 13.19s/it]

 53%|█████▎    | 16/30 [03:18<02:54, 12.47s/it]

 57%|█████▋    | 17/30 [03:31<02:44, 12.68s/it]

 60%|██████    | 18/30 [03:43<02:28, 12.34s/it]

 63%|██████▎   | 19/30 [03:53<02:10, 11.90s/it]

 67%|██████▋   | 20/30 [04:04<01:54, 11.48s/it]

 70%|███████   | 21/30 [04:14<01:39, 11.06s/it]

 73%|███████▎  | 22/30 [04:24<01:26, 10.77s/it]

 77%|███████▋  | 23/30 [04:35<01:15, 10.82s/it]

 80%|████████  | 24/30 [04:47<01:07, 11.29s/it]

 83%|████████▎ | 25/30 [05:00<00:58, 11.68s/it]

 87%|████████▋ | 26/30 [05:10<00:45, 11.30s/it]

 90%|█████████ | 27/30 [05:22<00:34, 11.36s/it]

 93%|█████████▎| 28/30 [05:32<00:21, 10.87s/it]

 97%|█████████▋| 29/30 [05:41<00:10, 10.49s/it]

100%|██████████| 30/30 [05:51<00:00, 10.29s/it]

100%|██████████| 30/30 [05:51<00:00, 11.72s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.93s/it]

100%|██████████| 2/2 [00:03<00:00,  1.50s/it]

100%|██████████| 2/2 [00:03<00:00,  1.56s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7709692504564949

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7695713607483303

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.762544036995745

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7548662197744979

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7485510918105303

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.747849099559775

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7279992197097432

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7217714145474419

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7199596656164698

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7125788190720708

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7709692504564949
BRAS...

seed           2.000000
BAMI           0.770969
CASW           0.829976
SCGRAPHM       0.390658
BRAS           0.838954
KBET           0.631973
CPCR           0.685803
bio_score      0.663868
batch_score    0.718910
joint_score    0.685885
dtype: float64

===== seed 3 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:14<07:14, 14.98s/it]

  7%|▋         | 2/30 [00:29<06:50, 14.67s/it]

 10%|█         | 3/30 [00:44<06:39, 14.81s/it]

 13%|█▎        | 4/30 [00:57<06:10, 14.26s/it]

 17%|█▋        | 5/30 [01:11<05:51, 14.06s/it]

 20%|██        | 6/30 [01:24<05:28, 13.67s/it]

 23%|██▎       | 7/30 [01:33<04:36, 12.00s/it]

 27%|██▋       | 8/30 [01:41<03:58, 10.85s/it]

 30%|███       | 9/30 [01:52<03:50, 10.99s/it]

 33%|███▎      | 10/30 [02:03<03:39, 10.96s/it]

 37%|███▋      | 11/30 [02:17<03:45, 11.86s/it]

 40%|████      | 12/30 [02:31<03:44, 12.45s/it]

 43%|████▎     | 13/30 [02:46<03:48, 13.43s/it]

 47%|████▋     | 14/30 [03:00<03:37, 13.60s/it]

 50%|█████     | 15/30 [03:14<03:25, 13.73s/it]

 53%|█████▎    | 16/30 [03:29<03:15, 13.93s/it]

 57%|█████▋    | 17/30 [03:44<03:05, 14.27s/it]

 60%|██████    | 18/30 [04:00<02:58, 14.87s/it]

 63%|██████▎   | 19/30 [04:14<02:39, 14.52s/it]

 67%|██████▋   | 20/30 [04:28<02:23, 14.38s/it]

 70%|███████   | 21/30 [04:41<02:06, 14.11s/it]

 73%|███████▎  | 22/30 [04:55<01:50, 13.81s/it]

 77%|███████▋  | 23/30 [05:09<01:37, 13.95s/it]

 80%|████████  | 24/30 [05:23<01:23, 13.93s/it]

 83%|████████▎ | 25/30 [05:37<01:09, 13.89s/it]

 87%|████████▋ | 26/30 [05:51<00:56, 14.22s/it]

 90%|█████████ | 27/30 [06:01<00:38, 12.90s/it]

 93%|█████████▎| 28/30 [06:13<00:25, 12.60s/it]

 97%|█████████▋| 29/30 [06:25<00:12, 12.49s/it]

100%|██████████| 30/30 [06:36<00:00, 11.78s/it]

100%|██████████| 30/30 [06:36<00:00, 13.20s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:02<00:02,  2.63s/it]

100%|██████████| 2/2 [00:04<00:00,  2.04s/it]

100%|██████████| 2/2 [00:04<00:00,  2.13s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7835522428105471

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7708955101249696

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7599579615241976

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7646776764146482

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7523645043191183

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7330411348215641

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7316484941732173

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7246890597132895

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7137639314948189

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7107522487232717

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7835522428105471
BRAS...

seed           3.000000
BAMI           0.783552
CASW           0.820874
SCGRAPHM       0.341725
BRAS           0.853937
KBET           0.645443
CPCR           0.893009
bio_score      0.648717
batch_score    0.797463
joint_score    0.708215
dtype: float64

===== seed 4 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:14<07:04, 14.63s/it]

  7%|▋         | 2/30 [00:29<07:01, 15.04s/it]

 10%|█         | 3/30 [00:43<06:30, 14.45s/it]

 13%|█▎        | 4/30 [00:56<06:03, 13.96s/it]

 17%|█▋        | 5/30 [01:10<05:46, 13.86s/it]

 20%|██        | 6/30 [01:21<05:09, 12.91s/it]

 23%|██▎       | 7/30 [01:34<04:52, 12.72s/it]

 27%|██▋       | 8/30 [01:47<04:41, 12.81s/it]

 30%|███       | 9/30 [02:01<04:39, 13.31s/it]

 33%|███▎      | 10/30 [02:13<04:20, 13.02s/it]

 37%|███▋      | 11/30 [02:27<04:11, 13.24s/it]

 40%|████      | 12/30 [02:35<03:29, 11.64s/it]

 43%|████▎     | 13/30 [02:45<03:08, 11.10s/it]

 47%|████▋     | 14/30 [03:00<03:15, 12.25s/it]

 50%|█████     | 15/30 [03:17<03:25, 13.70s/it]

 53%|█████▎    | 16/30 [03:34<03:24, 14.63s/it]

 57%|█████▋    | 17/30 [03:50<03:15, 15.01s/it]

 60%|██████    | 18/30 [04:10<03:18, 16.57s/it]

 63%|██████▎   | 19/30 [04:26<03:00, 16.39s/it]

 67%|██████▋   | 20/30 [04:41<02:41, 16.10s/it]

 70%|███████   | 21/30 [04:56<02:22, 15.81s/it]

 73%|███████▎  | 22/30 [05:12<02:05, 15.67s/it]

 77%|███████▋  | 23/30 [05:28<01:50, 15.75s/it]

 80%|████████  | 24/30 [05:46<01:38, 16.50s/it]

 83%|████████▎ | 25/30 [06:03<01:23, 16.68s/it]

 87%|████████▋ | 26/30 [06:20<01:07, 16.91s/it]

 90%|█████████ | 27/30 [06:37<00:50, 16.77s/it]

 93%|█████████▎| 28/30 [06:50<00:31, 15.84s/it]

 97%|█████████▋| 29/30 [07:07<00:15, 15.91s/it]

100%|██████████| 30/30 [07:23<00:00, 16.10s/it]

100%|██████████| 30/30 [07:23<00:00, 14.79s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:02<00:02,  2.22s/it]

100%|██████████| 2/2 [00:03<00:00,  1.55s/it]

100%|██████████| 2/2 [00:03<00:00,  1.65s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8115021388453955

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7599310865940665

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7766098154299462

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7524096427865744

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7400639450026899

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7347255453743925

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7289419577418761

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7142162499092265

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7058815005490139

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7097913307095228

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8115021388453955
BRAS...

seed           4.000000
BAMI           0.811502
CASW           0.816268
SCGRAPHM       0.361548
BRAS           0.843845
KBET           0.623282
CPCR           0.868765
bio_score      0.663106
batch_score    0.778630
joint_score    0.709316
dtype: float64

===== seed 5 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:15<07:35, 15.70s/it]

  7%|▋         | 2/30 [00:31<07:16, 15.59s/it]

 10%|█         | 3/30 [00:45<06:44, 15.00s/it]

 13%|█▎        | 4/30 [00:59<06:17, 14.51s/it]

 17%|█▋        | 5/30 [01:13<06:03, 14.56s/it]

 20%|██        | 6/30 [01:27<05:45, 14.39s/it]

 23%|██▎       | 7/30 [01:37<04:51, 12.66s/it]

 27%|██▋       | 8/30 [01:45<04:07, 11.26s/it]

 30%|███       | 9/30 [01:53<03:36, 10.32s/it]

 33%|███▎      | 10/30 [02:01<03:11,  9.59s/it]

 37%|███▋      | 11/30 [02:09<02:52,  9.08s/it]

 40%|████      | 12/30 [02:17<02:38,  8.78s/it]

 43%|████▎     | 13/30 [02:25<02:25,  8.57s/it]

 47%|████▋     | 14/30 [02:33<02:14,  8.38s/it]

 50%|█████     | 15/30 [02:41<02:03,  8.25s/it]

 53%|█████▎    | 16/30 [02:49<01:54,  8.15s/it]

 57%|█████▋    | 17/30 [02:57<01:45,  8.13s/it]

 60%|██████    | 18/30 [03:05<01:36,  8.07s/it]

 63%|██████▎   | 19/30 [03:17<01:42,  9.32s/it]

 67%|██████▋   | 20/30 [03:39<02:10, 13.02s/it]

 70%|███████   | 21/30 [03:59<02:15, 15.03s/it]

 73%|███████▎  | 22/30 [04:18<02:11, 16.41s/it]

 77%|███████▋  | 23/30 [04:38<02:01, 17.38s/it]

 80%|████████  | 24/30 [04:57<01:47, 17.93s/it]

 83%|████████▎ | 25/30 [05:16<01:31, 18.32s/it]

 87%|████████▋ | 26/30 [05:36<01:15, 18.83s/it]

 90%|█████████ | 27/30 [05:55<00:56, 18.83s/it]

 93%|█████████▎| 28/30 [06:13<00:36, 18.40s/it]

 97%|█████████▋| 29/30 [06:31<00:18, 18.28s/it]

100%|██████████| 30/30 [06:48<00:00, 18.17s/it]

100%|██████████| 30/30 [06:48<00:00, 13.63s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.82s/it]

100%|██████████| 2/2 [00:03<00:00,  1.58s/it]

100%|██████████| 2/2 [00:03<00:00,  1.62s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7628719796063728

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7612065051500676

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7637973074214164

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.76201167574038

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7527326948231674

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7452718615068066

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7396256658290808

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7283772764976387

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7268016348005762

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7173878680339085

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7637973074214164
BRAS...

seed           5.000000
BAMI           0.763797
CASW           0.826850
SCGRAPHM       0.336912
BRAS           0.855552
KBET           0.662143
CPCR           0.882671
bio_score      0.642520
batch_score    0.800122
joint_score    0.705560
dtype: float64

===== seed 6 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:19<09:16, 19.17s/it]

  7%|▋         | 2/30 [00:38<09:04, 19.44s/it]

 10%|█         | 3/30 [00:56<08:27, 18.79s/it]

 13%|█▎        | 4/30 [01:12<07:39, 17.67s/it]

 17%|█▋        | 5/30 [01:28<07:02, 16.89s/it]

 20%|██        | 6/30 [01:43<06:33, 16.38s/it]

 23%|██▎       | 7/30 [01:59<06:13, 16.24s/it]

 27%|██▋       | 8/30 [02:14<05:50, 15.95s/it]

 30%|███       | 9/30 [02:29<05:22, 15.36s/it]

 33%|███▎      | 10/30 [02:41<04:51, 14.58s/it]

 37%|███▋      | 11/30 [02:50<04:00, 12.65s/it]

 40%|████      | 12/30 [02:58<03:21, 11.21s/it]

 43%|████▎     | 13/30 [03:05<02:53, 10.19s/it]

 47%|████▋     | 14/30 [03:13<02:31,  9.47s/it]

 50%|█████     | 15/30 [03:22<02:19,  9.33s/it]

 53%|█████▎    | 16/30 [03:30<02:04,  8.86s/it]

 57%|█████▋    | 17/30 [03:42<02:06,  9.70s/it]

 60%|██████    | 18/30 [03:54<02:07, 10.65s/it]

 63%|██████▎   | 19/30 [04:08<02:06, 11.51s/it]

 67%|██████▋   | 20/30 [04:21<01:59, 11.94s/it]

 70%|███████   | 21/30 [04:34<01:50, 12.23s/it]

 73%|███████▎  | 22/30 [04:42<01:27, 10.90s/it]

 77%|███████▋  | 23/30 [05:00<01:32, 13.18s/it]

 80%|████████  | 24/30 [05:20<01:30, 15.10s/it]

 83%|████████▎ | 25/30 [05:40<01:23, 16.63s/it]

 87%|████████▋ | 26/30 [06:01<01:11, 17.86s/it]

 90%|█████████ | 27/30 [06:18<00:53, 17.70s/it]

 93%|█████████▎| 28/30 [06:37<00:36, 18.23s/it]

 97%|█████████▋| 29/30 [06:56<00:18, 18.35s/it]

100%|██████████| 30/30 [07:14<00:00, 18.33s/it]

100%|██████████| 30/30 [07:14<00:00, 14.49s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:06<00:06,  6.33s/it]

100%|██████████| 2/2 [00:09<00:00,  4.76s/it]

100%|██████████| 2/2 [00:09<00:00,  5.00s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7612649815647298

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7397689238421348

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7555707717407397

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7576378902715346

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7394137787379321

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7348772048358082

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.733688513710458

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7145148779147223

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7102673692944197

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7069901977441821

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7612649815647298
BRAS...

seed           6.000000
BAMI           0.761265
CASW           0.813052
SCGRAPHM       0.345554
BRAS           0.875904
KBET           0.659709
CPCR           0.898456
bio_score      0.639957
batch_score    0.811356
joint_score    0.708517
dtype: float64

===== seed 7 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:18<08:42, 18.02s/it]

  7%|▋         | 2/30 [00:35<08:07, 17.42s/it]

 10%|█         | 3/30 [00:49<07:17, 16.20s/it]

 13%|█▎        | 4/30 [01:04<06:42, 15.48s/it]

 17%|█▋        | 5/30 [01:19<06:23, 15.35s/it]

 20%|██        | 6/30 [01:35<06:14, 15.60s/it]

 23%|██▎       | 7/30 [01:49<05:50, 15.25s/it]

 27%|██▋       | 8/30 [02:04<05:31, 15.09s/it]

 30%|███       | 9/30 [02:19<05:13, 14.94s/it]

 33%|███▎      | 10/30 [02:33<04:54, 14.71s/it]

 37%|███▋      | 11/30 [02:49<04:45, 15.00s/it]

 40%|████      | 12/30 [03:04<04:33, 15.20s/it]

 43%|████▎     | 13/30 [03:20<04:19, 15.27s/it]

 47%|████▋     | 14/30 [03:34<03:58, 14.91s/it]

 50%|█████     | 15/30 [03:49<03:43, 14.88s/it]

 53%|█████▎    | 16/30 [04:02<03:23, 14.54s/it]

 57%|█████▋    | 17/30 [04:17<03:09, 14.54s/it]

 60%|██████    | 18/30 [04:31<02:51, 14.32s/it]

 63%|██████▎   | 19/30 [04:45<02:36, 14.20s/it]

 67%|██████▋   | 20/30 [04:58<02:19, 13.96s/it]

 70%|███████   | 21/30 [05:12<02:05, 13.99s/it]

 73%|███████▎  | 22/30 [05:25<01:49, 13.69s/it]

 77%|███████▋  | 23/30 [05:37<01:31, 13.04s/it]

 80%|████████  | 24/30 [05:45<01:10, 11.81s/it]

 83%|████████▎ | 25/30 [05:54<00:53, 10.69s/it]

 87%|████████▋ | 26/30 [06:02<00:39,  9.88s/it]

 90%|█████████ | 27/30 [06:10<00:27,  9.33s/it]

 93%|█████████▎| 28/30 [06:18<00:17,  8.99s/it]

 97%|█████████▋| 29/30 [06:29<00:09,  9.77s/it]

100%|██████████| 30/30 [06:43<00:00, 10.93s/it]

100%|██████████| 30/30 [06:43<00:00, 13.45s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:05<00:05,  5.35s/it]

100%|██████████| 2/2 [00:08<00:00,  4.10s/it]

100%|██████████| 2/2 [00:08<00:00,  4.29s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8078084104320914

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7719881679691712

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8022035298394492

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7894721924426761

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7897571098318589

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7659410542981673

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.75159989776088

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7485878442551961

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7408898009232051

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7371114340473185

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8078084104320914
BRAS...

seed           7.000000
BAMI           0.807808
CASW           0.835504
SCGRAPHM       0.464404
BRAS           0.851466
KBET           0.620421
CPCR           0.853218
bio_score      0.702572
batch_score    0.775035
joint_score    0.731557
dtype: float64

===== seed 8 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:08<04:13,  8.73s/it]

  7%|▋         | 2/30 [00:30<07:38, 16.39s/it]

 10%|█         | 3/30 [00:51<08:19, 18.50s/it]

 13%|█▎        | 4/30 [01:10<08:06, 18.72s/it]

 17%|█▋        | 5/30 [01:29<07:52, 18.89s/it]

 20%|██        | 6/30 [01:48<07:36, 19.02s/it]

 23%|██▎       | 7/30 [02:07<07:11, 18.77s/it]

 27%|██▋       | 8/30 [02:25<06:50, 18.66s/it]

 30%|███       | 9/30 [02:43<06:23, 18.28s/it]

 33%|███▎      | 10/30 [03:00<05:59, 18.00s/it]

 37%|███▋      | 11/30 [03:18<05:42, 18.03s/it]

 40%|████      | 12/30 [03:38<05:32, 18.47s/it]

 43%|████▎     | 13/30 [03:56<05:11, 18.31s/it]

 47%|████▋     | 14/30 [04:13<04:48, 18.05s/it]

 50%|█████     | 15/30 [04:30<04:25, 17.73s/it]

 53%|█████▎    | 16/30 [04:47<04:06, 17.61s/it]

 57%|█████▋    | 17/30 [05:03<03:41, 17.01s/it]

 60%|██████    | 18/30 [05:17<03:12, 16.06s/it]

 63%|██████▎   | 19/30 [05:32<02:53, 15.77s/it]

 67%|██████▋   | 20/30 [05:46<02:31, 15.18s/it]

 70%|███████   | 21/30 [05:59<02:10, 14.49s/it]

 73%|███████▎  | 22/30 [06:08<01:44, 13.02s/it]

 77%|███████▋  | 23/30 [06:16<01:20, 11.49s/it]

 80%|████████  | 24/30 [06:24<01:02, 10.41s/it]

 83%|████████▎ | 25/30 [06:32<00:48,  9.65s/it]

 87%|████████▋ | 26/30 [06:40<00:36,  9.18s/it]

 90%|█████████ | 27/30 [06:48<00:26,  8.91s/it]

 93%|█████████▎| 28/30 [07:00<00:19,  9.91s/it]

 97%|█████████▋| 29/30 [07:13<00:10, 10.76s/it]

100%|██████████| 30/30 [07:26<00:00, 11.50s/it]

100%|██████████| 30/30 [07:26<00:00, 14.90s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.84s/it]

100%|██████████| 2/2 [00:02<00:00,  1.40s/it]

100%|██████████| 2/2 [00:02<00:00,  1.46s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7906437132122746

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7678206649193975

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7571587235851498

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7543416178462182

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7400123003920154

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7260478627461691

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7201891252385417

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7191310319603922

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7197828622005987

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7152615036921117

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7906437132122746
BRAS...

seed           8.000000
BAMI           0.790644
CASW           0.806064
SCGRAPHM       0.361776
BRAS           0.843803
KBET           0.642227
CPCR           0.652577
bio_score      0.652828
batch_score    0.712869
joint_score    0.676844
dtype: float64

===== seed 9 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:14<07:01, 14.54s/it]

  7%|▋         | 2/30 [00:29<06:54, 14.80s/it]

 10%|█         | 3/30 [00:38<05:29, 12.19s/it]

 13%|█▎        | 4/30 [00:55<06:02, 13.93s/it]

 17%|█▋        | 5/30 [01:14<06:32, 15.71s/it]

 20%|██        | 6/30 [01:31<06:32, 16.35s/it]

 23%|██▎       | 7/30 [01:49<06:26, 16.80s/it]

 27%|██▋       | 8/30 [02:08<06:24, 17.50s/it]

 30%|███       | 9/30 [02:25<06:04, 17.38s/it]

 33%|███▎      | 10/30 [02:41<05:38, 16.93s/it]

 37%|███▋      | 11/30 [02:57<05:14, 16.57s/it]

 40%|████      | 12/30 [03:13<04:54, 16.37s/it]

 43%|████▎     | 13/30 [03:29<04:39, 16.44s/it]

 47%|████▋     | 14/30 [03:46<04:23, 16.47s/it]

 50%|█████     | 15/30 [04:01<04:03, 16.26s/it]

 53%|█████▎    | 16/30 [04:14<03:31, 15.11s/it]

 57%|█████▋    | 17/30 [04:22<02:48, 12.94s/it]

 60%|██████    | 18/30 [04:30<02:16, 11.40s/it]

 63%|██████▎   | 19/30 [04:38<01:55, 10.54s/it]

 67%|██████▋   | 20/30 [04:48<01:43, 10.39s/it]

 70%|███████   | 21/30 [05:02<01:42, 11.40s/it]

 73%|███████▎  | 22/30 [05:15<01:34, 11.85s/it]

 77%|███████▋  | 23/30 [05:24<01:16, 10.98s/it]

 80%|████████  | 24/30 [05:43<01:20, 13.34s/it]

 83%|████████▎ | 25/30 [06:02<01:16, 15.26s/it]

 87%|████████▋ | 26/30 [06:21<01:04, 16.17s/it]

 90%|█████████ | 27/30 [06:40<00:51, 17.01s/it]

 93%|█████████▎| 28/30 [06:59<00:35, 17.64s/it]

 97%|█████████▋| 29/30 [07:17<00:17, 17.96s/it]

100%|██████████| 30/30 [07:30<00:00, 16.43s/it]

100%|██████████| 30/30 [07:30<00:00, 15.03s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:04<00:04,  4.79s/it]

100%|██████████| 2/2 [00:07<00:00,  3.61s/it]

100%|██████████| 2/2 [00:07<00:00,  3.79s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7371634152070856

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7381182475410871

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7455559777040643

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7434437418393207

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7400663762155545

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7340994340478318

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7374185133180116

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7316787545028706

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7268120213538346

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.724318013732914

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7455559777040643
BRAS...

seed           9.000000
BAMI           0.745556
CASW           0.837173
SCGRAPHM       0.375268
BRAS           0.769553
KBET           0.590061
CPCR           0.889916
bio_score      0.652666
batch_score    0.749843
joint_score    0.691537
dtype: float64

===== seed 10 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=32 value_lambda=0.5033965087804688 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:18<09:04, 18.78s/it]

  7%|▋         | 2/30 [00:38<09:03, 19.40s/it]

 10%|█         | 3/30 [00:56<08:20, 18.53s/it]

 13%|█▎        | 4/30 [01:13<07:52, 18.19s/it]

 17%|█▋        | 5/30 [01:30<07:19, 17.57s/it]

 20%|██        | 6/30 [01:46<06:51, 17.13s/it]

 23%|██▎       | 7/30 [02:02<06:26, 16.79s/it]

 27%|██▋       | 8/30 [02:17<05:54, 16.10s/it]

 30%|███       | 9/30 [02:32<05:31, 15.79s/it]

 33%|███▎      | 10/30 [02:47<05:10, 15.55s/it]

 37%|███▋      | 11/30 [03:00<04:43, 14.92s/it]

 40%|████      | 12/30 [03:12<04:12, 14.05s/it]

 43%|████▎     | 13/30 [03:20<03:27, 12.19s/it]

 47%|████▋     | 14/30 [03:28<02:53, 10.86s/it]

 50%|█████     | 15/30 [03:36<02:29, 10.00s/it]

 53%|█████▎    | 16/30 [03:47<02:22, 10.16s/it]

 57%|█████▋    | 17/30 [04:00<02:25, 11.23s/it]

 60%|██████    | 18/30 [04:15<02:27, 12.28s/it]

 63%|██████▎   | 19/30 [04:29<02:21, 12.84s/it]

 67%|██████▋   | 20/30 [04:42<02:07, 12.70s/it]

 70%|███████   | 21/30 [04:50<01:41, 11.33s/it]

 73%|███████▎  | 22/30 [05:06<01:42, 12.80s/it]

 77%|███████▋  | 23/30 [05:28<01:48, 15.56s/it]

 80%|████████  | 24/30 [05:48<01:41, 16.91s/it]

 83%|████████▎ | 25/30 [06:08<01:28, 17.69s/it]

 87%|████████▋ | 26/30 [06:27<01:13, 18.27s/it]

 90%|█████████ | 27/30 [06:45<00:54, 18.23s/it]

 93%|█████████▎| 28/30 [07:05<00:37, 18.76s/it]

 97%|█████████▋| 29/30 [07:23<00:18, 18.54s/it]

100%|██████████| 30/30 [07:43<00:00, 19.01s/it]

100%|██████████| 30/30 [07:43<00:00, 15.46s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:06<00:06,  6.06s/it]

100%|██████████| 2/2 [00:10<00:00,  4.85s/it]

100%|██████████| 2/2 [00:10<00:00,  5.03s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8233232493906156

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7870572628550326

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7723692422075503

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7706019957058979

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7571234732296002

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7350454860675086

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7349092338672418

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7327504367002581

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7278733199889943

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7188453322386544

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8233232493906156
BRAS...

seed           10.000000
BAMI            0.823323
CASW            0.829614
SCGRAPHM        0.374959
BRAS            0.844074
KBET            0.617056
CPCR            0.748374
bio_score       0.675965
batch_score     0.736501
joint_score     0.700180
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.797208,0.827366,0.548570,0.866577,0.678643,0.788522,0.724382,0.777914,0.745795
1,2,0.770969,0.829976,0.390658,0.838954,0.631973,0.685803,0.663868,0.718910,0.685885
2,3,0.783552,0.820874,0.341725,0.853937,0.645443,0.893009,0.648717,0.797463,0.708215
3,4,0.811502,0.816268,0.361548,0.843845,0.623282,0.868765,0.663106,0.778630,0.709316
4,5,0.763797,0.826850,0.336912,0.855552,0.662143,0.882671,0.642520,0.800122,0.705560
5,6,0.761265,0.813052,0.345554,0.875904,0.659709,0.898456,0.639957,0.811356,0.708517
6,7,0.807808,0.835504,0.464404,0.851466,0.620421,0.853218,0.702572,0.775035,0.731557
7,8,0.790644,0.806064,0.361776,0.843803,0.642227,0.652577,0.652828,0.712869,0.676844
8,9,0.745556,0.837173,0.375268,0.769553,0.590061,0.889916,0.652666,0.749843,0.691537
9,10,0.823323,0.829614,0.374959,0.844074,0.617056,0.748374,0.675965,0.736501,0.700180

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.785563  0.023742  0.745556  0.823323
CASW         0.824274  0.009502  0.806064  0.837173
SCGRAPHM     0.390138  0.063130  0.336912  0.548570
BRAS         0.844366  0.027170  0.769553  0.875904
KBET         0.637096  0.024637  0.590061  0.678643
CPCR         0.816131  0.087060  0.652577  0.898456
bio_score    0.666658  0.025949  0.639957  0.724382
batch_score  0.765864  0.032811  0.712869  0.811356
joint_score  0.706341  0.019380  0.676844  0.745795