# LIGER default - nph_cerebellum

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'nph_cerebellum'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'Sample'
LABEL_KEY = 'Celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'nph_cerebellum'
assert BATCH_KEY == 'Sample'
assert LABEL_KEY == 'Celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                         nph_cerebellum
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                               Sample
label_key                                             Celltype
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=84619 n_batches=2 n_labels=8
CPCR preflight: eligible_labels=8

In [4]:
LIGER_DEFAULT_ARGS = {
    "k": 20,
    "value_lambda": 5.0,
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_default(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_DEFAULT_ARGS["k"],
        lam=LIGER_DEFAULT_ARGS["value_lambda"],
        max_iterations=LIGER_DEFAULT_ARGS["max_iters"],
        mode=LIGER_DEFAULT_ARGS["mode"],
        layer=LIGER_DEFAULT_ARGS["layer"],
        seed=seed,
    )


pd.Series(LIGER_DEFAULT_ARGS, name="default_setting")

k                   20
value_lambda       5.0
max_iters           30
mode              core
layer           counts
Name: default_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_default(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:08<04:12,  8.71s/it]

  7%|▋         | 2/30 [00:15<03:36,  7.74s/it]

 10%|█         | 3/30 [00:22<03:20,  7.44s/it]

 13%|█▎        | 4/30 [00:31<03:23,  7.82s/it]

 17%|█▋        | 5/30 [00:38<03:10,  7.64s/it]

 20%|██        | 6/30 [00:45<03:00,  7.52s/it]

 23%|██▎       | 7/30 [00:53<02:51,  7.44s/it]

 27%|██▋       | 8/30 [01:00<02:44,  7.48s/it]

 30%|███       | 9/30 [01:08<02:36,  7.47s/it]

 33%|███▎      | 10/30 [01:15<02:27,  7.35s/it]

 37%|███▋      | 11/30 [01:22<02:17,  7.23s/it]

 40%|████      | 12/30 [01:29<02:10,  7.23s/it]

 43%|████▎     | 13/30 [01:36<02:02,  7.19s/it]

 47%|████▋     | 14/30 [01:44<01:57,  7.34s/it]

 50%|█████     | 15/30 [01:51<01:48,  7.25s/it]

 53%|█████▎    | 16/30 [01:58<01:40,  7.15s/it]

 57%|█████▋    | 17/30 [02:05<01:32,  7.14s/it]

 60%|██████    | 18/30 [02:12<01:24,  7.06s/it]

 63%|██████▎   | 19/30 [02:19<01:17,  7.05s/it]

 67%|██████▋   | 20/30 [02:26<01:12,  7.27s/it]

 70%|███████   | 21/30 [02:34<01:06,  7.38s/it]

 73%|███████▎  | 22/30 [02:42<00:59,  7.40s/it]

 77%|███████▋  | 23/30 [02:48<00:50,  7.26s/it]

 80%|████████  | 24/30 [02:58<00:46,  7.80s/it]

 83%|████████▎ | 25/30 [03:10<00:45,  9.05s/it]

 87%|████████▋ | 26/30 [03:16<00:33,  8.38s/it]

 90%|█████████ | 27/30 [03:23<00:23,  7.80s/it]

 93%|█████████▎| 28/30 [03:32<00:16,  8.10s/it]

 97%|█████████▋| 29/30 [03:43<00:08,  8.99s/it]

100%|██████████| 30/30 [03:51<00:00,  8.90s/it]

100%|██████████| 30/30 [03:51<00:00,  7.73s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:02<00:02,  2.58s/it]

100%|██████████| 2/2 [00:04<00:00,  2.09s/it]

100%|██████████| 2/2 [00:04<00:00,  2.16s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.7793007220985694

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7922402038044493

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7871106009330838

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7820855039244157

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7611663974383736

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7524333179403102

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7413037417255094

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7250327423394998

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7161510565341914

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7129075564225174

WARNING:2026-07-23 19:22:18,238:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7922402038044493
BRAS...

seed           1.000000
BAMI           0.792240
CASW           0.791940
SCGRAPHM       0.385928
BRAS           0.871827
KBET           0.662997
CPCR           0.149700
bio_score      0.656703
batch_score    0.561508
joint_score    0.618625
dtype: float64

===== seed 2 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:09<04:44,  9.80s/it]

  7%|▋         | 2/30 [00:19<04:33,  9.76s/it]

 10%|█         | 3/30 [00:27<03:58,  8.82s/it]

 13%|█▎        | 4/30 [00:34<03:37,  8.36s/it]

 17%|█▋        | 5/30 [00:45<03:49,  9.19s/it]

 20%|██        | 6/30 [00:54<03:38,  9.10s/it]

 23%|██▎       | 7/30 [01:05<03:44,  9.76s/it]

 27%|██▋       | 8/30 [01:13<03:21,  9.14s/it]

 30%|███       | 9/30 [01:20<02:58,  8.50s/it]

 33%|███▎      | 10/30 [01:27<02:42,  8.11s/it]

 37%|███▋      | 11/30 [01:35<02:33,  8.10s/it]

 40%|████      | 12/30 [01:46<02:39,  8.85s/it]

 43%|████▎     | 13/30 [01:55<02:31,  8.91s/it]

 47%|████▋     | 14/30 [02:03<02:18,  8.64s/it]

 50%|█████     | 15/30 [02:10<02:04,  8.30s/it]

 53%|█████▎    | 16/30 [02:18<01:51,  7.99s/it]

 57%|█████▋    | 17/30 [02:27<01:49,  8.45s/it]

 60%|██████    | 18/30 [02:37<01:46,  8.88s/it]

 63%|██████▎   | 19/30 [02:47<01:39,  9.07s/it]

 67%|██████▋   | 20/30 [02:56<01:30,  9.07s/it]

 70%|███████   | 21/30 [03:05<01:22,  9.13s/it]

 73%|███████▎  | 22/30 [03:13<01:10,  8.82s/it]

 77%|███████▋  | 23/30 [03:21<00:58,  8.43s/it]

 80%|████████  | 24/30 [03:28<00:48,  8.13s/it]

 83%|████████▎ | 25/30 [03:35<00:39,  7.87s/it]

 87%|████████▋ | 26/30 [03:43<00:30,  7.71s/it]

 90%|█████████ | 27/30 [03:50<00:22,  7.63s/it]

 93%|█████████▎| 28/30 [03:58<00:15,  7.72s/it]

 97%|█████████▋| 29/30 [04:05<00:07,  7.53s/it]

100%|██████████| 30/30 [04:12<00:00,  7.39s/it]

100%|██████████| 30/30 [04:12<00:00,  8.42s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.95s/it]

100%|██████████| 2/2 [00:03<00:00,  1.50s/it]

100%|██████████| 2/2 [00:03<00:00,  1.57s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7751010539109421

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.760249910709578

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7513019558703391

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7461954350966918

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.74394150795535

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7366944539851353

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7399141277385035

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7336135943302858

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.730808946864105

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7292421840285666

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7751010539109421
BRAS...

seed           2.000000
BAMI           0.775101
CASW           0.763847
SCGRAPHM       0.462604
BRAS           0.844292
KBET           0.689364
CPCR           0.070653
bio_score      0.667184
batch_score    0.534769
joint_score    0.614218
dtype: float64

===== seed 3 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:07<03:50,  7.94s/it]

  7%|▋         | 2/30 [00:14<03:16,  7.03s/it]

 10%|█         | 3/30 [00:27<04:25,  9.84s/it]

 13%|█▎        | 4/30 [00:33<03:39,  8.43s/it]

 17%|█▋        | 5/30 [00:40<03:11,  7.67s/it]

 20%|██        | 6/30 [00:46<02:56,  7.36s/it]

 23%|██▎       | 7/30 [00:54<02:47,  7.30s/it]

 27%|██▋       | 8/30 [01:07<03:26,  9.37s/it]

 30%|███       | 9/30 [01:15<03:03,  8.76s/it]

 33%|███▎      | 10/30 [01:22<02:47,  8.37s/it]

 37%|███▋      | 11/30 [01:30<02:37,  8.31s/it]

 40%|████      | 12/30 [01:39<02:28,  8.27s/it]

 43%|████▎     | 13/30 [01:55<03:04, 10.86s/it]

 47%|████▋     | 14/30 [02:02<02:31,  9.47s/it]

 50%|█████     | 15/30 [02:11<02:21,  9.44s/it]

 53%|█████▎    | 16/30 [02:22<02:16,  9.77s/it]

 57%|█████▋    | 17/30 [02:32<02:11, 10.11s/it]

 60%|██████    | 18/30 [02:45<02:09, 10.79s/it]

 63%|██████▎   | 19/30 [02:57<02:02, 11.16s/it]

 67%|██████▋   | 20/30 [03:06<01:45, 10.57s/it]

 70%|███████   | 21/30 [03:15<01:31, 10.17s/it]

 73%|███████▎  | 22/30 [03:25<01:20, 10.10s/it]

 77%|███████▋  | 23/30 [03:33<01:06,  9.49s/it]

 80%|████████  | 24/30 [03:41<00:52,  8.81s/it]

 83%|████████▎ | 25/30 [03:49<00:44,  8.80s/it]

 87%|████████▋ | 26/30 [03:59<00:36,  9.08s/it]

 90%|█████████ | 27/30 [04:07<00:25,  8.66s/it]

 93%|█████████▎| 28/30 [04:14<00:16,  8.31s/it]

 97%|█████████▋| 29/30 [04:22<00:08,  8.10s/it]

100%|██████████| 30/30 [04:29<00:00,  7.95s/it]

100%|██████████| 30/30 [04:29<00:00,  9.00s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:02<00:02,  2.27s/it]

100%|██████████| 2/2 [00:03<00:00,  1.85s/it]

100%|██████████| 2/2 [00:03<00:00,  1.91s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7641244565808657

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7834726143382623

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7796653397495942

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.765071796087294

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7386738446633541

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7365840108889705

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7258427369835163

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7250567434464227

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.723469703160866

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7180626380530808

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7834726143382623
BRAS...

seed           3.000000
BAMI           0.783473
CASW           0.831708
SCGRAPHM       0.424301
BRAS           0.862478
KBET           0.619516
CPCR           0.475901
bio_score      0.679827
batch_score    0.652631
joint_score    0.668949
dtype: float64

===== seed 4 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:13<06:17, 13.03s/it]

  7%|▋         | 2/30 [00:20<04:25,  9.49s/it]

 10%|█         | 3/30 [00:27<03:48,  8.46s/it]

 13%|█▎        | 4/30 [00:34<03:28,  8.01s/it]

 17%|█▋        | 5/30 [00:45<03:44,  8.98s/it]

 20%|██        | 6/30 [00:54<03:38,  9.09s/it]

 23%|██▎       | 7/30 [01:05<03:41,  9.64s/it]

 27%|██▋       | 8/30 [01:12<03:12,  8.76s/it]

 30%|███       | 9/30 [01:19<02:50,  8.14s/it]

 33%|███▎      | 10/30 [01:26<02:39,  7.96s/it]

 37%|███▋      | 11/30 [01:35<02:35,  8.19s/it]

 40%|████      | 12/30 [01:45<02:38,  8.80s/it]

 43%|████▎     | 13/30 [01:57<02:44,  9.66s/it]

 47%|████▋     | 14/30 [02:09<02:48, 10.55s/it]

 50%|█████     | 15/30 [02:22<02:46, 11.10s/it]

 53%|█████▎    | 16/30 [02:31<02:29, 10.65s/it]

 57%|█████▋    | 17/30 [02:38<02:04,  9.60s/it]

 60%|██████    | 18/30 [02:45<01:43,  8.66s/it]

 63%|██████▎   | 19/30 [02:51<01:28,  8.01s/it]

 67%|██████▋   | 20/30 [02:58<01:14,  7.49s/it]

 70%|███████   | 21/30 [03:04<01:04,  7.19s/it]

 73%|███████▎  | 22/30 [03:13<01:00,  7.62s/it]

 77%|███████▋  | 23/30 [03:23<00:57,  8.27s/it]

 80%|████████  | 24/30 [03:29<00:47,  7.84s/it]

 83%|████████▎ | 25/30 [03:35<00:36,  7.33s/it]

 87%|████████▋ | 26/30 [03:42<00:27,  6.96s/it]

 90%|█████████ | 27/30 [03:48<00:20,  6.73s/it]

 93%|█████████▎| 28/30 [03:54<00:13,  6.62s/it]

 97%|█████████▋| 29/30 [04:01<00:06,  6.83s/it]

100%|██████████| 30/30 [04:11<00:00,  7.64s/it]

100%|██████████| 30/30 [04:11<00:00,  8.38s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:02<00:02,  2.45s/it]

100%|██████████| 2/2 [00:03<00:00,  1.87s/it]

100%|██████████| 2/2 [00:03<00:00,  1.96s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8184227571080802

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7983170317925777

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7860211501457931

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.774317409236954

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7549773994067429

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7545324384633058

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7536345740104079

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7486966347447773

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7449779636036193

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7346032088154054

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8184227571080802
BRAS...

seed           4.000000
BAMI           0.818423
CASW           0.810065
SCGRAPHM       0.369165
BRAS           0.846228
KBET           0.685910
CPCR           0.390821
bio_score      0.665884
batch_score    0.640986
joint_score    0.655925
dtype: float64

===== seed 5 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:07<03:42,  7.66s/it]

  7%|▋         | 2/30 [00:13<03:07,  6.68s/it]

 10%|█         | 3/30 [00:20<03:03,  6.79s/it]

 13%|█▎        | 4/30 [00:27<02:59,  6.89s/it]

 17%|█▋        | 5/30 [00:34<02:51,  6.85s/it]

 20%|██        | 6/30 [00:40<02:40,  6.70s/it]

 23%|██▎       | 7/30 [00:49<02:46,  7.23s/it]

 27%|██▋       | 8/30 [00:55<02:34,  7.04s/it]

 30%|███       | 9/30 [01:02<02:25,  6.95s/it]

 33%|███▎      | 10/30 [01:12<02:35,  7.76s/it]

 37%|███▋      | 11/30 [01:18<02:21,  7.45s/it]

 40%|████      | 12/30 [01:25<02:10,  7.25s/it]

 43%|████▎     | 13/30 [01:33<02:07,  7.50s/it]

 47%|████▋     | 14/30 [01:41<02:01,  7.59s/it]

 50%|█████     | 15/30 [01:48<01:49,  7.29s/it]

 53%|█████▎    | 16/30 [01:54<01:39,  7.13s/it]

 57%|█████▋    | 17/30 [02:01<01:31,  7.01s/it]

 60%|██████    | 18/30 [02:08<01:22,  6.88s/it]

 63%|██████▎   | 19/30 [02:14<01:15,  6.85s/it]

 67%|██████▋   | 20/30 [02:21<01:08,  6.80s/it]

 70%|███████   | 21/30 [02:28<01:01,  6.84s/it]

 73%|███████▎  | 22/30 [02:37<00:59,  7.45s/it]

 77%|███████▋  | 23/30 [02:43<00:50,  7.15s/it]

 80%|████████  | 24/30 [02:50<00:42,  7.01s/it]

 83%|████████▎ | 25/30 [03:00<00:38,  7.74s/it]

 87%|████████▋ | 26/30 [03:07<00:31,  7.75s/it]

 90%|█████████ | 27/30 [03:13<00:21,  7.20s/it]

 93%|█████████▎| 28/30 [03:19<00:13,  6.82s/it]

 97%|█████████▋| 29/30 [03:25<00:06,  6.59s/it]

100%|██████████| 30/30 [03:31<00:00,  6.45s/it]

100%|██████████| 30/30 [03:31<00:00,  7.06s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.81s/it]

100%|██████████| 2/2 [00:02<00:00,  1.39s/it]

100%|██████████| 2/2 [00:02<00:00,  1.45s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7669737089179901

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7566822681301962

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7662383396093522

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7514380645034832

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7380918720965267

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.736327210189946

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.732957158215899

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.731558885601253

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7291495576352658

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7271420411875775

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7669737089179901
BRAS...

seed           5.000000
BAMI           0.766974
CASW           0.800844
SCGRAPHM       0.356768
BRAS           0.792666
KBET           0.686762
CPCR           0.532776
bio_score      0.641529
batch_score    0.670735
joint_score    0.653211
dtype: float64

===== seed 6 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:08<04:20,  8.98s/it]

  7%|▋         | 2/30 [00:15<03:23,  7.28s/it]

 10%|█         | 3/30 [00:25<03:49,  8.52s/it]

 13%|█▎        | 4/30 [00:34<03:48,  8.80s/it]

 17%|█▋        | 5/30 [00:41<03:24,  8.19s/it]

 20%|██        | 6/30 [00:49<03:15,  8.15s/it]

 23%|██▎       | 7/30 [00:59<03:18,  8.64s/it]

 27%|██▋       | 8/30 [01:07<03:07,  8.51s/it]

 30%|███       | 9/30 [01:16<03:05,  8.82s/it]

 33%|███▎      | 10/30 [01:27<03:06,  9.32s/it]

 37%|███▋      | 11/30 [01:35<02:50,  8.98s/it]

 40%|████      | 12/30 [01:42<02:31,  8.43s/it]

 43%|████▎     | 13/30 [01:52<02:32,  8.94s/it]

 47%|████▋     | 14/30 [02:01<02:20,  8.78s/it]

 50%|█████     | 15/30 [02:09<02:07,  8.53s/it]

 53%|█████▎    | 16/30 [02:17<01:58,  8.46s/it]

 57%|█████▋    | 17/30 [02:24<01:45,  8.10s/it]

 60%|██████    | 18/30 [02:33<01:40,  8.36s/it]

 63%|██████▎   | 19/30 [02:42<01:34,  8.58s/it]

 67%|██████▋   | 20/30 [02:50<01:24,  8.46s/it]

 70%|███████   | 21/30 [02:58<01:14,  8.33s/it]

 73%|███████▎  | 22/30 [03:07<01:06,  8.25s/it]

 77%|███████▋  | 23/30 [03:17<01:01,  8.82s/it]

 80%|████████  | 24/30 [03:24<00:50,  8.43s/it]

 83%|████████▎ | 25/30 [03:34<00:44,  8.87s/it]

 87%|████████▋ | 26/30 [03:44<00:37,  9.29s/it]

 90%|█████████ | 27/30 [03:53<00:27,  9.11s/it]

 93%|█████████▎| 28/30 [04:05<00:19,  9.83s/it]

 97%|█████████▋| 29/30 [04:18<00:10, 10.77s/it]

100%|██████████| 30/30 [04:29<00:00, 11.07s/it]

100%|██████████| 30/30 [04:29<00:00,  8.99s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.83s/it]

100%|██████████| 2/2 [00:02<00:00,  1.40s/it]

100%|██████████| 2/2 [00:02<00:00,  1.47s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7514334719772069

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.780726383554347

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7673279161045232

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7582795512505148

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.756439315365888

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7520462529047901

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7491289302551307

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7469208253477906

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7331061710845771

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7337874554655225

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.780726383554347
BRAS...

seed           6.000000
BAMI           0.780726
CASW           0.811975
SCGRAPHM       0.412460
BRAS           0.800622
KBET           0.721172
CPCR           0.397298
bio_score      0.668387
batch_score    0.639697
joint_score    0.656911
dtype: float64

===== seed 7 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:16,  6.79s/it]

  7%|▋         | 2/30 [00:12<02:45,  5.92s/it]

 10%|█         | 3/30 [00:18<02:39,  5.92s/it]

 13%|█▎        | 4/30 [00:25<02:51,  6.58s/it]

 17%|█▋        | 5/30 [00:31<02:41,  6.45s/it]

 20%|██        | 6/30 [00:42<03:12,  8.01s/it]

 23%|██▎       | 7/30 [00:54<03:29,  9.10s/it]

 27%|██▋       | 8/30 [01:07<03:49, 10.42s/it]

 30%|███       | 9/30 [01:17<03:37, 10.37s/it]

 33%|███▎      | 10/30 [01:29<03:35, 10.76s/it]

 37%|███▋      | 11/30 [01:41<03:33, 11.24s/it]

 40%|████      | 12/30 [01:52<03:21, 11.22s/it]

 43%|████▎     | 13/30 [01:59<02:45,  9.75s/it]

 47%|████▋     | 14/30 [02:06<02:22,  8.92s/it]

 50%|█████     | 15/30 [02:19<02:35, 10.35s/it]

 53%|█████▎    | 16/30 [02:30<02:27, 10.57s/it]

 57%|█████▋    | 17/30 [02:42<02:20, 10.83s/it]

 60%|██████    | 18/30 [02:53<02:11, 10.98s/it]

 63%|██████▎   | 19/30 [03:06<02:07, 11.59s/it]

 67%|██████▋   | 20/30 [03:20<02:02, 12.21s/it]

 70%|███████   | 21/30 [03:33<01:51, 12.35s/it]

 73%|███████▎  | 22/30 [03:45<01:39, 12.43s/it]

 77%|███████▋  | 23/30 [03:57<01:26, 12.39s/it]

 80%|████████  | 24/30 [04:09<01:13, 12.21s/it]

 83%|████████▎ | 25/30 [04:17<00:54, 10.81s/it]

 87%|████████▋ | 26/30 [04:24<00:38,  9.70s/it]

 90%|█████████ | 27/30 [04:34<00:29,  9.67s/it]

 93%|█████████▎| 28/30 [04:42<00:18,  9.40s/it]

 97%|█████████▋| 29/30 [04:53<00:09,  9.66s/it]

100%|██████████| 30/30 [05:01<00:00,  9.40s/it]

100%|██████████| 30/30 [05:01<00:00, 10.06s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:02<00:02,  2.18s/it]

100%|██████████| 2/2 [00:03<00:00,  1.70s/it]

100%|██████████| 2/2 [00:03<00:00,  1.77s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.813866540869151

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7961502813179405

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7879319839411936

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7852658065683233

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7477188881366365

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.736913065765012

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7357366815874669

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7244024214208464

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7213797613486994

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7195755706387627

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.813866540869151
BRAS...

seed           7.000000
BAMI           0.813867
CASW           0.795767
SCGRAPHM       0.370584
BRAS           0.835463
KBET           0.661107
CPCR           0.276032
bio_score      0.660073
batch_score    0.590867
joint_score    0.632390
dtype: float64

===== seed 8 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:15<07:16, 15.05s/it]

  7%|▋         | 2/30 [00:26<06:06, 13.09s/it]

 10%|█         | 3/30 [00:39<05:46, 12.82s/it]

 13%|█▎        | 4/30 [00:51<05:25, 12.52s/it]

 17%|█▋        | 5/30 [01:04<05:14, 12.59s/it]

 20%|██        | 6/30 [01:17<05:05, 12.75s/it]

 23%|██▎       | 7/30 [01:29<04:49, 12.57s/it]

 27%|██▋       | 8/30 [01:39<04:21, 11.87s/it]

 30%|███       | 9/30 [01:50<04:04, 11.65s/it]

 33%|███▎      | 10/30 [01:59<03:34, 10.74s/it]

 37%|███▋      | 11/30 [02:06<03:04,  9.72s/it]

 40%|████      | 12/30 [02:15<02:49,  9.41s/it]

 43%|████▎     | 13/30 [02:22<02:26,  8.60s/it]

 47%|████▋     | 14/30 [02:32<02:26,  9.15s/it]

 50%|█████     | 15/30 [02:40<02:09,  8.65s/it]

 53%|█████▎    | 16/30 [02:50<02:07,  9.14s/it]

 57%|█████▋    | 17/30 [03:01<02:04,  9.58s/it]

 60%|██████    | 18/30 [03:13<02:04, 10.41s/it]

 63%|██████▎   | 19/30 [03:25<01:58, 10.78s/it]

 67%|██████▋   | 20/30 [03:37<01:52, 11.24s/it]

 70%|███████   | 21/30 [03:49<01:43, 11.51s/it]

 73%|███████▎  | 22/30 [04:01<01:33, 11.71s/it]

 77%|███████▋  | 23/30 [04:12<01:20, 11.50s/it]

100%|██████████| 30/30 [04:12<00:00,  8.43s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:01<00:01,  1.83s/it]

100%|██████████| 2/2 [00:02<00:00,  1.40s/it]

100%|██████████| 2/2 [00:02<00:00,  1.47s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7687386361734967

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7562604275856186

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.75655204351914

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7504439971618224

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7428657537789348

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7304815105878054

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7295801240633688

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7260705189082435

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7246302410842005

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7163149681915676

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7687386361734967
BRAS...

seed           8.000000
BAMI           0.768739
CASW           0.815509
SCGRAPHM       0.475992
BRAS           0.804225
KBET           0.730703
CPCR           0.070316
bio_score      0.686747
batch_score    0.535081
joint_score    0.626080
dtype: float64

===== seed 9 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:11<05:31, 11.42s/it]

  7%|▋         | 2/30 [00:20<04:39,  9.99s/it]

 10%|█         | 3/30 [00:30<04:31, 10.05s/it]

 13%|█▎        | 4/30 [00:42<04:43, 10.90s/it]

 17%|█▋        | 5/30 [00:52<04:23, 10.54s/it]

 20%|██        | 6/30 [00:59<03:41,  9.21s/it]

 23%|██▎       | 7/30 [01:05<03:09,  8.26s/it]

 27%|██▋       | 8/30 [01:11<02:47,  7.62s/it]

 30%|███       | 9/30 [01:18<02:31,  7.24s/it]

 33%|███▎      | 10/30 [01:24<02:17,  6.90s/it]

 37%|███▋      | 11/30 [01:30<02:05,  6.60s/it]

 40%|████      | 12/30 [01:36<01:54,  6.38s/it]

 43%|████▎     | 13/30 [01:42<01:45,  6.23s/it]

 47%|████▋     | 14/30 [01:49<01:44,  6.56s/it]

 50%|█████     | 15/30 [01:56<01:39,  6.63s/it]

 53%|█████▎    | 16/30 [02:02<01:30,  6.46s/it]

 57%|█████▋    | 17/30 [02:12<01:37,  7.49s/it]

 60%|██████    | 18/30 [02:24<01:48,  9.02s/it]

 63%|██████▎   | 19/30 [02:34<01:43,  9.39s/it]

 67%|██████▋   | 20/30 [02:46<01:39,  9.94s/it]

 70%|███████   | 21/30 [02:55<01:28,  9.84s/it]

 73%|███████▎  | 22/30 [03:04<01:17,  9.63s/it]

 77%|███████▋  | 23/30 [03:14<01:07,  9.66s/it]

 80%|████████  | 24/30 [03:24<00:57,  9.66s/it]

 83%|████████▎ | 25/30 [03:34<00:49,  9.86s/it]

 87%|████████▋ | 26/30 [03:45<00:41, 10.31s/it]

 90%|█████████ | 27/30 [03:52<00:27,  9.21s/it]

 93%|█████████▎| 28/30 [03:58<00:16,  8.25s/it]

 97%|█████████▋| 29/30 [04:04<00:07,  7.58s/it]

100%|██████████| 30/30 [04:21<00:00, 10.51s/it]

100%|██████████| 30/30 [04:21<00:00,  8.73s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:04<00:04,  4.30s/it]

100%|██████████| 2/2 [00:08<00:00,  4.04s/it]

100%|██████████| 2/2 [00:08<00:00,  4.08s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7900628260602996

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7868249634946347

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7831609519154287

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.777094187920536

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7575273960051889

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7556804419585996

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7506414314113354

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7405267990804467

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7377270416498899

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7300064428746489

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7900628260602996
BRAS...

seed           9.000000
BAMI           0.790063
CASW           0.806228
SCGRAPHM       0.387219
BRAS           0.853150
KBET           0.703475
CPCR           0.249315
bio_score      0.661170
batch_score    0.601980
joint_score    0.637494
dtype: float64

===== seed 10 =====

Removing 1023 genes not expressing in FM3.

Removing 246 genes not expressing in MM1.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:12<06:07, 12.66s/it]

  7%|▋         | 2/30 [00:21<04:43, 10.13s/it]

 10%|█         | 3/30 [00:28<04:02,  8.99s/it]

 13%|█▎        | 4/30 [00:37<03:56,  9.11s/it]

 17%|█▋        | 5/30 [00:45<03:34,  8.57s/it]

 20%|██        | 6/30 [00:53<03:19,  8.31s/it]

 23%|██▎       | 7/30 [01:01<03:13,  8.40s/it]

 27%|██▋       | 8/30 [01:13<03:25,  9.32s/it]

 30%|███       | 9/30 [01:24<03:31, 10.05s/it]

 33%|███▎      | 10/30 [01:36<03:28, 10.42s/it]

 37%|███▋      | 11/30 [01:47<03:21, 10.60s/it]

 40%|████      | 12/30 [01:53<02:47,  9.30s/it]

 43%|████▎     | 13/30 [01:59<02:21,  8.34s/it]

 47%|████▋     | 14/30 [02:08<02:13,  8.37s/it]

 50%|█████     | 15/30 [02:21<02:28,  9.90s/it]

 53%|█████▎    | 16/30 [02:34<02:33, 10.98s/it]

 57%|█████▋    | 17/30 [02:50<02:41, 12.45s/it]

 60%|██████    | 18/30 [03:04<02:32, 12.73s/it]

 63%|██████▎   | 19/30 [03:17<02:21, 12.84s/it]

 67%|██████▋   | 20/30 [03:32<02:16, 13.64s/it]

 70%|███████   | 21/30 [03:45<02:00, 13.34s/it]

 73%|███████▎  | 22/30 [03:59<01:47, 13.45s/it]

 77%|███████▋  | 23/30 [04:14<01:37, 13.96s/it]

 80%|████████  | 24/30 [04:29<01:25, 14.18s/it]

 83%|████████▎ | 25/30 [04:44<01:12, 14.50s/it]

 87%|████████▋ | 26/30 [04:59<00:58, 14.63s/it]

 90%|█████████ | 27/30 [05:17<00:47, 15.81s/it]

 93%|█████████▎| 28/30 [05:31<00:30, 15.26s/it]

 97%|█████████▋| 29/30 [05:46<00:15, 15.14s/it]

100%|██████████| 30/30 [06:01<00:00, 15.00s/it]

100%|██████████| 30/30 [06:01<00:00, 12.04s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:02<00:02,  3.00s/it]

100%|██████████| 2/2 [00:04<00:00,  2.27s/it]

100%|██████████| 2/2 [00:04<00:00,  2.38s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7871563666119501

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7672195854222685

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7859584440792118

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7672481096226842

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7601070158833957

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7512668604945603

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7444916168901137

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.732148764840995

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7315641254269334

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7327459620713402

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7871563666119501
BRAS...

seed           10.000000
BAMI            0.787156
CASW            0.785641
SCGRAPHM        0.383329
BRAS            0.875592
KBET            0.697236
CPCR            0.217986
bio_score       0.652042
batch_score     0.596938
joint_score     0.630001
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.792240,0.791940,0.385928,0.871827,0.662997,0.149700,0.656703,0.561508,0.618625
1,2,0.775101,0.763847,0.462604,0.844292,0.689364,0.070653,0.667184,0.534769,0.614218
2,3,0.783473,0.831708,0.424301,0.862478,0.619516,0.475901,0.679827,0.652631,0.668949
3,4,0.818423,0.810065,0.369165,0.846228,0.685910,0.390821,0.665884,0.640986,0.655925
4,5,0.766974,0.800844,0.356768,0.792666,0.686762,0.532776,0.641529,0.670735,0.653211
5,6,0.780726,0.811975,0.412460,0.800622,0.721172,0.397298,0.668387,0.639697,0.656911
6,7,0.813867,0.795767,0.370584,0.835463,0.661107,0.276032,0.660073,0.590867,0.632390
7,8,0.768739,0.815509,0.475992,0.804225,0.730703,0.070316,0.686747,0.535081,0.626080
8,9,0.790063,0.806228,0.387219,0.853150,0.703475,0.249315,0.661170,0.601980,0.637494
9,10,0.787156,0.785641,0.383329,0.875592,0.697236,0.217986,0.652042,0.596938,0.630001

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.787676  0.016338  0.766974  0.818423
CASW         0.801352  0.017629  0.763847  0.831708
SCGRAPHM     0.402835  0.038319  0.356768  0.475992
BRAS         0.838654  0.028440  0.792666  0.875592
KBET         0.685824  0.030410  0.619516  0.730703
CPCR         0.283080  0.154205  0.070316  0.532776
bio_score    0.663955  0.012351  0.641529  0.686747
batch_score  0.602519  0.045841  0.534769  0.670735
joint_score  0.639380  0.017401  0.614218  0.668949