# LIGER best - human_pbmc_sequencing_techs

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'human_pbmc_sequencing_techs'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'Method'
LABEL_KEY = 'CellType'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'human_pbmc_sequencing_techs'
assert BATCH_KEY == 'Method'
assert LABEL_KEY == 'CellType'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                            human_pbmc_sequencing_techs
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                               Method
label_key                                             CellType
metrics      [BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=30975 n_batches=9 n_labels=9
ISOLISI preflight: min_batch_coverage=6 isolated_labels=['Plasmacytoid dendritic cell']
CPCR preflight: eligible_labels=9

In [4]:
OPTUNA_STUDY_NAME = 'liger_human_pbmc_sequencing_techs_joint_expanded_metrics_scgraphm_v1'
OPTUNA_BEST_TRIAL = 66
OPTUNA_BEST_VALUE = 0.7563842962154299
OPTUNA_BEST_PARAMS = {'k': 60, 'value_lambda': 8.399253389874715}

LIGER_BEST_ARGS = {
    "k": OPTUNA_BEST_PARAMS["k"],
    "value_lambda": OPTUNA_BEST_PARAMS["value_lambda"],
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_best(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_BEST_ARGS["k"],
        lam=LIGER_BEST_ARGS["value_lambda"],
        max_iterations=LIGER_BEST_ARGS["max_iters"],
        mode=LIGER_BEST_ARGS["mode"],
        layer=LIGER_BEST_ARGS["layer"],
        seed=seed,
    )


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **LIGER_BEST_ARGS,
    },
    name="best_setting",
)

study           liger_human_pbmc_sequencing_techs_joint_expand...
best_trial                                                     66
best_value                                               0.756384
k                                                              60
value_lambda                                             8.399253
max_iters                                                      30
mode                                                         core
layer                                                      counts
Name: best_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.

Removing 10166 genes not expressing in Drop-seq.
Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:44<21:39, 44.82s/it]

  7%|▋         | 2/30 [01:29<20:56, 44.89s/it]

 10%|█         | 3/30 [02:13<19:54, 44.23s/it]

 13%|█▎        | 4/30 [02:57<19:10, 44.25s/it]

 17%|█▋        | 5/30 [03:39<18:02, 43.30s/it]

 20%|██        | 6/30 [04:21<17:10, 42.94s/it]

 23%|██▎       | 7/30 [05:05<16:33, 43.18s/it]

 27%|██▋       | 8/30 [05:49<15:58, 43.55s/it]

 30%|███       | 9/30 [06:30<14:56, 42.69s/it]

 33%|███▎      | 10/30 [07:11<14:03, 42.17s/it]

 37%|███▋      | 11/30 [07:53<13:23, 42.28s/it]

 40%|████      | 12/30 [08:35<12:39, 42.21s/it]

 43%|████▎     | 13/30 [09:18<11:59, 42.30s/it]

 47%|████▋     | 14/30 [09:57<11:04, 41.51s/it]

 50%|█████     | 15/30 [10:35<10:03, 40.23s/it]

 53%|█████▎    | 16/30 [11:12<09:11, 39.37s/it]

 57%|█████▋    | 17/30 [11:51<08:29, 39.22s/it]

 60%|██████    | 18/30 [12:31<07:53, 39.46s/it]

 63%|██████▎   | 19/30 [13:10<07:12, 39.31s/it]

 67%|██████▋   | 20/30 [13:51<06:39, 39.93s/it]

 70%|███████   | 21/30 [14:35<06:08, 40.94s/it]

 73%|███████▎  | 22/30 [15:14<05:24, 40.53s/it]

 77%|███████▋  | 23/30 [15:53<04:41, 40.14s/it]

 80%|████████  | 24/30 [16:35<04:03, 40.59s/it]

 83%|████████▎ | 25/30 [17:17<03:24, 40.89s/it]

 87%|████████▋ | 26/30 [17:55<02:40, 40.23s/it]

 90%|█████████ | 27/30 [18:36<02:00, 40.26s/it]

 93%|█████████▎| 28/30 [19:17<01:21, 40.56s/it]

 97%|█████████▋| 29/30 [19:57<00:40, 40.31s/it]

100%|██████████| 30/30 [20:34<00:00, 39.48s/it]

100%|██████████| 30/30 [20:34<00:00, 41.16s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 17.65it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.01it/s]

 67%|██████▋   | 6/9 [00:00<00:00, 10.63it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  9.95it/s]

100%|██████████| 9/9 [00:00<00:00, 11.56it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.7080408755663727

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7047497799522087

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6840027668370712

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6779532808764444

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6719233239851212

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6676714474770653

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6624933222734474

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.661349697777766

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.655248122279944

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6487657294063163

WARNING:2026-07-23 18:17:17,301:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7080408755663727
BRAS...

seed           1.000000
BAMI           0.708041
CASW           0.527243
SCGRAPHM       0.800625
ISOLISI        0.987703
BRAS           0.901900
KBET           0.418963
CPCR           0.950457
bio_score      0.755903
batch_score    0.757106
joint_score    0.756384
dtype: float64

===== seed 2 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:43<20:56, 43.31s/it]

  7%|▋         | 2/30 [01:24<19:44, 42.29s/it]

 10%|█         | 3/30 [02:03<18:14, 40.52s/it]

 13%|█▎        | 4/30 [02:55<19:30, 45.02s/it]

 17%|█▋        | 5/30 [03:33<17:43, 42.56s/it]

 20%|██        | 6/30 [04:13<16:38, 41.60s/it]

 23%|██▎       | 7/30 [04:53<15:45, 41.09s/it]

 27%|██▋       | 8/30 [05:32<14:48, 40.40s/it]

 30%|███       | 9/30 [06:11<14:00, 40.00s/it]

 33%|███▎      | 10/30 [06:51<13:20, 40.04s/it]

 37%|███▋      | 11/30 [07:30<12:36, 39.83s/it]

 40%|████      | 12/30 [08:11<12:03, 40.20s/it]

 43%|████▎     | 13/30 [08:51<11:22, 40.16s/it]

 47%|████▋     | 14/30 [09:32<10:42, 40.16s/it]

 50%|█████     | 15/30 [10:13<10:08, 40.58s/it]

 53%|█████▎    | 16/30 [10:52<09:22, 40.16s/it]

 57%|█████▋    | 17/30 [11:36<08:54, 41.10s/it]

 60%|██████    | 18/30 [12:20<08:23, 41.99s/it]

 63%|██████▎   | 19/30 [13:01<07:39, 41.76s/it]

 67%|██████▋   | 20/30 [13:42<06:55, 41.57s/it]

 70%|███████   | 21/30 [14:24<06:15, 41.71s/it]

 73%|███████▎  | 22/30 [15:05<05:32, 41.57s/it]

 77%|███████▋  | 23/30 [15:47<04:51, 41.65s/it]

 80%|████████  | 24/30 [16:28<04:08, 41.43s/it]

 83%|████████▎ | 25/30 [17:06<03:21, 40.34s/it]

 87%|████████▋ | 26/30 [17:45<02:39, 39.94s/it]

 90%|█████████ | 27/30 [18:25<02:00, 40.12s/it]

 93%|█████████▎| 28/30 [19:05<01:19, 39.89s/it]

 97%|█████████▋| 29/30 [19:45<00:40, 40.16s/it]

100%|██████████| 30/30 [20:25<00:00, 40.05s/it]

100%|██████████| 30/30 [20:25<00:00, 40.86s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 17.21it/s]

 44%|████▍     | 4/9 [00:00<00:00, 12.96it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.43it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  7.41it/s]

100%|██████████| 9/9 [00:00<00:00,  9.12it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6600475443825203

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6969790223190026

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6854268336547703

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6702630272613684

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6534734790283027

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6571641752460774

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6594165499874637

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6556584723818791

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6556756270724312

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6498751260630998

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6969790223190026
BRAS...

seed           2.000000
BAMI           0.696979
CASW           0.523673
SCGRAPHM       0.809999
ISOLISI        0.983704
BRAS           0.892451
KBET           0.408122
CPCR           0.922519
bio_score      0.753589
batch_score    0.741031
joint_score    0.748566
dtype: float64

===== seed 3 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:44<21:16, 44.02s/it]

  7%|▋         | 2/30 [01:24<19:33, 41.91s/it]

 10%|█         | 3/30 [01:58<17:16, 38.40s/it]

 13%|█▎        | 4/30 [02:35<16:25, 37.92s/it]

 17%|█▋        | 5/30 [03:17<16:17, 39.09s/it]

 20%|██        | 6/30 [03:56<15:41, 39.24s/it]

 23%|██▎       | 7/30 [04:34<14:55, 38.94s/it]

 27%|██▋       | 8/30 [05:16<14:33, 39.72s/it]

 30%|███       | 9/30 [05:57<14:06, 40.29s/it]

 33%|███▎      | 10/30 [06:37<13:23, 40.16s/it]

 37%|███▋      | 11/30 [07:18<12:46, 40.34s/it]

 40%|████      | 12/30 [07:58<12:03, 40.18s/it]

 43%|████▎     | 13/30 [08:40<11:32, 40.76s/it]

 47%|████▋     | 14/30 [09:22<10:59, 41.20s/it]

 50%|█████     | 15/30 [10:01<10:08, 40.53s/it]

 53%|█████▎    | 16/30 [10:41<09:24, 40.29s/it]

 57%|█████▋    | 17/30 [11:22<08:48, 40.63s/it]

 60%|██████    | 18/30 [12:01<08:01, 40.13s/it]

 63%|██████▎   | 19/30 [12:43<07:26, 40.59s/it]

 67%|██████▋   | 20/30 [13:25<06:51, 41.17s/it]

 70%|███████   | 21/30 [14:05<06:05, 40.64s/it]

 73%|███████▎  | 22/30 [14:46<05:26, 40.82s/it]

 77%|███████▋  | 23/30 [15:28<04:49, 41.31s/it]

 80%|████████  | 24/30 [16:09<04:07, 41.18s/it]

 83%|████████▎ | 25/30 [16:50<03:25, 41.02s/it]

 87%|████████▋ | 26/30 [17:32<02:45, 41.30s/it]

 90%|█████████ | 27/30 [18:13<02:04, 41.34s/it]

 93%|█████████▎| 28/30 [18:54<01:22, 41.16s/it]

 97%|█████████▋| 29/30 [19:36<00:41, 41.30s/it]

100%|██████████| 30/30 [20:14<00:00, 40.26s/it]

100%|██████████| 30/30 [20:14<00:00, 40.47s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 17.66it/s]

 44%|████▍     | 4/9 [00:00<00:00, 12.82it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.52it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  7.27it/s]

100%|██████████| 9/9 [00:01<00:00,  8.96it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6880646822906741

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6892971002235805

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.69409703418434

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6848691020456196

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6725904024828658

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6670608567756615

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6577441218756297

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6558676367704342

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6545415103396898

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6531979208152184

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.69409703418434
BRAS...

seed           3.000000
BAMI           0.694097
CASW           0.520800
SCGRAPHM       0.779184
ISOLISI        0.974436
BRAS           0.889236
KBET           0.422818
CPCR           0.919312
bio_score      0.742129
batch_score    0.743789
joint_score    0.742793
dtype: float64

===== seed 4 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:45<21:45, 45.02s/it]

  7%|▋         | 2/30 [01:30<21:02, 45.09s/it]

 10%|█         | 3/30 [02:14<20:09, 44.80s/it]

 13%|█▎        | 4/30 [03:00<19:37, 45.29s/it]

 17%|█▋        | 5/30 [03:42<18:22, 44.10s/it]

 20%|██        | 6/30 [04:27<17:43, 44.33s/it]

 23%|██▎       | 7/30 [05:09<16:40, 43.51s/it]

 27%|██▋       | 8/30 [05:50<15:38, 42.64s/it]

 30%|███       | 9/30 [06:33<14:58, 42.80s/it]

 33%|███▎      | 10/30 [07:11<13:50, 41.53s/it]

 37%|███▋      | 11/30 [07:50<12:54, 40.78s/it]

 40%|████      | 12/30 [08:29<12:03, 40.18s/it]

 43%|████▎     | 13/30 [09:07<11:08, 39.34s/it]

 47%|████▋     | 14/30 [09:47<10:35, 39.70s/it]

 50%|█████     | 15/30 [10:28<10:00, 40.05s/it]

 53%|█████▎    | 16/30 [11:09<09:23, 40.22s/it]

 57%|█████▋    | 17/30 [11:48<08:39, 39.94s/it]

 60%|██████    | 18/30 [12:27<07:55, 39.61s/it]

 63%|██████▎   | 19/30 [13:09<07:23, 40.28s/it]

 67%|██████▋   | 20/30 [13:48<06:40, 40.04s/it]

 70%|███████   | 21/30 [14:26<05:55, 39.46s/it]

 73%|███████▎  | 22/30 [15:04<05:12, 39.06s/it]

 77%|███████▋  | 23/30 [15:44<04:34, 39.24s/it]

 80%|████████  | 24/30 [16:23<03:54, 39.06s/it]

 83%|████████▎ | 25/30 [17:02<03:16, 39.26s/it]

 87%|████████▋ | 26/30 [17:42<02:36, 39.24s/it]

 90%|█████████ | 27/30 [18:23<01:59, 39.84s/it]

 93%|█████████▎| 28/30 [19:04<01:20, 40.23s/it]

 97%|█████████▋| 29/30 [19:45<00:40, 40.56s/it]

100%|██████████| 30/30 [20:27<00:00, 40.81s/it]

100%|██████████| 30/30 [20:27<00:00, 40.91s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 17.79it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.10it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.61it/s]

 78%|███████▊  | 7/9 [00:00<00:00,  6.08it/s]

100%|██████████| 9/9 [00:01<00:00,  8.12it/s]

100%|██████████| 9/9 [00:01<00:00,  8.31it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7144446336957468

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7093557623175984

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7153570760791514

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6975866053293261

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6957347661301055

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.690369517769236

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6774477077789344

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6742252452157262

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.661986933149474

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6524269937426226

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7153570760791514
BRAS...

seed           4.000000
BAMI           0.715357
CASW           0.517274
SCGRAPHM       0.801480
ISOLISI        0.984642
BRAS           0.864391
KBET           0.411038
CPCR           0.883178
bio_score      0.754688
batch_score    0.719536
joint_score    0.740627
dtype: float64

===== seed 5 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:45<22:12, 45.95s/it]

  7%|▋         | 2/30 [01:31<21:24, 45.88s/it]

 10%|█         | 3/30 [02:14<20:05, 44.65s/it]

 13%|█▎        | 4/30 [02:54<18:29, 42.68s/it]

 17%|█▋        | 5/30 [03:34<17:23, 41.75s/it]

 20%|██        | 6/30 [04:16<16:45, 41.90s/it]

 23%|██▎       | 7/30 [04:58<15:59, 41.72s/it]

 27%|██▋       | 8/30 [05:38<15:08, 41.28s/it]

 30%|███       | 9/30 [06:17<14:10, 40.52s/it]

 33%|███▎      | 10/30 [06:56<13:19, 39.97s/it]

 37%|███▋      | 11/30 [07:39<12:58, 40.97s/it]

 40%|████      | 12/30 [08:20<12:19, 41.08s/it]

 43%|████▎     | 13/30 [09:00<11:30, 40.63s/it]

 47%|████▋     | 14/30 [09:42<10:56, 41.03s/it]

 50%|█████     | 15/30 [10:22<10:09, 40.66s/it]

 53%|█████▎    | 16/30 [11:01<09:24, 40.35s/it]

 57%|█████▋    | 17/30 [11:43<08:48, 40.67s/it]

 60%|██████    | 18/30 [12:22<08:04, 40.36s/it]

 63%|██████▎   | 19/30 [13:03<07:26, 40.59s/it]

 67%|██████▋   | 20/30 [13:43<06:41, 40.19s/it]

 70%|███████   | 21/30 [14:20<05:52, 39.21s/it]

 73%|███████▎  | 22/30 [14:58<05:11, 38.96s/it]

 77%|███████▋  | 23/30 [15:36<04:30, 38.64s/it]

 80%|████████  | 24/30 [16:12<03:47, 37.87s/it]

 83%|████████▎ | 25/30 [16:51<03:11, 38.31s/it]

 87%|████████▋ | 26/30 [17:29<02:32, 38.25s/it]

 90%|█████████ | 27/30 [18:07<01:54, 38.09s/it]

 93%|█████████▎| 28/30 [18:46<01:16, 38.34s/it]

 97%|█████████▋| 29/30 [19:24<00:38, 38.11s/it]

100%|██████████| 30/30 [20:03<00:00, 38.45s/it]

100%|██████████| 30/30 [20:03<00:00, 40.11s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 18.00it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.03it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.12it/s]

 89%|████████▉ | 8/9 [00:01<00:00,  6.90it/s]

100%|██████████| 9/9 [00:01<00:00,  8.62it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7150271858786545

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7071595303910131

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7019749154251875

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6900266871565686

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.689139965700956

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6774044075374258

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6802310028932116

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.662789494708242

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6631851150032209

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6622153645116113

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7150271858786545
BRAS...

seed           5.000000
BAMI           0.715027
CASW           0.532131
SCGRAPHM       0.789437
ISOLISI        0.984329
BRAS           0.873244
KBET           0.481107
CPCR           0.946424
bio_score      0.755231
batch_score    0.766925
joint_score    0.759909
dtype: float64

===== seed 6 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:43<21:05, 43.63s/it]

  7%|▋         | 2/30 [01:28<20:35, 44.14s/it]

 10%|█         | 3/30 [02:08<19:11, 42.65s/it]

 13%|█▎        | 4/30 [02:51<18:24, 42.47s/it]

 17%|█▋        | 5/30 [03:30<17:17, 41.50s/it]

 20%|██        | 6/30 [04:13<16:45, 41.92s/it]

 23%|██▎       | 7/30 [04:56<16:09, 42.15s/it]

 27%|██▋       | 8/30 [05:38<15:26, 42.11s/it]

 30%|███       | 9/30 [06:19<14:37, 41.80s/it]

 33%|███▎      | 10/30 [06:59<13:45, 41.29s/it]

 37%|███▋      | 11/30 [07:39<12:59, 41.00s/it]

 40%|████      | 12/30 [08:24<12:36, 42.00s/it]

 43%|████▎     | 13/30 [09:08<12:04, 42.60s/it]

 47%|████▋     | 14/30 [09:46<11:02, 41.40s/it]

 50%|█████     | 15/30 [10:30<10:30, 42.00s/it]

 53%|█████▎    | 16/30 [11:11<09:43, 41.67s/it]

 57%|█████▋    | 17/30 [11:49<08:49, 40.75s/it]

 60%|██████    | 18/30 [12:30<08:08, 40.73s/it]

 63%|██████▎   | 19/30 [13:13<07:34, 41.34s/it]

 67%|██████▋   | 20/30 [13:53<06:49, 40.98s/it]

 70%|███████   | 21/30 [14:33<06:06, 40.67s/it]

 73%|███████▎  | 22/30 [15:14<05:27, 40.96s/it]

 77%|███████▋  | 23/30 [15:55<04:46, 40.98s/it]

 80%|████████  | 24/30 [16:37<04:06, 41.11s/it]

 83%|████████▎ | 25/30 [17:16<03:22, 40.49s/it]

 87%|████████▋ | 26/30 [17:57<02:42, 40.62s/it]

 90%|█████████ | 27/30 [18:38<02:02, 40.72s/it]

 93%|█████████▎| 28/30 [19:16<01:19, 39.97s/it]

 97%|█████████▋| 29/30 [19:55<00:39, 39.63s/it]

100%|██████████| 30/30 [20:36<00:00, 40.03s/it]

100%|██████████| 30/30 [20:36<00:00, 41.21s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 18.52it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.28it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.97it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  7.19it/s]

100%|██████████| 9/9 [00:01<00:00,  8.89it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7055603729408197

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6950298576371992

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6957485917325698

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6913903012242215

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6920926001396887

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6859887345895634

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6853859591678717

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6717081088430654

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6625293701729381

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6586077821365512

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7055603729408197
BRAS...

seed           6.000000
BAMI           0.705560
CASW           0.531478
SCGRAPHM       0.792994
ISOLISI        0.979937
BRAS           0.885354
KBET           0.429890
CPCR           0.908583
bio_score      0.752492
batch_score    0.741275
joint_score    0.748006
dtype: float64

===== seed 7 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:42<20:44, 42.90s/it]

  7%|▋         | 2/30 [01:25<19:57, 42.75s/it]

 10%|█         | 3/30 [02:07<19:04, 42.37s/it]

 13%|█▎        | 4/30 [02:47<18:02, 41.63s/it]

 17%|█▋        | 5/30 [03:30<17:31, 42.06s/it]

 20%|██        | 6/30 [04:11<16:38, 41.62s/it]

 23%|██▎       | 7/30 [04:51<15:47, 41.20s/it]

 27%|██▋       | 8/30 [05:33<15:07, 41.23s/it]

 30%|███       | 9/30 [06:14<14:29, 41.39s/it]

 33%|███▎      | 10/30 [06:56<13:47, 41.39s/it]

 37%|███▋      | 11/30 [07:37<13:04, 41.31s/it]

 40%|████      | 12/30 [08:22<12:44, 42.45s/it]

 43%|████▎     | 13/30 [09:03<11:51, 41.86s/it]

 47%|████▋     | 14/30 [09:43<11:01, 41.35s/it]

 50%|█████     | 15/30 [10:25<10:24, 41.63s/it]

 53%|█████▎    | 16/30 [11:06<09:40, 41.46s/it]

 57%|█████▋    | 17/30 [11:47<08:58, 41.46s/it]

 60%|██████    | 18/30 [12:29<08:16, 41.35s/it]

 63%|██████▎   | 19/30 [13:10<07:35, 41.37s/it]

 67%|██████▋   | 20/30 [13:51<06:51, 41.18s/it]

 70%|███████   | 21/30 [14:31<06:08, 40.95s/it]

 73%|███████▎  | 22/30 [15:11<05:25, 40.70s/it]

 77%|███████▋  | 23/30 [15:53<04:46, 40.95s/it]

 80%|████████  | 24/30 [16:33<04:04, 40.70s/it]

 83%|████████▎ | 25/30 [17:19<03:31, 42.25s/it]

 87%|████████▋ | 26/30 [17:58<02:45, 41.46s/it]

 90%|█████████ | 27/30 [18:52<02:15, 45.00s/it]

 93%|█████████▎| 28/30 [19:34<01:28, 44.10s/it]

 97%|█████████▋| 29/30 [20:15<00:43, 43.25s/it]

100%|██████████| 30/30 [21:14<00:00, 47.89s/it]

100%|██████████| 30/30 [21:14<00:00, 42.47s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 18.28it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.17it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.00it/s]

 89%|████████▉ | 8/9 [00:01<00:00,  6.73it/s]

100%|██████████| 9/9 [00:01<00:00,  8.48it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6724083152303528

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6883467618130439

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6833883850777912

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6693928969519001

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6686471470483146

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6689858489333304

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6619704775031049

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6634012274074133

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6486758434911758

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.648621326331761

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6883467618130439
BRAS...

seed           7.000000
BAMI           0.688347
CASW           0.515198
SCGRAPHM       0.783076
ISOLISI        0.973838
BRAS           0.891100
KBET           0.412342
CPCR           0.904499
bio_score      0.740115
batch_score    0.735980
joint_score    0.738461
dtype: float64

===== seed 8 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:41<20:10, 41.73s/it]

  7%|▋         | 2/30 [01:22<19:13, 41.18s/it]

 10%|█         | 3/30 [01:59<17:45, 39.46s/it]

 13%|█▎        | 4/30 [02:37<16:45, 38.66s/it]

 17%|█▋        | 5/30 [03:15<16:00, 38.43s/it]

 20%|██        | 6/30 [03:53<15:20, 38.33s/it]

 23%|██▎       | 7/30 [04:31<14:40, 38.30s/it]

 27%|██▋       | 8/30 [05:10<14:03, 38.32s/it]

 30%|███       | 9/30 [05:47<13:17, 37.97s/it]

 33%|███▎      | 10/30 [06:23<12:27, 37.37s/it]

 37%|███▋      | 11/30 [07:01<11:51, 37.46s/it]

 40%|████      | 12/30 [07:38<11:11, 37.32s/it]

 43%|████▎     | 13/30 [08:15<10:37, 37.47s/it]

 47%|████▋     | 14/30 [08:53<10:00, 37.54s/it]

 50%|█████     | 15/30 [09:31<09:22, 37.52s/it]

 53%|█████▎    | 16/30 [10:08<08:44, 37.49s/it]

 57%|█████▋    | 17/30 [10:46<08:10, 37.71s/it]

 60%|██████    | 18/30 [11:24<07:32, 37.73s/it]

 63%|██████▎   | 19/30 [12:00<06:50, 37.30s/it]

 67%|██████▋   | 20/30 [12:36<06:07, 36.76s/it]

 70%|███████   | 21/30 [13:13<05:33, 37.05s/it]

 73%|███████▎  | 22/30 [13:52<05:00, 37.52s/it]

 77%|███████▋  | 23/30 [14:29<04:20, 37.22s/it]

 80%|████████  | 24/30 [15:05<03:42, 37.02s/it]

 83%|████████▎ | 25/30 [15:42<03:04, 36.99s/it]

 87%|████████▋ | 26/30 [16:18<02:26, 36.59s/it]

 90%|█████████ | 27/30 [16:54<01:49, 36.45s/it]

 93%|█████████▎| 28/30 [17:31<01:13, 36.70s/it]

 97%|█████████▋| 29/30 [18:08<00:36, 36.77s/it]

100%|██████████| 30/30 [18:45<00:00, 36.90s/it]

100%|██████████| 30/30 [18:45<00:00, 37.53s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 18.50it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.31it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.00it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  7.31it/s]

100%|██████████| 9/9 [00:01<00:00,  9.00it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6915561239067362

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7103776144109638

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7027403105996951

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6918139686154821

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6843019408130666

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6770690106668203

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6756140423818647

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6726671415987407

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6650068706598652

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6568921924080229

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7103776144109638
BRAS...

seed           8.000000
BAMI           0.710378
CASW           0.513810
SCGRAPHM       0.790494
ISOLISI        0.980232
BRAS           0.858887
KBET           0.384007
CPCR           0.906365
bio_score      0.748728
batch_score    0.716419
joint_score    0.735805
dtype: float64

===== seed 9 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:47<23:03, 47.70s/it]

  7%|▋         | 2/30 [01:30<21:01, 45.05s/it]

 10%|█         | 3/30 [02:13<19:52, 44.16s/it]

 13%|█▎        | 4/30 [02:55<18:37, 42.97s/it]

 17%|█▋        | 5/30 [03:34<17:25, 41.83s/it]

 20%|██        | 6/30 [04:14<16:23, 40.97s/it]

 23%|██▎       | 7/30 [04:52<15:22, 40.10s/it]

 27%|██▋       | 8/30 [05:31<14:37, 39.87s/it]

 30%|███       | 9/30 [06:09<13:43, 39.24s/it]

 33%|███▎      | 10/30 [07:03<14:31, 43.56s/it]

 37%|███▋      | 11/30 [07:40<13:14, 41.81s/it]

 40%|████      | 12/30 [08:19<12:14, 40.80s/it]

 43%|████▎     | 13/30 [08:58<11:23, 40.20s/it]

 47%|████▋     | 14/30 [09:33<10:19, 38.71s/it]

 50%|█████     | 15/30 [10:08<09:24, 37.61s/it]

 53%|█████▎    | 16/30 [10:46<08:47, 37.65s/it]

 57%|█████▋    | 17/30 [11:23<08:07, 37.50s/it]

 60%|██████    | 18/30 [12:01<07:33, 37.80s/it]

 63%|██████▎   | 19/30 [12:43<07:06, 38.79s/it]

 67%|██████▋   | 20/30 [13:16<06:12, 37.26s/it]

 70%|███████   | 21/30 [13:52<05:31, 36.85s/it]

 73%|███████▎  | 22/30 [14:45<05:33, 41.65s/it]

 77%|███████▋  | 23/30 [15:21<04:40, 40.07s/it]

 80%|████████  | 24/30 [16:01<03:58, 39.81s/it]

 83%|████████▎ | 25/30 [16:38<03:15, 39.15s/it]

 87%|████████▋ | 26/30 [17:18<02:37, 39.27s/it]

 90%|█████████ | 27/30 [17:54<01:55, 38.47s/it]

 93%|█████████▎| 28/30 [18:32<01:16, 38.31s/it]

 97%|█████████▋| 29/30 [19:09<00:37, 37.94s/it]

100%|██████████| 30/30 [19:48<00:00, 38.29s/it]

100%|██████████| 30/30 [19:48<00:00, 39.63s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 17.53it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.15it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.54it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  7.45it/s]

100%|██████████| 9/9 [00:00<00:00,  9.17it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6670497543632314

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.699225245922369

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6917408372592135

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6860313281199332

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6705050775259653

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6592555917894157

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6542834390206522

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6493541757736737

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.642585637142305

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6422987132479593

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.699225245922369
BRAS...

seed           9.000000
BAMI           0.699225
CASW           0.530055
SCGRAPHM       0.800015
ISOLISI        0.981828
BRAS           0.887702
KBET           0.442990
CPCR           0.902704
bio_score      0.752781
batch_score    0.744466
joint_score    0.749455
dtype: float64

===== seed 10 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=60 value_lambda=8.399253389874715 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:41<20:15, 41.91s/it]

  7%|▋         | 2/30 [01:24<19:37, 42.05s/it]

 10%|█         | 3/30 [02:02<18:11, 40.41s/it]

 13%|█▎        | 4/30 [02:40<17:08, 39.54s/it]

 17%|█▋        | 5/30 [03:20<16:30, 39.63s/it]

 20%|██        | 6/30 [03:59<15:46, 39.44s/it]

 23%|██▎       | 7/30 [04:38<15:02, 39.22s/it]

 27%|██▋       | 8/30 [05:16<14:11, 38.72s/it]

 30%|███       | 9/30 [05:52<13:18, 38.02s/it]

 33%|███▎      | 10/30 [06:31<12:43, 38.20s/it]

 37%|███▋      | 11/30 [07:08<12:02, 38.04s/it]

 40%|████      | 12/30 [07:46<11:23, 37.99s/it]

 43%|████▎     | 13/30 [08:25<10:49, 38.19s/it]

 47%|████▋     | 14/30 [09:03<10:09, 38.11s/it]

 50%|█████     | 15/30 [09:40<09:27, 37.80s/it]

 53%|█████▎    | 16/30 [10:17<08:46, 37.64s/it]

 57%|█████▋    | 17/30 [10:56<08:14, 38.00s/it]

 60%|██████    | 18/30 [11:32<07:30, 37.52s/it]

 63%|██████▎   | 19/30 [12:11<06:55, 37.81s/it]

 67%|██████▋   | 20/30 [12:50<06:23, 38.36s/it]

 70%|███████   | 21/30 [13:28<05:43, 38.14s/it]

 73%|███████▎  | 22/30 [14:05<05:03, 37.92s/it]

 77%|███████▋  | 23/30 [14:43<04:23, 37.71s/it]

 80%|████████  | 24/30 [15:20<03:45, 37.63s/it]

 83%|████████▎ | 25/30 [15:58<03:09, 37.84s/it]

 87%|████████▋ | 26/30 [16:34<02:28, 37.11s/it]

 90%|█████████ | 27/30 [17:10<01:50, 36.86s/it]

 93%|█████████▎| 28/30 [17:49<01:14, 37.38s/it]

 97%|█████████▋| 29/30 [18:30<00:38, 38.49s/it]

100%|██████████| 30/30 [19:09<00:00, 38.83s/it]

100%|██████████| 30/30 [19:09<00:00, 38.33s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 18.39it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.33it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.83it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  7.16it/s]

100%|██████████| 9/9 [00:01<00:00,  8.85it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.665167547127887

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6896878270749035

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6751025336376122

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6812806409256503

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6745905760033982

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6629756883796456

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6599196158076097

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6529344218056637

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6532303684025467

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6466917136738822

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6896878270749035
BRAS...

seed           10.000000
BAMI            0.689688
CASW            0.518763
SCGRAPHM        0.809080
ISOLISI         0.976491
BRAS            0.866047
KBET            0.396425
CPCR            0.913967
bio_score       0.748506
batch_score     0.725480
joint_score     0.739295
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,ISOLISI,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.708041,0.527243,0.800625,0.987703,0.901900,0.418963,0.950457,0.755903,0.757106,0.756384
1,2,0.696979,0.523673,0.809999,0.983704,0.892451,0.408122,0.922519,0.753589,0.741031,0.748566
2,3,0.694097,0.520800,0.779184,0.974436,0.889236,0.422818,0.919312,0.742129,0.743789,0.742793
3,4,0.715357,0.517274,0.801480,0.984642,0.864391,0.411038,0.883178,0.754688,0.719536,0.740627
4,5,0.715027,0.532131,0.789437,0.984329,0.873244,0.481107,0.946424,0.755231,0.766925,0.759909
5,6,0.705560,0.531478,0.792994,0.979937,0.885354,0.429890,0.908583,0.752492,0.741275,0.748006
6,7,0.688347,0.515198,0.783076,0.973838,0.891100,0.412342,0.904499,0.740115,0.735980,0.738461
7,8,0.710378,0.513810,0.790494,0.980232,0.858887,0.384007,0.906365,0.748728,0.716419,0.735805
8,9,0.699225,0.530055,0.800015,0.981828,0.887702,0.442990,0.902704,0.752781,0.744466,0.749455
9,10,0.689688,0.518763,0.809080,0.976491,0.866047,0.396425,0.913967,0.748506,0.725480,0.739295

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.702270  0.009487  0.688347  0.715357
CASW         0.523043  0.006514  0.513810  0.532131
SCGRAPHM     0.795638  0.009826  0.779184  0.809999
ISOLISI      0.980714  0.004392  0.973838  0.987703
BRAS         0.881031  0.013602  0.858887  0.901900
KBET         0.420770  0.025485  0.384007  0.481107
CPCR         0.915801  0.019246  0.883178  0.950457
bio_score    0.750416  0.005223  0.740115  0.755903
batch_score  0.739201  0.015000  0.716419  0.766925
joint_score  0.745930  0.007541  0.735805  0.759909