# LIGER default - human_pbmc_sequencing_techs

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'human_pbmc_sequencing_techs'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'Method'
LABEL_KEY = 'CellType'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'human_pbmc_sequencing_techs'
assert BATCH_KEY == 'Method'
assert LABEL_KEY == 'CellType'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                            human_pbmc_sequencing_techs
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                               Method
label_key                                             CellType
metrics      [BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=30975 n_batches=9 n_labels=9
ISOLISI preflight: min_batch_coverage=6 isolated_labels=['Plasmacytoid dendritic cell']
CPCR preflight: eligible_labels=9

In [4]:
LIGER_DEFAULT_ARGS = {
    "k": 20,
    "value_lambda": 5.0,
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_default(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_DEFAULT_ARGS["k"],
        lam=LIGER_DEFAULT_ARGS["value_lambda"],
        max_iterations=LIGER_DEFAULT_ARGS["max_iters"],
        mode=LIGER_DEFAULT_ARGS["mode"],
        layer=LIGER_DEFAULT_ARGS["layer"],
        seed=seed,
    )


pd.Series(LIGER_DEFAULT_ARGS, name="default_setting")

k                   20
value_lambda       5.0
max_iters           30
mode              core
layer           counts
Name: default_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_default(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.

Removing 10166 genes not expressing in Drop-seq.
Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:20<10:01, 20.74s/it]

  7%|▋         | 2/30 [00:41<09:43, 20.83s/it]

 10%|█         | 3/30 [01:02<09:25, 20.94s/it]

 13%|█▎        | 4/30 [01:23<09:02, 20.85s/it]

 17%|█▋        | 5/30 [01:42<08:27, 20.28s/it]

 20%|██        | 6/30 [02:02<08:00, 20.02s/it]

 23%|██▎       | 7/30 [02:21<07:36, 19.85s/it]

 27%|██▋       | 8/30 [02:42<07:23, 20.14s/it]

 30%|███       | 9/30 [03:02<07:01, 20.09s/it]

 33%|███▎      | 10/30 [03:22<06:39, 19.95s/it]

 37%|███▋      | 11/30 [03:41<06:17, 19.88s/it]

 40%|████      | 12/30 [04:01<05:55, 19.74s/it]

 43%|████▎     | 13/30 [04:21<05:38, 19.92s/it]

 47%|████▋     | 14/30 [04:42<05:23, 20.24s/it]

 50%|█████     | 15/30 [05:01<04:59, 19.95s/it]

 53%|█████▎    | 16/30 [05:21<04:37, 19.85s/it]

 57%|█████▋    | 17/30 [05:42<04:22, 20.15s/it]

 60%|██████    | 18/30 [06:02<04:02, 20.22s/it]

 63%|██████▎   | 19/30 [06:24<03:46, 20.62s/it]

 67%|██████▋   | 20/30 [06:45<03:27, 20.76s/it]

 70%|███████   | 21/30 [07:05<03:06, 20.67s/it]

 73%|███████▎  | 22/30 [07:24<02:41, 20.18s/it]

 77%|███████▋  | 23/30 [07:44<02:20, 20.06s/it]

 80%|████████  | 24/30 [08:13<02:15, 22.65s/it]

 83%|████████▎ | 25/30 [08:35<01:53, 22.67s/it]

 87%|████████▋ | 26/30 [08:55<01:27, 21.86s/it]

 90%|█████████ | 27/30 [09:15<01:03, 21.14s/it]

 93%|█████████▎| 28/30 [09:34<00:41, 20.52s/it]

 97%|█████████▋| 29/30 [09:53<00:20, 20.02s/it]

100%|██████████| 30/30 [10:11<00:00, 19.56s/it]

100%|██████████| 30/30 [10:11<00:00, 20.40s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 17.31it/s]

 44%|████▍     | 4/9 [00:00<00:00, 12.40it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  9.74it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  9.02it/s]

100%|██████████| 9/9 [00:00<00:00, 10.61it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.721416486318263

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7102826075335407

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6777754322868786

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6661465818206783

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6575614071939767

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6449539464763467

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6414422568818149

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6345034666443475

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6319830037448588

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6276502689743265

WARNING:2026-07-23 17:09:34,086:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.721416486318263
BRAS...

seed           1.000000
BAMI           0.721416
CASW           0.557856
SCGRAPHM       0.799157
ISOLISI        0.979438
BRAS           0.803629
KBET           0.314853
CPCR           0.784247
bio_score      0.764467
batch_score    0.634243
joint_score    0.712377
dtype: float64

===== seed 2 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:19<09:28, 19.61s/it]

  7%|▋         | 2/30 [00:40<09:30, 20.39s/it]

 10%|█         | 3/30 [00:59<08:54, 19.81s/it]

 13%|█▎        | 4/30 [01:18<08:27, 19.51s/it]

 17%|█▋        | 5/30 [01:38<08:06, 19.48s/it]

 20%|██        | 6/30 [01:56<07:38, 19.11s/it]

 23%|██▎       | 7/30 [02:15<07:17, 19.04s/it]

 27%|██▋       | 8/30 [02:34<07:01, 19.18s/it]

 30%|███       | 9/30 [02:53<06:38, 19.00s/it]

 33%|███▎      | 10/30 [03:12<06:17, 18.88s/it]

 37%|███▋      | 11/30 [03:30<05:56, 18.78s/it]

 40%|████      | 12/30 [03:49<05:38, 18.78s/it]

 43%|████▎     | 13/30 [04:07<05:18, 18.71s/it]

 47%|████▋     | 14/30 [04:26<05:00, 18.77s/it]

 50%|█████     | 15/30 [04:46<04:43, 18.87s/it]

 53%|█████▎    | 16/30 [05:05<04:24, 18.92s/it]

 57%|█████▋    | 17/30 [05:23<04:05, 18.86s/it]

 60%|██████    | 18/30 [05:42<03:47, 18.92s/it]

 63%|██████▎   | 19/30 [06:02<03:29, 19.04s/it]

 67%|██████▋   | 20/30 [06:21<03:10, 19.07s/it]

 70%|███████   | 21/30 [06:40<02:50, 18.99s/it]

 73%|███████▎  | 22/30 [06:59<02:32, 19.02s/it]

 77%|███████▋  | 23/30 [07:18<02:14, 19.16s/it]

 80%|████████  | 24/30 [07:38<01:55, 19.24s/it]

 83%|████████▎ | 25/30 [08:11<01:57, 23.47s/it]

 87%|████████▋ | 26/30 [08:31<01:29, 22.35s/it]

 90%|█████████ | 27/30 [08:51<01:04, 21.63s/it]

 93%|█████████▎| 28/30 [09:10<00:42, 21.05s/it]

 97%|█████████▋| 29/30 [09:32<00:21, 21.11s/it]

100%|██████████| 30/30 [09:54<00:00, 21.49s/it]

100%|██████████| 30/30 [09:54<00:00, 19.81s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 14.53it/s]

 44%|████▍     | 4/9 [00:00<00:00, 11.54it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.67it/s]

 78%|███████▊  | 7/9 [00:00<00:00,  6.18it/s]

 89%|████████▉ | 8/9 [00:01<00:00,  6.56it/s]

100%|██████████| 9/9 [00:01<00:00,  8.05it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7172609840918984

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.705480671955474

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7057264630953861

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6920113697695002

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6833918613572345

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6714742676835108

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6512695278788575

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6475496228146849

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6446496091276906

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6396297936245733

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7172609840918984
BRAS...

seed           2.000000
BAMI           0.717261
CASW           0.575699
SCGRAPHM       0.787987
ISOLISI        0.974873
BRAS           0.804782
KBET           0.316989
CPCR           0.836208
bio_score      0.763955
batch_score    0.652660
joint_score    0.719437
dtype: float64

===== seed 3 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:21<10:32, 21.80s/it]

  7%|▋         | 2/30 [00:43<10:11, 21.84s/it]

 10%|█         | 3/30 [01:03<09:26, 20.98s/it]

 13%|█▎        | 4/30 [01:23<08:57, 20.67s/it]

 17%|█▋        | 5/30 [01:43<08:26, 20.27s/it]

 20%|██        | 6/30 [02:07<08:35, 21.48s/it]

 23%|██▎       | 7/30 [02:26<07:59, 20.84s/it]

 27%|██▋       | 8/30 [02:46<07:28, 20.41s/it]

 30%|███       | 9/30 [03:06<07:06, 20.32s/it]

 33%|███▎      | 10/30 [03:26<06:44, 20.21s/it]

 37%|███▋      | 11/30 [03:46<06:21, 20.10s/it]

 40%|████      | 12/30 [04:05<05:57, 19.84s/it]

 43%|████▎     | 13/30 [04:25<05:36, 19.82s/it]

 47%|████▋     | 14/30 [04:45<05:18, 19.89s/it]

 50%|█████     | 15/30 [05:05<04:59, 19.97s/it]

 53%|█████▎    | 16/30 [05:26<04:44, 20.34s/it]

 57%|█████▋    | 17/30 [05:45<04:20, 20.05s/it]

 60%|██████    | 18/30 [06:08<04:08, 20.69s/it]

 63%|██████▎   | 19/30 [06:29<03:49, 20.89s/it]

 67%|██████▋   | 20/30 [06:49<03:24, 20.48s/it]

 70%|███████   | 21/30 [07:10<03:06, 20.73s/it]

 73%|███████▎  | 22/30 [07:31<02:45, 20.74s/it]

 77%|███████▋  | 23/30 [07:52<02:26, 20.96s/it]

 80%|████████  | 24/30 [08:14<02:06, 21.10s/it]

 83%|████████▎ | 25/30 [08:34<01:44, 20.84s/it]

 87%|████████▋ | 26/30 [08:54<01:23, 20.77s/it]

 90%|█████████ | 27/30 [09:15<01:02, 20.85s/it]

 93%|█████████▎| 28/30 [09:35<00:41, 20.60s/it]

 97%|█████████▋| 29/30 [09:56<00:20, 20.53s/it]

100%|██████████| 30/30 [10:16<00:00, 20.30s/it]

100%|██████████| 30/30 [10:16<00:00, 20.53s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 16.72it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.12it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.45it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  7.32it/s]

100%|██████████| 9/9 [00:00<00:00,  9.01it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7120817614631489

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7065996214943774

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6888148269730711

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6662883914874888

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6547461334995994

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6508110543657536

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6451313204750438

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6424950512805845

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6396083826271435

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6338213157387713

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7120817614631489
BRAS...

seed           3.000000
BAMI           0.712082
CASW           0.580418
SCGRAPHM       0.812956
ISOLISI        0.964998
BRAS           0.833160
KBET           0.307773
CPCR           0.898785
bio_score      0.767614
batch_score    0.679906
joint_score    0.732530
dtype: float64

===== seed 4 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:20<09:59, 20.68s/it]

  7%|▋         | 2/30 [00:41<09:43, 20.85s/it]

 10%|█         | 3/30 [01:01<09:08, 20.30s/it]

 13%|█▎        | 4/30 [01:24<09:18, 21.46s/it]

 17%|█▋        | 5/30 [01:46<08:56, 21.47s/it]

 20%|██        | 6/30 [02:07<08:35, 21.49s/it]

 23%|██▎       | 7/30 [02:28<08:10, 21.33s/it]

 27%|██▋       | 8/30 [02:48<07:37, 20.79s/it]

 30%|███       | 9/30 [03:08<07:12, 20.58s/it]

 33%|███▎      | 10/30 [03:27<06:45, 20.26s/it]

 37%|███▋      | 11/30 [03:47<06:23, 20.17s/it]

 40%|████      | 12/30 [04:08<06:03, 20.21s/it]

 43%|████▎     | 13/30 [04:27<05:41, 20.10s/it]

 47%|████▋     | 14/30 [04:47<05:18, 19.92s/it]

 50%|█████     | 15/30 [05:08<05:04, 20.33s/it]

 53%|█████▎    | 16/30 [05:29<04:44, 20.33s/it]

 57%|█████▋    | 17/30 [05:49<04:24, 20.36s/it]

 60%|██████    | 18/30 [06:09<04:01, 20.12s/it]

 63%|██████▎   | 19/30 [06:29<03:41, 20.11s/it]

 67%|██████▋   | 20/30 [06:51<03:27, 20.73s/it]

 70%|███████   | 21/30 [07:11<03:04, 20.45s/it]

 73%|███████▎  | 22/30 [07:31<02:42, 20.37s/it]

 77%|███████▋  | 23/30 [07:50<02:20, 20.12s/it]

 80%|████████  | 24/30 [08:09<01:58, 19.80s/it]

 83%|████████▎ | 25/30 [08:28<01:37, 19.45s/it]

 87%|████████▋ | 26/30 [08:47<01:17, 19.33s/it]

 90%|█████████ | 27/30 [09:05<00:56, 18.94s/it]

 93%|█████████▎| 28/30 [09:24<00:37, 18.95s/it]

 97%|█████████▋| 29/30 [09:43<00:18, 18.81s/it]

100%|██████████| 30/30 [10:01<00:00, 18.68s/it]

100%|██████████| 30/30 [10:01<00:00, 20.05s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 17.72it/s]

 44%|████▍     | 4/9 [00:00<00:00, 12.69it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.20it/s]

 78%|███████▊  | 7/9 [00:00<00:00,  6.40it/s]

100%|██████████| 9/9 [00:01<00:00,  8.47it/s]

100%|██████████| 9/9 [00:01<00:00,  8.67it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7406292149054763

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7194394504325194

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7102067882186125

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6931843870895188

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6787885801692691

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6695782582502873

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6679126611359841

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6657696216916853

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.658431002727594

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6404894151553538

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7406292149054763
BRAS...

seed           4.000000
BAMI           0.740629
CASW           0.591567
SCGRAPHM       0.803158
ISOLISI        0.968303
BRAS           0.749774
KBET           0.309674
CPCR           0.810053
bio_score      0.775914
batch_score    0.623167
joint_score    0.714815
dtype: float64

===== seed 5 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.

Removing 10166 genes not expressing in Drop-seq.
Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:20<10:07, 20.94s/it]

  7%|▋         | 2/30 [00:41<09:39, 20.69s/it]

 10%|█         | 3/30 [01:01<09:09, 20.34s/it]

 13%|█▎        | 4/30 [01:20<08:40, 20.03s/it]

 17%|█▋        | 5/30 [01:40<08:20, 20.03s/it]

 20%|██        | 6/30 [02:01<08:01, 20.08s/it]

 23%|██▎       | 7/30 [02:20<07:36, 19.86s/it]

 27%|██▋       | 8/30 [02:40<07:14, 19.73s/it]

 30%|███       | 9/30 [03:02<07:13, 20.66s/it]

 33%|███▎      | 10/30 [03:22<06:46, 20.31s/it]

 37%|███▋      | 11/30 [03:42<06:24, 20.24s/it]

 40%|████      | 12/30 [04:01<06:00, 20.05s/it]

 43%|████▎     | 13/30 [04:24<05:54, 20.86s/it]

 47%|████▋     | 14/30 [04:45<05:34, 20.92s/it]

 50%|█████     | 15/30 [05:06<05:14, 20.96s/it]

 53%|█████▎    | 16/30 [05:29<04:59, 21.38s/it]

 57%|█████▋    | 17/30 [05:50<04:37, 21.36s/it]

 60%|██████    | 18/30 [06:11<04:15, 21.25s/it]

 63%|██████▎   | 19/30 [06:32<03:53, 21.23s/it]

 67%|██████▋   | 20/30 [06:52<03:28, 20.85s/it]

 70%|███████   | 21/30 [07:12<03:04, 20.46s/it]

 73%|███████▎  | 22/30 [07:31<02:41, 20.24s/it]

 77%|███████▋  | 23/30 [07:51<02:19, 19.99s/it]

 80%|████████  | 24/30 [08:10<01:58, 19.82s/it]

 83%|████████▎ | 25/30 [08:30<01:39, 19.80s/it]

 87%|████████▋ | 26/30 [08:49<01:18, 19.52s/it]

 90%|█████████ | 27/30 [09:09<00:59, 19.67s/it]

 93%|█████████▎| 28/30 [09:30<00:40, 20.01s/it]

 97%|█████████▋| 29/30 [09:53<00:20, 20.96s/it]

100%|██████████| 30/30 [10:14<00:00, 21.16s/it]

100%|██████████| 30/30 [10:14<00:00, 20.50s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 15.16it/s]

 44%|████▍     | 4/9 [00:00<00:00, 11.60it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.17it/s]

 78%|███████▊  | 7/9 [00:00<00:00,  5.99it/s]

 89%|████████▉ | 8/9 [00:01<00:00,  6.62it/s]

100%|██████████| 9/9 [00:01<00:00,  7.93it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7480061249680322

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7038272527305278

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6864450231430684

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6799200020743297

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6626841862803986

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6595885492246261

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6498805080980785

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6451573000197369

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6368655431785059

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6374227578080243

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7480061249680322
BRAS...

seed           5.000000
BAMI           0.748006
CASW           0.588567
SCGRAPHM       0.816893
ISOLISI        0.963288
BRAS           0.767606
KBET           0.362855
CPCR           0.868141
bio_score      0.779188
batch_score    0.666200
joint_score    0.733993
dtype: float64

===== seed 6 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:22<10:50, 22.42s/it]

  7%|▋         | 2/30 [00:45<10:42, 22.94s/it]

 10%|█         | 3/30 [01:07<10:00, 22.25s/it]

 13%|█▎        | 4/30 [01:27<09:21, 21.58s/it]

 17%|█▋        | 5/30 [01:49<09:00, 21.64s/it]

 20%|██        | 6/30 [02:12<08:47, 21.99s/it]

 23%|██▎       | 7/30 [02:35<08:39, 22.60s/it]

 27%|██▋       | 8/30 [02:58<08:18, 22.66s/it]

 30%|███       | 9/30 [03:18<07:37, 21.77s/it]

 33%|███▎      | 10/30 [03:38<07:05, 21.27s/it]

 37%|███▋      | 11/30 [03:59<06:40, 21.08s/it]

 40%|████      | 12/30 [04:21<06:25, 21.39s/it]

 43%|████▎     | 13/30 [04:41<05:57, 21.01s/it]

 47%|████▋     | 14/30 [05:00<05:27, 20.49s/it]

 50%|█████     | 15/30 [05:20<05:04, 20.30s/it]

 53%|█████▎    | 16/30 [05:41<04:44, 20.31s/it]

 57%|█████▋    | 17/30 [06:01<04:25, 20.39s/it]

 60%|██████    | 18/30 [06:21<04:01, 20.09s/it]

 63%|██████▎   | 19/30 [06:39<03:36, 19.69s/it]

 67%|██████▋   | 20/30 [06:59<03:17, 19.73s/it]

 70%|███████   | 21/30 [07:20<02:59, 19.99s/it]

 73%|███████▎  | 22/30 [07:39<02:37, 19.68s/it]

 77%|███████▋  | 23/30 [08:00<02:21, 20.26s/it]

 80%|████████  | 24/30 [08:25<02:09, 21.50s/it]

 83%|████████▎ | 25/30 [08:49<01:52, 22.48s/it]

 87%|████████▋ | 26/30 [09:09<01:26, 21.62s/it]

 90%|█████████ | 27/30 [09:32<01:05, 21.97s/it]

 93%|█████████▎| 28/30 [09:53<00:43, 21.71s/it]

 97%|█████████▋| 29/30 [10:19<00:22, 22.98s/it]

100%|██████████| 30/30 [10:41<00:00, 22.60s/it]

100%|██████████| 30/30 [10:41<00:00, 21.37s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 16.83it/s]

 44%|████▍     | 4/9 [00:00<00:00, 12.21it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.82it/s]

 78%|███████▊  | 7/9 [00:00<00:00,  6.53it/s]

100%|██████████| 9/9 [00:01<00:00,  8.57it/s]

100%|██████████| 9/9 [00:01<00:00,  8.65it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7122992641982695

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7291327761601062

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7052116455272728

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6997910459012922

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6937569494918622

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6827189818674081

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6678059153572089

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6663939514927898

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6614277752711551

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6567775803997661

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7291327761601062
BRAS...

seed           6.000000
BAMI           0.729133
CASW           0.579408
SCGRAPHM       0.782761
ISOLISI        0.968280
BRAS           0.771439
KBET           0.348327
CPCR           0.835282
bio_score      0.764895
batch_score    0.651683
joint_score    0.719610
dtype: float64

===== seed 7 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.
Removing 12104 genes not expressing in Seq-Well.

Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:22<11:02, 22.86s/it]

  7%|▋         | 2/30 [00:45<10:39, 22.82s/it]

 10%|█         | 3/30 [01:06<09:50, 21.88s/it]

 13%|█▎        | 4/30 [01:26<09:12, 21.24s/it]

 17%|█▋        | 5/30 [01:46<08:38, 20.73s/it]

 20%|██        | 6/30 [02:09<08:36, 21.53s/it]

 23%|██▎       | 7/30 [02:36<08:58, 23.40s/it]

 27%|██▋       | 8/30 [03:03<08:59, 24.53s/it]

 30%|███       | 9/30 [03:30<08:51, 25.33s/it]

 33%|███▎      | 10/30 [03:56<08:25, 25.27s/it]

 37%|███▋      | 11/30 [04:25<08:24, 26.54s/it]

 40%|████      | 12/30 [04:56<08:21, 27.87s/it]

 43%|████▎     | 13/30 [05:27<08:08, 28.76s/it]

 47%|████▋     | 14/30 [05:50<07:12, 27.01s/it]

 50%|█████     | 15/30 [06:16<06:40, 26.73s/it]

 53%|█████▎    | 16/30 [06:41<06:07, 26.23s/it]

 57%|█████▋    | 17/30 [07:02<05:22, 24.78s/it]

 60%|██████    | 18/30 [07:25<04:50, 24.17s/it]

 63%|██████▎   | 19/30 [07:51<04:30, 24.61s/it]

 67%|██████▋   | 20/30 [08:12<03:55, 23.52s/it]

 70%|███████   | 21/30 [08:37<03:38, 24.24s/it]

 73%|███████▎  | 22/30 [09:03<03:17, 24.72s/it]

 77%|███████▋  | 23/30 [09:31<02:59, 25.70s/it]

 80%|████████  | 24/30 [09:52<02:24, 24.16s/it]

 83%|████████▎ | 25/30 [10:12<01:54, 22.89s/it]

 87%|████████▋ | 26/30 [10:32<01:27, 21.94s/it]

 90%|█████████ | 27/30 [10:51<01:03, 21.18s/it]

 93%|█████████▎| 28/30 [11:09<00:40, 20.38s/it]

 97%|█████████▋| 29/30 [11:29<00:20, 20.16s/it]

100%|██████████| 30/30 [11:50<00:00, 20.29s/it]

100%|██████████| 30/30 [11:50<00:00, 23.67s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 14.03it/s]

 44%|████▍     | 4/9 [00:00<00:00,  9.99it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.26it/s]

 78%|███████▊  | 7/9 [00:01<00:00,  5.53it/s]

 89%|████████▉ | 8/9 [00:01<00:00,  6.04it/s]

100%|██████████| 9/9 [00:01<00:00,  7.29it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6779888707824742

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6658228343194381

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6667519455950678

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6463819166601547

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6478294243687489

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6360200017676234

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6312496005935101

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6218749693797092

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6221227942326433

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6186838927813905

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6779888707824742
BRAS...

seed           7.000000
BAMI           0.677989
CASW           0.564708
SCGRAPHM       0.828301
ISOLISI        0.978930
BRAS           0.753928
KBET           0.310127
CPCR           0.860144
bio_score      0.762482
batch_score    0.641400
joint_score    0.714049
dtype: float64

===== seed 8 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.

Removing 10166 genes not expressing in Drop-seq.
Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:24<11:53, 24.60s/it]

  7%|▋         | 2/30 [00:53<12:44, 27.29s/it]

 10%|█         | 3/30 [01:16<11:14, 24.99s/it]

 13%|█▎        | 4/30 [01:35<09:53, 22.83s/it]

 17%|█▋        | 5/30 [01:54<08:57, 21.50s/it]

 20%|██        | 6/30 [02:13<08:14, 20.59s/it]

 23%|██▎       | 7/30 [02:32<07:39, 20.00s/it]

 27%|██▋       | 8/30 [02:54<07:32, 20.56s/it]

 30%|███       | 9/30 [03:15<07:17, 20.85s/it]

 33%|███▎      | 10/30 [03:36<06:57, 20.86s/it]

 37%|███▋      | 11/30 [03:57<06:39, 21.02s/it]

 40%|████      | 12/30 [04:20<06:25, 21.39s/it]

 43%|████▎     | 13/30 [04:38<05:49, 20.58s/it]

 47%|████▋     | 14/30 [04:58<05:26, 20.43s/it]

 50%|█████     | 15/30 [05:20<05:10, 20.70s/it]

 53%|█████▎    | 16/30 [05:41<04:53, 20.96s/it]

 57%|█████▋    | 17/30 [06:02<04:31, 20.91s/it]

 60%|██████    | 18/30 [06:22<04:08, 20.73s/it]

 63%|██████▎   | 19/30 [06:43<03:48, 20.82s/it]

 67%|██████▋   | 20/30 [07:02<03:22, 20.24s/it]

 70%|███████   | 21/30 [07:22<02:59, 19.98s/it]

 73%|███████▎  | 22/30 [07:40<02:35, 19.46s/it]

 77%|███████▋  | 23/30 [07:57<02:12, 18.86s/it]

 80%|████████  | 24/30 [08:15<01:51, 18.55s/it]

 83%|████████▎ | 25/30 [08:38<01:39, 19.90s/it]

 87%|████████▋ | 26/30 [09:01<01:23, 20.77s/it]

 90%|█████████ | 27/30 [09:27<01:06, 22.31s/it]

 93%|█████████▎| 28/30 [09:51<00:45, 22.86s/it]

 97%|█████████▋| 29/30 [10:10<00:21, 21.65s/it]

100%|██████████| 30/30 [10:28<00:00, 20.63s/it]

100%|██████████| 30/30 [10:28<00:00, 20.95s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 14.71it/s]

 44%|████▍     | 4/9 [00:00<00:00, 10.99it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.16it/s]

 78%|███████▊  | 7/9 [00:00<00:00,  5.98it/s]

 89%|████████▉ | 8/9 [00:01<00:00,  6.67it/s]

100%|██████████| 9/9 [00:01<00:00,  7.96it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7188143118682013

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7096581480097788

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7077136227119678

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6912078810745849

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6804792280570269

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6716550096141667

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6646869183874651

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6583131811507801

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6508580012924513

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6509132583723215

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7188143118682013
BRAS...

seed           8.000000
BAMI           0.718814
CASW           0.575433
SCGRAPHM       0.805528
ISOLISI        0.970256
BRAS           0.829161
KBET           0.353127
CPCR           0.881920
bio_score      0.767508
batch_score    0.688069
joint_score    0.735732
dtype: float64

===== seed 9 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:28<13:34, 28.10s/it]

  7%|▋         | 2/30 [00:52<12:06, 25.96s/it]

 10%|█         | 3/30 [01:18<11:45, 26.11s/it]

 13%|█▎        | 4/30 [01:39<10:26, 24.09s/it]

 17%|█▋        | 5/30 [01:59<09:18, 22.34s/it]

 20%|██        | 6/30 [02:17<08:23, 20.97s/it]

 23%|██▎       | 7/30 [02:42<08:30, 22.20s/it]

 27%|██▋       | 8/30 [03:06<08:22, 22.83s/it]

 30%|███       | 9/30 [03:27<07:48, 22.33s/it]

 33%|███▎      | 10/30 [03:54<07:57, 23.87s/it]

 37%|███▋      | 11/30 [04:22<07:56, 25.06s/it]

 40%|████      | 12/30 [04:47<07:31, 25.10s/it]

 43%|████▎     | 13/30 [05:11<06:59, 24.67s/it]

 47%|████▋     | 14/30 [05:33<06:21, 23.82s/it]

 50%|█████     | 15/30 [05:58<06:02, 24.19s/it]

 53%|█████▎    | 16/30 [06:19<05:27, 23.40s/it]

 57%|█████▋    | 17/30 [06:41<04:58, 22.97s/it]

 60%|██████    | 18/30 [07:08<04:48, 24.08s/it]

 63%|██████▎   | 19/30 [07:33<04:26, 24.18s/it]

 67%|██████▋   | 20/30 [07:55<03:56, 23.64s/it]

 70%|███████   | 21/30 [08:19<03:34, 23.83s/it]

 73%|███████▎  | 22/30 [08:38<02:58, 22.33s/it]

 77%|███████▋  | 23/30 [08:57<02:29, 21.38s/it]

 80%|████████  | 24/30 [09:18<02:07, 21.30s/it]

 83%|████████▎ | 25/30 [09:39<01:46, 21.20s/it]

 87%|████████▋ | 26/30 [10:03<01:28, 22.02s/it]

 90%|█████████ | 27/30 [10:26<01:06, 22.13s/it]

 93%|█████████▎| 28/30 [10:46<00:43, 21.67s/it]

 97%|█████████▋| 29/30 [11:06<00:20, 21.00s/it]

100%|██████████| 30/30 [11:33<00:00, 22.92s/it]

100%|██████████| 30/30 [11:33<00:00, 23.12s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 14.11it/s]

 44%|████▍     | 4/9 [00:00<00:00,  9.89it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  6.60it/s]

 78%|███████▊  | 7/9 [00:01<00:00,  5.19it/s]

 89%|████████▉ | 8/9 [00:01<00:00,  5.63it/s]

100%|██████████| 9/9 [00:01<00:00,  6.85it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7428733517523399

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7186701165763004

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7207608053065414

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7161621864639377

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.710711254923672

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6909099402594837

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6816786908272354

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6692680916202859

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6600942839307371

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6503532857087426

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7428733517523399
BRAS...

seed           9.000000
BAMI           0.742873
CASW           0.576169
SCGRAPHM       0.796430
ISOLISI        0.974898
BRAS           0.756948
KBET           0.341412
CPCR           0.838861
bio_score      0.772593
batch_score    0.645740
joint_score    0.721852
dtype: float64

===== seed 10 =====

Removing 10937 genes not expressing in 10x Chromium (v2).
Removing 13264 genes not expressing in 10x Chromium (v2) A.
Removing 13130 genes not expressing in 10x Chromium (v2) B.
Removing 11755 genes not expressing in 10x Chromium (v3).
Removing 11156 genes not expressing in CEL-Seq2.
Removing 10166 genes not expressing in Drop-seq.

Removing 12104 genes not expressing in Seq-Well.
Removing 8321 genes not expressing in Smart-seq2.
Removing 13662 genes not expressing in inDrops.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:25<12:11, 25.24s/it]

  7%|▋         | 2/30 [00:49<11:25, 24.50s/it]

 10%|█         | 3/30 [01:13<10:57, 24.34s/it]

 13%|█▎        | 4/30 [01:37<10:33, 24.36s/it]

 17%|█▋        | 5/30 [01:59<09:45, 23.44s/it]

 20%|██        | 6/30 [02:21<09:09, 22.88s/it]

 23%|██▎       | 7/30 [02:45<08:55, 23.27s/it]

 27%|██▋       | 8/30 [03:09<08:36, 23.48s/it]

 30%|███       | 9/30 [03:33<08:14, 23.54s/it]

 33%|███▎      | 10/30 [03:53<07:32, 22.62s/it]

 37%|███▋      | 11/30 [04:14<06:58, 22.03s/it]

 40%|████      | 12/30 [04:32<06:14, 20.81s/it]

 43%|████▎     | 13/30 [04:55<06:07, 21.63s/it]

 47%|████▋     | 14/30 [05:21<06:03, 22.75s/it]

 50%|█████     | 15/30 [05:47<05:56, 23.77s/it]

 53%|█████▎    | 16/30 [06:13<05:41, 24.42s/it]

 57%|█████▋    | 17/30 [06:35<05:10, 23.90s/it]

 60%|██████    | 18/30 [06:55<04:32, 22.72s/it]

 63%|██████▎   | 19/30 [07:25<04:34, 24.94s/it]

 67%|██████▋   | 20/30 [07:59<04:34, 27.46s/it]

 70%|███████   | 21/30 [08:30<04:17, 28.64s/it]

 73%|███████▎  | 22/30 [09:00<03:51, 28.90s/it]

 77%|███████▋  | 23/30 [09:33<03:31, 30.26s/it]

 80%|████████  | 24/30 [09:59<02:54, 29.01s/it]

 83%|████████▎ | 25/30 [10:26<02:21, 28.37s/it]

 87%|████████▋ | 26/30 [10:51<01:49, 27.29s/it]

 90%|█████████ | 27/30 [11:15<01:18, 26.32s/it]

 93%|█████████▎| 28/30 [11:43<00:53, 26.74s/it]

 97%|█████████▋| 29/30 [12:02<00:24, 24.56s/it]

100%|██████████| 30/30 [12:26<00:00, 24.47s/it]

100%|██████████| 30/30 [12:26<00:00, 24.90s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 6 batches per label
isolated labels: ['Plasmacytoid dendritic cell']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 18.90it/s]

 44%|████▍     | 4/9 [00:00<00:00, 13.29it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.32it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  6.95it/s]

100%|██████████| 9/9 [00:01<00:00,  8.71it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7195789592365229

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7216315112607085

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7028812803922099

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7028633051920283

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6910535150997498

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6733678444202703

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6705053888146211

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6649472632323516

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6583420898915161

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6570281859987709

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7216315112607085
BRAS...

seed           10.000000
BAMI            0.721632
CASW            0.581930
SCGRAPHM        0.797778
ISOLISI         0.962259
BRAS            0.758385
KBET            0.357438
CPCR            0.852383
bio_score       0.765900
batch_score     0.656069
joint_score     0.721967
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,ISOLISI,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.721416,0.557856,0.799157,0.979438,0.803629,0.314853,0.784247,0.764467,0.634243,0.712377
1,2,0.717261,0.575699,0.787987,0.974873,0.804782,0.316989,0.836208,0.763955,0.652660,0.719437
2,3,0.712082,0.580418,0.812956,0.964998,0.833160,0.307773,0.898785,0.767614,0.679906,0.732530
3,4,0.740629,0.591567,0.803158,0.968303,0.749774,0.309674,0.810053,0.775914,0.623167,0.714815
4,5,0.748006,0.588567,0.816893,0.963288,0.767606,0.362855,0.868141,0.779188,0.666200,0.733993
5,6,0.729133,0.579408,0.782761,0.968280,0.771439,0.348327,0.835282,0.764895,0.651683,0.719610
6,7,0.677989,0.564708,0.828301,0.978930,0.753928,0.310127,0.860144,0.762482,0.641400,0.714049
7,8,0.718814,0.575433,0.805528,0.970256,0.829161,0.353127,0.881920,0.767508,0.688069,0.735732
8,9,0.742873,0.576169,0.796430,0.974898,0.756948,0.341412,0.838861,0.772593,0.645740,0.721852
9,10,0.721632,0.581930,0.797778,0.962259,0.758385,0.357438,0.852383,0.765900,0.656069,0.721967

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.722984  0.018891  0.677989  0.748006
CASW         0.577176  0.009539  0.557856  0.591567
SCGRAPHM     0.803095  0.012879  0.782761  0.828301
ISOLISI      0.970552  0.005911  0.962259  0.979438
BRAS         0.782881  0.030251  0.749774  0.833160
KBET         0.332258  0.021173  0.307773  0.362855
CPCR         0.846602  0.031892  0.784247  0.898785
bio_score    0.768452  0.005297  0.762482  0.779188
batch_score  0.653914  0.018868  0.623167  0.688069
joint_score  0.722636  0.008118  0.712377  0.735732