# LIGER best - cellranger_versions

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'cellranger_versions'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'batch'
LABEL_KEY = 'cell_type'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'cellranger_versions'
assert BATCH_KEY == 'batch'
assert LABEL_KEY == 'cell_type'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                    cellranger_versions
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                batch
label_key                                            cell_type
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=19202 n_batches=2 n_labels=15
CPCR preflight: eligible_labels=12

In [4]:
OPTUNA_STUDY_NAME = 'liger_cellranger_versions_joint_expanded_metrics_scgraphm_v1'
OPTUNA_BEST_TRIAL = 99
OPTUNA_BEST_VALUE = 0.8281505136576194
OPTUNA_BEST_PARAMS = {'k': 20, 'value_lambda': 2.8640197425940483}

LIGER_BEST_ARGS = {
    "k": OPTUNA_BEST_PARAMS["k"],
    "value_lambda": OPTUNA_BEST_PARAMS["value_lambda"],
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_best(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_BEST_ARGS["k"],
        lam=LIGER_BEST_ARGS["value_lambda"],
        max_iterations=LIGER_BEST_ARGS["max_iters"],
        mode=LIGER_BEST_ARGS["mode"],
        layer=LIGER_BEST_ARGS["layer"],
        seed=seed,
    )


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **LIGER_BEST_ARGS,
    },
    name="best_setting",
)

study           liger_cellranger_versions_joint_expanded_metri...
best_trial                                                     99
best_value                                               0.828151
k                                                              20
value_lambda                                              2.86402
max_iters                                                      30
mode                                                         core
layer                                                      counts
Name: best_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:39,  5.51s/it]

  7%|▋         | 2/30 [00:11<02:39,  5.68s/it]

 10%|█         | 3/30 [00:16<02:32,  5.66s/it]

 13%|█▎        | 4/30 [00:26<03:07,  7.22s/it]

 17%|█▋        | 5/30 [00:34<03:06,  7.47s/it]

 20%|██        | 6/30 [00:40<02:48,  7.03s/it]

 23%|██▎       | 7/30 [00:46<02:32,  6.63s/it]

 27%|██▋       | 8/30 [00:53<02:26,  6.64s/it]

 30%|███       | 9/30 [01:04<02:53,  8.27s/it]

 33%|███▎      | 10/30 [01:13<02:44,  8.25s/it]

 37%|███▋      | 11/30 [01:18<02:21,  7.45s/it]

 40%|████      | 12/30 [01:25<02:09,  7.21s/it]

 43%|████▎     | 13/30 [01:31<01:55,  6.79s/it]

 47%|████▋     | 14/30 [01:37<01:44,  6.51s/it]

 50%|█████     | 15/30 [01:43<01:35,  6.37s/it]

 53%|█████▎    | 16/30 [01:48<01:26,  6.16s/it]

 57%|█████▋    | 17/30 [01:54<01:19,  6.11s/it]

 60%|██████    | 18/30 [02:00<01:11,  5.98s/it]

 63%|██████▎   | 19/30 [02:08<01:11,  6.50s/it]

 67%|██████▋   | 20/30 [02:14<01:04,  6.49s/it]

 70%|███████   | 21/30 [02:21<00:57,  6.44s/it]

 73%|███████▎  | 22/30 [02:26<00:49,  6.24s/it]

 77%|███████▋  | 23/30 [02:32<00:42,  6.10s/it]

 80%|████████  | 24/30 [02:38<00:36,  6.00s/it]

 83%|████████▎ | 25/30 [02:44<00:29,  5.99s/it]

 87%|████████▋ | 26/30 [02:50<00:23,  5.99s/it]

 90%|█████████ | 27/30 [02:56<00:18,  6.01s/it]

 93%|█████████▎| 28/30 [03:02<00:11,  5.99s/it]

 97%|█████████▋| 29/30 [03:08<00:05,  5.93s/it]

100%|██████████| 30/30 [03:15<00:00,  6.24s/it]

100%|██████████| 30/30 [03:15<00:00,  6.50s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.48it/s]

100%|██████████| 2/2 [00:00<00:00,  2.03it/s]

100%|██████████| 2/2 [00:00<00:00,  2.09it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.8429740391177498

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8470425012104491

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8311597403853772

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8246496855438379

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8171559008931814

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.8035087737269768

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8013362242812497

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7787905813715935

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7802399003287573

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7641971315267165

WARNING:2026-07-23 16:03:52,863:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8470425012104491
BRAS...

seed           1.000000
BAMI           0.847043
CASW           0.691690
SCGRAPHM       0.671396
BRAS           0.946068
KBET           0.951120
CPCR           0.998748
bio_score      0.736710
batch_score    0.965312
joint_score    0.828151
dtype: float64

===== seed 2 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:14,  6.70s/it]

  7%|▋         | 2/30 [00:12<02:48,  6.03s/it]

 10%|█         | 3/30 [00:17<02:36,  5.81s/it]

 13%|█▎        | 4/30 [00:23<02:28,  5.71s/it]

 17%|█▋        | 5/30 [00:29<02:23,  5.75s/it]

 20%|██        | 6/30 [00:34<02:15,  5.65s/it]

 23%|██▎       | 7/30 [00:40<02:07,  5.56s/it]

 27%|██▋       | 8/30 [00:45<02:03,  5.60s/it]

 30%|███       | 9/30 [00:51<01:58,  5.64s/it]

 33%|███▎      | 10/30 [00:57<01:56,  5.84s/it]

 37%|███▋      | 11/30 [01:03<01:51,  5.87s/it]

 40%|████      | 12/30 [01:09<01:45,  5.89s/it]

 43%|████▎     | 13/30 [01:15<01:41,  5.97s/it]

 47%|████▋     | 14/30 [01:21<01:35,  5.95s/it]

 50%|█████     | 15/30 [01:27<01:28,  5.88s/it]

 53%|█████▎    | 16/30 [01:33<01:22,  5.87s/it]

 57%|█████▋    | 17/30 [01:38<01:15,  5.83s/it]

 60%|██████    | 18/30 [01:44<01:10,  5.87s/it]

 63%|██████▎   | 19/30 [01:50<01:04,  5.83s/it]

 67%|██████▋   | 20/30 [01:57<01:00,  6.05s/it]

 70%|███████   | 21/30 [02:04<00:56,  6.28s/it]

 73%|███████▎  | 22/30 [02:10<00:49,  6.19s/it]

 77%|███████▋  | 23/30 [02:15<00:41,  5.95s/it]

 80%|████████  | 24/30 [02:20<00:35,  5.84s/it]

 83%|████████▎ | 25/30 [02:26<00:29,  5.86s/it]

 87%|████████▋ | 26/30 [02:32<00:23,  5.83s/it]

 90%|█████████ | 27/30 [02:38<00:17,  5.78s/it]

 93%|█████████▎| 28/30 [02:43<00:11,  5.73s/it]

 97%|█████████▋| 29/30 [02:50<00:05,  5.92s/it]

100%|██████████| 30/30 [02:55<00:00,  5.81s/it]

100%|██████████| 30/30 [02:55<00:00,  5.86s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.64it/s]

100%|██████████| 2/2 [00:00<00:00,  2.05it/s]

100%|██████████| 2/2 [00:00<00:00,  2.11it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8074201966714366

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8174652024171942

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8075781532023599

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7918377354234625

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7835700824248286

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7788061524952155

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7665462631662885

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7676063302644117

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7597562101732807

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7472116940688964

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8174652024171942
BRAS...

seed           2.000000
BAMI           0.817465
CASW           0.639408
SCGRAPHM       0.703120
BRAS           0.934449
KBET           0.958483
CPCR           0.994235
bio_score      0.719998
batch_score    0.962389
joint_score    0.816954
dtype: float64

===== seed 3 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:31,  5.21s/it]

  7%|▋         | 2/30 [00:11<02:37,  5.61s/it]

 10%|█         | 3/30 [00:16<02:33,  5.68s/it]

 13%|█▎        | 4/30 [00:23<02:33,  5.90s/it]

 17%|█▋        | 5/30 [00:29<02:31,  6.07s/it]

 20%|██        | 6/30 [00:36<02:31,  6.31s/it]

 23%|██▎       | 7/30 [00:42<02:25,  6.31s/it]

 27%|██▋       | 8/30 [00:48<02:16,  6.19s/it]

 30%|███       | 9/30 [00:53<02:05,  5.97s/it]

 33%|███▎      | 10/30 [00:59<01:59,  5.97s/it]

 37%|███▋      | 11/30 [01:05<01:50,  5.84s/it]

 40%|████      | 12/30 [01:11<01:44,  5.79s/it]

 43%|████▎     | 13/30 [01:16<01:37,  5.71s/it]

 47%|████▋     | 14/30 [01:22<01:30,  5.63s/it]

 50%|█████     | 15/30 [01:27<01:25,  5.68s/it]

 53%|█████▎    | 16/30 [01:34<01:21,  5.82s/it]

 57%|█████▋    | 17/30 [01:39<01:14,  5.76s/it]

 60%|██████    | 18/30 [01:45<01:08,  5.68s/it]

 63%|██████▎   | 19/30 [01:50<01:02,  5.65s/it]

 67%|██████▋   | 20/30 [01:56<00:56,  5.61s/it]

 70%|███████   | 21/30 [02:01<00:50,  5.60s/it]

 73%|███████▎  | 22/30 [02:07<00:44,  5.61s/it]

 77%|███████▋  | 23/30 [02:13<00:39,  5.58s/it]

 80%|████████  | 24/30 [02:18<00:33,  5.62s/it]

 83%|████████▎ | 25/30 [02:24<00:28,  5.69s/it]

 87%|████████▋ | 26/30 [02:30<00:22,  5.71s/it]

 90%|█████████ | 27/30 [02:36<00:17,  5.73s/it]

 93%|█████████▎| 28/30 [02:41<00:11,  5.77s/it]

 97%|█████████▋| 29/30 [02:47<00:05,  5.70s/it]

100%|██████████| 30/30 [02:53<00:00,  5.70s/it]

100%|██████████| 30/30 [02:53<00:00,  5.77s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.50it/s]

100%|██████████| 2/2 [00:00<00:00,  2.06it/s]

100%|██████████| 2/2 [00:00<00:00,  2.12it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7877589330593426

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7851450886595384

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7732864805395782

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7739360373964033

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7575505373700162

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7513462977566876

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7533827804807453

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7416249553947034

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7461792040639457

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7210467625652514

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7877589330593426
BRAS...
seed           3.000000
BAMI           0.787759
CASW           0.615931
SCGRAPHM       0.741547
BRAS           0.934736
KBET           0.939678
CPCR           0.996471
bio_score      0.715079
batch_score    0.956962
joint_score    0.811832
dtype: float64

===== seed 4 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:51,  5.92s/it]

  7%|▋         | 2/30 [00:12<02:56,  6.29s/it]

 10%|█         | 3/30 [00:19<02:54,  6.46s/it]

 13%|█▎        | 4/30 [00:25<02:48,  6.49s/it]

 17%|█▋        | 5/30 [00:32<02:41,  6.46s/it]

 20%|██        | 6/30 [00:38<02:32,  6.34s/it]

 23%|██▎       | 7/30 [00:45<02:30,  6.52s/it]

 27%|██▋       | 8/30 [00:51<02:19,  6.36s/it]

 30%|███       | 9/30 [00:57<02:13,  6.37s/it]

 33%|███▎      | 10/30 [01:04<02:08,  6.42s/it]

 37%|███▋      | 11/30 [01:10<02:02,  6.46s/it]

 40%|████      | 12/30 [01:16<01:53,  6.33s/it]

 43%|████▎     | 13/30 [01:22<01:46,  6.26s/it]

 47%|████▋     | 14/30 [01:29<01:42,  6.39s/it]

 50%|█████     | 15/30 [01:35<01:34,  6.27s/it]

 53%|█████▎    | 16/30 [01:41<01:28,  6.30s/it]

 57%|█████▋    | 17/30 [01:48<01:22,  6.37s/it]

 60%|██████    | 18/30 [01:55<01:20,  6.68s/it]

 63%|██████▎   | 19/30 [02:02<01:13,  6.72s/it]

 67%|██████▋   | 20/30 [02:08<01:05,  6.57s/it]

 70%|███████   | 21/30 [02:14<00:57,  6.40s/it]

 73%|███████▎  | 22/30 [02:21<00:51,  6.44s/it]

 77%|███████▋  | 23/30 [02:27<00:44,  6.43s/it]

 80%|████████  | 24/30 [02:34<00:38,  6.50s/it]

 83%|████████▎ | 25/30 [02:40<00:32,  6.49s/it]

 87%|████████▋ | 26/30 [02:46<00:25,  6.37s/it]

 90%|█████████ | 27/30 [02:54<00:20,  6.75s/it]

 93%|█████████▎| 28/30 [03:07<00:17,  8.55s/it]

 97%|█████████▋| 29/30 [03:14<00:08,  8.02s/it]

100%|██████████| 30/30 [03:20<00:00,  7.58s/it]

100%|██████████| 30/30 [03:20<00:00,  6.69s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.32it/s]

100%|██████████| 2/2 [00:01<00:00,  1.88it/s]

100%|██████████| 2/2 [00:01<00:00,  1.93it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8210812968828358

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7939897168652843

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7830624820333174

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7837791441568946

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7694101421000525

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7705885061574969

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7641843922199901

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7574608611456202

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7517200856594617

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7376838423858517

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8210812968828358
BRAS...
seed           4.000000
BAMI           0.821081
CASW           0.643358
SCGRAPHM       0.722044
BRAS           0.915232
KBET           0.953769
CPCR           0.994072
bio_score      0.728828
batch_score    0.954358
joint_score    0.819040
dtype: float64

===== seed 5 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:33,  5.28s/it]

  7%|▋         | 2/30 [00:11<02:38,  5.66s/it]

 10%|█         | 3/30 [00:18<02:49,  6.29s/it]

 13%|█▎        | 4/30 [00:24<02:45,  6.37s/it]

 17%|█▋        | 5/30 [00:31<02:40,  6.41s/it]

 20%|██        | 6/30 [00:37<02:32,  6.37s/it]

 23%|██▎       | 7/30 [00:44<02:30,  6.55s/it]

 27%|██▋       | 8/30 [00:50<02:20,  6.40s/it]

 30%|███       | 9/30 [00:56<02:13,  6.35s/it]

 33%|███▎      | 10/30 [01:03<02:09,  6.48s/it]

 37%|███▋      | 11/30 [01:09<02:02,  6.44s/it]

 40%|████      | 12/30 [01:15<01:53,  6.32s/it]

 43%|████▎     | 13/30 [01:21<01:46,  6.25s/it]

 47%|████▋     | 14/30 [01:27<01:37,  6.10s/it]

 50%|█████     | 15/30 [01:33<01:30,  6.02s/it]

 53%|█████▎    | 16/30 [01:39<01:23,  6.00s/it]

 57%|█████▋    | 17/30 [01:45<01:18,  6.07s/it]

 60%|██████    | 18/30 [01:51<01:13,  6.11s/it]

 63%|██████▎   | 19/30 [01:58<01:07,  6.09s/it]

 67%|██████▋   | 20/30 [02:03<01:00,  6.03s/it]

 70%|███████   | 21/30 [02:10<00:54,  6.07s/it]

 73%|███████▎  | 22/30 [02:16<00:48,  6.10s/it]

 77%|███████▋  | 23/30 [02:22<00:42,  6.10s/it]

 80%|████████  | 24/30 [02:29<00:38,  6.35s/it]

 83%|████████▎ | 25/30 [02:36<00:32,  6.53s/it]

 87%|████████▋ | 26/30 [02:42<00:25,  6.40s/it]

 90%|█████████ | 27/30 [02:48<00:18,  6.26s/it]

 93%|█████████▎| 28/30 [02:54<00:12,  6.16s/it]

 97%|█████████▋| 29/30 [02:59<00:06,  6.05s/it]

100%|██████████| 30/30 [03:06<00:00,  6.11s/it]

100%|██████████| 30/30 [03:06<00:00,  6.21s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.45it/s]

100%|██████████| 2/2 [00:01<00:00,  1.94it/s]

100%|██████████| 2/2 [00:01<00:00,  2.00it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7976110420140964

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7947046489260553

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7664763783700113

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7787249767679536

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7614313548787854

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7576080667744604

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7474919754002133

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7405005603684064

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7375749150039043

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.731388035023195

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7976110420140964
BRAS...
seed           5.000000
BAMI           0.797611
CASW           0.634127
SCGRAPHM       0.675289
BRAS           0.872238
KBET           0.888118
CPCR           0.935702
bio_score      0.702342
batch_score    0.898686
joint_score    0.780880
dtype: float64

===== seed 6 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:34,  5.33s/it]

  7%|▋         | 2/30 [00:12<02:54,  6.25s/it]

 10%|█         | 3/30 [00:18<02:45,  6.13s/it]

 13%|█▎        | 4/30 [00:24<02:41,  6.19s/it]

 17%|█▋        | 5/30 [00:30<02:37,  6.29s/it]

 20%|██        | 6/30 [00:36<02:28,  6.18s/it]

 23%|██▎       | 7/30 [00:43<02:23,  6.25s/it]

 27%|██▋       | 8/30 [00:49<02:19,  6.34s/it]

 30%|███       | 9/30 [00:55<02:09,  6.17s/it]

 33%|███▎      | 10/30 [01:01<02:02,  6.12s/it]

 37%|███▋      | 11/30 [01:07<01:56,  6.14s/it]

 40%|████      | 12/30 [01:13<01:49,  6.08s/it]

 43%|████▎     | 13/30 [01:19<01:42,  6.05s/it]

 47%|████▋     | 14/30 [01:26<01:38,  6.17s/it]

 50%|█████     | 15/30 [01:32<01:31,  6.08s/it]

 53%|█████▎    | 16/30 [01:38<01:26,  6.20s/it]

 57%|█████▋    | 17/30 [01:44<01:21,  6.23s/it]

 60%|██████    | 18/30 [01:51<01:15,  6.29s/it]

 63%|██████▎   | 19/30 [01:57<01:09,  6.36s/it]

 67%|██████▋   | 20/30 [02:04<01:03,  6.36s/it]

 70%|███████   | 21/30 [02:10<00:55,  6.20s/it]

 73%|███████▎  | 22/30 [02:15<00:48,  6.11s/it]

 77%|███████▋  | 23/30 [02:21<00:42,  6.01s/it]

 80%|████████  | 24/30 [02:27<00:35,  6.00s/it]

 83%|████████▎ | 25/30 [02:33<00:29,  5.96s/it]

 87%|████████▋ | 26/30 [02:39<00:23,  5.86s/it]

 90%|█████████ | 27/30 [02:44<00:17,  5.77s/it]

 93%|█████████▎| 28/30 [02:50<00:11,  5.76s/it]

 97%|█████████▋| 29/30 [02:56<00:05,  5.79s/it]

100%|██████████| 30/30 [03:01<00:00,  5.72s/it]

100%|██████████| 30/30 [03:01<00:00,  6.06s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.50it/s]

100%|██████████| 2/2 [00:00<00:00,  2.04it/s]

100%|██████████| 2/2 [00:00<00:00,  2.09it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7857784595763118

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8163552483484076

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8106952164508154

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7861487592116229

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7811619113725835

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.777367689447146

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7636389319722231

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7574552664552965

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7604730744525453

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7449118105201649

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8163552483484076
BRAS...
seed           6.000000
BAMI           0.816355
CASW           0.630815
SCGRAPHM       0.683943
BRAS           0.945073
KBET           0.928582
CPCR           0.996576
bio_score      0.710371
batch_score    0.956744
joint_score    0.808920
dtype: float64

===== seed 7 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:40,  5.54s/it]

  7%|▋         | 2/30 [00:11<02:38,  5.67s/it]

 10%|█         | 3/30 [00:17<02:34,  5.73s/it]

 13%|█▎        | 4/30 [00:22<02:29,  5.76s/it]

 17%|█▋        | 5/30 [00:28<02:25,  5.83s/it]

 20%|██        | 6/30 [00:34<02:21,  5.89s/it]

 23%|██▎       | 7/30 [00:40<02:16,  5.93s/it]

 27%|██▋       | 8/30 [00:46<02:11,  5.96s/it]

 30%|███       | 9/30 [00:53<02:08,  6.13s/it]

 33%|███▎      | 10/30 [00:59<02:01,  6.07s/it]

 37%|███▋      | 11/30 [01:05<01:56,  6.12s/it]

 40%|████      | 12/30 [01:11<01:48,  6.06s/it]

 43%|████▎     | 13/30 [01:17<01:43,  6.08s/it]

 47%|████▋     | 14/30 [01:23<01:36,  6.06s/it]

 50%|█████     | 15/30 [01:29<01:29,  5.99s/it]

 53%|█████▎    | 16/30 [01:35<01:24,  6.04s/it]

 57%|█████▋    | 17/30 [01:41<01:19,  6.11s/it]

 60%|██████    | 18/30 [01:48<01:13,  6.13s/it]

 63%|██████▎   | 19/30 [01:53<01:06,  6.04s/it]

 67%|██████▋   | 20/30 [01:59<00:59,  5.97s/it]

 70%|███████   | 21/30 [02:05<00:53,  5.93s/it]

 73%|███████▎  | 22/30 [02:11<00:47,  5.90s/it]

 77%|███████▋  | 23/30 [02:17<00:41,  5.86s/it]

 80%|████████  | 24/30 [02:23<00:36,  6.01s/it]

 83%|████████▎ | 25/30 [02:30<00:31,  6.29s/it]

 87%|████████▋ | 26/30 [02:37<00:25,  6.42s/it]

 90%|█████████ | 27/30 [02:43<00:19,  6.44s/it]

 93%|█████████▎| 28/30 [02:50<00:13,  6.52s/it]

 97%|█████████▋| 29/30 [02:56<00:06,  6.49s/it]

100%|██████████| 30/30 [03:02<00:00,  6.38s/it]

100%|██████████| 30/30 [03:02<00:00,  6.10s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.58it/s]

100%|██████████| 2/2 [00:00<00:00,  2.10it/s]

100%|██████████| 2/2 [00:00<00:00,  2.16it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8212306082925775

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8257683869200034

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8022526824052607

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7957121125044931

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.79069773368605

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7895944464286385

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7768149774059524

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7684061998822141

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7677289277554374

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7679413129172651

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8257683869200034
BRAS...

seed           7.000000
BAMI           0.825768
CASW           0.670626
SCGRAPHM       0.669183
BRAS           0.928102
KBET           0.906812
CPCR           0.996318
bio_score      0.721859
batch_score    0.943744
joint_score    0.810613
dtype: float64

===== seed 8 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:04<02:21,  4.88s/it]

  7%|▋         | 2/30 [00:10<02:29,  5.32s/it]

 10%|█         | 3/30 [00:16<02:31,  5.61s/it]

 13%|█▎        | 4/30 [00:22<02:30,  5.80s/it]

 17%|█▋        | 5/30 [00:28<02:24,  5.76s/it]

 20%|██        | 6/30 [00:33<02:16,  5.68s/it]

 23%|██▎       | 7/30 [00:39<02:13,  5.82s/it]

 27%|██▋       | 8/30 [00:45<02:08,  5.86s/it]

 30%|███       | 9/30 [00:51<02:01,  5.80s/it]

 33%|███▎      | 10/30 [00:57<01:56,  5.83s/it]

 37%|███▋      | 11/30 [01:03<01:52,  5.92s/it]

 40%|████      | 12/30 [01:09<01:45,  5.88s/it]

 43%|████▎     | 13/30 [01:15<01:39,  5.87s/it]

 47%|████▋     | 14/30 [01:22<01:42,  6.41s/it]

 50%|█████     | 15/30 [01:30<01:39,  6.66s/it]

 53%|█████▎    | 16/30 [01:37<01:34,  6.76s/it]

 57%|█████▋    | 17/30 [01:43<01:28,  6.82s/it]

 60%|██████    | 18/30 [01:51<01:24,  7.04s/it]

 63%|██████▎   | 19/30 [01:57<01:15,  6.83s/it]

 67%|██████▋   | 20/30 [02:04<01:07,  6.72s/it]

 70%|███████   | 21/30 [02:11<01:00,  6.72s/it]

 73%|███████▎  | 22/30 [02:16<00:51,  6.39s/it]

 77%|███████▋  | 23/30 [02:22<00:43,  6.15s/it]

 80%|████████  | 24/30 [02:28<00:36,  6.06s/it]

 83%|████████▎ | 25/30 [02:34<00:30,  6.15s/it]

 87%|████████▋ | 26/30 [02:40<00:24,  6.11s/it]

 90%|█████████ | 27/30 [02:46<00:18,  6.20s/it]

 93%|█████████▎| 28/30 [02:52<00:12,  6.09s/it]

 97%|█████████▋| 29/30 [02:58<00:06,  6.12s/it]

100%|██████████| 30/30 [03:04<00:00,  6.02s/it]

100%|██████████| 30/30 [03:04<00:00,  6.16s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.56it/s]

100%|██████████| 2/2 [00:00<00:00,  2.10it/s]

100%|██████████| 2/2 [00:00<00:00,  2.14it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7990827363964675

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.817653751463846

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7895409341812663

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.791688758071631

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7871716465568449

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.777898699722879

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7698794647386016

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7659682108484763

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7570227073433248

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7540654462179652

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.817653751463846
BRAS...
seed           8.000000
BAMI           0.817654
CASW           0.625171
SCGRAPHM       0.678817
BRAS           0.916397
KBET           0.923007
CPCR           0.988967
bio_score      0.707214
batch_score    0.942791
joint_score    0.801445
dtype: float64

===== seed 9 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:32,  5.25s/it]

  7%|▋         | 2/30 [00:10<02:34,  5.52s/it]

 10%|█         | 3/30 [00:16<02:34,  5.71s/it]

 13%|█▎        | 4/30 [00:23<02:32,  5.88s/it]

 17%|█▋        | 5/30 [00:28<02:25,  5.82s/it]

 20%|██        | 6/30 [00:34<02:21,  5.89s/it]

 23%|██▎       | 7/30 [00:40<02:14,  5.87s/it]

 27%|██▋       | 8/30 [00:46<02:08,  5.85s/it]

 30%|███       | 9/30 [00:52<02:02,  5.85s/it]

 33%|███▎      | 10/30 [00:58<01:57,  5.85s/it]

 37%|███▋      | 11/30 [01:04<01:53,  5.96s/it]

 40%|████      | 12/30 [01:10<01:46,  5.93s/it]

 43%|████▎     | 13/30 [01:16<01:40,  5.93s/it]

 47%|████▋     | 14/30 [01:21<01:33,  5.85s/it]

 50%|█████     | 15/30 [01:27<01:28,  5.90s/it]

 53%|█████▎    | 16/30 [01:33<01:22,  5.92s/it]

 57%|█████▋    | 17/30 [01:39<01:17,  5.93s/it]

 60%|██████    | 18/30 [01:46<01:13,  6.09s/it]

 63%|██████▎   | 19/30 [01:52<01:08,  6.25s/it]

 67%|██████▋   | 20/30 [01:58<01:01,  6.11s/it]

 70%|███████   | 21/30 [02:04<00:54,  6.04s/it]

 73%|███████▎  | 22/30 [02:10<00:47,  5.97s/it]

 77%|███████▋  | 23/30 [02:16<00:41,  5.92s/it]

 80%|████████  | 24/30 [02:21<00:35,  5.89s/it]

 83%|████████▎ | 25/30 [02:27<00:29,  5.87s/it]

 87%|████████▋ | 26/30 [02:33<00:23,  5.84s/it]

 90%|█████████ | 27/30 [02:39<00:17,  5.80s/it]

 93%|█████████▎| 28/30 [02:45<00:11,  5.81s/it]

 97%|█████████▋| 29/30 [02:51<00:05,  5.99s/it]

100%|██████████| 30/30 [02:57<00:00,  5.92s/it]

100%|██████████| 30/30 [02:57<00:00,  5.91s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.43it/s]

100%|██████████| 2/2 [00:00<00:00,  2.05it/s]

100%|██████████| 2/2 [00:00<00:00,  2.10it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8400980878385135

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8244416917450674

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8136749850983845

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8072764939786369

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8062016536800991

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7948773599584603

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.79107369309386

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7815880993919418

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7721265051624445

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7710092278452879

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8400980878385135
BRAS...
seed           9.000000
BAMI           0.840098
CASW           0.662662
SCGRAPHM       0.670472
BRAS           0.920136
KBET           0.845064
CPCR           0.969496
bio_score      0.724411
batch_score    0.911565
joint_score    0.799273
dtype: float64

===== seed 10 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=2.8640197425940483 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:37,  5.43s/it]

  7%|▋         | 2/30 [00:11<02:35,  5.56s/it]

 10%|█         | 3/30 [00:16<02:32,  5.65s/it]

 13%|█▎        | 4/30 [00:23<02:33,  5.90s/it]

 17%|█▋        | 5/30 [00:28<02:26,  5.87s/it]

 20%|██        | 6/30 [00:35<02:24,  6.00s/it]

 23%|██▎       | 7/30 [00:40<02:15,  5.87s/it]

 27%|██▋       | 8/30 [00:46<02:07,  5.81s/it]

 30%|███       | 9/30 [00:52<02:01,  5.78s/it]

 33%|███▎      | 10/30 [00:57<01:55,  5.78s/it]

 37%|███▋      | 11/30 [01:03<01:48,  5.69s/it]

 40%|████      | 12/30 [01:09<01:42,  5.69s/it]

 43%|████▎     | 13/30 [01:14<01:37,  5.72s/it]

 47%|████▋     | 14/30 [01:20<01:30,  5.66s/it]

 50%|█████     | 15/30 [01:26<01:24,  5.63s/it]

 53%|█████▎    | 16/30 [01:31<01:19,  5.71s/it]

 57%|█████▋    | 17/30 [01:37<01:14,  5.73s/it]

 60%|██████    | 18/30 [01:43<01:08,  5.68s/it]

 63%|██████▎   | 19/30 [01:49<01:02,  5.71s/it]

 67%|██████▋   | 20/30 [01:54<00:57,  5.74s/it]

 70%|███████   | 21/30 [02:01<00:54,  6.05s/it]

 73%|███████▎  | 22/30 [02:08<00:50,  6.34s/it]

 77%|███████▋  | 23/30 [02:15<00:44,  6.43s/it]

 80%|████████  | 24/30 [02:21<00:39,  6.52s/it]

 83%|████████▎ | 25/30 [02:29<00:33,  6.76s/it]

 87%|████████▋ | 26/30 [02:37<00:28,  7.05s/it]

 90%|█████████ | 27/30 [02:44<00:21,  7.04s/it]

 93%|█████████▎| 28/30 [02:50<00:13,  6.89s/it]

 97%|█████████▋| 29/30 [02:57<00:06,  6.98s/it]

100%|██████████| 30/30 [03:04<00:00,  6.91s/it]

100%|██████████| 30/30 [03:04<00:00,  6.15s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.99it/s]

100%|██████████| 2/2 [00:01<00:00,  1.60it/s]

100%|██████████| 2/2 [00:01<00:00,  1.64it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8263234362360276

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8089022758571737

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7942362878230749

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7944482227941694

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7908592851814493

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.774113416606392

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7734176536446691

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7780555304283077

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7571602212384682

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7416374467219452

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8263234362360276
BRAS...

seed           10.000000
BAMI            0.826323
CASW            0.630669
SCGRAPHM        0.645647
BRAS            0.878266
KBET            0.898147
CPCR            0.974084
bio_score       0.700880
batch_score     0.916832
joint_score     0.787261
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.847043,0.691690,0.671396,0.946068,0.951120,0.998748,0.736710,0.965312,0.828151
1,2,0.817465,0.639408,0.703120,0.934449,0.958483,0.994235,0.719998,0.962389,0.816954
2,3,0.787759,0.615931,0.741547,0.934736,0.939678,0.996471,0.715079,0.956962,0.811832
3,4,0.821081,0.643358,0.722044,0.915232,0.953769,0.994072,0.728828,0.954358,0.819040
4,5,0.797611,0.634127,0.675289,0.872238,0.888118,0.935702,0.702342,0.898686,0.780880
5,6,0.816355,0.630815,0.683943,0.945073,0.928582,0.996576,0.710371,0.956744,0.808920
6,7,0.825768,0.670626,0.669183,0.928102,0.906812,0.996318,0.721859,0.943744,0.810613
7,8,0.817654,0.625171,0.678817,0.916397,0.923007,0.988967,0.707214,0.942791,0.801445
8,9,0.840098,0.662662,0.670472,0.920136,0.845064,0.969496,0.724411,0.911565,0.799273
9,10,0.826323,0.630669,0.645647,0.878266,0.898147,0.974084,0.700880,0.916832,0.787261

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.819716  0.016658  0.787759  0.847043
CASW         0.644446  0.022232  0.615931  0.691690
SCGRAPHM     0.686146  0.026858  0.645647  0.741547
BRAS         0.919070  0.024186  0.872238  0.946068
KBET         0.919278  0.033672  0.845064  0.958483
CPCR         0.984467  0.018850  0.935702  0.998748
bio_score    0.716769  0.011106  0.700880  0.736710
batch_score  0.940938  0.022319  0.898686  0.965312
joint_score  0.806437  0.013751  0.780880  0.828151