# LIGER default - cellranger_versions

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'cellranger_versions'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'batch'
LABEL_KEY = 'cell_type'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'cellranger_versions'
assert BATCH_KEY == 'batch'
assert LABEL_KEY == 'cell_type'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                    cellranger_versions
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                batch
label_key                                            cell_type
metrics               [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=19202 n_batches=2 n_labels=15
CPCR preflight: eligible_labels=12

In [4]:
LIGER_DEFAULT_ARGS = {
    "k": 20,
    "value_lambda": 5.0,
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_default(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_DEFAULT_ARGS["k"],
        lam=LIGER_DEFAULT_ARGS["value_lambda"],
        max_iterations=LIGER_DEFAULT_ARGS["max_iters"],
        mode=LIGER_DEFAULT_ARGS["mode"],
        layer=LIGER_DEFAULT_ARGS["layer"],
        seed=seed,
    )


pd.Series(LIGER_DEFAULT_ARGS, name="default_setting")

k                   20
value_lambda       5.0
max_iters           30
mode              core
layer           counts
Name: default_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_default(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:44,  5.67s/it]

  7%|▋         | 2/30 [00:12<02:52,  6.15s/it]

 10%|█         | 3/30 [00:17<02:42,  6.01s/it]

 13%|█▎        | 4/30 [00:23<02:28,  5.70s/it]

 17%|█▋        | 5/30 [00:28<02:18,  5.53s/it]

 20%|██        | 6/30 [00:33<02:09,  5.41s/it]

 23%|██▎       | 7/30 [00:38<02:02,  5.34s/it]

 27%|██▋       | 8/30 [00:44<01:56,  5.30s/it]

 30%|███       | 9/30 [00:49<01:50,  5.26s/it]

 33%|███▎      | 10/30 [00:54<01:44,  5.24s/it]

 37%|███▋      | 11/30 [00:59<01:39,  5.22s/it]

 40%|████      | 12/30 [01:05<01:35,  5.31s/it]

 43%|████▎     | 13/30 [01:10<01:31,  5.36s/it]

 47%|████▋     | 14/30 [01:15<01:25,  5.33s/it]

 50%|█████     | 15/30 [01:21<01:20,  5.36s/it]

 53%|█████▎    | 16/30 [01:26<01:14,  5.34s/it]

 57%|█████▋    | 17/30 [01:32<01:10,  5.39s/it]

 60%|██████    | 18/30 [01:37<01:04,  5.36s/it]

 63%|██████▎   | 19/30 [01:42<00:58,  5.34s/it]

 67%|██████▋   | 20/30 [01:47<00:53,  5.33s/it]

 70%|███████   | 21/30 [01:53<00:47,  5.32s/it]

 73%|███████▎  | 22/30 [01:58<00:42,  5.31s/it]

 77%|███████▋  | 23/30 [02:03<00:37,  5.30s/it]

 80%|████████  | 24/30 [02:09<00:31,  5.30s/it]

 83%|████████▎ | 25/30 [02:14<00:26,  5.30s/it]

 87%|████████▋ | 26/30 [02:19<00:21,  5.29s/it]

 90%|█████████ | 27/30 [02:24<00:15,  5.28s/it]

 93%|█████████▎| 28/30 [02:30<00:10,  5.28s/it]

 97%|█████████▋| 29/30 [02:35<00:05,  5.28s/it]

100%|██████████| 30/30 [02:40<00:00,  5.27s/it]

100%|██████████| 30/30 [02:40<00:00,  5.36s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.82it/s]

100%|██████████| 2/2 [00:00<00:00,  2.29it/s]

100%|██████████| 2/2 [00:00<00:00,  2.35it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.8324431497005258

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8340686099778641

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.81151732112938

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.817919297133493

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8023107684839128

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.797779158366514

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7919172725996365

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7811878463479762

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7633849953503157

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7589419282315862

WARNING:2026-07-23 16:02:30,436:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8340686099778641
BRAS...

seed           1.000000
BAMI           0.834069
CASW           0.694363
SCGRAPHM       0.679933
BRAS           0.931736
KBET           0.951628
CPCR           0.997981
bio_score      0.736122
batch_score    0.960448
joint_score    0.825852
dtype: float64

===== seed 2 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:04<02:20,  4.86s/it]

  7%|▋         | 2/30 [00:10<02:23,  5.12s/it]

 10%|█         | 3/30 [00:15<02:19,  5.17s/it]

 13%|█▎        | 4/30 [00:20<02:13,  5.14s/it]

 17%|█▋        | 5/30 [00:25<02:08,  5.15s/it]

 20%|██        | 6/30 [00:30<02:03,  5.16s/it]

 23%|██▎       | 7/30 [00:36<01:59,  5.18s/it]

 27%|██▋       | 8/30 [00:41<01:54,  5.18s/it]

 30%|███       | 9/30 [00:46<01:49,  5.19s/it]

 33%|███▎      | 10/30 [00:51<01:43,  5.19s/it]

 37%|███▋      | 11/30 [00:56<01:38,  5.21s/it]

 40%|████      | 12/30 [01:02<01:34,  5.23s/it]

 43%|████▎     | 13/30 [01:07<01:29,  5.25s/it]

 47%|████▋     | 14/30 [01:12<01:24,  5.25s/it]

 50%|█████     | 15/30 [01:17<01:18,  5.25s/it]

 53%|█████▎    | 16/30 [01:23<01:13,  5.25s/it]

 57%|█████▋    | 17/30 [01:28<01:08,  5.26s/it]

 60%|██████    | 18/30 [01:33<01:03,  5.25s/it]

 63%|██████▎   | 19/30 [01:38<00:57,  5.25s/it]

 67%|██████▋   | 20/30 [01:44<00:52,  5.25s/it]

 70%|███████   | 21/30 [01:49<00:47,  5.26s/it]

 73%|███████▎  | 22/30 [01:54<00:42,  5.27s/it]

 77%|███████▋  | 23/30 [02:00<00:36,  5.27s/it]

 80%|████████  | 24/30 [02:05<00:31,  5.26s/it]

 83%|████████▎ | 25/30 [02:10<00:26,  5.25s/it]

 87%|████████▋ | 26/30 [02:15<00:20,  5.24s/it]

 90%|█████████ | 27/30 [02:21<00:15,  5.24s/it]

 93%|█████████▎| 28/30 [02:26<00:10,  5.24s/it]

 97%|█████████▋| 29/30 [02:31<00:05,  5.23s/it]

100%|██████████| 30/30 [02:36<00:00,  5.26s/it]

100%|██████████| 30/30 [02:36<00:00,  5.23s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.78it/s]

100%|██████████| 2/2 [00:00<00:00,  2.25it/s]

100%|██████████| 2/2 [00:00<00:00,  2.31it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8036442386646592

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8062598642994281

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7983216220765521

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7908053244316096

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7785890244086773

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7753194522186245

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.76819569754399

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7592525398383582

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7557038457819095

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7499291909499586

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8062598642994281
BRAS...

seed           2.000000
BAMI           0.806260
CASW           0.640075
SCGRAPHM       0.695768
BRAS           0.934386
KBET           0.957541
CPCR           0.996833
bio_score      0.714034
batch_score    0.962920
joint_score    0.813588
dtype: float64

===== seed 3 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:04<02:20,  4.83s/it]

  7%|▋         | 2/30 [00:10<02:25,  5.19s/it]

 10%|█         | 3/30 [00:15<02:22,  5.28s/it]

 13%|█▎        | 4/30 [00:20<02:17,  5.29s/it]

 17%|█▋        | 5/30 [00:26<02:11,  5.27s/it]

 20%|██        | 6/30 [00:31<02:05,  5.22s/it]

 23%|██▎       | 7/30 [00:36<01:58,  5.16s/it]

 27%|██▋       | 8/30 [00:41<01:52,  5.13s/it]

 30%|███       | 9/30 [00:46<01:47,  5.12s/it]

 33%|███▎      | 10/30 [00:51<01:42,  5.11s/it]

 37%|███▋      | 11/30 [00:56<01:37,  5.15s/it]

 40%|████      | 12/30 [01:01<01:32,  5.15s/it]

 43%|████▎     | 13/30 [01:07<01:27,  5.15s/it]

 47%|████▋     | 14/30 [01:12<01:22,  5.16s/it]

 50%|█████     | 15/30 [01:17<01:17,  5.16s/it]

 53%|█████▎    | 16/30 [01:22<01:12,  5.16s/it]

 57%|█████▋    | 17/30 [01:27<01:07,  5.17s/it]

 60%|██████    | 18/30 [01:33<01:02,  5.18s/it]

 63%|██████▎   | 19/30 [01:38<00:57,  5.19s/it]

 67%|██████▋   | 20/30 [01:43<00:51,  5.19s/it]

 70%|███████   | 21/30 [01:48<00:46,  5.20s/it]

 73%|███████▎  | 22/30 [01:53<00:41,  5.20s/it]

 77%|███████▋  | 23/30 [01:59<00:36,  5.20s/it]

 80%|████████  | 24/30 [02:04<00:31,  5.20s/it]

 83%|████████▎ | 25/30 [02:09<00:26,  5.21s/it]

 87%|████████▋ | 26/30 [02:14<00:20,  5.22s/it]

 90%|█████████ | 27/30 [02:19<00:15,  5.21s/it]

 93%|█████████▎| 28/30 [02:25<00:10,  5.21s/it]

 97%|█████████▋| 29/30 [02:30<00:05,  5.21s/it]

100%|██████████| 30/30 [02:35<00:00,  5.21s/it]

100%|██████████| 30/30 [02:35<00:00,  5.19s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.77it/s]

100%|██████████| 2/2 [00:00<00:00,  2.24it/s]

100%|██████████| 2/2 [00:00<00:00,  2.30it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7906772319948111

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7844687667793846

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.779063933171489

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7696003546223357

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7628916668031067

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7576605554142789

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7554372505141115

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7486556360248727

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7404246167023735

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7370442024712915

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7906772319948111
BRAS...

seed           3.000000
BAMI           0.790677
CASW           0.620343
SCGRAPHM       0.735915
BRAS           0.929512
KBET           0.954535
CPCR           0.996538
bio_score      0.715645
batch_score    0.960195
joint_score    0.813465
dtype: float64

===== seed 4 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:48,  5.82s/it]

  7%|▋         | 2/30 [00:11<02:42,  5.79s/it]

 10%|█         | 3/30 [00:17<02:33,  5.68s/it]

 13%|█▎        | 4/30 [00:22<02:23,  5.52s/it]

 17%|█▋        | 5/30 [00:27<02:15,  5.42s/it]

 20%|██        | 6/30 [00:32<02:08,  5.36s/it]

 23%|██▎       | 7/30 [00:38<02:02,  5.33s/it]

 27%|██▋       | 8/30 [00:43<01:56,  5.28s/it]

 30%|███       | 9/30 [00:48<01:50,  5.25s/it]

 33%|███▎      | 10/30 [00:53<01:44,  5.22s/it]

 37%|███▋      | 11/30 [00:58<01:38,  5.20s/it]

 40%|████      | 12/30 [01:04<01:33,  5.19s/it]

 43%|████▎     | 13/30 [01:09<01:28,  5.18s/it]

 47%|████▋     | 14/30 [01:14<01:22,  5.19s/it]

 50%|█████     | 15/30 [01:19<01:17,  5.18s/it]

 53%|█████▎    | 16/30 [01:24<01:12,  5.18s/it]

 57%|█████▋    | 17/30 [01:29<01:07,  5.19s/it]

 60%|██████    | 18/30 [01:35<01:02,  5.18s/it]

 63%|██████▎   | 19/30 [01:40<00:56,  5.18s/it]

 67%|██████▋   | 20/30 [01:45<00:51,  5.16s/it]

 70%|███████   | 21/30 [01:50<00:46,  5.15s/it]

 73%|███████▎  | 22/30 [01:55<00:41,  5.14s/it]

 77%|███████▋  | 23/30 [02:00<00:35,  5.13s/it]

 80%|████████  | 24/30 [02:05<00:30,  5.13s/it]

 83%|████████▎ | 25/30 [02:11<00:25,  5.16s/it]

 87%|████████▋ | 26/30 [02:16<00:20,  5.16s/it]

 90%|█████████ | 27/30 [02:21<00:15,  5.17s/it]

 93%|█████████▎| 28/30 [02:26<00:10,  5.17s/it]

 97%|█████████▋| 29/30 [02:31<00:05,  5.17s/it]

100%|██████████| 30/30 [02:37<00:00,  5.28s/it]

100%|██████████| 30/30 [02:37<00:00,  5.24s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.76it/s]

100%|██████████| 2/2 [00:00<00:00,  2.23it/s]

100%|██████████| 2/2 [00:00<00:00,  2.30it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8055684849505877

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8068463441066107

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7856948235910686

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7860922259455012

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7754909858533892

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7649748901071564

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7669344430993006

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7601204684602267

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.75463631458157

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7449233082364384

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8068463441066107
BRAS...

seed           4.000000
BAMI           0.806846
CASW           0.640687
SCGRAPHM       0.717531
BRAS           0.914713
KBET           0.954109
CPCR           0.996450
bio_score      0.721688
batch_score    0.955091
joint_score    0.815049
dtype: float64

===== seed 5 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:41,  5.58s/it]

  7%|▋         | 2/30 [00:10<02:31,  5.41s/it]

 10%|█         | 3/30 [00:16<02:24,  5.37s/it]

 13%|█▎        | 4/30 [00:21<02:16,  5.26s/it]

 17%|█▋        | 5/30 [00:26<02:14,  5.39s/it]

 20%|██        | 6/30 [00:33<02:15,  5.65s/it]

 23%|██▎       | 7/30 [00:39<02:12,  5.77s/it]

 27%|██▋       | 8/30 [00:45<02:11,  5.97s/it]

 30%|███       | 9/30 [00:51<02:04,  5.92s/it]

 33%|███▎      | 10/30 [00:56<01:53,  5.67s/it]

 37%|███▋      | 11/30 [01:01<01:44,  5.49s/it]

 40%|████      | 12/30 [01:06<01:36,  5.35s/it]

 43%|████▎     | 13/30 [01:11<01:29,  5.26s/it]

 47%|████▋     | 14/30 [01:16<01:23,  5.20s/it]

 50%|█████     | 15/30 [01:21<01:17,  5.15s/it]

 53%|█████▎    | 16/30 [01:26<01:11,  5.12s/it]

 57%|█████▋    | 17/30 [01:31<01:06,  5.10s/it]

 60%|██████    | 18/30 [01:36<01:01,  5.09s/it]

 63%|██████▎   | 19/30 [01:41<00:55,  5.09s/it]

 67%|██████▋   | 20/30 [01:46<00:50,  5.09s/it]

 70%|███████   | 21/30 [01:52<00:45,  5.09s/it]

 73%|███████▎  | 22/30 [01:57<00:40,  5.10s/it]

 77%|███████▋  | 23/30 [02:02<00:35,  5.10s/it]

 80%|████████  | 24/30 [02:07<00:30,  5.10s/it]

 83%|████████▎ | 25/30 [02:12<00:25,  5.10s/it]

 87%|████████▋ | 26/30 [02:17<00:20,  5.10s/it]

 90%|█████████ | 27/30 [02:22<00:15,  5.10s/it]

 93%|█████████▎| 28/30 [02:27<00:10,  5.15s/it]

 97%|█████████▋| 29/30 [02:33<00:05,  5.13s/it]

100%|██████████| 30/30 [02:38<00:00,  5.12s/it]

100%|██████████| 30/30 [02:38<00:00,  5.27s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.79it/s]

100%|██████████| 2/2 [00:00<00:00,  2.27it/s]

100%|██████████| 2/2 [00:00<00:00,  2.33it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7655650194482517

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7690321874897301

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7701566344865366

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7647995889372231

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7621518018385252

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7584865801534535

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7551015402573099

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7508311696622134

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.729242162224358

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.723456304112713

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7701566344865366
BRAS...

seed           5.000000
BAMI           0.770157
CASW           0.638184
SCGRAPHM       0.677810
BRAS           0.884303
KBET           0.894990
CPCR           0.948187
bio_score      0.695383
batch_score    0.909160
joint_score    0.780894
dtype: float64

===== seed 6 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:04<02:16,  4.72s/it]

  7%|▋         | 2/30 [00:09<02:20,  5.03s/it]

 10%|█         | 3/30 [00:15<02:18,  5.12s/it]

 13%|█▎        | 4/30 [00:20<02:15,  5.20s/it]

 17%|█▋        | 5/30 [00:25<02:08,  5.14s/it]

 20%|██        | 6/30 [00:30<02:03,  5.16s/it]

 23%|██▎       | 7/30 [00:35<01:57,  5.12s/it]

 27%|██▋       | 8/30 [00:40<01:52,  5.10s/it]

 30%|███       | 9/30 [00:45<01:46,  5.08s/it]

 33%|███▎      | 10/30 [00:50<01:41,  5.08s/it]

 37%|███▋      | 11/30 [00:56<01:36,  5.07s/it]

 40%|████      | 12/30 [01:01<01:31,  5.09s/it]

 43%|████▎     | 13/30 [01:06<01:27,  5.13s/it]

 47%|████▋     | 14/30 [01:11<01:22,  5.15s/it]

 50%|█████     | 15/30 [01:16<01:16,  5.13s/it]

 53%|█████▎    | 16/30 [01:21<01:11,  5.11s/it]

 57%|█████▋    | 17/30 [01:26<01:06,  5.10s/it]

 60%|██████    | 18/30 [01:31<01:01,  5.09s/it]

 63%|██████▎   | 19/30 [01:36<00:56,  5.09s/it]

 67%|██████▋   | 20/30 [01:42<00:50,  5.10s/it]

 70%|███████   | 21/30 [01:47<00:45,  5.10s/it]

 73%|███████▎  | 22/30 [01:52<00:40,  5.11s/it]

 77%|███████▋  | 23/30 [01:57<00:35,  5.12s/it]

 80%|████████  | 24/30 [02:02<00:30,  5.12s/it]

 83%|████████▎ | 25/30 [02:07<00:25,  5.13s/it]

 87%|████████▋ | 26/30 [02:12<00:20,  5.16s/it]

 90%|█████████ | 27/30 [02:18<00:16,  5.38s/it]

 93%|█████████▎| 28/30 [02:24<00:10,  5.31s/it]

 97%|█████████▋| 29/30 [02:29<00:05,  5.33s/it]

100%|██████████| 30/30 [02:34<00:00,  5.29s/it]

100%|██████████| 30/30 [02:34<00:00,  5.15s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.78it/s]

100%|██████████| 2/2 [00:00<00:00,  2.27it/s]

100%|██████████| 2/2 [00:00<00:00,  2.33it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8072123881554611

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8126834302756002

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7957466047498313

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7936632357807296

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7801113088013168

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7720882803190396

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.76552384064575

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7703232498565629

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7527342213424757

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7468609254006563

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8126834302756002
BRAS...

seed           6.000000
BAMI           0.812683
CASW           0.629874
SCGRAPHM       0.672648
BRAS           0.940124
KBET           0.947523
CPCR           0.997876
bio_score      0.705069
batch_score    0.961841
joint_score    0.807777
dtype: float64

===== seed 7 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:51,  5.92s/it]

  7%|▋         | 2/30 [00:12<02:51,  6.14s/it]

 10%|█         | 3/30 [00:17<02:41,  5.98s/it]

 13%|█▎        | 4/30 [00:23<02:28,  5.70s/it]

 17%|█▋        | 5/30 [00:28<02:18,  5.54s/it]

 20%|██        | 6/30 [00:33<02:10,  5.46s/it]

 23%|██▎       | 7/30 [00:39<02:04,  5.41s/it]

 27%|██▋       | 8/30 [00:44<01:58,  5.38s/it]

 30%|███       | 9/30 [00:49<01:52,  5.35s/it]

 33%|███▎      | 10/30 [00:54<01:46,  5.32s/it]

 37%|███▋      | 11/30 [01:00<01:40,  5.29s/it]

 40%|████      | 12/30 [01:05<01:34,  5.27s/it]

 43%|████▎     | 13/30 [01:10<01:29,  5.26s/it]

 47%|████▋     | 14/30 [01:15<01:23,  5.24s/it]

 50%|█████     | 15/30 [01:21<01:18,  5.24s/it]

 53%|█████▎    | 16/30 [01:26<01:13,  5.23s/it]

 57%|█████▋    | 17/30 [01:31<01:07,  5.22s/it]

 60%|██████    | 18/30 [01:36<01:02,  5.22s/it]

 63%|██████▎   | 19/30 [01:41<00:57,  5.21s/it]

 67%|██████▋   | 20/30 [01:47<00:52,  5.21s/it]

 70%|███████   | 21/30 [01:52<00:46,  5.21s/it]

 73%|███████▎  | 22/30 [01:57<00:41,  5.21s/it]

 77%|███████▋  | 23/30 [02:02<00:36,  5.21s/it]

 80%|████████  | 24/30 [02:07<00:31,  5.20s/it]

 83%|████████▎ | 25/30 [02:13<00:26,  5.20s/it]

 87%|████████▋ | 26/30 [02:18<00:20,  5.20s/it]

 90%|█████████ | 27/30 [02:23<00:15,  5.19s/it]

 93%|█████████▎| 28/30 [02:28<00:10,  5.18s/it]

 97%|█████████▋| 29/30 [02:33<00:05,  5.18s/it]

100%|██████████| 30/30 [02:38<00:00,  5.17s/it]

100%|██████████| 30/30 [02:38<00:00,  5.30s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.78it/s]

100%|██████████| 2/2 [00:00<00:00,  2.27it/s]

100%|██████████| 2/2 [00:00<00:00,  2.33it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8324326737178259

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8183905854471121

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8138933401181148

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8117938770541185

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7975438743359319

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7893851534143183

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7946462904811977

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7805170824092952

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7705133191289278

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.758437408785745

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8324326737178259
BRAS...

seed           7.000000
BAMI           0.832433
CASW           0.661039
SCGRAPHM       0.645563
BRAS           0.914108
KBET           0.905905
CPCR           0.989720
bio_score      0.713011
batch_score    0.936578
joint_score    0.802438
dtype: float64

===== seed 8 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:45,  5.71s/it]

  7%|▋         | 2/30 [00:12<02:50,  6.09s/it]

 10%|█         | 3/30 [00:17<02:36,  5.80s/it]

 13%|█▎        | 4/30 [00:22<02:25,  5.60s/it]

 17%|█▋        | 5/30 [00:28<02:18,  5.52s/it]

 20%|██        | 6/30 [00:33<02:11,  5.48s/it]

 23%|██▎       | 7/30 [00:38<02:05,  5.44s/it]

 27%|██▋       | 8/30 [00:44<01:59,  5.41s/it]

 30%|███       | 9/30 [00:49<01:53,  5.40s/it]

 33%|███▎      | 10/30 [00:55<01:47,  5.39s/it]

 37%|███▋      | 11/30 [01:00<01:42,  5.37s/it]

 40%|████      | 12/30 [01:05<01:36,  5.36s/it]

 43%|████▎     | 13/30 [01:11<01:30,  5.35s/it]

 47%|████▋     | 14/30 [01:16<01:25,  5.34s/it]

 50%|█████     | 15/30 [01:21<01:20,  5.35s/it]

 53%|█████▎    | 16/30 [01:27<01:14,  5.33s/it]

 57%|█████▋    | 17/30 [01:32<01:09,  5.31s/it]

 60%|██████    | 18/30 [01:37<01:03,  5.30s/it]

 63%|██████▎   | 19/30 [01:42<00:58,  5.29s/it]

 67%|██████▋   | 20/30 [01:48<00:52,  5.28s/it]

 70%|███████   | 21/30 [01:53<00:47,  5.26s/it]

 73%|███████▎  | 22/30 [01:58<00:42,  5.25s/it]

 77%|███████▋  | 23/30 [02:03<00:37,  5.30s/it]

 80%|████████  | 24/30 [02:09<00:31,  5.29s/it]

 83%|████████▎ | 25/30 [02:14<00:26,  5.27s/it]

 87%|████████▋ | 26/30 [02:19<00:21,  5.26s/it]

 90%|█████████ | 27/30 [02:24<00:15,  5.25s/it]

 93%|█████████▎| 28/30 [02:30<00:10,  5.25s/it]

 97%|█████████▋| 29/30 [02:35<00:05,  5.25s/it]

100%|██████████| 30/30 [02:40<00:00,  5.25s/it]

100%|██████████| 30/30 [02:40<00:00,  5.35s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.76it/s]

100%|██████████| 2/2 [00:00<00:00,  2.26it/s]

100%|██████████| 2/2 [00:00<00:00,  2.32it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7967052453045398

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8004423679373706

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7878770315029627

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7847914951994411

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7813671763181033

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7731208849057057

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7446156332364843

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7417069530927918

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7248246198183376

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7219173828639821

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8004423679373706
BRAS...

seed           8.000000
BAMI           0.800442
CASW           0.664458
SCGRAPHM       0.672312
BRAS           0.954907
KBET           0.861425
CPCR           0.998381
bio_score      0.712404
batch_score    0.938238
joint_score    0.802737
dtype: float64

===== seed 9 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:04<02:20,  4.83s/it]

  7%|▋         | 2/30 [00:10<02:24,  5.17s/it]

 10%|█         | 3/30 [00:15<02:21,  5.25s/it]

 13%|█▎        | 4/30 [00:20<02:16,  5.25s/it]

 17%|█▋        | 5/30 [00:26<02:11,  5.26s/it]

 20%|██        | 6/30 [00:31<02:06,  5.28s/it]

 23%|██▎       | 7/30 [00:36<02:02,  5.31s/it]

 27%|██▋       | 8/30 [00:42<01:58,  5.38s/it]

 30%|███       | 9/30 [00:47<01:53,  5.38s/it]

 33%|███▎      | 10/30 [00:53<01:47,  5.39s/it]

 37%|███▋      | 11/30 [00:58<01:42,  5.39s/it]

 40%|████      | 12/30 [01:03<01:36,  5.38s/it]

 43%|████▎     | 13/30 [01:09<01:31,  5.37s/it]

 47%|████▋     | 14/30 [01:14<01:25,  5.36s/it]

 50%|█████     | 15/30 [01:19<01:20,  5.36s/it]

 53%|█████▎    | 16/30 [01:25<01:14,  5.35s/it]

 57%|█████▋    | 17/30 [01:30<01:09,  5.34s/it]

 60%|██████    | 18/30 [01:35<01:03,  5.33s/it]

 63%|██████▎   | 19/30 [01:41<00:58,  5.33s/it]

 67%|██████▋   | 20/30 [01:46<00:53,  5.32s/it]

 70%|███████   | 21/30 [01:51<00:47,  5.32s/it]

 73%|███████▎  | 22/30 [01:57<00:42,  5.32s/it]

 77%|███████▋  | 23/30 [02:02<00:37,  5.32s/it]

 80%|████████  | 24/30 [02:07<00:31,  5.32s/it]

 83%|████████▎ | 25/30 [02:13<00:26,  5.32s/it]

 87%|████████▋ | 26/30 [02:18<00:21,  5.32s/it]

 90%|█████████ | 27/30 [02:23<00:15,  5.32s/it]

 93%|█████████▎| 28/30 [02:29<00:10,  5.32s/it]

 97%|█████████▋| 29/30 [02:34<00:05,  5.32s/it]

100%|██████████| 30/30 [02:39<00:00,  5.32s/it]

100%|██████████| 30/30 [02:39<00:00,  5.32s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.72it/s]

100%|██████████| 2/2 [00:00<00:00,  2.22it/s]

100%|██████████| 2/2 [00:00<00:00,  2.28it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8272868578019756

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8345139311840658

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8122427953604349

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8031266320768922

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7982793555886024

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7911576407955938

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7839536361549634

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7770441574148791

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7745495344706268

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7625770010129452

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8345139311840658
BRAS...

seed           9.000000
BAMI           0.834514
CASW           0.689065
SCGRAPHM       0.661615
BRAS           0.948760
KBET           0.963793
CPCR           0.998243
bio_score      0.728398
batch_score    0.970266
joint_score    0.825145
dtype: float64

===== seed 10 =====

Removing 22 genes not expressing in v6.
Index(['AMPD1', 'CRYGD', 'CPA3', 'C3orf80', 'PROM1', 'UBE2QL1', 'NR2F1',
       'STC2', 'FREM1', 'AP003096.1', 'GAL', 'GPRC5D', 'AC079949.6', 'SIX1',
       'IGHV3-64', 'ARHGDIG', 'SCNN1B', 'SPACA3', 'HOXB9', 'ONECUT2', 'SLC1A6',
       'KRTAP19-1'],
      dtype='object', name='gene')

Removing 9 genes not expressing in v8.
Index(['CRYGD', 'C3orf80', 'STC2', 'IGHV3-64', 'ARHGDIG', 'SPACA3', 'HOXB9',
       'ONECUT2', 'KRTAP19-1'],
      dtype='object', name='gene')

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:04<02:21,  4.88s/it]

  7%|▋         | 2/30 [00:10<02:23,  5.13s/it]

 10%|█         | 3/30 [00:15<02:20,  5.21s/it]

 13%|█▎        | 4/30 [00:20<02:14,  5.19s/it]

 17%|█▋        | 5/30 [00:25<02:09,  5.17s/it]

 20%|██        | 6/30 [00:30<02:03,  5.15s/it]

 23%|██▎       | 7/30 [00:36<01:58,  5.16s/it]

 27%|██▋       | 8/30 [00:41<01:53,  5.16s/it]

 30%|███       | 9/30 [00:46<01:48,  5.17s/it]

 33%|███▎      | 10/30 [00:51<01:43,  5.16s/it]

 37%|███▋      | 11/30 [00:56<01:38,  5.16s/it]

 40%|████      | 12/30 [01:01<01:32,  5.15s/it]

 43%|████▎     | 13/30 [01:07<01:27,  5.15s/it]

 47%|████▋     | 14/30 [01:12<01:22,  5.15s/it]

 50%|█████     | 15/30 [01:17<01:17,  5.15s/it]

 53%|█████▎    | 16/30 [01:22<01:12,  5.15s/it]

 57%|█████▋    | 17/30 [01:27<01:07,  5.19s/it]

 60%|██████    | 18/30 [01:33<01:02,  5.21s/it]

 63%|██████▎   | 19/30 [01:38<00:57,  5.19s/it]

 67%|██████▋   | 20/30 [01:43<00:51,  5.18s/it]

 70%|███████   | 21/30 [01:48<00:46,  5.17s/it]

 73%|███████▎  | 22/30 [01:53<00:41,  5.16s/it]

 77%|███████▋  | 23/30 [01:58<00:36,  5.16s/it]

 80%|████████  | 24/30 [02:03<00:30,  5.16s/it]

 83%|████████▎ | 25/30 [02:09<00:25,  5.16s/it]

 87%|████████▋ | 26/30 [02:14<00:20,  5.15s/it]

 90%|█████████ | 27/30 [02:19<00:15,  5.16s/it]

 93%|█████████▎| 28/30 [02:24<00:10,  5.15s/it]

 97%|█████████▋| 29/30 [02:29<00:05,  5.15s/it]

100%|██████████| 30/30 [02:34<00:00,  5.14s/it]

100%|██████████| 30/30 [02:34<00:00,  5.16s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping MAIT as it has <100 cells
Skipping Megakaryocyte as it has <100 cells

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping gd T as it has <100 cells
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.77it/s]

100%|██████████| 2/2 [00:00<00:00,  2.25it/s]

100%|██████████| 2/2 [00:00<00:00,  2.31it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8352008704953682

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8380248243798901

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.824168499929678

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8151834302931333

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8077205781941379

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7994110600736379

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7841643704026191

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7819654908558199

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.771974925604772

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7598611019403673

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8380248243798901
BRAS...

seed           10.000000
BAMI            0.838025
CASW            0.673566
SCGRAPHM        0.651759
BRAS            0.921701
KBET            0.906460
CPCR            0.990455
bio_score       0.721117
batch_score     0.939539
joint_score     0.808486
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.834069,0.694363,0.679933,0.931736,0.951628,0.997981,0.736122,0.960448,0.825852
1,2,0.806260,0.640075,0.695768,0.934386,0.957541,0.996833,0.714034,0.962920,0.813588
2,3,0.790677,0.620343,0.735915,0.929512,0.954535,0.996538,0.715645,0.960195,0.813465
3,4,0.806846,0.640687,0.717531,0.914713,0.954109,0.996450,0.721688,0.955091,0.815049
4,5,0.770157,0.638184,0.677810,0.884303,0.894990,0.948187,0.695383,0.909160,0.780894
5,6,0.812683,0.629874,0.672648,0.940124,0.947523,0.997876,0.705069,0.961841,0.807777
6,7,0.832433,0.661039,0.645563,0.914108,0.905905,0.989720,0.713011,0.936578,0.802438
7,8,0.800442,0.664458,0.672312,0.954907,0.861425,0.998381,0.712404,0.938238,0.802737
8,9,0.834514,0.689065,0.661615,0.948760,0.963793,0.998243,0.728398,0.970266,0.825145
9,10,0.838025,0.673566,0.651759,0.921701,0.906460,0.990455,0.721117,0.939539,0.808486

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.812611  0.021176  0.770157  0.838025
CASW         0.655165  0.023923  0.620343  0.694363
SCGRAPHM     0.681085  0.026854  0.645563  0.735915
BRAS         0.927425  0.019168  0.884303  0.954907
KBET         0.929791  0.033047  0.861425  0.963793
CPCR         0.991066  0.014602  0.948187  0.998381
bio_score    0.716287  0.010894  0.695383  0.736122
batch_score  0.949427  0.017463  0.909160  0.970266
joint_score  0.809543  0.012220  0.780894  0.825852