# scVI default - nph_cerebellum

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

This notebook is intentionally unexecuted.

In [1]:
import gc
import inspect
import json
import os
import sys
from pathlib import Path

os.environ["PYTHONNOUSERSITE"] = "1"
PROJECT_ROOT = (
    "/ubc/cs/research/beaver/projects/"
    "Single-cell-integration-metrics"
)
os.environ["R_HOME"] = (
    f"{PROJECT_ROOT}/CondaEnv/scvi_py310/lib/R"
)
os.environ["R_LIBS_SITE"] = (
    f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R/library"
)
sys.path.insert(0, f"{PROJECT_ROOT}/scib")

OPTIMIZER_PATH = Path(
    PROJECT_ROOT,
    "scripts",
    "optuna_multi_metrics",
    "optuna_scvi",
    "optimize_scvi_multi_metrics.py",
)
sys.path.insert(0, str(OPTIMIZER_PATH.parent))

import anndata as ad
import numpy as np
import pandas as pd
import torch
import optimize_scvi_multi_metrics as scvi_workflow

assert Path(scvi_workflow.__file__).resolve() == OPTIMIZER_PATH

In [2]:
DATASET_NAME = 'nph_cerebellum'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEYS = ('Sample',)
BATCH_KEY = BATCH_KEYS[0]
LABEL_KEY = 'Celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_NEIGHBORS = 15
USE_HVG = True
N_TOP_HVG = 2000
MAX_EPOCHS = 400

EMBED_KEY = "X_scvi"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "scvi_metric_batch"
METRIC_LABEL_KEY = "scvi_metric_label"

assert DATASET_NAME == 'nph_cerebellum'
assert BATCH_KEYS == ('Sample',)
assert LABEL_KEY == 'Celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_keys": list(BATCH_KEYS),
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
        "use_hvg": USE_HVG,
        "n_top_hvg": N_TOP_HVG,
        "max_epochs": MAX_EPOCHS,
    },
    name="configuration",
)

dataset                                          nph_cerebellum
data_path     /ubc/cs/research/beaver/projects/Single-cell-i...
batch_keys                                             [Sample]
label_key                                              Celltype
metrics                [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
use_hvg                                                    True
n_top_hvg                                                  2000
max_epochs                                                  400
Name: configuration, dtype: object

In [3]:
scvi_workflow.DATA_PATH = DATA_PATH
scvi_workflow.DATASET_NAME = DATASET_NAME
scvi_workflow.BATCH_KEYS = list(BATCH_KEYS)
scvi_workflow.BATCH_KEY = BATCH_KEY
scvi_workflow.LABEL_KEY = LABEL_KEY
scvi_workflow.USE_HVG = USE_HVG
scvi_workflow.N_TOP_HVG = N_TOP_HVG
scvi_workflow.MAX_EPOCHS = MAX_EPOCHS
scvi_workflow.N_NEIGHBORS = N_NEIGHBORS
scvi_workflow.EMBED_KEY = EMBED_KEY
scvi_workflow.CLUSTER_KEY = CLUSTER_KEY
scvi_workflow.METRIC_BATCH_KEY = METRIC_BATCH_KEY
scvi_workflow.METRIC_LABEL_KEY = METRIC_LABEL_KEY

scvi_workflow.USE_BAMI = "BAMI" in SELECTED_METRICS
scvi_workflow.USE_CASW = "CASW" in SELECTED_METRICS
scvi_workflow.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
scvi_workflow.USE_TRAJ = "TRAJ" in SELECTED_METRICS
scvi_workflow.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
scvi_workflow.USE_BRAS = "BRAS" in SELECTED_METRICS
scvi_workflow.USE_KBET = "KBET" in SELECTED_METRICS
scvi_workflow.USE_CPCR = "CPCR" in SELECTED_METRICS

scvi_workflow.validate_configuration(SELECTED_METRICS)
scvi_workflow.validate_dataset_contents()

pd.Series(
    {
        "optimizer": str(OPTIMIZER_PATH),
        "scvi_version": scvi_workflow.scvi.__version__,
        "cuda_available": torch.cuda.is_available(),
    },
    name="preflight",
)

Dataset preflight: n_obs=84619 n_batches=2 n_labels=8 counts_layer=True
CPCR preflight: eligible_labels=8

optimizer         /ubc/cs/research/beaver/projects/Single-cell-i...
scvi_version                                                  1.3.3
cuda_available                                                 True
Name: preflight, dtype: object

In [4]:
constructor_signature = inspect.signature(
    scvi_workflow.scvi.model.SCVI.__init__
)
training_signature = inspect.signature(
    scvi_workflow.scvi.train.TrainingPlan.__init__
)
assert scvi_workflow.scvi.__version__ == "1.3.3"
assert constructor_signature.parameters["n_latent"].default == 10
assert constructor_signature.parameters["n_hidden"].default == 128
assert constructor_signature.parameters["n_layers"].default == 1
assert constructor_signature.parameters["dropout_rate"].default == 0.1
assert training_signature.parameters["lr"].default == 0.001

SCVI_PARAMS = {'n_latent': 10, 'n_hidden': 128, 'n_layers': 1, 'dropout_rate': 0.1, 'lr': 0.001}
assert tuple(SCVI_PARAMS) == ('n_latent', 'n_hidden', 'n_layers', 'dropout_rate', 'lr')

pd.Series(
    {
        **SCVI_PARAMS,
        "gene_likelihood": "zinb",
        "dispersion": "gene",
        "latent_distribution": "normal",
        "early_stopping": True,
        "max_epochs": MAX_EPOCHS,
        "use_hvg": USE_HVG,
        "n_top_hvg": N_TOP_HVG,
    },
    name="default_setting",
)

def run_scvi_setting(adata, seed):
    return scvi_workflow.run_scvi(
        adata,
        n_latent=SCVI_PARAMS["n_latent"],
        n_hidden=SCVI_PARAMS["n_hidden"],
        n_layers=SCVI_PARAMS["n_layers"],
        dropout_rate=SCVI_PARAMS["dropout_rate"],
        lr=SCVI_PARAMS["lr"],
        seed=int(seed),
    )

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    result = scvi_workflow.compute_joint_metrics(adata_raw, adata_int)
    if tuple(result) != (
        *SELECTED_METRICS,
        "bio_score",
        "batch_score",
        "joint_score",
    ):
        raise ValueError(f"Unexpected metric result keys: {tuple(result)}")
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_scvi_setting(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

[rank: 0] Seed set to 0

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

You are using a CUDA device ('NVIDIA L40S') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.82s/it]

100%|██████████| 2/2 [00:06<00:00,  2.90s/it]

100%|██████████| 2/2 [00:06<00:00,  3.04s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.791708442413233

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8254933356446283

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8076180804212583

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8058076663314243

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8025449209626162

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7850528746756349

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7808657717477351

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7777033570868186

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7755615497821279

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.773229226942287

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-08-18 14:47:18,859:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8254933356446283
BRAS...

seed           0.000000
BAMI           0.825493
CASW           0.621871
SCGRAPHM       0.721818
BRAS           0.828683
KBET           0.334861
CPCR           0.001755
bio_score      0.723061
batch_score    0.388433
joint_score    0.589210
dtype: float64

===== seed 1 =====

[rank: 0] Seed set to 1

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.81s/it]

100%|██████████| 2/2 [00:06<00:00,  2.88s/it]

100%|██████████| 2/2 [00:06<00:00,  3.02s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7711609552774881

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8405048049061993

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8183680721073421

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8064584793829846

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7933077614851116

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7912353481765612

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7895113298824279

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7852918060527718

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.77989390436967

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7790321792535163

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8405048049061993
BRAS...

seed           1.000000
BAMI           0.840505
CASW           0.627034
SCGRAPHM       0.602255
BRAS           0.826289
KBET           0.315150
CPCR           0.000257
bio_score      0.689931
batch_score    0.380565
joint_score    0.566185
dtype: float64

===== seed 2 =====

[rank: 0] Seed set to 2

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.86s/it]

100%|██████████| 2/2 [00:06<00:00,  2.91s/it]

100%|██████████| 2/2 [00:06<00:00,  3.05s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.804560452133964

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.814142595264483

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8075547112969891

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7972175687859872

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7880956842261462

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7843999587175408

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7806982890881855

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7785263720337631

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7756893337848519

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7723744054181578

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.814142595264483
BRAS...

seed           2.000000
BAMI           0.814143
CASW           0.622572
SCGRAPHM       0.691986
BRAS           0.833112
KBET           0.305531
CPCR           0.001805
bio_score      0.709567
batch_score    0.380150
joint_score    0.577800
dtype: float64

===== seed 3 =====

[rank: 0] Seed set to 3

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()

GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.88s/it]

100%|██████████| 2/2 [00:06<00:00,  2.94s/it]

100%|██████████| 2/2 [00:06<00:00,  3.08s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8083691805685423

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.838448839761987

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8260246707344436

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8179708773229105

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7908674408960316

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7869323905164755

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7805325588491432

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.774129147081156

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7753668761490141

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7708306454788969

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.838448839761987
BRAS...

seed           3.000000
BAMI           0.838449
CASW           0.626155
SCGRAPHM       0.714228
BRAS           0.844324
KBET           0.344732
CPCR           0.003206
bio_score      0.726277
batch_score    0.397421
joint_score    0.594735
dtype: float64

===== seed 4 =====

[rank: 0] Seed set to 4

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:04<00:04,  4.19s/it]

100%|██████████| 2/2 [00:06<00:00,  3.16s/it]

100%|██████████| 2/2 [00:06<00:00,  3.31s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8148598301618183

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8245721427193017

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7974072950790225

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7912560324503737

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7972369145972567

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7950453627863888

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.791604619549551

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7755222858860105

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7695248300866533

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7689853170291253

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8245721427193017
BRAS...

seed           4.000000
BAMI           0.824572
CASW           0.625614
SCGRAPHM       0.650177
BRAS           0.839333
KBET           0.361931
CPCR           0.005679
bio_score      0.700121
batch_score    0.402314
joint_score    0.580998
dtype: float64

===== seed 5 =====

[rank: 0] Seed set to 5

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.91s/it]

100%|██████████| 2/2 [00:06<00:00,  2.90s/it]

100%|██████████| 2/2 [00:06<00:00,  3.05s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8029771467599206

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.806656146097099

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7943637659896555

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8032878590294479

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.795913310334229

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7921401990597725

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7880785909143467

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7876831876932535

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7731074143107162

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7782513113589562

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.806656146097099
BRAS...

seed           5.000000
BAMI           0.806656
CASW           0.625214
SCGRAPHM       0.679569
BRAS           0.840681
KBET           0.365309
CPCR           0.002011
bio_score      0.703813
batch_score    0.402667
joint_score    0.583355
dtype: float64

===== seed 6 =====

[rank: 0] Seed set to 6

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.94s/it]

100%|██████████| 2/2 [00:06<00:00,  2.97s/it]

100%|██████████| 2/2 [00:06<00:00,  3.12s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7926939646826443

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8174606400088792

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8149533188627168

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7933963049430225

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.802811162062454

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7945168568771673

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7881278322656518

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7819045832370247

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7778513911663125

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.776317390276109

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8174606400088792
BRAS...

seed           6.000000
BAMI           0.817461
CASW           0.620137
SCGRAPHM       0.678378
BRAS           0.839204
KBET           0.331359
CPCR           0.004451
bio_score      0.705325
batch_score    0.391671
joint_score    0.579864
dtype: float64

===== seed 7 =====

[rank: 0] Seed set to 7

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [01:46<01:46, 106.06s/it]

100%|██████████| 2/2 [02:41<00:00, 76.25s/it]

100%|██████████| 2/2 [02:41<00:00, 80.73s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8003792476987575

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8171647049430378

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8107061477891052

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8007964526828795

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7949137844289634

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7878387802795555

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7833343916263262

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7788541875393016

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7774921113621817

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7747929720860361

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8171647049430378
BRAS...

seed           7.000000
BAMI           0.817165
CASW           0.624317
SCGRAPHM       0.709250
BRAS           0.827980
KBET           0.324315
CPCR           0.003152
bio_score      0.716911
batch_score    0.385149
joint_score    0.584206
dtype: float64

===== seed 8 =====

[rank: 0] Seed set to 8

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.96s/it]

100%|██████████| 2/2 [00:06<00:00,  2.93s/it]

100%|██████████| 2/2 [00:06<00:00,  3.09s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7761780354381008

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7993844547673881

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7951048224189737

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7961934998437407

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7931277185653762

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.783540630954853

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7830470462293083

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.779450296080048

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7787002560777754

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7750280985279674

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7993844547673881
BRAS...

seed           8.000000
BAMI           0.799384
CASW           0.626700
SCGRAPHM       0.708217
BRAS           0.830368
KBET           0.327421
CPCR           0.002222
bio_score      0.711434
batch_score    0.386671
joint_score    0.581529
dtype: float64

===== seed 9 =====

[rank: 0] Seed set to 9

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
GPU available: True (cuda), used: True

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.

Training:   0%|          | 0/400 [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_epochs=400` reached.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/scvi_py310/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.
scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:03<00:03,  3.91s/it]

100%|██████████| 2/2 [00:06<00:00,  2.94s/it]

100%|██████████| 2/2 [00:06<00:00,  3.09s/it]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res_df = pd.concat([res_df, _row_df], axis=0, sort=False)
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts = adata.obs.groupby(label_key).agg(

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8078572665344677

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8010920228241999

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8126177602005084

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7951062841956406

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7904602483137737

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7856784453529391

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7784140670630163

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7774283563853099

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7725628547234294

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7694550718580795

optimised clustering against scvi_metric_label
optimal cluster resolution: 0.6
optimal score: 0.8126177602005084
BRAS...

seed           9.000000
BAMI           0.812618
CASW           0.624216
SCGRAPHM       0.639705
BRAS           0.824654
KBET           0.302050
CPCR           0.001137
bio_score      0.692180
batch_score    0.375947
joint_score    0.565687
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.825493,0.621871,0.721818,0.828683,0.334861,0.001755,0.723061,0.388433,0.589210
1,1,0.840505,0.627034,0.602255,0.826289,0.315150,0.000257,0.689931,0.380565,0.566185
2,2,0.814143,0.622572,0.691986,0.833112,0.305531,0.001805,0.709567,0.380150,0.577800
3,3,0.838449,0.626155,0.714228,0.844324,0.344732,0.003206,0.726277,0.397421,0.594735
4,4,0.824572,0.625614,0.650177,0.839333,0.361931,0.005679,0.700121,0.402314,0.580998
5,5,0.806656,0.625214,0.679569,0.840681,0.365309,0.002011,0.703813,0.402667,0.583355
6,6,0.817461,0.620137,0.678378,0.839204,0.331359,0.004451,0.705325,0.391671,0.579864
7,7,0.817165,0.624317,0.709250,0.827980,0.324315,0.003152,0.716911,0.385149,0.584206
8,8,0.799384,0.626700,0.708217,0.830368,0.327421,0.002222,0.711434,0.386671,0.581529
9,9,0.812618,0.624216,0.639705,0.824654,0.302050,0.001137,0.692180,0.375947,0.565687

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.819645  0.012317  0.799384  0.840505
CASW         0.624383  0.002131  0.620137  0.627034
SCGRAPHM     0.679558  0.036434  0.602255  0.721818
BRAS         0.833463  0.006551  0.824654  0.844324
KBET         0.331266  0.020328  0.302050  0.365309
CPCR         0.002568  0.001518  0.000257  0.005679
bio_score    0.707862  0.011480  0.689931  0.726277
batch_score  0.389099  0.008845  0.375947  0.402667
joint_score  0.580357  0.008565  0.565687  0.594735