# LIGER best - scib_sim1

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'scib_sim1'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'Batch'
LABEL_KEY = 'Group'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'scib_sim1'
assert BATCH_KEY == 'Batch'
assert LABEL_KEY == 'Group'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                              scib_sim1
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                Batch
label_key                                                Group
metrics      [BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=12097 n_batches=6 n_labels=7
ISOLISI preflight: min_batch_coverage=2 isolated_labels=['Group7']
CPCR preflight: eligible_labels=7

In [4]:
OPTUNA_STUDY_NAME = 'liger_scib_sim1_joint_expanded_metrics_scgraphm_v1'
OPTUNA_BEST_TRIAL = 74
OPTUNA_BEST_VALUE = 0.8738907224919364
OPTUNA_BEST_PARAMS = {'k': 26, 'value_lambda': 5.474813020467679}

LIGER_BEST_ARGS = {
    "k": OPTUNA_BEST_PARAMS["k"],
    "value_lambda": OPTUNA_BEST_PARAMS["value_lambda"],
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_best(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_BEST_ARGS["k"],
        lam=LIGER_BEST_ARGS["value_lambda"],
        max_iterations=LIGER_BEST_ARGS["max_iters"],
        mode=LIGER_BEST_ARGS["mode"],
        layer=LIGER_BEST_ARGS["layer"],
        seed=seed,
    )


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **LIGER_BEST_ARGS,
    },
    name="best_setting",
)

study           liger_scib_sim1_joint_expanded_metrics_scgraph...
best_trial                                                     74
best_value                                               0.873891
k                                                              26
value_lambda                                             5.474813
max_iters                                                      30
mode                                                         core
layer                                                      counts
Name: best_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:08<04:06,  8.50s/it]

  7%|▋         | 2/30 [00:19<04:36,  9.88s/it]

 10%|█         | 3/30 [00:28<04:16,  9.50s/it]

 13%|█▎        | 4/30 [00:37<03:58,  9.18s/it]

 17%|█▋        | 5/30 [00:45<03:44,  8.97s/it]

 20%|██        | 6/30 [00:53<03:29,  8.73s/it]

 23%|██▎       | 7/30 [01:02<03:17,  8.58s/it]

 27%|██▋       | 8/30 [01:10<03:05,  8.42s/it]

 30%|███       | 9/30 [01:18<02:54,  8.31s/it]

 33%|███▎      | 10/30 [01:26<02:45,  8.26s/it]

 37%|███▋      | 11/30 [01:35<02:43,  8.62s/it]

 40%|████      | 12/30 [01:44<02:32,  8.45s/it]

 43%|████▎     | 13/30 [01:52<02:21,  8.31s/it]

 47%|████▋     | 14/30 [02:01<02:16,  8.55s/it]

 50%|█████     | 15/30 [02:09<02:08,  8.57s/it]

 53%|█████▎    | 16/30 [02:20<02:07,  9.11s/it]

 57%|█████▋    | 17/30 [02:29<01:59,  9.16s/it]

 60%|██████    | 18/30 [02:40<01:56,  9.68s/it]

 63%|██████▎   | 19/30 [02:49<01:46,  9.70s/it]

 67%|██████▋   | 20/30 [02:59<01:36,  9.65s/it]

 70%|███████   | 21/30 [03:12<01:35, 10.61s/it]

 73%|███████▎  | 22/30 [03:22<01:22, 10.32s/it]

 77%|███████▋  | 23/30 [03:31<01:09,  9.97s/it]

 80%|████████  | 24/30 [03:40<00:59,  9.89s/it]

 83%|████████▎ | 25/30 [03:49<00:47,  9.49s/it]

 87%|████████▋ | 26/30 [03:57<00:36,  9.07s/it]

 90%|█████████ | 27/30 [04:05<00:26,  8.76s/it]

 93%|█████████▎| 28/30 [04:13<00:16,  8.45s/it]

 97%|█████████▋| 29/30 [04:21<00:08,  8.39s/it]

100%|██████████| 30/30 [04:32<00:00,  9.09s/it]

100%|██████████| 30/30 [04:32<00:00,  9.08s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.13it/s]

 33%|███▎      | 2/6 [00:00<00:01,  3.74it/s]

 50%|█████     | 3/6 [00:00<00:00,  3.56it/s]

 67%|██████▋   | 4/6 [00:01<00:00,  3.54it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  3.73it/s]

100%|██████████| 6/6 [00:01<00:00,  4.36it/s]

100%|██████████| 6/6 [00:01<00:00,  3.97it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.9901226414403427

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9901226414403427

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9901226414403427

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9869482297661183

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.963035723707521

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9632215131840143

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9419531667394001

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9281671012365089

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9145038417033196

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9042466932351563

WARNING:2026-07-23 18:35:24,667:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9901226414403427
BRAS...

seed           1.000000
BAMI           0.990123
CASW           0.677408
SCGRAPHM       0.679922
ISOLISI        1.000000
BRAS           0.958874
KBET           0.839650
CPCR           0.989772
bio_score      0.836863
batch_score    0.929432
joint_score    0.873891
dtype: float64

===== seed 2 =====

Removing 28 genes not expressing in Batch1.

Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:07<03:35,  7.43s/it]

  7%|▋         | 2/30 [00:18<04:21,  9.35s/it]

 10%|█         | 3/30 [00:30<04:46, 10.60s/it]

 13%|█▎        | 4/30 [00:39<04:24, 10.19s/it]

 17%|█▋        | 5/30 [00:50<04:16, 10.28s/it]

 20%|██        | 6/30 [00:59<03:59, 10.00s/it]

 23%|██▎       | 7/30 [01:08<03:44,  9.78s/it]

 27%|██▋       | 8/30 [01:18<03:32,  9.66s/it]

 30%|███       | 9/30 [01:27<03:22,  9.63s/it]

 33%|███▎      | 10/30 [01:36<03:08,  9.40s/it]

 37%|███▋      | 11/30 [01:45<02:53,  9.14s/it]

 40%|████      | 12/30 [01:53<02:40,  8.94s/it]

 43%|████▎     | 13/30 [02:01<02:26,  8.60s/it]

 47%|████▋     | 14/30 [02:09<02:16,  8.50s/it]

 50%|█████     | 15/30 [02:18<02:09,  8.65s/it]

 53%|█████▎    | 16/30 [02:28<02:03,  8.84s/it]

 57%|█████▋    | 17/30 [02:37<01:54,  8.82s/it]

 60%|██████    | 18/30 [02:46<01:46,  8.89s/it]

 63%|██████▎   | 19/30 [02:54<01:37,  8.83s/it]

 67%|██████▋   | 20/30 [03:03<01:27,  8.80s/it]

 70%|███████   | 21/30 [03:13<01:22,  9.15s/it]

 73%|███████▎  | 22/30 [03:22<01:13,  9.21s/it]

 77%|███████▋  | 23/30 [03:31<01:02,  8.98s/it]

 80%|████████  | 24/30 [03:43<01:00, 10.08s/it]

 83%|████████▎ | 25/30 [03:56<00:54, 10.91s/it]

 87%|████████▋ | 26/30 [04:07<00:43, 10.87s/it]

 90%|█████████ | 27/30 [04:16<00:31, 10.41s/it]

 93%|█████████▎| 28/30 [04:27<00:20, 10.44s/it]

 97%|█████████▋| 29/30 [04:36<00:10, 10.11s/it]

100%|██████████| 30/30 [04:45<00:00,  9.81s/it]

100%|██████████| 30/30 [04:45<00:00,  9.53s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.83it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.72it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.06it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  3.97it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.23it/s]

100%|██████████| 6/6 [00:01<00:00,  4.88it/s]

100%|██████████| 6/6 [00:01<00:00,  4.53it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.991678195260396

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9906039932605971

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9906039932605971

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9906039932605971

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9906039932605971

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9672245684007154

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9664107755034305

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9434885900818196

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9179408905975932

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.887077626655867

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.991678195260396
BRAS...
seed           2.000000
BAMI           0.991678
CASW           0.637789
SCGRAPHM       0.469387
ISOLISI        1.000000
BRAS           0.957513
KBET           0.824589
CPCR           0.991553
bio_score      0.774714
batch_score    0.924552
joint_score    0.834649
dtype: float64

===== seed 3 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:18,  6.84s/it]

  7%|▋         | 2/30 [00:15<03:46,  8.10s/it]

 10%|█         | 3/30 [00:25<03:59,  8.85s/it]

 13%|█▎        | 4/30 [00:35<04:00,  9.24s/it]

 17%|█▋        | 5/30 [00:45<04:01,  9.66s/it]

 20%|██        | 6/30 [00:55<03:54,  9.75s/it]

 23%|██▎       | 7/30 [01:06<03:53, 10.15s/it]

 27%|██▋       | 8/30 [01:18<03:52, 10.58s/it]

 30%|███       | 9/30 [01:28<03:41, 10.55s/it]

 33%|███▎      | 10/30 [01:38<03:25, 10.28s/it]

 37%|███▋      | 11/30 [01:48<03:12, 10.11s/it]

 40%|████      | 12/30 [01:59<03:08, 10.50s/it]

 43%|████▎     | 13/30 [02:09<02:57, 10.45s/it]

 47%|████▋     | 14/30 [02:17<02:35,  9.73s/it]

 50%|█████     | 15/30 [02:26<02:21,  9.44s/it]

 53%|█████▎    | 16/30 [02:34<02:06,  9.03s/it]

 57%|█████▋    | 17/30 [02:42<01:52,  8.69s/it]

 60%|██████    | 18/30 [02:51<01:44,  8.75s/it]

 63%|██████▎   | 19/30 [02:59<01:33,  8.54s/it]

 67%|██████▋   | 20/30 [03:08<01:25,  8.58s/it]

 70%|███████   | 21/30 [03:16<01:17,  8.58s/it]

 73%|███████▎  | 22/30 [03:25<01:08,  8.56s/it]

 77%|███████▋  | 23/30 [03:34<01:00,  8.61s/it]

 80%|████████  | 24/30 [03:43<00:53,  8.87s/it]

 83%|████████▎ | 25/30 [03:55<00:48,  9.70s/it]

 87%|████████▋ | 26/30 [04:05<00:39,  9.76s/it]

 90%|█████████ | 27/30 [04:14<00:28,  9.54s/it]

 93%|█████████▎| 28/30 [04:23<00:19,  9.59s/it]

 97%|█████████▋| 29/30 [04:32<00:09,  9.36s/it]

100%|██████████| 30/30 [04:42<00:00,  9.38s/it]

100%|██████████| 30/30 [04:42<00:00,  9.40s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:02,  2.26it/s]

 33%|███▎      | 2/6 [00:00<00:01,  2.82it/s]

 50%|█████     | 3/6 [00:01<00:01,  2.70it/s]

 67%|██████▋   | 4/6 [00:01<00:00,  2.75it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  2.97it/s]

100%|██████████| 6/6 [00:01<00:00,  3.33it/s]

100%|██████████| 6/6 [00:01<00:00,  3.00it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9512310462920053

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9498886779473318

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9498886779473318

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9483384467316047

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9483384467316047

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9260749126379816

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9037706942846643

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9039526238894545

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8803756694565408

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8694215870106096

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9512310462920053
BRAS...
seed           3.000000
BAMI           0.951231
CASW           0.645359
SCGRAPHM       0.470487
ISOLISI        1.000000
BRAS           0.925093
KBET           0.712429
CPCR           0.949283
bio_score      0.766769
batch_score    0.862268
joint_score    0.804969
dtype: float64

===== seed 4 =====

Removing 28 genes not expressing in Batch1.

Removing 26 genes not expressing in Batch2.
Removing 28 genes not expressing in Batch3.

Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')
Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:07,  6.48s/it]

  7%|▋         | 2/30 [00:17<04:14,  9.09s/it]

 10%|█         | 3/30 [00:27<04:19,  9.60s/it]

 13%|█▎        | 4/30 [00:38<04:24, 10.18s/it]

 17%|█▋        | 5/30 [00:51<04:35, 11.03s/it]

 20%|██        | 6/30 [01:02<04:24, 11.04s/it]

 23%|██▎       | 7/30 [01:10<03:56, 10.28s/it]

 27%|██▋       | 8/30 [01:19<03:33,  9.72s/it]

 30%|███       | 9/30 [01:28<03:20,  9.53s/it]

 33%|███▎      | 10/30 [01:37<03:09,  9.47s/it]

 37%|███▋      | 11/30 [01:46<02:56,  9.29s/it]

 40%|████      | 12/30 [01:57<02:53,  9.61s/it]

 43%|████▎     | 13/30 [02:09<02:57, 10.42s/it]

 47%|████▋     | 14/30 [02:19<02:46, 10.38s/it]

 50%|█████     | 15/30 [02:28<02:30, 10.03s/it]

 53%|█████▎    | 16/30 [02:38<02:18,  9.89s/it]

 57%|█████▋    | 17/30 [02:49<02:14, 10.34s/it]

 60%|██████    | 18/30 [03:00<02:06, 10.51s/it]

 63%|██████▎   | 19/30 [03:10<01:51, 10.18s/it]

 67%|██████▋   | 20/30 [03:20<01:43, 10.31s/it]

 70%|███████   | 21/30 [03:29<01:28,  9.88s/it]

 73%|███████▎  | 22/30 [03:38<01:16,  9.51s/it]

 77%|███████▋  | 23/30 [03:47<01:06,  9.43s/it]

 80%|████████  | 24/30 [03:58<00:59,  9.92s/it]

 83%|████████▎ | 25/30 [04:07<00:48,  9.66s/it]

 87%|████████▋ | 26/30 [04:16<00:37,  9.44s/it]

 90%|█████████ | 27/30 [04:26<00:28,  9.45s/it]

 93%|█████████▎| 28/30 [04:34<00:18,  9.23s/it]

 97%|█████████▋| 29/30 [04:44<00:09,  9.49s/it]

100%|██████████| 30/30 [04:54<00:00,  9.59s/it]

100%|██████████| 30/30 [04:54<00:00,  9.83s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.25it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.48it/s]

 50%|█████     | 3/6 [00:00<00:00,  3.97it/s]

 67%|██████▋   | 4/6 [00:01<00:00,  3.87it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.09it/s]

100%|██████████| 6/6 [00:01<00:00,  4.75it/s]

100%|██████████| 6/6 [00:01<00:00,  4.37it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9883785446383309

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9883785446383309

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9875391037174768

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9856058776339996

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9846726797048249

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9613843764778879

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9495638308638438

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9453255102988379

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9001962315736126

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8986187752686373

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9883785446383309
BRAS...
seed           4.000000
BAMI           0.988379
CASW           0.631450
SCGRAPHM       0.369704
ISOLISI        1.000000
BRAS           0.960996
KBET           0.804379
CPCR           0.990186
bio_score      0.747383
batch_score    0.918520
joint_score    0.815838
dtype: float64

===== seed 5 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:08<03:55,  8.12s/it]

  7%|▋         | 2/30 [00:17<04:13,  9.06s/it]

 10%|█         | 3/30 [00:28<04:25,  9.83s/it]

 13%|█▎        | 4/30 [00:40<04:35, 10.58s/it]

 17%|█▋        | 5/30 [00:53<04:44, 11.40s/it]

 20%|██        | 6/30 [01:05<04:41, 11.73s/it]

 23%|██▎       | 7/30 [01:15<04:19, 11.29s/it]

 27%|██▋       | 8/30 [01:26<04:02, 11.02s/it]

 30%|███       | 9/30 [01:36<03:42, 10.59s/it]

 33%|███▎      | 10/30 [01:45<03:27, 10.39s/it]

 37%|███▋      | 11/30 [01:54<03:05,  9.74s/it]

 40%|████      | 12/30 [02:02<02:48,  9.34s/it]

 43%|████▎     | 13/30 [02:15<02:55, 10.29s/it]

 47%|████▋     | 14/30 [02:27<02:55, 10.99s/it]

 50%|█████     | 15/30 [02:39<02:46, 11.13s/it]

 53%|█████▎    | 16/30 [02:52<02:43, 11.71s/it]

 57%|█████▋    | 17/30 [03:04<02:35, 11.97s/it]

 60%|██████    | 18/30 [03:15<02:20, 11.68s/it]

 63%|██████▎   | 19/30 [03:27<02:08, 11.72s/it]

 67%|██████▋   | 20/30 [03:38<01:54, 11.46s/it]

 70%|███████   | 21/30 [03:50<01:45, 11.69s/it]

 73%|███████▎  | 22/30 [04:03<01:36, 12.06s/it]

 77%|███████▋  | 23/30 [04:16<01:26, 12.32s/it]

 80%|████████  | 24/30 [04:27<01:11, 11.95s/it]

 83%|████████▎ | 25/30 [04:38<00:58, 11.69s/it]

 87%|████████▋ | 26/30 [04:49<00:45, 11.43s/it]

 90%|█████████ | 27/30 [04:58<00:32, 10.81s/it]

 93%|█████████▎| 28/30 [05:09<00:21, 10.63s/it]

 97%|█████████▋| 29/30 [05:20<00:10, 10.91s/it]

100%|██████████| 30/30 [05:38<00:00, 12.92s/it]

100%|██████████| 30/30 [05:38<00:00, 11.28s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  2.74it/s]

 33%|███▎      | 2/6 [00:00<00:01,  2.90it/s]

 50%|█████     | 3/6 [00:01<00:01,  2.39it/s]

 67%|██████▋   | 4/6 [00:01<00:00,  2.31it/s]

 83%|████████▎ | 5/6 [00:02<00:00,  2.31it/s]

100%|██████████| 6/6 [00:02<00:00,  2.66it/s]

100%|██████████| 6/6 [00:02<00:00,  2.54it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9935192733126703

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9935192733126703

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9935192733126703

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9892673042071208

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9891794174105822

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.965354896147443

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.964889656296062

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9423368628833991

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9062387764298131

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.9027314658457406

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9935192733126703
BRAS...
seed           5.000000
BAMI           0.993519
CASW           0.658597
SCGRAPHM       0.717419
ISOLISI        1.000000
BRAS           0.964788
KBET           0.804383
CPCR           0.988634
bio_score      0.842384
batch_score    0.919268
joint_score    0.873137
dtype: float64

===== seed 6 =====

Removing 28 genes not expressing in Batch1.

Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.

Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')
Removing 27 genes not expressing in Batch5.

Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:13,  6.68s/it]

  7%|▋         | 2/30 [00:14<03:33,  7.63s/it]

 10%|█         | 3/30 [00:27<04:27,  9.91s/it]

 13%|█▎        | 4/30 [00:40<04:47, 11.07s/it]

 17%|█▋        | 5/30 [00:49<04:15, 10.20s/it]

 20%|██        | 6/30 [00:57<03:49,  9.55s/it]

 23%|██▎       | 7/30 [01:05<03:28,  9.07s/it]

 27%|██▋       | 8/30 [01:13<03:15,  8.89s/it]

 30%|███       | 9/30 [01:22<03:02,  8.70s/it]

 33%|███▎      | 10/30 [01:30<02:51,  8.58s/it]

 37%|███▋      | 11/30 [01:38<02:40,  8.45s/it]

 40%|████      | 12/30 [01:46<02:30,  8.34s/it]

 43%|████▎     | 13/30 [01:55<02:21,  8.31s/it]

 47%|████▋     | 14/30 [02:03<02:11,  8.21s/it]

 50%|█████     | 15/30 [02:11<02:03,  8.23s/it]

 53%|█████▎    | 16/30 [02:19<01:54,  8.16s/it]

 57%|█████▋    | 17/30 [02:27<01:47,  8.28s/it]

 60%|██████    | 18/30 [02:36<01:39,  8.25s/it]

 63%|██████▎   | 19/30 [02:44<01:29,  8.16s/it]

 67%|██████▋   | 20/30 [02:52<01:21,  8.15s/it]

 70%|███████   | 21/30 [03:00<01:13,  8.15s/it]

 73%|███████▎  | 22/30 [03:08<01:05,  8.14s/it]

 77%|███████▋  | 23/30 [03:16<00:56,  8.12s/it]

 80%|████████  | 24/30 [03:25<00:50,  8.49s/it]

 83%|████████▎ | 25/30 [03:33<00:41,  8.34s/it]

 87%|████████▋ | 26/30 [03:41<00:33,  8.29s/it]

 90%|█████████ | 27/30 [03:50<00:24,  8.22s/it]

 93%|█████████▎| 28/30 [03:58<00:16,  8.23s/it]

 97%|█████████▋| 29/30 [04:06<00:08,  8.38s/it]

100%|██████████| 30/30 [04:15<00:00,  8.49s/it]

100%|██████████| 30/30 [04:15<00:00,  8.52s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.10it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.36it/s]

 50%|█████     | 3/6 [00:00<00:00,  3.96it/s]

 67%|██████▋   | 4/6 [00:01<00:00,  3.76it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.09it/s]

100%|██████████| 6/6 [00:01<00:00,  4.80it/s]

100%|██████████| 6/6 [00:01<00:00,  4.35it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8686408180281917

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8686408180281917

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8667218157380475

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.8666489511512301

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8666489511512301

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.8375805809571439

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8068601495738236

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8010553170643805

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8011814179877288

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7668814284733165

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8686408180281917
BRAS...
seed           6.000000
BAMI           0.868641
CASW           0.633012
SCGRAPHM       0.465446
ISOLISI        0.966426
BRAS           0.875442
KBET           0.706913
CPCR           0.980287
bio_score      0.733381
batch_score    0.854214
joint_score    0.781714
dtype: float64

===== seed 7 =====

Removing 28 genes not expressing in Batch1.

Removing 26 genes not expressing in Batch2.
Removing 28 genes not expressing in Batch3.

Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')
Removing 27 genes not expressing in Batch5.

Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:04,  6.37s/it]

  7%|▋         | 2/30 [00:16<04:07,  8.85s/it]

 10%|█         | 3/30 [00:25<04:00,  8.91s/it]

 13%|█▎        | 4/30 [00:34<03:51,  8.90s/it]

 17%|█▋        | 5/30 [00:43<03:41,  8.85s/it]

 20%|██        | 6/30 [00:52<03:32,  8.84s/it]

 23%|██▎       | 7/30 [01:00<03:18,  8.63s/it]

 27%|██▋       | 8/30 [01:08<03:06,  8.49s/it]

 30%|███       | 9/30 [01:17<02:57,  8.47s/it]

 33%|███▎      | 10/30 [01:25<02:47,  8.37s/it]

 37%|███▋      | 11/30 [01:33<02:37,  8.30s/it]

 40%|████      | 12/30 [01:41<02:29,  8.29s/it]

 43%|████▎     | 13/30 [01:50<02:22,  8.39s/it]

 47%|████▋     | 14/30 [01:58<02:13,  8.34s/it]

 50%|█████     | 15/30 [02:06<02:04,  8.29s/it]

 53%|█████▎    | 16/30 [02:15<01:55,  8.28s/it]

 57%|█████▋    | 17/30 [02:23<01:47,  8.25s/it]

 60%|██████    | 18/30 [02:31<01:38,  8.25s/it]

 63%|██████▎   | 19/30 [02:39<01:30,  8.21s/it]

 67%|██████▋   | 20/30 [02:48<01:23,  8.31s/it]

 70%|███████   | 21/30 [02:59<01:24,  9.35s/it]

 73%|███████▎  | 22/30 [03:08<01:11,  8.97s/it]

 77%|███████▋  | 23/30 [03:18<01:06,  9.44s/it]

 80%|████████  | 24/30 [03:28<00:58,  9.70s/it]

 83%|████████▎ | 25/30 [03:41<00:53, 10.72s/it]

 87%|████████▋ | 26/30 [03:50<00:39,  9.95s/it]

 90%|█████████ | 27/30 [03:58<00:28,  9.41s/it]

 93%|█████████▎| 28/30 [04:06<00:18,  9.00s/it]

 97%|█████████▋| 29/30 [04:14<00:08,  8.72s/it]

100%|██████████| 30/30 [04:22<00:00,  8.54s/it]

100%|██████████| 30/30 [04:22<00:00,  8.75s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.24it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.32it/s]

 50%|█████     | 3/6 [00:00<00:00,  3.81it/s]

 67%|██████▋   | 4/6 [00:01<00:00,  3.66it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  3.99it/s]

100%|██████████| 6/6 [00:01<00:00,  4.54it/s]

100%|██████████| 6/6 [00:01<00:00,  4.20it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9738805292470787

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9740165972869608

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.969972321545946

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9698976176766221

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9690036972680373

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9482094383559684

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9329924743671755

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9115888881690253

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9026888563810649

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8887704107874772

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.9740165972869608
BRAS...
seed           7.000000
BAMI           0.974017
CASW           0.659325
SCGRAPHM       0.520579
ISOLISI        1.000000
BRAS           0.943565
KBET           0.825628
CPCR           0.966548
bio_score      0.788480
batch_score    0.911913
joint_score    0.837853
dtype: float64

===== seed 8 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:10<04:57, 10.25s/it]

  7%|▋         | 2/30 [00:19<04:33,  9.76s/it]

 10%|█         | 3/30 [00:29<04:21,  9.68s/it]

 13%|█▎        | 4/30 [00:38<04:05,  9.44s/it]

 17%|█▋        | 5/30 [00:46<03:48,  9.14s/it]

 20%|██        | 6/30 [00:55<03:33,  8.91s/it]

 23%|██▎       | 7/30 [01:03<03:20,  8.71s/it]

 27%|██▋       | 8/30 [01:11<03:08,  8.58s/it]

 30%|███       | 9/30 [01:20<02:58,  8.51s/it]

 33%|███▎      | 10/30 [01:29<02:55,  8.76s/it]

 37%|███▋      | 11/30 [01:38<02:49,  8.90s/it]

 40%|████      | 12/30 [01:47<02:39,  8.88s/it]

 43%|████▎     | 13/30 [01:56<02:30,  8.88s/it]

 47%|████▋     | 14/30 [02:05<02:22,  8.88s/it]

 50%|█████     | 15/30 [02:13<02:09,  8.66s/it]

 53%|█████▎    | 16/30 [02:22<02:02,  8.78s/it]

 57%|█████▋    | 17/30 [02:31<01:53,  8.70s/it]

 60%|██████    | 18/30 [02:40<01:45,  8.79s/it]

 63%|██████▎   | 19/30 [02:49<01:38,  9.00s/it]

 67%|██████▋   | 20/30 [02:58<01:29,  8.98s/it]

 70%|███████   | 21/30 [03:08<01:22,  9.17s/it]

 73%|███████▎  | 22/30 [03:17<01:12,  9.10s/it]

 77%|███████▋  | 23/30 [03:27<01:05,  9.41s/it]

 80%|████████  | 24/30 [03:36<00:56,  9.41s/it]

 83%|████████▎ | 25/30 [03:45<00:45,  9.19s/it]

 87%|████████▋ | 26/30 [03:53<00:35,  8.93s/it]

 90%|█████████ | 27/30 [04:02<00:26,  8.76s/it]

 93%|█████████▎| 28/30 [04:11<00:17,  8.97s/it]

 97%|█████████▋| 29/30 [04:22<00:09,  9.48s/it]

100%|██████████| 30/30 [04:30<00:00,  9.22s/it]

100%|██████████| 30/30 [04:30<00:00,  9.03s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  3.81it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.05it/s]

 50%|█████     | 3/6 [00:00<00:00,  3.80it/s]

 67%|██████▋   | 4/6 [00:01<00:00,  3.75it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.13it/s]

100%|██████████| 6/6 [00:01<00:00,  4.77it/s]

100%|██████████| 6/6 [00:01<00:00,  4.29it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9586896309837718

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9586896309837718

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9567358637700764

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9567358637700764

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9567358637700764

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9327112026853449

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9276588014330317

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8980217305935482

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8794615348127334

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8666855349807263

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9586896309837718
BRAS...
seed           8.000000
BAMI           0.958690
CASW           0.640901
SCGRAPHM       0.608211
ISOLISI        1.000000
BRAS           0.932893
KBET           0.749928
CPCR           0.973574
bio_score      0.801950
batch_score    0.885465
joint_score    0.835356
dtype: float64

===== seed 9 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:07<03:32,  7.32s/it]

  7%|▋         | 2/30 [00:17<04:10,  8.94s/it]

 10%|█         | 3/30 [00:26<04:07,  9.18s/it]

 13%|█▎        | 4/30 [00:36<04:00,  9.27s/it]

 17%|█▋        | 5/30 [00:45<03:49,  9.20s/it]

 20%|██        | 6/30 [00:54<03:39,  9.15s/it]

 23%|██▎       | 7/30 [01:03<03:30,  9.15s/it]

 27%|██▋       | 8/30 [01:12<03:20,  9.11s/it]

 30%|███       | 9/30 [01:21<03:10,  9.08s/it]

 33%|███▎      | 10/30 [01:30<03:01,  9.07s/it]

 37%|███▋      | 11/30 [01:40<02:55,  9.23s/it]

 40%|████      | 12/30 [01:49<02:44,  9.13s/it]

 43%|████▎     | 13/30 [01:57<02:33,  9.04s/it]

 47%|████▋     | 14/30 [02:06<02:24,  9.03s/it]

 50%|█████     | 15/30 [02:17<02:24,  9.62s/it]

 53%|█████▎    | 16/30 [02:26<02:09,  9.23s/it]

 57%|█████▋    | 17/30 [02:34<01:57,  9.02s/it]

 60%|██████    | 18/30 [02:56<02:33, 12.80s/it]

 63%|██████▎   | 19/30 [03:10<02:24, 13.17s/it]

 67%|██████▋   | 20/30 [03:21<02:05, 12.54s/it]

 70%|███████   | 21/30 [03:33<01:50, 12.32s/it]

 73%|███████▎  | 22/30 [03:41<01:29, 11.15s/it]

 77%|███████▋  | 23/30 [03:50<01:12, 10.29s/it]

 80%|████████  | 24/30 [03:58<00:58,  9.72s/it]

 83%|████████▎ | 25/30 [04:07<00:47,  9.55s/it]

 87%|████████▋ | 26/30 [04:18<00:40, 10.09s/it]

 90%|█████████ | 27/30 [04:30<00:31, 10.43s/it]

 93%|█████████▎| 28/30 [04:40<00:20, 10.42s/it]

 97%|█████████▋| 29/30 [04:49<00:10, 10.14s/it]

100%|██████████| 30/30 [04:59<00:00,  9.97s/it]

100%|██████████| 30/30 [04:59<00:00,  9.99s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.48it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.49it/s]

 50%|█████     | 3/6 [00:00<00:00,  3.89it/s]

 67%|██████▋   | 4/6 [00:01<00:00,  3.68it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.20it/s]

100%|██████████| 6/6 [00:01<00:00,  4.84it/s]

100%|██████████| 6/6 [00:01<00:00,  4.40it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9113523038307211

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9101412742613798

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9101760669740333

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9103453548660431

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.907154089912889

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.8848056389613587

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8479418068943991

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8492661945130593

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8187124569986703

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8186019289843804

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9113523038307211
BRAS...
seed           9.000000
BAMI           0.911352
CASW           0.639411
SCGRAPHM       0.634002
ISOLISI        0.988476
BRAS           0.899932
KBET           0.788694
CPCR           0.980274
bio_score      0.793310
batch_score    0.889633
joint_score    0.831839
dtype: float64

===== seed 10 =====

Removing 28 genes not expressing in Batch1.

Removing 26 genes not expressing in Batch2.
Removing 28 genes not expressing in Batch3.

Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')
Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=26 value_lambda=5.474813020467679 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:07<03:26,  7.12s/it]

  7%|▋         | 2/30 [00:17<04:10,  8.95s/it]

 10%|█         | 3/30 [00:27<04:15,  9.45s/it]

 13%|█▎        | 4/30 [00:36<04:02,  9.34s/it]

 17%|█▋        | 5/30 [00:46<03:54,  9.40s/it]

 20%|██        | 6/30 [00:55<03:46,  9.45s/it]

 23%|██▎       | 7/30 [01:06<03:46,  9.85s/it]

 27%|██▋       | 8/30 [01:15<03:32,  9.67s/it]

 30%|███       | 9/30 [01:23<03:13,  9.21s/it]

 33%|███▎      | 10/30 [01:31<02:57,  8.90s/it]

 37%|███▋      | 11/30 [01:40<02:46,  8.76s/it]

 40%|████      | 12/30 [01:48<02:36,  8.69s/it]

 43%|████▎     | 13/30 [01:58<02:31,  8.93s/it]

 47%|████▋     | 14/30 [02:09<02:30,  9.43s/it]

 50%|█████     | 15/30 [02:17<02:16,  9.10s/it]

 53%|█████▎    | 16/30 [02:25<02:05,  8.94s/it]

 57%|█████▋    | 17/30 [02:35<01:59,  9.23s/it]

 60%|██████    | 18/30 [02:44<01:49,  9.11s/it]

 63%|██████▎   | 19/30 [02:53<01:38,  8.97s/it]

 67%|██████▋   | 20/30 [03:02<01:31,  9.18s/it]

 70%|███████   | 21/30 [03:12<01:23,  9.27s/it]

 73%|███████▎  | 22/30 [03:20<01:11,  8.99s/it]

 77%|███████▋  | 23/30 [03:29<01:01,  8.77s/it]

 80%|████████  | 24/30 [03:37<00:51,  8.59s/it]

 83%|████████▎ | 25/30 [03:45<00:42,  8.51s/it]

 87%|████████▋ | 26/30 [03:53<00:33,  8.46s/it]

 90%|█████████ | 27/30 [04:02<00:25,  8.40s/it]

 93%|█████████▎| 28/30 [04:10<00:16,  8.32s/it]

 97%|█████████▋| 29/30 [04:18<00:08,  8.26s/it]

100%|██████████| 30/30 [04:26<00:00,  8.19s/it]

100%|██████████| 30/30 [04:26<00:00,  8.88s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.80it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.87it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.41it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.34it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.78it/s]

100%|██████████| 6/6 [00:01<00:00,  5.51it/s]

100%|██████████| 6/6 [00:01<00:00,  5.00it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9734082351145216

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.971131016921169

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9739129054407166

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9736611145247247

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9739094833516424

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.951720453160738

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9208216091152818

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9170255044181077

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9175648488150469

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8950975887427134

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.9739129054407166
BRAS...
seed           10.000000
BAMI            0.973913
CASW            0.668676
SCGRAPHM        0.534908
ISOLISI         1.000000
BRAS            0.954378
KBET            0.801355
CPCR            0.986678
bio_score       0.794374
batch_score     0.914137
joint_score     0.842279
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,ISOLISI,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.990123,0.677408,0.679922,1.000000,0.958874,0.839650,0.989772,0.836863,0.929432,0.873891
1,2,0.991678,0.637789,0.469387,1.000000,0.957513,0.824589,0.991553,0.774714,0.924552,0.834649
2,3,0.951231,0.645359,0.470487,1.000000,0.925093,0.712429,0.949283,0.766769,0.862268,0.804969
3,4,0.988379,0.631450,0.369704,1.000000,0.960996,0.804379,0.990186,0.747383,0.918520,0.815838
4,5,0.993519,0.658597,0.717419,1.000000,0.964788,0.804383,0.988634,0.842384,0.919268,0.873137
5,6,0.868641,0.633012,0.465446,0.966426,0.875442,0.706913,0.980287,0.733381,0.854214,0.781714
6,7,0.974017,0.659325,0.520579,1.000000,0.943565,0.825628,0.966548,0.788480,0.911913,0.837853
7,8,0.958690,0.640901,0.608211,1.000000,0.932893,0.749928,0.973574,0.801950,0.885465,0.835356
8,9,0.911352,0.639411,0.634002,0.988476,0.899932,0.788694,0.980274,0.793310,0.889633,0.831839
9,10,0.973913,0.668676,0.534908,1.000000,0.954378,0.801355,0.986678,0.794374,0.914137,0.842279

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.960154  0.038757  0.868641  0.993519
CASW         0.649193  0.015009  0.631450  0.677408
SCGRAPHM     0.547006  0.104324  0.369704  0.717419
ISOLISI      0.995490  0.010279  0.966426  1.000000
BRAS         0.937348  0.028130  0.875442  0.964788
KBET         0.785795  0.044525  0.706913  0.839650
CPCR         0.979679  0.012715  0.949283  0.991553
bio_score    0.787961  0.032968  0.733381  0.842384
batch_score  0.900940  0.025209  0.854214  0.929432
joint_score  0.833153  0.026669  0.781714  0.873891