# LIGER default - scib_sim1

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'scib_sim1'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'Batch'
LABEL_KEY = 'Group'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'scib_sim1'
assert BATCH_KEY == 'Batch'
assert LABEL_KEY == 'Group'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                              scib_sim1
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                Batch
label_key                                                Group
metrics      [BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=12097 n_batches=6 n_labels=7
ISOLISI preflight: min_batch_coverage=2 isolated_labels=['Group7']
CPCR preflight: eligible_labels=7

In [4]:
LIGER_DEFAULT_ARGS = {
    "k": 20,
    "value_lambda": 5.0,
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_default(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_DEFAULT_ARGS["k"],
        lam=LIGER_DEFAULT_ARGS["value_lambda"],
        max_iterations=LIGER_DEFAULT_ARGS["max_iters"],
        mode=LIGER_DEFAULT_ARGS["mode"],
        layer=LIGER_DEFAULT_ARGS["layer"],
        seed=seed,
    )


pd.Series(LIGER_DEFAULT_ARGS, name="default_setting")

k                   20
value_lambda       5.0
max_iters           30
mode              core
layer           counts
Name: default_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_default(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:22,  6.99s/it]

  7%|▋         | 2/30 [00:14<03:24,  7.31s/it]

 10%|█         | 3/30 [00:22<03:26,  7.64s/it]

 13%|█▎        | 4/30 [00:30<03:20,  7.72s/it]

 17%|█▋        | 5/30 [00:38<03:12,  7.69s/it]

 20%|██        | 6/30 [00:45<03:02,  7.61s/it]

 23%|██▎       | 7/30 [00:51<02:44,  7.16s/it]

 27%|██▋       | 8/30 [00:57<02:30,  6.85s/it]

 30%|███       | 9/30 [01:04<02:19,  6.65s/it]

 33%|███▎      | 10/30 [01:10<02:10,  6.51s/it]

 37%|███▋      | 11/30 [01:16<02:01,  6.42s/it]

 40%|████      | 12/30 [01:22<01:54,  6.36s/it]

 43%|████▎     | 13/30 [01:28<01:47,  6.31s/it]

 47%|████▋     | 14/30 [01:35<01:40,  6.27s/it]

 50%|█████     | 15/30 [01:41<01:32,  6.18s/it]

 53%|█████▎    | 16/30 [01:47<01:25,  6.13s/it]

 57%|█████▋    | 17/30 [01:53<01:19,  6.08s/it]

 60%|██████    | 18/30 [01:59<01:12,  6.05s/it]

 63%|██████▎   | 19/30 [02:05<01:06,  6.03s/it]

 67%|██████▋   | 20/30 [02:11<01:00,  6.01s/it]

 70%|███████   | 21/30 [02:16<00:53,  6.00s/it]

 73%|███████▎  | 22/30 [02:22<00:47,  5.99s/it]

 77%|███████▋  | 23/30 [02:28<00:41,  5.99s/it]

 80%|████████  | 24/30 [02:34<00:35,  5.98s/it]

 83%|████████▎ | 25/30 [02:40<00:29,  5.98s/it]

 87%|████████▋ | 26/30 [02:46<00:23,  5.98s/it]

 90%|█████████ | 27/30 [02:52<00:17,  5.98s/it]

 93%|█████████▎| 28/30 [02:58<00:11,  5.98s/it]

 97%|█████████▋| 29/30 [03:04<00:05,  5.99s/it]

100%|██████████| 30/30 [03:10<00:00,  5.99s/it]

100%|██████████| 30/30 [03:10<00:00,  6.36s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.54it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.33it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.24it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.19it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.42it/s]

100%|██████████| 6/6 [00:01<00:00,  5.23it/s]

100%|██████████| 6/6 [00:01<00:00,  4.71it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.9157006615281792

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9157006615281792

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9157006615281792

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9157006615281792

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8943681687973228

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.8660837596315897

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.863859319376305

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8370893504729969

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8351651333918775

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8145156514390536

WARNING:2026-07-23 17:53:33,189:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9157006615281792
BRAS...

seed           1.000000
BAMI           0.915701
CASW           0.659620
SCGRAPHM       0.563042
ISOLISI        1.000000
BRAS           0.858983
KBET           0.602514
CPCR           0.911163
bio_score      0.784591
batch_score    0.790886
joint_score    0.787109
dtype: float64

===== seed 2 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:31,  5.21s/it]

  7%|▋         | 2/30 [00:11<02:44,  5.88s/it]

 10%|█         | 3/30 [00:18<02:49,  6.29s/it]

 13%|█▎        | 4/30 [00:24<02:46,  6.40s/it]

 17%|█▋        | 5/30 [00:31<02:40,  6.40s/it]

 20%|██        | 6/30 [00:37<02:34,  6.43s/it]

 23%|██▎       | 7/30 [00:44<02:27,  6.41s/it]

 27%|██▋       | 8/30 [00:50<02:20,  6.38s/it]

 30%|███       | 9/30 [00:56<02:13,  6.36s/it]

 33%|███▎      | 10/30 [01:03<02:06,  6.35s/it]

 37%|███▋      | 11/30 [01:09<02:00,  6.34s/it]

 40%|████      | 12/30 [01:15<01:53,  6.33s/it]

 43%|████▎     | 13/30 [01:22<01:47,  6.33s/it]

 47%|████▋     | 14/30 [01:28<01:41,  6.32s/it]

 50%|█████     | 15/30 [01:34<01:34,  6.32s/it]

 53%|█████▎    | 16/30 [01:40<01:28,  6.31s/it]

 57%|█████▋    | 17/30 [01:47<01:22,  6.31s/it]

 60%|██████    | 18/30 [01:53<01:15,  6.31s/it]

 63%|██████▎   | 19/30 [01:59<01:09,  6.31s/it]

 67%|██████▋   | 20/30 [02:06<01:03,  6.31s/it]

 70%|███████   | 21/30 [02:12<00:56,  6.31s/it]

 73%|███████▎  | 22/30 [02:18<00:50,  6.31s/it]

 77%|███████▋  | 23/30 [02:25<00:44,  6.30s/it]

 80%|████████  | 24/30 [02:31<00:37,  6.30s/it]

 83%|████████▎ | 25/30 [02:37<00:31,  6.30s/it]

 87%|████████▋ | 26/30 [02:44<00:25,  6.30s/it]

 90%|█████████ | 27/30 [02:50<00:18,  6.31s/it]

 93%|█████████▎| 28/30 [02:56<00:12,  6.31s/it]

 97%|█████████▋| 29/30 [03:02<00:06,  6.30s/it]

100%|██████████| 30/30 [03:09<00:00,  6.31s/it]

100%|██████████| 30/30 [03:09<00:00,  6.31s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.83it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.84it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.39it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.24it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.61it/s]

100%|██████████| 6/6 [00:01<00:00,  5.38it/s]

100%|██████████| 6/6 [00:01<00:00,  4.90it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9715835766509536

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.968970672930724

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.968970672930724

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.968711704362681

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9450450900721636

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9115801395148903

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.911341362475201

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8918731628565619

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.9002338447477259

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8755447206083882

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9715835766509536
BRAS...

seed           2.000000
BAMI           0.971584
CASW           0.688954
SCGRAPHM       0.497149
ISOLISI        1.000000
BRAS           0.918104
KBET           0.813948
CPCR           0.979888
bio_score      0.789422
batch_score    0.903980
joint_score    0.835245
dtype: float64

===== seed 3 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:29,  5.15s/it]

  7%|▋         | 2/30 [00:11<02:43,  5.85s/it]

 10%|█         | 3/30 [00:18<02:48,  6.25s/it]

 13%|█▎        | 4/30 [00:24<02:44,  6.31s/it]

 17%|█▋        | 5/30 [00:30<02:37,  6.28s/it]

 20%|██        | 6/30 [00:37<02:30,  6.26s/it]

 23%|██▎       | 7/30 [00:43<02:23,  6.25s/it]

 27%|██▋       | 8/30 [00:49<02:17,  6.25s/it]

 30%|███       | 9/30 [00:55<02:11,  6.25s/it]

 33%|███▎      | 10/30 [01:02<02:05,  6.28s/it]

 37%|███▋      | 11/30 [01:08<02:00,  6.32s/it]

 40%|████      | 12/30 [01:14<01:53,  6.32s/it]

 43%|████▎     | 13/30 [01:21<01:47,  6.31s/it]

 47%|████▋     | 14/30 [01:27<01:40,  6.31s/it]

 50%|█████     | 15/30 [01:33<01:34,  6.31s/it]

 53%|█████▎    | 16/30 [01:40<01:28,  6.31s/it]

 57%|█████▋    | 17/30 [01:46<01:22,  6.31s/it]

 60%|██████    | 18/30 [01:52<01:15,  6.32s/it]

 63%|██████▎   | 19/30 [01:59<01:09,  6.32s/it]

 67%|██████▋   | 20/30 [02:05<01:03,  6.32s/it]

 70%|███████   | 21/30 [02:11<00:56,  6.32s/it]

 73%|███████▎  | 22/30 [02:18<00:50,  6.33s/it]

 77%|███████▋  | 23/30 [02:24<00:44,  6.33s/it]

 80%|████████  | 24/30 [02:30<00:37,  6.33s/it]

 83%|████████▎ | 25/30 [02:37<00:31,  6.33s/it]

 87%|████████▋ | 26/30 [02:43<00:25,  6.33s/it]

 90%|█████████ | 27/30 [02:49<00:19,  6.34s/it]

 93%|█████████▎| 28/30 [02:56<00:12,  6.34s/it]

 97%|█████████▋| 29/30 [03:02<00:06,  6.35s/it]

100%|██████████| 30/30 [03:08<00:00,  6.35s/it]

100%|██████████| 30/30 [03:08<00:00,  6.29s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.45it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.63it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.39it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.28it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.69it/s]

100%|██████████| 6/6 [00:01<00:00,  5.48it/s]

100%|██████████| 6/6 [00:01<00:00,  4.92it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9014417444867847

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9014417444867847

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9014417444867847

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9014417444867847

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8799187657136616

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.86831370382384

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8475802738631499

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8141905673849618

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8037517008187858

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7880035687335063

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9014417444867847
BRAS...

seed           3.000000
BAMI           0.901442
CASW           0.637498
SCGRAPHM       0.571281
ISOLISI        0.895580
BRAS           0.897594
KBET           0.738227
CPCR           0.947762
bio_score      0.751450
batch_score    0.861194
joint_score    0.795348
dtype: float64

===== seed 4 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:29,  5.15s/it]

  7%|▋         | 2/30 [00:11<02:43,  5.82s/it]

 10%|█         | 3/30 [00:18<02:48,  6.25s/it]

 13%|█▎        | 4/30 [00:24<02:44,  6.32s/it]

 17%|█▋        | 5/30 [00:30<02:37,  6.29s/it]

 20%|██        | 6/30 [00:37<02:30,  6.27s/it]

 23%|██▎       | 7/30 [00:43<02:23,  6.24s/it]

 27%|██▋       | 8/30 [00:49<02:17,  6.23s/it]

 30%|███       | 9/30 [00:55<02:10,  6.22s/it]

 33%|███▎      | 10/30 [01:01<02:04,  6.21s/it]

 37%|███▋      | 11/30 [01:08<01:57,  6.21s/it]

 40%|████      | 12/30 [01:14<01:51,  6.21s/it]

 43%|████▎     | 13/30 [01:20<01:45,  6.21s/it]

 47%|████▋     | 14/30 [01:26<01:38,  6.19s/it]

 50%|█████     | 15/30 [01:32<01:32,  6.14s/it]

 53%|█████▎    | 16/30 [01:38<01:25,  6.11s/it]

 57%|█████▋    | 17/30 [01:44<01:19,  6.09s/it]

 60%|██████    | 18/30 [01:50<01:12,  6.07s/it]

 63%|██████▎   | 19/30 [01:56<01:06,  6.07s/it]

 67%|██████▋   | 20/30 [02:02<01:00,  6.07s/it]

 70%|███████   | 21/30 [02:08<00:54,  6.07s/it]

 73%|███████▎  | 22/30 [02:15<00:48,  6.07s/it]

 77%|███████▋  | 23/30 [02:21<00:42,  6.07s/it]

 80%|████████  | 24/30 [02:27<00:36,  6.07s/it]

 83%|████████▎ | 25/30 [02:33<00:30,  6.07s/it]

 87%|████████▋ | 26/30 [02:39<00:24,  6.07s/it]

 90%|█████████ | 27/30 [02:45<00:18,  6.07s/it]

 93%|█████████▎| 28/30 [02:51<00:12,  6.07s/it]

 97%|█████████▋| 29/30 [02:57<00:06,  6.12s/it]

100%|██████████| 30/30 [03:03<00:00,  6.16s/it]

100%|██████████| 30/30 [03:03<00:00,  6.13s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.47it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.72it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.38it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.36it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.53it/s]

100%|██████████| 6/6 [00:01<00:00,  5.29it/s]

100%|██████████| 6/6 [00:01<00:00,  4.84it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8355013769749433

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8355013769749433

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.8350184516218432

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.833516409388217

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.805872031998647

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.793282253442858

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7839929651395087

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7661418798123681

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7612528499508684

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7274514333954909

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8355013769749433
BRAS...

seed           4.000000
BAMI           0.835501
CASW           0.659449
SCGRAPHM       0.405611
ISOLISI        0.970705
BRAS           0.840752
KBET           0.633219
CPCR           0.959466
bio_score      0.717816
batch_score    0.811146
joint_score    0.755148
dtype: float64

===== seed 5 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:25,  5.03s/it]

  7%|▋         | 2/30 [00:11<02:39,  5.70s/it]

 10%|█         | 3/30 [00:17<02:45,  6.13s/it]

 13%|█▎        | 4/30 [00:24<02:42,  6.24s/it]

 17%|█▋        | 5/30 [00:30<02:36,  6.24s/it]

 20%|██        | 6/30 [00:36<02:28,  6.20s/it]

 23%|██▎       | 7/30 [00:42<02:21,  6.14s/it]

 27%|██▋       | 8/30 [00:48<02:14,  6.10s/it]

 30%|███       | 9/30 [00:54<02:07,  6.07s/it]

 33%|███▎      | 10/30 [01:00<02:01,  6.06s/it]

 37%|███▋      | 11/30 [01:06<01:54,  6.05s/it]

 40%|████      | 12/30 [01:12<01:48,  6.05s/it]

 43%|████▎     | 13/30 [01:18<01:42,  6.05s/it]

 47%|████▋     | 14/30 [01:24<01:36,  6.04s/it]

 50%|█████     | 15/30 [01:30<01:30,  6.05s/it]

 53%|█████▎    | 16/30 [01:36<01:24,  6.06s/it]

 57%|█████▋    | 17/30 [01:43<01:18,  6.07s/it]

 60%|██████    | 18/30 [01:49<01:12,  6.08s/it]

 63%|██████▎   | 19/30 [01:55<01:06,  6.08s/it]

 67%|██████▋   | 20/30 [02:01<01:00,  6.08s/it]

 70%|███████   | 21/30 [02:07<00:54,  6.09s/it]

 73%|███████▎  | 22/30 [02:13<00:48,  6.09s/it]

 77%|███████▋  | 23/30 [02:19<00:42,  6.09s/it]

 80%|████████  | 24/30 [02:25<00:36,  6.09s/it]

 83%|████████▎ | 25/30 [02:31<00:30,  6.09s/it]

 87%|████████▋ | 26/30 [02:37<00:24,  6.10s/it]

 90%|█████████ | 27/30 [02:44<00:18,  6.10s/it]

 93%|█████████▎| 28/30 [02:50<00:12,  6.10s/it]

 97%|█████████▋| 29/30 [02:56<00:06,  6.10s/it]

100%|██████████| 30/30 [03:02<00:00,  6.10s/it]

100%|██████████| 30/30 [03:02<00:00,  6.08s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.42it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.64it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.33it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.47it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.71it/s]

100%|██████████| 6/6 [00:01<00:00,  5.50it/s]

100%|██████████| 6/6 [00:01<00:00,  4.95it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9566361249406803

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9555068519595558

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9566230321491273

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9303598061271349

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9302436454382492

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9097640170362821

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8859586144776719

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8794514316298556

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8707520644995421

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.868406057228587

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9566361249406803
BRAS...

seed           5.000000
BAMI           0.956636
CASW           0.666879
SCGRAPHM       0.487641
ISOLISI        1.000000
BRAS           0.935850
KBET           0.759588
CPCR           0.970469
bio_score      0.777789
batch_score    0.888636
joint_score    0.822128
dtype: float64

===== seed 6 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:18,  6.85s/it]

  7%|▋         | 2/30 [00:14<03:31,  7.56s/it]

 10%|█         | 3/30 [00:23<03:31,  7.82s/it]

 13%|█▎        | 4/30 [00:30<03:23,  7.82s/it]

 17%|█▋        | 5/30 [00:38<03:14,  7.77s/it]

 20%|██        | 6/30 [00:46<03:04,  7.70s/it]

 23%|██▎       | 7/30 [00:54<02:58,  7.77s/it]

 27%|██▋       | 8/30 [01:00<02:40,  7.28s/it]

 30%|███       | 9/30 [01:06<02:26,  6.95s/it]

 33%|███▎      | 10/30 [01:12<02:14,  6.74s/it]

 37%|███▋      | 11/30 [01:19<02:05,  6.60s/it]

 40%|████      | 12/30 [01:25<01:57,  6.52s/it]

 43%|████▎     | 13/30 [01:31<01:49,  6.44s/it]

 47%|████▋     | 14/30 [01:37<01:42,  6.39s/it]

 50%|█████     | 15/30 [01:44<01:35,  6.36s/it]

 53%|█████▎    | 16/30 [01:50<01:28,  6.33s/it]

 57%|█████▋    | 17/30 [01:56<01:22,  6.31s/it]

 60%|██████    | 18/30 [02:02<01:15,  6.31s/it]

 63%|██████▎   | 19/30 [02:09<01:09,  6.30s/it]

 67%|██████▋   | 20/30 [02:15<01:02,  6.29s/it]

 70%|███████   | 21/30 [02:21<00:56,  6.29s/it]

 73%|███████▎  | 22/30 [02:28<00:50,  6.29s/it]

 77%|███████▋  | 23/30 [02:34<00:44,  6.29s/it]

 80%|████████  | 24/30 [02:40<00:37,  6.29s/it]

 83%|████████▎ | 25/30 [02:46<00:31,  6.29s/it]

 87%|████████▋ | 26/30 [02:53<00:25,  6.30s/it]

 90%|█████████ | 27/30 [02:59<00:18,  6.30s/it]

 93%|█████████▎| 28/30 [03:05<00:12,  6.30s/it]

 97%|█████████▋| 29/30 [03:12<00:06,  6.30s/it]

100%|██████████| 30/30 [03:18<00:00,  6.31s/it]

100%|██████████| 30/30 [03:18<00:00,  6.62s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.54it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.60it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.33it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.33it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.72it/s]

100%|██████████| 6/6 [00:01<00:00,  5.49it/s]

100%|██████████| 6/6 [00:01<00:00,  4.93it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9501687166418447

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9501687166418447

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9501687166418447

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9274026367849643

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9272269548857218

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9046594194196383

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8951732726218149

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8815422467001952

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.873244263435371

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8415496989618282

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9501687166418447
BRAS...

seed           6.000000
BAMI           0.950169
CASW           0.680305
SCGRAPHM       0.650456
ISOLISI        1.000000
BRAS           0.869141
KBET           0.711416
CPCR           0.948206
bio_score      0.820232
batch_score    0.842921
joint_score    0.829308
dtype: float64

===== seed 7 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:06<03:08,  6.49s/it]

  7%|▋         | 2/30 [00:14<03:20,  7.16s/it]

 10%|█         | 3/30 [00:20<03:08,  6.97s/it]

 13%|█▎        | 4/30 [00:27<02:55,  6.76s/it]

 17%|█▋        | 5/30 [00:33<02:44,  6.58s/it]

 20%|██        | 6/30 [00:39<02:34,  6.46s/it]

 23%|██▎       | 7/30 [00:45<02:26,  6.38s/it]

 27%|██▋       | 8/30 [00:52<02:19,  6.33s/it]

 30%|███       | 9/30 [00:58<02:12,  6.29s/it]

 33%|███▎      | 10/30 [01:04<02:05,  6.27s/it]

 37%|███▋      | 11/30 [01:10<01:58,  6.25s/it]

 40%|████      | 12/30 [01:17<01:52,  6.24s/it]

 43%|████▎     | 13/30 [01:23<01:46,  6.24s/it]

 47%|████▋     | 14/30 [01:29<01:39,  6.24s/it]

 50%|█████     | 15/30 [01:35<01:33,  6.24s/it]

 53%|█████▎    | 16/30 [01:42<01:27,  6.23s/it]

 57%|█████▋    | 17/30 [01:48<01:21,  6.24s/it]

 60%|██████    | 18/30 [01:54<01:14,  6.24s/it]

 63%|██████▎   | 19/30 [02:00<01:08,  6.24s/it]

 67%|██████▋   | 20/30 [02:06<01:02,  6.24s/it]

 70%|███████   | 21/30 [02:13<00:56,  6.24s/it]

 73%|███████▎  | 22/30 [02:19<00:49,  6.24s/it]

 77%|███████▋  | 23/30 [02:25<00:43,  6.24s/it]

 80%|████████  | 24/30 [02:31<00:37,  6.24s/it]

 83%|████████▎ | 25/30 [02:38<00:31,  6.24s/it]

 87%|████████▋ | 26/30 [02:44<00:24,  6.24s/it]

 90%|█████████ | 27/30 [02:50<00:18,  6.24s/it]

 93%|█████████▎| 28/30 [02:56<00:12,  6.24s/it]

 97%|█████████▋| 29/30 [03:03<00:06,  6.24s/it]

100%|██████████| 30/30 [03:09<00:00,  6.24s/it]

100%|██████████| 30/30 [03:09<00:00,  6.31s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.18it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.49it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.28it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.44it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.92it/s]

100%|██████████| 6/6 [00:01<00:00,  5.66it/s]

100%|██████████| 6/6 [00:01<00:00,  5.00it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9863317530738692

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9844406832889319

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9844406832889319

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9846908137785367

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9613472213283528

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9264016074250582

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.9262796896743898

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.9176534074508484

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8976668081759406

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8904081429401616

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9863317530738692
BRAS...

seed           7.000000
BAMI           0.986332
CASW           0.683189
SCGRAPHM       0.595987
ISOLISI        1.000000
BRAS           0.946992
KBET           0.800236
CPCR           0.987306
bio_score      0.816377
batch_score    0.911511
joint_score    0.854431
dtype: float64

===== seed 8 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:07<03:39,  7.57s/it]

  7%|▋         | 2/30 [00:15<03:44,  8.03s/it]

 10%|█         | 3/30 [00:23<03:33,  7.92s/it]

 13%|█▎        | 4/30 [00:30<03:11,  7.38s/it]

 17%|█▋        | 5/30 [00:36<02:55,  7.01s/it]

 20%|██        | 6/30 [00:42<02:42,  6.77s/it]

 23%|██▎       | 7/30 [00:49<02:32,  6.62s/it]

 27%|██▋       | 8/30 [00:55<02:23,  6.52s/it]

 30%|███       | 9/30 [01:01<02:15,  6.45s/it]

 33%|███▎      | 10/30 [01:08<02:08,  6.41s/it]

 37%|███▋      | 11/30 [01:14<02:01,  6.38s/it]

 40%|████      | 12/30 [01:20<01:54,  6.36s/it]

 43%|████▎     | 13/30 [01:27<01:47,  6.35s/it]

 47%|████▋     | 14/30 [01:33<01:41,  6.34s/it]

 50%|█████     | 15/30 [01:39<01:35,  6.34s/it]

 53%|█████▎    | 16/30 [01:46<01:28,  6.34s/it]

 57%|█████▋    | 17/30 [01:52<01:22,  6.34s/it]

 60%|██████    | 18/30 [01:58<01:16,  6.33s/it]

 63%|██████▎   | 19/30 [02:05<01:09,  6.34s/it]

 67%|██████▋   | 20/30 [02:11<01:03,  6.34s/it]

 70%|███████   | 21/30 [02:17<00:57,  6.34s/it]

 73%|███████▎  | 22/30 [02:24<00:50,  6.34s/it]

 77%|███████▋  | 23/30 [02:30<00:44,  6.35s/it]

 80%|████████  | 24/30 [02:36<00:38,  6.35s/it]

 83%|████████▎ | 25/30 [02:43<00:31,  6.35s/it]

 87%|████████▋ | 26/30 [02:49<00:25,  6.34s/it]

 90%|█████████ | 27/30 [02:55<00:18,  6.32s/it]

 93%|█████████▎| 28/30 [03:02<00:12,  6.31s/it]

 97%|█████████▋| 29/30 [03:08<00:06,  6.31s/it]

100%|██████████| 30/30 [03:14<00:00,  6.31s/it]

100%|██████████| 30/30 [03:14<00:00,  6.49s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.38it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.51it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.33it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.47it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.91it/s]

100%|██████████| 6/6 [00:01<00:00,  5.65it/s]

100%|██████████| 6/6 [00:01<00:00,  5.02it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9326363260583119

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9320902267748447

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.928960186311238

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.928960186311238

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8965172150911406

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.8800114550721893

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8708621119409883

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8712916636923485

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8547032301076256

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8468041519954395

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9326363260583119
BRAS...
seed           8.000000
BAMI           0.932636
CASW           0.664475
SCGRAPHM       0.507258
ISOLISI        1.000000
BRAS           0.876458
KBET           0.700825
CPCR           0.932125
bio_score      0.776092
batch_score    0.836469
joint_score    0.800243
dtype: float64

===== seed 9 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:05<02:30,  5.18s/it]

  7%|▋         | 2/30 [00:11<02:43,  5.83s/it]

 10%|█         | 3/30 [00:18<02:49,  6.27s/it]

 13%|█▎        | 4/30 [00:24<02:45,  6.37s/it]

 17%|█▋        | 5/30 [00:31<02:39,  6.39s/it]

 20%|██        | 6/30 [00:37<02:32,  6.37s/it]

 23%|██▎       | 7/30 [00:43<02:25,  6.34s/it]

 27%|██▋       | 8/30 [00:50<02:19,  6.33s/it]

 30%|███       | 9/30 [00:56<02:12,  6.32s/it]

 33%|███▎      | 10/30 [01:02<02:06,  6.32s/it]

 37%|███▋      | 11/30 [01:09<02:00,  6.33s/it]

 40%|████      | 12/30 [01:15<01:53,  6.33s/it]

 43%|████▎     | 13/30 [01:21<01:47,  6.33s/it]

 47%|████▋     | 14/30 [01:28<01:42,  6.39s/it]

 50%|█████     | 15/30 [01:34<01:35,  6.37s/it]

 53%|█████▎    | 16/30 [01:40<01:29,  6.37s/it]

 57%|█████▋    | 17/30 [01:48<01:26,  6.67s/it]

 60%|██████    | 18/30 [01:54<01:18,  6.58s/it]

 63%|██████▎   | 19/30 [02:01<01:11,  6.51s/it]

 67%|██████▋   | 20/30 [02:07<01:04,  6.46s/it]

 70%|███████   | 21/30 [02:13<00:57,  6.43s/it]

 73%|███████▎  | 22/30 [02:20<00:51,  6.41s/it]

 77%|███████▋  | 23/30 [02:26<00:44,  6.40s/it]

 80%|████████  | 24/30 [02:32<00:38,  6.39s/it]

 83%|████████▎ | 25/30 [02:39<00:31,  6.39s/it]

 87%|████████▋ | 26/30 [02:45<00:25,  6.38s/it]

 90%|█████████ | 27/30 [02:51<00:18,  6.31s/it]

 93%|█████████▎| 28/30 [02:57<00:12,  6.25s/it]

 97%|█████████▋| 29/30 [03:03<00:06,  6.21s/it]

100%|██████████| 30/30 [03:10<00:00,  6.18s/it]

100%|██████████| 30/30 [03:10<00:00,  6.34s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.42it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.50it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.28it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.30it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.75it/s]

100%|██████████| 6/6 [00:01<00:00,  5.49it/s]

100%|██████████| 6/6 [00:01<00:00,  4.90it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9573395528209069

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9546883340561719

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9531936826030106

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9509905363847632

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.9488256975108036

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.9145282360015504

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8963686121460651

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8887392888586882

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.8564559589406187

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.8475706573039633

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9573395528209069
BRAS...
seed           9.000000
BAMI           0.957340
CASW           0.690844
SCGRAPHM       0.512678
ISOLISI        1.000000
BRAS           0.919457
KBET           0.811886
CPCR           0.974354
bio_score      0.790215
batch_score    0.901899
joint_score    0.834889
dtype: float64

===== seed 10 =====

Removing 28 genes not expressing in Batch1.
Removing 26 genes not expressing in Batch2.

Removing 28 genes not expressing in Batch3.
Removing 24 genes not expressing in Batch4.
Index(['Gene148', 'Gene1364', 'Gene1573', 'Gene1596', 'Gene1989', 'Gene2028',
       'Gene2271', 'Gene2661', 'Gene3065', 'Gene3185', 'Gene3587', 'Gene4753',
       'Gene5428', 'Gene5635', 'Gene6048', 'Gene6098', 'Gene6420', 'Gene7428',
       'Gene8000', 'Gene8427', 'Gene8705', 'Gene8711', 'Gene9481', 'Gene9519'],
      dtype='object', name='gene')

Removing 27 genes not expressing in Batch5.
Removing 27 genes not expressing in Batch6.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:07<03:25,  7.07s/it]

  7%|▋         | 2/30 [00:14<03:26,  7.37s/it]

 10%|█         | 3/30 [00:22<03:28,  7.71s/it]

 13%|█▎        | 4/30 [00:30<03:16,  7.54s/it]

 17%|█▋        | 5/30 [00:36<02:56,  7.05s/it]

 20%|██        | 6/30 [00:42<02:41,  6.75s/it]

 23%|██▎       | 7/30 [00:48<02:30,  6.55s/it]

 27%|██▋       | 8/30 [00:54<02:20,  6.37s/it]

 30%|███       | 9/30 [01:00<02:11,  6.25s/it]

 33%|███▎      | 10/30 [01:06<02:03,  6.17s/it]

 37%|███▋      | 11/30 [01:12<01:56,  6.11s/it]

 40%|████      | 12/30 [01:18<01:49,  6.08s/it]

 43%|████▎     | 13/30 [01:24<01:42,  6.05s/it]

 47%|████▋     | 14/30 [01:30<01:36,  6.04s/it]

 50%|█████     | 15/30 [01:36<01:30,  6.03s/it]

 53%|█████▎    | 16/30 [01:42<01:24,  6.03s/it]

 57%|█████▋    | 17/30 [01:48<01:18,  6.03s/it]

 60%|██████    | 18/30 [01:54<01:12,  6.03s/it]

 63%|██████▎   | 19/30 [02:00<01:06,  6.04s/it]

 67%|██████▋   | 20/30 [02:06<01:00,  6.04s/it]

 70%|███████   | 21/30 [02:12<00:54,  6.05s/it]

 73%|███████▎  | 22/30 [02:18<00:48,  6.04s/it]

 77%|███████▋  | 23/30 [02:24<00:42,  6.05s/it]

 80%|████████  | 24/30 [02:30<00:36,  6.05s/it]

 83%|████████▎ | 25/30 [02:36<00:30,  6.05s/it]

 87%|████████▋ | 26/30 [02:43<00:24,  6.06s/it]

 90%|█████████ | 27/30 [02:49<00:18,  6.07s/it]

 93%|█████████▎| 28/30 [02:55<00:12,  6.08s/it]

 97%|█████████▋| 29/30 [03:01<00:06,  6.08s/it]

100%|██████████| 30/30 [03:07<00:00,  6.08s/it]

100%|██████████| 30/30 [03:07<00:00,  6.25s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Isolated labels CLISI...
isolated labels: no more than 2 batches per label
isolated labels: ['Group7']

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/6 [00:00<?, ?it/s]

 17%|█▋        | 1/6 [00:00<00:01,  4.56it/s]

 33%|███▎      | 2/6 [00:00<00:00,  4.64it/s]

 50%|█████     | 3/6 [00:00<00:00,  4.35it/s]

 67%|██████▋   | 4/6 [00:00<00:00,  4.47it/s]

 83%|████████▎ | 5/6 [00:01<00:00,  4.83it/s]

100%|██████████| 6/6 [00:01<00:00,  5.58it/s]

100%|██████████| 6/6 [00:01<00:00,  5.01it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.9238386808403789

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.9238386808403789

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.9238386808403789

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.9238386808403789

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.8778360768459588

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.8505881857783404

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.8503867725717423

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.8149860106986528

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7901962367313118

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7729734389052753

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.9238386808403789
BRAS...

seed           10.000000
BAMI            0.923839
CASW            0.640204
SCGRAPHM        0.429121
ISOLISI         0.981894
BRAS            0.960460
KBET            0.833946
CPCR            0.988342
bio_score       0.743764
batch_score     0.927583
joint_score     0.817292
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,ISOLISI,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.915701,0.659620,0.563042,1.000000,0.858983,0.602514,0.911163,0.784591,0.790886,0.787109
1,2,0.971584,0.688954,0.497149,1.000000,0.918104,0.813948,0.979888,0.789422,0.903980,0.835245
2,3,0.901442,0.637498,0.571281,0.895580,0.897594,0.738227,0.947762,0.751450,0.861194,0.795348
3,4,0.835501,0.659449,0.405611,0.970705,0.840752,0.633219,0.959466,0.717816,0.811146,0.755148
4,5,0.956636,0.666879,0.487641,1.000000,0.935850,0.759588,0.970469,0.777789,0.888636,0.822128
5,6,0.950169,0.680305,0.650456,1.000000,0.869141,0.711416,0.948206,0.820232,0.842921,0.829308
6,7,0.986332,0.683189,0.595987,1.000000,0.946992,0.800236,0.987306,0.816377,0.911511,0.854431
7,8,0.932636,0.664475,0.507258,1.000000,0.876458,0.700825,0.932125,0.776092,0.836469,0.800243
8,9,0.957340,0.690844,0.512678,1.000000,0.919457,0.811886,0.974354,0.790215,0.901899,0.834889
9,10,0.923839,0.640204,0.429121,0.981894,0.960460,0.833946,0.988342,0.743764,0.927583,0.817292

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.933118  0.040821  0.835501  0.986332
CASW         0.667142  0.017876  0.637498  0.690844
SCGRAPHM     0.522022  0.070967  0.405611  0.650456
ISOLISI      0.984818  0.031280  0.895580  1.000000
BRAS         0.902379  0.038084  0.840752  0.960460
KBET         0.740581  0.074920  0.602514  0.833946
CPCR         0.959908  0.023898  0.911163  0.988342
bio_score    0.776775  0.030112  0.717816  0.820232
batch_score  0.867623  0.043772  0.790886  0.927583
joint_score  0.813114  0.027476  0.755148  0.854431