# LIGER default - human_pancreas

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'human_pancreas'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'tech'
LABEL_KEY = 'celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'human_pancreas'
assert BATCH_KEY == 'tech'
assert LABEL_KEY == 'celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                         human_pancreas
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                 tech
label_key                                             celltype
metrics      [BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=16382 n_batches=9 n_labels=14
ISOLISI preflight: min_batch_coverage=4 isolated_labels=['t_cell']
CPCR preflight: eligible_labels=9

In [4]:
LIGER_DEFAULT_ARGS = {
    "k": 20,
    "value_lambda": 5.0,
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_default(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_DEFAULT_ARGS["k"],
        lam=LIGER_DEFAULT_ARGS["value_lambda"],
        max_iterations=LIGER_DEFAULT_ARGS["max_iters"],
        mode=LIGER_DEFAULT_ARGS["mode"],
        layer=LIGER_DEFAULT_ARGS["layer"],
        seed=seed,
    )


pd.Series(LIGER_DEFAULT_ARGS, name="default_setting")

k                   20
value_lambda       5.0
max_iters           30
mode              core
layer           counts
Name: default_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_default(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.

Removing 2032 genes not expressing in smarter.
Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:45<21:56, 45.40s/it]

  7%|▋         | 2/30 [01:28<20:41, 44.32s/it]

 10%|█         | 3/30 [02:16<20:40, 45.95s/it]

 13%|█▎        | 4/30 [04:09<31:22, 72.39s/it]

 17%|█▋        | 5/30 [04:28<22:08, 53.13s/it]

 20%|██        | 6/30 [04:47<16:36, 41.54s/it]

 23%|██▎       | 7/30 [05:05<12:58, 33.87s/it]

 27%|██▋       | 8/30 [06:31<18:26, 50.30s/it]

 30%|███       | 9/30 [06:48<13:58, 39.91s/it]

 33%|███▎      | 10/30 [07:08<11:15, 33.79s/it]

 37%|███▋      | 11/30 [07:27<09:18, 29.38s/it]

 40%|████      | 12/30 [08:30<11:50, 39.50s/it]

 43%|████▎     | 13/30 [09:29<12:50, 45.32s/it]

 47%|████▋     | 14/30 [11:07<16:20, 61.31s/it]

 50%|█████     | 15/30 [13:15<20:20, 81.38s/it]

 53%|█████▎    | 16/30 [15:34<23:04, 98.88s/it]

 57%|█████▋    | 17/30 [15:54<16:16, 75.11s/it]

 60%|██████    | 18/30 [16:13<11:37, 58.13s/it]

 63%|██████▎   | 19/30 [16:29<08:20, 45.51s/it]

 67%|██████▋   | 20/30 [16:44<06:03, 36.38s/it]

 70%|███████   | 21/30 [17:02<04:37, 30.88s/it]

 73%|███████▎  | 22/30 [17:20<03:36, 27.09s/it]

 77%|███████▋  | 23/30 [17:37<02:47, 23.96s/it]

 80%|████████  | 24/30 [17:55<02:12, 22.12s/it]

 83%|████████▎ | 25/30 [18:15<01:46, 21.39s/it]

 87%|████████▋ | 26/30 [18:33<01:21, 20.41s/it]

 90%|█████████ | 27/30 [18:58<01:05, 22.00s/it]

 93%|█████████▎| 28/30 [19:16<00:41, 20.64s/it]

 97%|█████████▋| 29/30 [19:35<00:20, 20.15s/it]

100%|██████████| 30/30 [20:43<00:00, 34.47s/it]

100%|██████████| 30/30 [20:43<00:00, 41.44s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.64it/s]

 44%|████▍     | 4/9 [00:00<00:00, 11.89it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 13.94it/s]

100%|██████████| 9/9 [00:00<00:00, 13.82it/s]

100%|██████████| 9/9 [00:00<00:00, 13.49it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.6723238276653566

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7024507888914537

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6999354745072939

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6869218793614763

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.680931435660943

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6802351631009211

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.669232943285972

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6658517505744452

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6681152733285675

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6572090720870589

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7024507888914537
BRAS...

WARNING:2026-07-23 16:21:28,963:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

seed           1.000000
BAMI           0.702451
CASW           0.621262
SCGRAPHM       0.467011
ISOLISI        0.869113
BRAS           0.719616
KBET           0.632439
CPCR           0.887774
bio_score      0.664959
batch_score    0.746610
joint_score    0.697619
dtype: float64

===== seed 2 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:15<07:15, 15.02s/it]

  7%|▋         | 2/30 [00:30<07:12, 15.46s/it]

 10%|█         | 3/30 [00:47<07:18, 16.23s/it]

 13%|█▎        | 4/30 [01:05<07:15, 16.75s/it]

 17%|█▋        | 5/30 [01:24<07:17, 17.48s/it]

 20%|██        | 6/30 [01:42<07:06, 17.77s/it]

 23%|██▎       | 7/30 [02:01<06:54, 18.03s/it]

 27%|██▋       | 8/30 [02:20<06:43, 18.33s/it]

 30%|███       | 9/30 [02:38<06:26, 18.41s/it]

 33%|███▎      | 10/30 [02:57<06:07, 18.38s/it]

 37%|███▋      | 11/30 [03:17<05:58, 18.87s/it]

 40%|████      | 12/30 [03:35<05:40, 18.89s/it]

 43%|████▎     | 13/30 [03:54<05:21, 18.88s/it]

 47%|████▋     | 14/30 [04:11<04:53, 18.33s/it]

 50%|█████     | 15/30 [04:30<04:35, 18.38s/it]

 53%|█████▎    | 16/30 [04:47<04:10, 17.87s/it]

 57%|█████▋    | 17/30 [05:03<03:46, 17.39s/it]

 60%|██████    | 18/30 [05:18<03:20, 16.67s/it]

 63%|██████▎   | 19/30 [05:36<03:07, 17.02s/it]

 67%|██████▋   | 20/30 [05:54<02:53, 17.33s/it]

 70%|███████   | 21/30 [06:11<02:36, 17.42s/it]

 73%|███████▎  | 22/30 [06:28<02:17, 17.20s/it]

 77%|███████▋  | 23/30 [06:45<01:59, 17.12s/it]

 80%|████████  | 24/30 [07:03<01:44, 17.47s/it]

 83%|████████▎ | 25/30 [07:23<01:30, 18.01s/it]

 87%|████████▋ | 26/30 [07:39<01:10, 17.60s/it]

 90%|█████████ | 27/30 [07:57<00:52, 17.57s/it]

 93%|█████████▎| 28/30 [08:15<00:35, 17.77s/it]

 97%|█████████▋| 29/30 [08:32<00:17, 17.49s/it]

100%|██████████| 30/30 [08:52<00:00, 18.31s/it]

100%|██████████| 30/30 [08:52<00:00, 17.75s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.26it/s]

 44%|████▍     | 4/9 [00:00<00:00, 11.27it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 14.42it/s]

100%|██████████| 9/9 [00:00<00:00, 14.79it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6716568467029793

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7047604411065687

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7152946814265152

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7144477672685721

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7046315268534643

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7007433338894624

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6851160623766094

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.682946614736727

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.674651432304097

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6728060136532824

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7152946814265152
BRAS...

seed           2.000000
BAMI           0.715295
CASW           0.651889
SCGRAPHM       0.424300
ISOLISI        0.743970
BRAS           0.700741
KBET           0.644083
CPCR           0.877965
bio_score      0.633864
batch_score    0.740930
joint_score    0.676690
dtype: float64

===== seed 3 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.

Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.

Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.
Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:19<09:31, 19.72s/it]

  7%|▋         | 2/30 [00:43<10:23, 22.28s/it]

 10%|█         | 3/30 [01:05<09:51, 21.89s/it]

 13%|█▎        | 4/30 [01:25<09:08, 21.10s/it]

 17%|█▋        | 5/30 [01:44<08:35, 20.62s/it]

 20%|██        | 6/30 [02:02<07:47, 19.47s/it]

 23%|██▎       | 7/30 [02:21<07:26, 19.40s/it]

 27%|██▋       | 8/30 [02:40<07:05, 19.32s/it]

 30%|███       | 9/30 [03:00<06:49, 19.49s/it]

 33%|███▎      | 10/30 [03:19<06:29, 19.45s/it]

 37%|███▋      | 11/30 [03:39<06:08, 19.41s/it]

 40%|████      | 12/30 [03:58<05:51, 19.51s/it]

 43%|████▎     | 13/30 [04:15<05:19, 18.80s/it]

 47%|████▋     | 14/30 [04:35<05:02, 18.93s/it]

 50%|█████     | 15/30 [04:55<04:48, 19.26s/it]

 53%|█████▎    | 16/30 [05:14<04:29, 19.26s/it]

 57%|█████▋    | 17/30 [05:34<04:13, 19.51s/it]

 60%|██████    | 18/30 [05:54<03:55, 19.61s/it]

 63%|██████▎   | 19/30 [06:14<03:35, 19.63s/it]

 67%|██████▋   | 20/30 [06:33<03:14, 19.44s/it]

 70%|███████   | 21/30 [06:52<02:54, 19.44s/it]

 73%|███████▎  | 22/30 [07:12<02:37, 19.63s/it]

 77%|███████▋  | 23/30 [07:31<02:14, 19.27s/it]

 80%|████████  | 24/30 [07:50<01:56, 19.36s/it]

 83%|████████▎ | 25/30 [08:09<01:35, 19.18s/it]

 87%|████████▋ | 26/30 [08:29<01:17, 19.42s/it]

 90%|█████████ | 27/30 [08:48<00:58, 19.36s/it]

 93%|█████████▎| 28/30 [09:08<00:38, 19.47s/it]

 97%|█████████▋| 29/30 [09:28<00:19, 19.64s/it]

100%|██████████| 30/30 [09:47<00:00, 19.54s/it]

100%|██████████| 30/30 [09:47<00:00, 19.59s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 13.09it/s]

 44%|████▍     | 4/9 [00:00<00:00, 10.10it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 12.20it/s]

100%|██████████| 9/9 [00:00<00:00, 13.32it/s]

100%|██████████| 9/9 [00:00<00:00, 12.62it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6840159402126629

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6885436416187566

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6997113643924093

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7015273342352925

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7013813931184019

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7034113511816379

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.690101359533774

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6721180711711764

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6671995670950117

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6635486862620609

optimised clustering against liger_metric_label
optimal cluster resolution: 1.2
optimal score: 0.7034113511816379
BRAS...

seed           3.000000
BAMI           0.703411
CASW           0.630812
SCGRAPHM       0.539123
ISOLISI        0.888613
BRAS           0.721760
KBET           0.638021
CPCR           0.879104
bio_score      0.690490
batch_score    0.746295
joint_score    0.712812
dtype: float64

===== seed 4 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:19<09:37, 19.92s/it]

  7%|▋         | 2/30 [00:39<09:15, 19.84s/it]

 10%|█         | 3/30 [00:58<08:36, 19.15s/it]

 13%|█▎        | 4/30 [01:17<08:17, 19.13s/it]

 17%|█▋        | 5/30 [01:37<08:05, 19.43s/it]

 20%|██        | 6/30 [01:56<07:45, 19.39s/it]

 23%|██▎       | 7/30 [02:17<07:38, 19.92s/it]

 27%|██▋       | 8/30 [02:37<07:18, 19.94s/it]

 30%|███       | 9/30 [02:57<06:56, 19.84s/it]

 33%|███▎      | 10/30 [03:16<06:36, 19.80s/it]

 37%|███▋      | 11/30 [03:37<06:20, 20.03s/it]

 40%|████      | 12/30 [03:56<05:56, 19.83s/it]

 43%|████▎     | 13/30 [04:15<05:30, 19.47s/it]

 47%|████▋     | 14/30 [04:33<05:04, 19.02s/it]

 50%|█████     | 15/30 [04:52<04:46, 19.13s/it]

 53%|█████▎    | 16/30 [05:12<04:29, 19.27s/it]

 57%|█████▋    | 17/30 [05:30<04:06, 18.95s/it]

 60%|██████    | 18/30 [05:49<03:49, 19.10s/it]

 63%|██████▎   | 19/30 [06:06<03:22, 18.44s/it]

 67%|██████▋   | 20/30 [06:25<03:04, 18.48s/it]

 70%|███████   | 21/30 [06:44<02:47, 18.57s/it]

 73%|███████▎  | 22/30 [07:02<02:28, 18.57s/it]

 77%|███████▋  | 23/30 [07:20<02:08, 18.42s/it]

 80%|████████  | 24/30 [07:38<01:48, 18.14s/it]

 83%|████████▎ | 25/30 [07:55<01:29, 17.87s/it]

 87%|████████▋ | 26/30 [08:17<01:16, 19.10s/it]

 90%|█████████ | 27/30 [08:37<00:58, 19.48s/it]

 93%|█████████▎| 28/30 [08:57<00:38, 19.41s/it]

 97%|█████████▋| 29/30 [09:13<00:18, 18.53s/it]

100%|██████████| 30/30 [09:31<00:00, 18.21s/it]

100%|██████████| 30/30 [09:31<00:00, 19.03s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.76it/s]

 44%|████▍     | 4/9 [00:00<00:00,  9.31it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 12.15it/s]

100%|██████████| 9/9 [00:00<00:00, 13.55it/s]

100%|██████████| 9/9 [00:00<00:00, 12.53it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6838786417766525

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6729532600659559

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.672537150023757

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.682349292717184

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6773183383576984

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6707977290889898

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6597471795159524

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6410929571406102

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.642780063991002

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6397258070503512

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6838786417766525
BRAS...

seed           4.000000
BAMI           0.683879
CASW           0.619423
SCGRAPHM       0.485865
ISOLISI        0.848413
BRAS           0.710803
KBET           0.665899
CPCR           0.867949
bio_score      0.659395
batch_score    0.748217
joint_score    0.694924
dtype: float64

===== seed 5 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:18<09:04, 18.78s/it]

  7%|▋         | 2/30 [00:38<08:55, 19.13s/it]

 10%|█         | 3/30 [00:57<08:36, 19.12s/it]

 13%|█▎        | 4/30 [01:24<09:41, 22.38s/it]

 17%|█▋        | 5/30 [01:43<08:51, 21.28s/it]

 20%|██        | 6/30 [02:02<08:10, 20.43s/it]

 23%|██▎       | 7/30 [02:20<07:26, 19.40s/it]

 27%|██▋       | 8/30 [02:37<06:49, 18.63s/it]

 30%|███       | 9/30 [02:52<06:09, 17.58s/it]

 33%|███▎      | 10/30 [03:10<05:54, 17.71s/it]

 37%|███▋      | 11/30 [03:28<05:37, 17.75s/it]

 40%|████      | 12/30 [03:48<05:31, 18.43s/it]

 43%|████▎     | 13/30 [04:06<05:14, 18.51s/it]

 47%|████▋     | 14/30 [04:25<04:58, 18.68s/it]

 50%|█████     | 15/30 [04:43<04:36, 18.43s/it]

 53%|█████▎    | 16/30 [05:02<04:18, 18.43s/it]

 57%|█████▋    | 17/30 [05:39<05:15, 24.26s/it]

 60%|██████    | 18/30 [06:30<06:25, 32.13s/it]

 63%|██████▎   | 19/30 [06:49<05:09, 28.11s/it]

 67%|██████▋   | 20/30 [07:05<04:05, 24.55s/it]

 70%|███████   | 21/30 [07:22<03:21, 22.42s/it]

 73%|███████▎  | 22/30 [07:43<02:54, 21.85s/it]

 77%|███████▋  | 23/30 [08:03<02:29, 21.35s/it]

 80%|████████  | 24/30 [08:22<02:03, 20.58s/it]

 83%|████████▎ | 25/30 [08:47<01:49, 21.92s/it]

 87%|████████▋ | 26/30 [09:05<01:23, 20.82s/it]

 90%|█████████ | 27/30 [09:22<00:59, 19.68s/it]

 93%|█████████▎| 28/30 [09:44<00:40, 20.19s/it]

 97%|█████████▋| 29/30 [09:59<00:18, 18.74s/it]

100%|██████████| 30/30 [10:19<00:00, 18.99s/it]

100%|██████████| 30/30 [10:19<00:00, 20.63s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 13.81it/s]

 44%|████▍     | 4/9 [00:00<00:00,  9.70it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 11.81it/s]

100%|██████████| 9/9 [00:00<00:00, 12.72it/s]

100%|██████████| 9/9 [00:00<00:00, 12.16it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7231572445875593

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7242272079529651

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7150816301000471

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7114738808493443

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7083646686258133

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7054221205430355

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7075936042223003

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6932983700319633

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6853254128720129

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6711501949066366

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7242272079529651
BRAS...

seed           5.000000
BAMI           0.724227
CASW           0.662620
SCGRAPHM       0.418117
ISOLISI        0.962172
BRAS           0.710237
KBET           0.624637
CPCR           0.880651
bio_score      0.691784
batch_score    0.738508
joint_score    0.710474
dtype: float64

===== seed 6 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:19<09:22, 19.39s/it]

  7%|▋         | 2/30 [00:39<09:22, 20.10s/it]

 10%|█         | 3/30 [00:59<08:53, 19.77s/it]

 13%|█▎        | 4/30 [01:14<07:43, 17.84s/it]

 17%|█▋        | 5/30 [01:29<06:58, 16.74s/it]

 20%|██        | 6/30 [01:44<06:27, 16.15s/it]

 23%|██▎       | 7/30 [02:00<06:15, 16.31s/it]

 27%|██▋       | 8/30 [02:15<05:47, 15.77s/it]

 30%|███       | 9/30 [02:31<05:33, 15.88s/it]

 33%|███▎      | 10/30 [02:46<05:11, 15.56s/it]

 37%|███▋      | 11/30 [03:02<04:58, 15.74s/it]

 40%|████      | 12/30 [03:17<04:38, 15.46s/it]

 43%|████▎     | 13/30 [03:34<04:33, 16.11s/it]

 47%|████▋     | 14/30 [03:50<04:13, 15.84s/it]

 50%|█████     | 15/30 [04:09<04:11, 16.78s/it]

 53%|█████▎    | 16/30 [04:23<03:46, 16.21s/it]

 57%|█████▋    | 17/30 [04:40<03:31, 16.26s/it]

 60%|██████    | 18/30 [04:57<03:17, 16.44s/it]

 63%|██████▎   | 19/30 [05:16<03:12, 17.46s/it]

 67%|██████▋   | 20/30 [05:33<02:52, 17.24s/it]

 70%|███████   | 21/30 [05:48<02:29, 16.59s/it]

 73%|███████▎  | 22/30 [06:04<02:10, 16.35s/it]

 77%|███████▋  | 23/30 [06:18<01:49, 15.57s/it]

 80%|████████  | 24/30 [06:33<01:32, 15.42s/it]

 83%|████████▎ | 25/30 [06:48<01:17, 15.40s/it]

 87%|████████▋ | 26/30 [07:04<01:01, 15.36s/it]

 90%|█████████ | 27/30 [07:19<00:45, 15.31s/it]

 93%|█████████▎| 28/30 [07:33<00:30, 15.14s/it]

 97%|█████████▋| 29/30 [07:48<00:15, 15.11s/it]

100%|██████████| 30/30 [08:04<00:00, 15.12s/it]

100%|██████████| 30/30 [08:04<00:00, 16.14s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.83it/s]

 44%|████▍     | 4/9 [00:00<00:00,  9.34it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 12.16it/s]

100%|██████████| 9/9 [00:00<00:00, 13.79it/s]

100%|██████████| 9/9 [00:00<00:00, 12.72it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6858739822282469

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7050116455000406

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6940705441766437

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.706393900166841

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7038752383359403

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6992083086100799

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.683594508955763

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6766486953739611

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.666867083784301

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6600222053403895

optimised clustering against liger_metric_label
optimal cluster resolution: 0.8
optimal score: 0.706393900166841
BRAS...

seed           6.000000
BAMI           0.706394
CASW           0.634714
SCGRAPHM       0.411769
ISOLISI        0.924355
BRAS           0.714133
KBET           0.618132
CPCR           0.873926
bio_score      0.669308
batch_score    0.735397
joint_score    0.695744
dtype: float64

===== seed 7 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:15<07:43, 15.97s/it]

  7%|▋         | 2/30 [00:32<07:29, 16.06s/it]

 10%|█         | 3/30 [00:47<07:09, 15.90s/it]

 13%|█▎        | 4/30 [01:02<06:38, 15.31s/it]

 17%|█▋        | 5/30 [01:18<06:30, 15.63s/it]

 20%|██        | 6/30 [01:33<06:13, 15.57s/it]

 23%|██▎       | 7/30 [01:49<05:58, 15.57s/it]

 27%|██▋       | 8/30 [02:05<05:45, 15.69s/it]

 30%|███       | 9/30 [02:22<05:39, 16.18s/it]

 33%|███▎      | 10/30 [02:37<05:17, 15.85s/it]

 37%|███▋      | 11/30 [02:54<05:07, 16.17s/it]

 40%|████      | 12/30 [03:12<04:58, 16.59s/it]

 43%|████▎     | 13/30 [03:30<04:52, 17.22s/it]

 47%|████▋     | 14/30 [03:45<04:24, 16.50s/it]

 50%|█████     | 15/30 [04:02<04:10, 16.70s/it]

 53%|█████▎    | 16/30 [04:19<03:54, 16.76s/it]

 57%|█████▋    | 17/30 [04:37<03:42, 17.08s/it]

 60%|██████    | 18/30 [04:56<03:30, 17.53s/it]

 63%|██████▎   | 19/30 [05:14<03:15, 17.75s/it]

 67%|██████▋   | 20/30 [05:33<03:00, 18.04s/it]

 70%|███████   | 21/30 [05:51<02:44, 18.27s/it]

 73%|███████▎  | 22/30 [06:08<02:21, 17.65s/it]

 77%|███████▋  | 23/30 [06:25<02:02, 17.46s/it]

 80%|████████  | 24/30 [06:43<01:46, 17.72s/it]

 83%|████████▎ | 25/30 [07:02<01:30, 18.02s/it]

 87%|████████▋ | 26/30 [07:19<01:11, 17.92s/it]

 90%|█████████ | 27/30 [07:38<00:54, 18.09s/it]

 93%|█████████▎| 28/30 [07:57<00:36, 18.42s/it]

 97%|█████████▋| 29/30 [08:17<00:18, 18.91s/it]

100%|██████████| 30/30 [08:37<00:00, 19.25s/it]

100%|██████████| 30/30 [08:37<00:00, 17.26s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.79it/s]

 44%|████▍     | 4/9 [00:00<00:00,  8.67it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 11.40it/s]

100%|██████████| 9/9 [00:00<00:00, 12.87it/s]

100%|██████████| 9/9 [00:00<00:00, 11.92it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6401242690798191

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6530001729954942

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6606812823743807

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6495784610982941

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6524662627738571

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6496285871996391

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.651818385922743

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6556440441560272

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6558363475694373

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6437016373563201

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6606812823743807
BRAS...

seed           7.000000
BAMI           0.660681
CASW           0.649574
SCGRAPHM       0.443274
ISOLISI        0.903313
BRAS           0.701237
KBET           0.613125
CPCR           0.857903
bio_score      0.664211
batch_score    0.724088
joint_score    0.688162
dtype: float64

===== seed 8 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:20<09:40, 20.03s/it]

  7%|▋         | 2/30 [00:40<09:34, 20.51s/it]

 10%|█         | 3/30 [00:59<08:54, 19.81s/it]

 13%|█▎        | 4/30 [01:18<08:20, 19.24s/it]

 17%|█▋        | 5/30 [01:38<08:05, 19.44s/it]

 20%|██        | 6/30 [01:56<07:37, 19.07s/it]

 23%|██▎       | 7/30 [02:13<07:06, 18.55s/it]

 27%|██▋       | 8/30 [02:33<06:58, 19.01s/it]

 30%|███       | 9/30 [02:52<06:36, 18.86s/it]

 33%|███▎      | 10/30 [03:11<06:19, 18.99s/it]

 37%|███▋      | 11/30 [03:28<05:50, 18.46s/it]

 40%|████      | 12/30 [03:48<05:36, 18.72s/it]

 43%|████▎     | 13/30 [04:09<05:31, 19.52s/it]

 47%|████▋     | 14/30 [04:28<05:10, 19.41s/it]

 50%|█████     | 15/30 [04:48<04:50, 19.38s/it]

 53%|█████▎    | 16/30 [05:04<04:18, 18.49s/it]

 57%|█████▋    | 17/30 [05:21<03:52, 17.90s/it]

 60%|██████    | 18/30 [05:38<03:35, 17.93s/it]

 63%|██████▎   | 19/30 [05:57<03:19, 18.16s/it]

 67%|██████▋   | 20/30 [06:16<03:02, 18.26s/it]

 70%|███████   | 21/30 [06:33<02:43, 18.11s/it]

 73%|███████▎  | 22/30 [06:50<02:20, 17.53s/it]

 77%|███████▋  | 23/30 [07:06<02:01, 17.32s/it]

 80%|████████  | 24/30 [07:24<01:44, 17.49s/it]

 83%|████████▎ | 25/30 [07:43<01:29, 17.98s/it]

 87%|████████▋ | 26/30 [08:03<01:14, 18.50s/it]

 90%|█████████ | 27/30 [08:21<00:54, 18.24s/it]

 93%|█████████▎| 28/30 [08:39<00:36, 18.32s/it]

 97%|█████████▋| 29/30 [08:57<00:18, 18.17s/it]

100%|██████████| 30/30 [09:16<00:00, 18.33s/it]

100%|██████████| 30/30 [09:16<00:00, 18.54s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Variance contribution increased after integration!
Setting PCR comparison score to 0.
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 13.27it/s]

 44%|████▍     | 4/9 [00:00<00:00,  9.33it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 12.39it/s]

100%|██████████| 9/9 [00:00<00:00, 13.61it/s]

100%|██████████| 9/9 [00:00<00:00, 12.67it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6450363601989798

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6793581921404245

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6758684762866809

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6745819087469215

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6763139972456568

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6799718931510478

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6629667942252467

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6616180970128146

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6558463675949927

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6503693515633484

optimised clustering against liger_metric_label
optimal cluster resolution: 1.2
optimal score: 0.6799718931510478
BRAS...

seed           8.000000
BAMI           0.679972
CASW           0.648844
SCGRAPHM       0.407732
ISOLISI        0.957099
BRAS           0.671626
KBET           0.653842
CPCR           0.862366
bio_score      0.673412
batch_score    0.729278
joint_score    0.695758
dtype: float64

===== seed 9 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:19<09:29, 19.63s/it]

  7%|▋         | 2/30 [00:38<09:02, 19.38s/it]

 10%|█         | 3/30 [00:56<08:24, 18.68s/it]

 13%|█▎        | 4/30 [01:15<08:11, 18.90s/it]

 17%|█▋        | 5/30 [01:34<07:47, 18.71s/it]

 20%|██        | 6/30 [01:52<07:28, 18.67s/it]

 23%|██▎       | 7/30 [02:08<06:48, 17.75s/it]

 27%|██▋       | 8/30 [02:27<06:36, 18.02s/it]

 30%|███       | 9/30 [02:47<06:29, 18.57s/it]

 33%|███▎      | 10/30 [03:04<06:02, 18.13s/it]

 37%|███▋      | 11/30 [03:22<05:47, 18.29s/it]

 40%|████      | 12/30 [03:41<05:29, 18.31s/it]

 43%|████▎     | 13/30 [04:01<05:22, 18.98s/it]

 47%|████▋     | 14/30 [04:20<05:03, 19.00s/it]

 50%|█████     | 15/30 [04:38<04:40, 18.68s/it]

 53%|█████▎    | 16/30 [04:54<04:10, 17.89s/it]

 57%|█████▋    | 17/30 [05:13<03:55, 18.15s/it]

 60%|██████    | 18/30 [05:31<03:38, 18.19s/it]

 63%|██████▎   | 19/30 [05:51<03:23, 18.51s/it]

 67%|██████▋   | 20/30 [06:09<03:03, 18.40s/it]

 70%|███████   | 21/30 [06:27<02:46, 18.47s/it]

 73%|███████▎  | 22/30 [06:44<02:24, 18.05s/it]

 77%|███████▋  | 23/30 [07:04<02:08, 18.39s/it]

 80%|████████  | 24/30 [07:23<01:51, 18.59s/it]

 83%|████████▎ | 25/30 [07:42<01:33, 18.71s/it]

 87%|████████▋ | 26/30 [08:01<01:15, 18.82s/it]

 90%|█████████ | 27/30 [08:20<00:56, 18.95s/it]

 93%|█████████▎| 28/30 [08:40<00:38, 19.30s/it]

 97%|█████████▋| 29/30 [08:59<00:19, 19.24s/it]

100%|██████████| 30/30 [09:18<00:00, 19.21s/it]

100%|██████████| 30/30 [09:18<00:00, 18.63s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 13.92it/s]

 44%|████▍     | 4/9 [00:00<00:00, 12.54it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 15.17it/s]

100%|██████████| 9/9 [00:00<00:00, 15.61it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.712371502149123

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7111355573466612

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7033756569904467

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.704176172197125

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6954853997159097

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6860397027369312

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6776691641764812

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.676736250939477

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6734322977439862

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.675346533778468

optimised clustering against liger_metric_label
optimal cluster resolution: 0.2
optimal score: 0.712371502149123
BRAS...

seed           9.000000
BAMI           0.712372
CASW           0.627279
SCGRAPHM       0.409365
ISOLISI        0.948630
BRAS           0.746140
KBET           0.637190
CPCR           0.902280
bio_score      0.674412
batch_score    0.761870
joint_score    0.709395
dtype: float64

===== seed 10 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=20 value_lambda=5.0 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:19<09:23, 19.43s/it]

  7%|▋         | 2/30 [00:41<09:42, 20.79s/it]

 10%|█         | 3/30 [01:00<09:00, 20.01s/it]

 13%|█▎        | 4/30 [01:19<08:28, 19.55s/it]

 17%|█▋        | 5/30 [01:37<07:59, 19.19s/it]

 20%|██        | 6/30 [01:57<07:47, 19.48s/it]

 23%|██▎       | 7/30 [02:17<07:26, 19.43s/it]

 27%|██▋       | 8/30 [02:34<06:51, 18.69s/it]

 30%|███       | 9/30 [02:53<06:37, 18.91s/it]

 33%|███▎      | 10/30 [03:12<06:18, 18.94s/it]

 37%|███▋      | 11/30 [03:31<05:58, 18.85s/it]

 40%|████      | 12/30 [03:51<05:46, 19.25s/it]

 43%|████▎     | 13/30 [04:09<05:23, 19.05s/it]

 47%|████▋     | 14/30 [04:29<05:05, 19.09s/it]

 50%|█████     | 15/30 [04:47<04:43, 18.90s/it]

 53%|█████▎    | 16/30 [05:06<04:22, 18.77s/it]

 57%|█████▋    | 17/30 [05:26<04:09, 19.23s/it]

 60%|██████    | 18/30 [05:45<03:51, 19.30s/it]

 63%|██████▎   | 19/30 [06:03<03:27, 18.91s/it]

 67%|██████▋   | 20/30 [06:22<03:08, 18.80s/it]

 70%|███████   | 21/30 [06:41<02:50, 18.91s/it]

 73%|███████▎  | 22/30 [06:59<02:29, 18.65s/it]

 77%|███████▋  | 23/30 [07:18<02:11, 18.72s/it]

 80%|████████  | 24/30 [07:37<01:53, 18.97s/it]

 83%|████████▎ | 25/30 [07:59<01:38, 19.80s/it]

 87%|████████▋ | 26/30 [08:21<01:21, 20.38s/it]

 90%|█████████ | 27/30 [08:42<01:01, 20.48s/it]

 93%|█████████▎| 28/30 [09:00<00:39, 19.98s/it]

 97%|█████████▋| 29/30 [09:19<00:19, 19.55s/it]

100%|██████████| 30/30 [09:37<00:00, 19.07s/it]

100%|██████████| 30/30 [09:37<00:00, 19.25s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 11.29it/s]

 44%|████▍     | 4/9 [00:00<00:00,  7.62it/s]

 67%|██████▋   | 6/9 [00:00<00:00, 10.61it/s]

 89%|████████▉ | 8/9 [00:00<00:00, 11.33it/s]

100%|██████████| 9/9 [00:00<00:00, 10.66it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6664771675217547

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6845312936503195

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6744281861443263

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6670701380737001

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6641014757788778

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6559973616849553

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6528160974519929

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.647191672260759

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6470078271487094

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6428729880954557

optimised clustering against liger_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6845312936503195
BRAS...

seed           10.000000
BAMI            0.684531
CASW            0.609103
SCGRAPHM        0.388067
ISOLISI         0.821953
BRAS            0.743364
KBET            0.638016
CPCR            0.855375
bio_score       0.625914
batch_score     0.745585
joint_score     0.673782
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,ISOLISI,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.702451,0.621262,0.467011,0.869113,0.719616,0.632439,0.887774,0.664959,0.746610,0.697619
1,2,0.715295,0.651889,0.424300,0.743970,0.700741,0.644083,0.877965,0.633864,0.740930,0.676690
2,3,0.703411,0.630812,0.539123,0.888613,0.721760,0.638021,0.879104,0.690490,0.746295,0.712812
3,4,0.683879,0.619423,0.485865,0.848413,0.710803,0.665899,0.867949,0.659395,0.748217,0.694924
4,5,0.724227,0.662620,0.418117,0.962172,0.710237,0.624637,0.880651,0.691784,0.738508,0.710474
5,6,0.706394,0.634714,0.411769,0.924355,0.714133,0.618132,0.873926,0.669308,0.735397,0.695744
6,7,0.660681,0.649574,0.443274,0.903313,0.701237,0.613125,0.857903,0.664211,0.724088,0.688162
7,8,0.679972,0.648844,0.407732,0.957099,0.671626,0.653842,0.862366,0.673412,0.729278,0.695758
8,9,0.712372,0.627279,0.409365,0.948630,0.746140,0.637190,0.902280,0.674412,0.761870,0.709395
9,10,0.684531,0.609103,0.388067,0.821953,0.743364,0.638016,0.855375,0.625914,0.745585,0.673782

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.697321  0.018458  0.660681  0.724227
CASW         0.635552  0.016212  0.609103  0.662620
SCGRAPHM     0.439462  0.043434  0.388067  0.539123
ISOLISI      0.886763  0.065210  0.743970  0.962172
BRAS         0.713966  0.020361  0.671626  0.746140
KBET         0.636538  0.015062  0.613125  0.665899
CPCR         0.874529  0.013604  0.855375  0.902280
bio_score    0.664775  0.020184  0.625914  0.691784
batch_score  0.741678  0.010122  0.724088  0.761870
joint_score  0.695536  0.012654  0.673782  0.712812