# LIGER best - human_pancreas

Seeds: `1-10`

Metrics: BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR

In [1]:
import gc
import importlib.util
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics'
os.environ["R_HOME"] = f"{PROJECT_ROOT}/CondaEnv/pyliger_env/lib/R"
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd

OPTIMIZER_PATH = (
    f"{PROJECT_ROOT}/scripts/optuna_multi_metrics/"
    "optuna_liger/optimize_liger_multi_metrics.py"
)
optimizer_spec = importlib.util.spec_from_file_location(
    "liger_opt",
    OPTIMIZER_PATH,
)
if optimizer_spec is None or optimizer_spec.loader is None:
    raise ImportError(f"Cannot load LIGER optimizer: {OPTIMIZER_PATH}")
liger_opt = importlib.util.module_from_spec(optimizer_spec)
sys.modules[optimizer_spec.name] = liger_opt
optimizer_spec.loader.exec_module(liger_opt)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATASET_NAME = 'human_pancreas'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'tech'
LABEL_KEY = 'celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

SEEDS = tuple(range(1, 11))
MODE = "core"
LAYER = "counts"
N_NEIGHBORS = 15
EMBED_KEY = "X_liger"

liger_opt.DATASET_NAME = DATASET_NAME
liger_opt.DATA_PATH = DATA_PATH
liger_opt.BATCH_KEY = BATCH_KEY
liger_opt.LABEL_KEY = LABEL_KEY
liger_opt.MODE = MODE
liger_opt.LAYER = LAYER
liger_opt.USE_BAMI = "BAMI" in SELECTED_METRICS
liger_opt.USE_CASW = "CASW" in SELECTED_METRICS
liger_opt.USE_SCGRAPHM = "SCGRAPHM" in SELECTED_METRICS
liger_opt.USE_TRAJ = "TRAJ" in SELECTED_METRICS
liger_opt.USE_ISOLISI = "ISOLISI" in SELECTED_METRICS
liger_opt.USE_BRAS = "BRAS" in SELECTED_METRICS
liger_opt.USE_KBET = "KBET" in SELECTED_METRICS
liger_opt.USE_CPCR = "CPCR" in SELECTED_METRICS

assert DATASET_NAME == 'human_pancreas'
assert BATCH_KEY == 'tech'
assert LABEL_KEY == 'celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'ISOLISI', 'BRAS', 'KBET', 'CPCR')
assert SEEDS == tuple(range(1, 11))
assert liger_opt.CORE_MAX_ITERS == 30
assert liger_opt.N_NEIGHBORS == N_NEIGHBORS
assert liger_opt.EMBED_KEY == EMBED_KEY

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(SEEDS),
        "mode": MODE,
        "layer": LAYER,
    },
    name="configuration",
)

dataset                                         human_pancreas
data_path    /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                 tech
label_key                                             celltype
metrics      [BAMI, CASW, SCGRAPHM, ISOLISI, BRAS, KBET, CPCR]
seeds                          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mode                                                      core
layer                                                   counts
Name: configuration, dtype: object

In [3]:
liger_opt.validate_metric_dependencies()
liger_opt.validate_configuration(list(SELECTED_METRICS))
liger_opt.validate_dataset_contents()

Dataset preflight: n_obs=16382 n_batches=9 n_labels=14
ISOLISI preflight: min_batch_coverage=4 isolated_labels=['t_cell']
CPCR preflight: eligible_labels=9

In [4]:
OPTUNA_STUDY_NAME = 'liger_human_pancreas_joint_expanded_metrics_scgraphm_v1'
OPTUNA_BEST_TRIAL = 31
OPTUNA_BEST_VALUE = 0.7222477364665002
OPTUNA_BEST_PARAMS = {'k': 24, 'value_lambda': 7.1943184973831205}

LIGER_BEST_ARGS = {
    "k": OPTUNA_BEST_PARAMS["k"],
    "value_lambda": OPTUNA_BEST_PARAMS["value_lambda"],
    "max_iters": 30,
    "mode": "core",
    "layer": "counts",
}


def run_liger_best(adata, seed):
    return liger_opt.run_liger(
        adata=adata,
        k=LIGER_BEST_ARGS["k"],
        lam=LIGER_BEST_ARGS["value_lambda"],
        max_iterations=LIGER_BEST_ARGS["max_iters"],
        mode=LIGER_BEST_ARGS["mode"],
        layer=LIGER_BEST_ARGS["layer"],
        seed=seed,
    )


pd.Series(
    {
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **LIGER_BEST_ARGS,
    },
    name="best_setting",
)

study           liger_human_pancreas_joint_expanded_metrics_sc...
best_trial                                                     31
best_value                                               0.722248
k                                                              24
value_lambda                                             7.194318
max_iters                                                      30
mode                                                         core
layer                                                      counts
Name: best_setting, dtype: object

In [5]:
def compute_joint_metrics(adata_raw, adata_int):
    return liger_opt.compute_joint_metrics(adata_raw, adata_int)

In [6]:
results = []

for seed in SEEDS:
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_liger_best(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 1 =====

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/dufunc.py:344: NumbaWarning: Compilation requested for previously compiled argument types ((uint32,)). This has no effect and perhaps indicates a bug in the calling code (compiling a ufunc more than once for the same signature

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.

Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.

Removing 2910 genes not expressing in inDrop3.

Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=1

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [03:19<1:36:39, 199.99s/it]

  7%|▋         | 2/30 [05:34<1:15:16, 161.32s/it]

 10%|█         | 3/30 [06:47<54:24, 120.89s/it]

 13%|█▎        | 4/30 [08:14<46:41, 107.76s/it]

 17%|█▋        | 5/30 [09:43<42:03, 100.94s/it]

 20%|██        | 6/30 [12:11<46:44, 116.86s/it]

 23%|██▎       | 7/30 [14:13<45:24, 118.46s/it]

 27%|██▋       | 8/30 [14:53<34:18, 93.56s/it]

 30%|███       | 9/30 [15:16<25:06, 71.73s/it]

 33%|███▎      | 10/30 [15:41<19:04, 57.20s/it]

 37%|███▋      | 11/30 [16:04<14:46, 46.65s/it]

 40%|████      | 12/30 [16:28<11:58, 39.94s/it]

 43%|████▎     | 13/30 [17:08<11:15, 39.71s/it]

 47%|████▋     | 14/30 [17:56<11:18, 42.39s/it]

 50%|█████     | 15/30 [19:11<13:00, 52.03s/it]

 53%|█████▎    | 16/30 [19:39<10:28, 44.93s/it]

 57%|█████▋    | 17/30 [20:03<08:23, 38.70s/it]

 60%|██████    | 18/30 [20:29<06:58, 34.84s/it]

 63%|██████▎   | 19/30 [20:58<06:03, 33.01s/it]

 67%|██████▋   | 20/30 [22:07<07:17, 43.75s/it]

 70%|███████   | 21/30 [22:32<05:44, 38.26s/it]

 73%|███████▎  | 22/30 [22:58<04:35, 34.49s/it]

 77%|███████▋  | 23/30 [23:22<03:40, 31.55s/it]

 80%|████████  | 24/30 [23:47<02:56, 29.43s/it]

 83%|████████▎ | 25/30 [24:13<02:21, 28.31s/it]

 87%|████████▋ | 26/30 [24:38<01:49, 27.36s/it]

 90%|█████████ | 27/30 [25:03<01:20, 26.69s/it]

 93%|█████████▎| 28/30 [25:28<00:52, 26.16s/it]

 97%|█████████▋| 29/30 [25:52<00:25, 25.66s/it]

100%|██████████| 30/30 [26:18<00:00, 25.61s/it]

100%|██████████| 30/30 [26:18<00:00, 52.61s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=1

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 13.18it/s]

 44%|████▍     | 4/9 [00:00<00:00,  5.68it/s]

 78%|███████▊  | 7/9 [00:01<00:00,  5.35it/s]

100%|██████████| 9/9 [00:01<00:00,  4.63it/s]

100%|██████████| 9/9 [00:01<00:00,  5.07it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.

resolution: 0.2, bAMI: 0.7144856072962852

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7325488616822042

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7495212147657205

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7419316660884363

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7319898657119576

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7291811979623208

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7248714415478088

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7264587376480787

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7202001817829852

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7143104970276998

WARNING:2026-07-23 16:28:22,761:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7495212147657205
BRAS...

seed           1.000000
BAMI           0.749521
CASW           0.641835
SCGRAPHM       0.482737
ISOLISI        0.948630
BRAS           0.723537
KBET           0.666964
CPCR           0.850793
bio_score      0.705681
batch_score    0.747098
joint_score    0.722248
dtype: float64

===== seed 2 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.

Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.

Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.
Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=2

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:51<24:50, 51.38s/it]

  7%|▋         | 2/30 [01:45<24:51, 53.27s/it]

 10%|█         | 3/30 [02:38<23:47, 52.88s/it]

 13%|█▎        | 4/30 [03:26<22:07, 51.04s/it]

 17%|█▋        | 5/30 [04:13<20:40, 49.62s/it]

 20%|██        | 6/30 [05:03<19:50, 49.59s/it]

 23%|██▎       | 7/30 [05:52<18:55, 49.38s/it]

 27%|██▋       | 8/30 [06:40<17:59, 49.08s/it]

 30%|███       | 9/30 [07:28<17:04, 48.80s/it]

 33%|███▎      | 10/30 [08:17<16:13, 48.68s/it]

 37%|███▋      | 11/30 [09:06<15:26, 48.75s/it]

 40%|████      | 12/30 [09:52<14:26, 48.12s/it]

 43%|████▎     | 13/30 [10:40<13:34, 47.89s/it]

 47%|████▋     | 14/30 [11:26<12:36, 47.28s/it]

 50%|█████     | 15/30 [12:11<11:40, 46.72s/it]

 53%|█████▎    | 16/30 [12:55<10:43, 45.96s/it]

 57%|█████▋    | 17/30 [13:41<09:56, 45.86s/it]

 60%|██████    | 18/30 [14:26<09:09, 45.76s/it]

 63%|██████▎   | 19/30 [15:12<08:23, 45.74s/it]

 67%|██████▋   | 20/30 [15:56<07:33, 45.34s/it]

 70%|███████   | 21/30 [16:42<06:48, 45.41s/it]

 73%|███████▎  | 22/30 [17:28<06:05, 45.70s/it]

 77%|███████▋  | 23/30 [18:13<05:17, 45.41s/it]

 80%|████████  | 24/30 [18:53<04:23, 43.87s/it]

 83%|████████▎ | 25/30 [19:33<03:33, 42.66s/it]

 87%|████████▋ | 26/30 [20:15<02:49, 42.34s/it]

 90%|█████████ | 27/30 [20:56<02:05, 41.98s/it]

 93%|█████████▎| 28/30 [21:37<01:23, 41.61s/it]

 97%|█████████▋| 29/30 [22:20<00:41, 42.00s/it]

100%|██████████| 30/30 [23:05<00:00, 42.98s/it]

100%|██████████| 30/30 [23:05<00:00, 46.18s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=2

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.61it/s]

 44%|████▍     | 4/9 [00:00<00:00, 11.13it/s]

 67%|██████▋   | 6/9 [00:00<00:00, 13.94it/s]

 89%|████████▉ | 8/9 [00:00<00:00, 14.52it/s]

100%|██████████| 9/9 [00:00<00:00, 13.83it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7115867395218268

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.707479504980861

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7242268165450371

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7107518868759672

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7087561823343462

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7039742772903088

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7021776013670596

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6994971079331418

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.695868114820476

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.69660106856767

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7242268165450371
BRAS...

seed           2.000000
BAMI           0.724227
CASW           0.656162
SCGRAPHM       0.394569
ISOLISI        0.909228
BRAS           0.731187
KBET           0.638978
CPCR           0.859166
bio_score      0.671046
batch_score    0.743110
joint_score    0.699872
dtype: float64

===== seed 3 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.

Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.
Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=3

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [01:28<42:42, 88.35s/it]

  7%|▋         | 2/30 [03:19<47:30, 101.82s/it]

 10%|█         | 3/30 [04:08<34:54, 77.59s/it]

 13%|█▎        | 4/30 [05:36<35:27, 81.81s/it]

 17%|█▋        | 5/30 [07:33<39:25, 94.61s/it]

 20%|██        | 6/30 [10:02<45:12, 113.04s/it]

 23%|██▎       | 7/30 [10:48<34:51, 90.95s/it]

 27%|██▋       | 8/30 [11:34<28:07, 76.69s/it]

 30%|███       | 9/30 [12:11<22:33, 64.46s/it]

 33%|███▎      | 10/30 [12:40<17:46, 53.35s/it]

 37%|███▋      | 11/30 [13:11<14:42, 46.43s/it]

 40%|████      | 12/30 [13:42<12:33, 41.87s/it]

 43%|████▎     | 13/30 [14:14<11:02, 38.96s/it]

 47%|████▋     | 14/30 [14:48<09:59, 37.46s/it]

 50%|█████     | 15/30 [15:23<09:10, 36.72s/it]

 53%|█████▎    | 16/30 [16:02<08:40, 37.18s/it]

 57%|█████▋    | 17/30 [16:44<08:24, 38.77s/it]

 60%|██████    | 18/30 [17:29<08:07, 40.59s/it]

 63%|██████▎   | 19/30 [18:13<07:37, 41.59s/it]

 67%|██████▋   | 20/30 [18:58<07:06, 42.66s/it]

 70%|███████   | 21/30 [19:39<06:20, 42.29s/it]

 73%|███████▎  | 22/30 [20:22<05:38, 42.36s/it]

 77%|███████▋  | 23/30 [21:06<05:00, 42.88s/it]

 80%|████████  | 24/30 [21:50<04:18, 43.10s/it]

 83%|████████▎ | 25/30 [22:33<03:35, 43.10s/it]

 87%|████████▋ | 26/30 [23:14<02:50, 42.70s/it]

 90%|█████████ | 27/30 [23:57<02:08, 42.76s/it]

 93%|█████████▎| 28/30 [24:41<01:26, 43.02s/it]

 97%|█████████▋| 29/30 [25:25<00:43, 43.34s/it]

100%|██████████| 30/30 [26:10<00:00, 43.69s/it]

100%|██████████| 30/30 [26:10<00:00, 52.34s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=3

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.19it/s]

 44%|████▍     | 4/9 [00:00<00:00, 10.96it/s]

 67%|██████▋   | 6/9 [00:00<00:00, 13.69it/s]

 89%|████████▉ | 8/9 [00:00<00:00, 14.49it/s]

100%|██████████| 9/9 [00:00<00:00, 13.81it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6443498614236333

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6779515501161507

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6960859075798275

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6846513725398276

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6769548032408252

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6733747688206747

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6665391524363126

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.666577198120897

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6598149592398086

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6641128467462821

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6960859075798275
BRAS...

seed           3.000000
BAMI           0.696086
CASW           0.624469
SCGRAPHM       0.424694
ISOLISI        0.882693
BRAS           0.691277
KBET           0.608915
CPCR           0.859246
bio_score      0.656986
batch_score    0.719813
joint_score    0.682116
dtype: float64

===== seed 4 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.

Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.

Removing 2032 genes not expressing in smarter.
Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=4

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:47<22:49, 47.21s/it]

  7%|▋         | 2/30 [01:35<22:17, 47.77s/it]

 10%|█         | 3/30 [02:21<21:10, 47.06s/it]

 13%|█▎        | 4/30 [03:03<19:35, 45.21s/it]

 17%|█▋        | 5/30 [03:39<17:24, 41.79s/it]

 20%|██        | 6/30 [04:14<15:47, 39.49s/it]

 23%|██▎       | 7/30 [04:50<14:41, 38.34s/it]

 27%|██▋       | 8/30 [05:27<13:52, 37.83s/it]

 30%|███       | 9/30 [06:03<13:00, 37.17s/it]

 33%|███▎      | 10/30 [06:39<12:19, 36.95s/it]

 37%|███▋      | 11/30 [07:15<11:36, 36.68s/it]

 40%|████      | 12/30 [07:49<10:45, 35.83s/it]

 43%|████▎     | 13/30 [08:24<10:05, 35.60s/it]

 47%|████▋     | 14/30 [08:59<09:26, 35.39s/it]

 50%|█████     | 15/30 [09:33<08:46, 35.07s/it]

 53%|█████▎    | 16/30 [10:08<08:09, 34.97s/it]

 57%|█████▋    | 17/30 [10:43<07:32, 34.84s/it]

 60%|██████    | 18/30 [11:16<06:52, 34.40s/it]

 63%|██████▎   | 19/30 [11:49<06:12, 33.84s/it]

 67%|██████▋   | 20/30 [12:22<05:37, 33.77s/it]

 70%|███████   | 21/30 [12:57<05:05, 33.95s/it]

 73%|███████▎  | 22/30 [13:33<04:37, 34.73s/it]

 77%|███████▋  | 23/30 [14:08<04:03, 34.77s/it]

 80%|████████  | 24/30 [14:42<03:27, 34.52s/it]

 83%|████████▎ | 25/30 [15:15<02:50, 34.14s/it]

 87%|████████▋ | 26/30 [15:52<02:19, 34.83s/it]

 90%|█████████ | 27/30 [16:32<01:49, 36.46s/it]

 93%|█████████▎| 28/30 [17:11<01:14, 37.33s/it]

 97%|█████████▋| 29/30 [17:49<00:37, 37.33s/it]

100%|██████████| 30/30 [18:25<00:00, 37.11s/it]

100%|██████████| 30/30 [18:25<00:00, 36.85s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=4

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 11.97it/s]

 44%|████▍     | 4/9 [00:00<00:00, 10.33it/s]

 67%|██████▋   | 6/9 [00:00<00:00, 13.14it/s]

 89%|████████▉ | 8/9 [00:00<00:00, 10.94it/s]

100%|██████████| 9/9 [00:00<00:00, 10.38it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6798717255835082

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6823770293987533

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6992502159934177

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6930936228072562

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.698155173439062

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6920390196554256

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6839241347872694

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.677078356366785

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6729978205208349

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6641092964522282

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6992502159934177
BRAS...

seed           4.000000
BAMI           0.699250
CASW           0.634973
SCGRAPHM       0.461559
ISOLISI        0.954033
BRAS           0.748331
KBET           0.640884
CPCR           0.894333
bio_score      0.687454
batch_score    0.761183
joint_score    0.716945
dtype: float64

===== seed 5 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.

Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.

Removing 2032 genes not expressing in smarter.
Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=5

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:47<22:44, 47.05s/it]

  7%|▋         | 2/30 [01:35<22:12, 47.59s/it]

 10%|█         | 3/30 [02:20<20:57, 46.58s/it]

 13%|█▎        | 4/30 [03:05<19:54, 45.93s/it]

 17%|█▋        | 5/30 [03:51<19:05, 45.83s/it]

 20%|██        | 6/30 [04:37<18:22, 45.92s/it]

 23%|██▎       | 7/30 [05:23<17:36, 45.95s/it]

 27%|██▋       | 8/30 [06:09<16:57, 46.23s/it]

 30%|███       | 9/30 [06:48<15:23, 43.99s/it]

 33%|███▎      | 10/30 [07:17<13:02, 39.15s/it]

 37%|███▋      | 11/30 [07:44<11:16, 35.63s/it]

 40%|████      | 12/30 [08:14<10:06, 33.70s/it]

 43%|████▎     | 13/30 [08:44<09:16, 32.72s/it]

 47%|████▋     | 14/30 [09:13<08:25, 31.59s/it]

 50%|█████     | 15/30 [09:42<07:42, 30.86s/it]

 53%|█████▎    | 16/30 [10:14<07:14, 31.01s/it]

 57%|█████▋    | 17/30 [10:55<07:23, 34.12s/it]

 60%|██████    | 18/30 [11:37<07:18, 36.57s/it]

 63%|██████▎   | 19/30 [12:18<06:56, 37.85s/it]

 67%|██████▋   | 20/30 [12:59<06:27, 38.76s/it]

 70%|███████   | 21/30 [13:39<05:51, 39.04s/it]

 73%|███████▎  | 22/30 [14:19<05:14, 39.32s/it]

 77%|███████▋  | 23/30 [14:58<04:35, 39.35s/it]

 80%|████████  | 24/30 [15:38<03:56, 39.40s/it]

 83%|████████▎ | 25/30 [16:18<03:18, 39.63s/it]

 87%|████████▋ | 26/30 [17:01<02:42, 40.67s/it]

 90%|█████████ | 27/30 [17:43<02:03, 41.17s/it]

 93%|█████████▎| 28/30 [18:26<01:23, 41.66s/it]

 97%|█████████▋| 29/30 [19:09<00:42, 42.06s/it]

100%|██████████| 30/30 [19:51<00:00, 41.89s/it]

100%|██████████| 30/30 [19:51<00:00, 39.70s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=5

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 11.77it/s]

 44%|████▍     | 4/9 [00:00<00:00, 10.46it/s]

 67%|██████▋   | 6/9 [00:00<00:00, 13.02it/s]

 89%|████████▉ | 8/9 [00:00<00:00, 13.91it/s]

100%|██████████| 9/9 [00:00<00:00, 12.98it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6985092983460324

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6995058367463447

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7126107028843324

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7104281930180554

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7026667812870712

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.706688963256076

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6884284865291908

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6871545836600962

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6868866504532773

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6832000457032713

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7126107028843324
BRAS...

seed           5.000000
BAMI           0.712611
CASW           0.651664
SCGRAPHM       0.391117
ISOLISI        0.864614
BRAS           0.733781
KBET           0.682429
CPCR           0.893991
bio_score      0.655001
batch_score    0.770067
joint_score    0.701028
dtype: float64

===== seed 6 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.

Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.
Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=6

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:44<21:38, 44.76s/it]

  7%|▋         | 2/30 [01:32<21:40, 46.44s/it]

 10%|█         | 3/30 [02:17<20:39, 45.90s/it]

 13%|█▎        | 4/30 [05:30<45:03, 103.97s/it]

 17%|█▋        | 5/30 [06:05<32:54, 78.97s/it]

 20%|██        | 6/30 [06:43<25:59, 64.96s/it]

 23%|██▎       | 7/30 [07:19<21:21, 55.72s/it]

 27%|██▋       | 8/30 [07:55<18:06, 49.40s/it]

 30%|███       | 9/30 [08:30<15:45, 45.02s/it]

 33%|███▎      | 10/30 [09:07<14:10, 42.54s/it]

 37%|███▋      | 11/30 [09:50<13:29, 42.59s/it]

 40%|████      | 12/30 [10:33<12:49, 42.73s/it]

 43%|████▎     | 13/30 [11:17<12:10, 42.99s/it]

 47%|████▋     | 14/30 [12:00<11:30, 43.18s/it]

 50%|█████     | 15/30 [18:39<37:35, 150.39s/it]

 53%|█████▎    | 16/30 [23:31<44:59, 192.82s/it]

 57%|█████▋    | 17/30 [23:58<31:00, 143.13s/it]

 60%|██████    | 18/30 [24:27<21:45, 108.79s/it]

 63%|██████▎   | 19/30 [24:56<15:32, 84.77s/it]

 67%|██████▋   | 20/30 [25:27<11:25, 68.54s/it]

 70%|███████   | 21/30 [25:58<08:35, 57.26s/it]

 73%|███████▎  | 22/30 [26:31<06:41, 50.25s/it]

 77%|███████▋  | 23/30 [27:01<05:09, 44.15s/it]

 80%|████████  | 24/30 [27:45<04:23, 43.85s/it]

 83%|████████▎ | 25/30 [28:28<03:38, 43.71s/it]

 87%|████████▋ | 26/30 [29:12<02:55, 43.78s/it]

 90%|█████████ | 27/30 [29:56<02:12, 44.02s/it]

 93%|█████████▎| 28/30 [30:39<01:27, 43.61s/it]

 97%|█████████▋| 29/30 [31:21<00:43, 43.12s/it]

100%|██████████| 30/30 [32:04<00:00, 43.05s/it]

100%|██████████| 30/30 [32:04<00:00, 64.15s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=6

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.21it/s]

 44%|████▍     | 4/9 [00:00<00:00,  5.74it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.50it/s]

 89%|████████▉ | 8/9 [00:00<00:00, 10.39it/s]

100%|██████████| 9/9 [00:00<00:00,  9.21it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7024075679311093

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6998322127970102

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7156200519904924

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7102682124720736

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7046644231529313

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.704345500674494

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6968888828541436

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6973343541411673

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6937794891850184

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6924959581120677

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7156200519904924
BRAS...

seed           6.000000
BAMI           0.715620
CASW           0.649403
SCGRAPHM       0.401541
ISOLISI        0.897554
BRAS           0.727209
KBET           0.643906
CPCR           0.861324
bio_score      0.666030
batch_score    0.744146
joint_score    0.697276
dtype: float64

===== seed 7 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.

Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=7

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:44<21:37, 44.73s/it]

  7%|▋         | 2/30 [01:30<21:02, 45.08s/it]

 10%|█         | 3/30 [02:14<20:10, 44.83s/it]

 13%|█▎        | 4/30 [08:36<1:17:01, 177.76s/it]

 17%|█▋        | 5/30 [10:02<1:00:16, 144.66s/it]

 20%|██        | 6/30 [10:36<42:51, 107.14s/it]

 23%|██▎       | 7/30 [11:12<32:12, 84.03s/it]

 27%|██▋       | 8/30 [11:46<24:57, 68.08s/it]

 30%|███       | 9/30 [12:19<20:00, 57.18s/it]

 33%|███▎      | 10/30 [12:53<16:37, 49.86s/it]

 37%|███▋      | 11/30 [13:31<14:37, 46.19s/it]

 40%|████      | 12/30 [14:13<13:26, 44.82s/it]

 43%|████▎     | 13/30 [14:53<12:19, 43.51s/it]

 47%|████▋     | 14/30 [15:33<11:20, 42.56s/it]

 50%|█████     | 15/30 [16:13<10:25, 41.69s/it]

 53%|█████▎    | 16/30 [16:55<09:42, 41.63s/it]

 57%|█████▋    | 17/30 [17:36<09:00, 41.57s/it]

 60%|██████    | 18/30 [18:18<08:18, 41.56s/it]

 63%|██████▎   | 19/30 [18:59<07:36, 41.52s/it]

 67%|██████▋   | 20/30 [19:40<06:54, 41.47s/it]

 70%|███████   | 21/30 [20:21<06:11, 41.24s/it]

 73%|███████▎  | 22/30 [21:03<05:31, 41.42s/it]

 77%|███████▋  | 23/30 [21:44<04:48, 41.26s/it]

 80%|████████  | 24/30 [22:25<04:07, 41.32s/it]

 83%|████████▎ | 25/30 [23:06<03:25, 41.15s/it]

 87%|████████▋ | 26/30 [23:47<02:44, 41.18s/it]

 90%|█████████ | 27/30 [24:43<02:16, 45.47s/it]

 93%|█████████▎| 28/30 [25:24<01:28, 44.11s/it]

 97%|█████████▋| 29/30 [25:58<00:41, 41.27s/it]

100%|██████████| 30/30 [26:31<00:00, 38.57s/it]

100%|██████████| 30/30 [26:31<00:00, 53.03s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=7

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 10.72it/s]

 44%|████▍     | 4/9 [00:00<00:00,  5.05it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.60it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  9.49it/s]

100%|██████████| 9/9 [00:01<00:00,  8.72it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6381025740663089

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6838477290524284

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6779473453857675

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6994312017029968

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6956156040018848

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6896003869828934

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6883549949434947

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6844400977841968

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6839551921122521

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.679852579335527

optimised clustering against liger_metric_label
optimal cluster resolution: 0.8
optimal score: 0.6994312017029968
BRAS...

seed           7.000000
BAMI           0.699431
CASW           0.624305
SCGRAPHM       0.396261
ISOLISI        0.895558
BRAS           0.732436
KBET           0.662243
CPCR           0.832170
bio_score      0.653889
batch_score    0.742283
joint_score    0.689246
dtype: float64

===== seed 8 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.

Removing 3518 genes not expressing in inDrop1.
Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=8

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:47<23:03, 47.69s/it]

  7%|▋         | 2/30 [01:35<22:16, 47.72s/it]

 10%|█         | 3/30 [02:20<20:53, 46.43s/it]

 13%|█▎        | 4/30 [03:07<20:16, 46.79s/it]

 17%|█▋        | 5/30 [03:53<19:18, 46.32s/it]

 20%|██        | 6/30 [04:39<18:28, 46.17s/it]

 23%|██▎       | 7/30 [05:22<17:22, 45.32s/it]

 27%|██▋       | 8/30 [09:59<43:36, 118.95s/it]

 30%|███       | 9/30 [17:00<1:14:43, 213.50s/it]

 33%|███▎      | 10/30 [17:42<53:32, 160.64s/it]

 37%|███▋      | 11/30 [18:27<39:35, 125.00s/it]

 40%|████      | 12/30 [19:09<29:59, 99.96s/it]

 43%|████▎     | 13/30 [19:51<23:21, 82.45s/it]

 47%|████▋     | 14/30 [20:33<18:42, 70.17s/it]

 50%|█████     | 15/30 [21:14<15:18, 61.26s/it]

 53%|█████▎    | 16/30 [21:54<12:48, 54.86s/it]

 57%|█████▋    | 17/30 [22:36<11:03, 51.01s/it]

 60%|██████    | 18/30 [23:18<09:40, 48.40s/it]

 63%|██████▎   | 19/30 [23:59<08:28, 46.26s/it]

 67%|██████▋   | 20/30 [24:39<07:22, 44.29s/it]

 70%|███████   | 21/30 [25:19<06:25, 42.84s/it]

 73%|███████▎  | 22/30 [25:57<05:33, 41.64s/it]

 77%|███████▋  | 23/30 [26:37<04:47, 41.02s/it]

 80%|████████  | 24/30 [27:16<04:02, 40.39s/it]

 83%|████████▎ | 25/30 [27:56<03:21, 40.24s/it]

 87%|████████▋ | 26/30 [28:37<02:42, 40.55s/it]

 90%|█████████ | 27/30 [29:20<02:03, 41.20s/it]

 93%|█████████▎| 28/30 [30:04<01:24, 42.13s/it]

 97%|█████████▋| 29/30 [30:48<00:42, 42.54s/it]

100%|██████████| 30/30 [31:30<00:00, 42.54s/it]

100%|██████████| 30/30 [31:30<00:00, 63.02s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=8

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 11.65it/s]

 44%|████▍     | 4/9 [00:00<00:00,  5.54it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  8.24it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  9.99it/s]

100%|██████████| 9/9 [00:00<00:00,  9.31it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6852032076141843

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7172453370177448

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7393323611326856

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7313335547579176

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7207958099732845

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7177125091164034

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7147820943084434

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.707548600393598

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7036610598044694

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.7024304753118872

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.7393323611326856
BRAS...

seed           8.000000
BAMI           0.739332
CASW           0.649495
SCGRAPHM       0.381866
ISOLISI        0.879271
BRAS           0.720716
KBET           0.644559
CPCR           0.834376
bio_score      0.662491
batch_score    0.733217
joint_score    0.690781
dtype: float64

===== seed 9 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.

Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.

Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=9

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:46<22:29, 46.54s/it]

  7%|▋         | 2/30 [01:32<21:33, 46.19s/it]

 10%|█         | 3/30 [08:45<1:40:14, 222.76s/it]

 13%|█▎        | 4/30 [09:53<1:10:07, 161.84s/it]

 17%|█▋        | 5/30 [10:34<49:10, 118.03s/it]

 20%|██        | 6/30 [11:14<36:42, 91.78s/it]

 23%|██▎       | 7/30 [11:57<29:03, 75.79s/it]

 27%|██▋       | 8/30 [12:41<24:02, 65.56s/it]

 30%|███       | 9/30 [13:25<20:32, 58.71s/it]

 33%|███▎      | 10/30 [14:07<17:53, 53.67s/it]

 37%|███▋      | 11/30 [14:49<15:53, 50.19s/it]

 40%|████      | 12/30 [15:31<14:18, 47.67s/it]

 43%|████▎     | 13/30 [16:12<12:52, 45.46s/it]

 47%|████▋     | 14/30 [16:54<11:50, 44.39s/it]

 50%|█████     | 15/30 [17:34<10:49, 43.30s/it]

 53%|█████▎    | 16/30 [18:16<10:00, 42.89s/it]

 57%|█████▋    | 17/30 [19:00<09:21, 43.18s/it]

 60%|██████    | 18/30 [19:43<08:38, 43.21s/it]

 63%|██████▎   | 19/30 [21:06<10:06, 55.15s/it]

 67%|██████▋   | 20/30 [21:49<08:35, 51.52s/it]

 70%|███████   | 21/30 [22:47<07:58, 53.21s/it]

 73%|███████▎  | 22/30 [23:32<06:45, 50.74s/it]

 77%|███████▋  | 23/30 [24:16<05:41, 48.83s/it]

 80%|████████  | 24/30 [24:59<04:42, 47.03s/it]

 83%|████████▎ | 25/30 [25:42<03:50, 46.00s/it]

 87%|████████▋ | 26/30 [26:27<03:01, 45.46s/it]

 90%|█████████ | 27/30 [27:10<02:14, 44.88s/it]

 93%|█████████▎| 28/30 [27:54<01:28, 44.48s/it]

 97%|█████████▋| 29/30 [28:38<00:44, 44.46s/it]

100%|██████████| 30/30 [29:25<00:00, 45.14s/it]

100%|██████████| 30/30 [29:25<00:00, 58.84s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=9

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 12.46it/s]

 44%|████▍     | 4/9 [00:00<00:00, 11.32it/s]

 78%|███████▊  | 7/9 [00:00<00:00, 13.74it/s]

100%|██████████| 9/9 [00:00<00:00, 15.19it/s]

100%|██████████| 9/9 [00:00<00:00, 14.15it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6746345736383509

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6857108054006955

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6871815172593878

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6811961305243817

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6772968090628102

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.671464753720927

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6698284765379007

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6710122357389656

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6602690780382126

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6673002594841265

optimised clustering against liger_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6871815172593878
BRAS...

seed           9.000000
BAMI           0.687182
CASW           0.620035
SCGRAPHM       0.538368
ISOLISI        0.789276
BRAS           0.734175
KBET           0.617278
CPCR           0.854880
bio_score      0.658715
batch_score    0.735444
joint_score    0.689407
dtype: float64

===== seed 10 =====

Removing 2011 genes not expressing in celseq.
Removing 2693 genes not expressing in celseq2.
Removing 2724 genes not expressing in fluidigmc1.
Removing 3518 genes not expressing in inDrop1.

Removing 3238 genes not expressing in inDrop2.
Removing 2910 genes not expressing in inDrop3.
Removing 3788 genes not expressing in inDrop4.
Removing 2032 genes not expressing in smarter.
Removing 1286 genes not expressing in smartseq2.

[LIGER PARAMS] function=optimize_ALS k=24 value_lambda=7.1943184973831205 max_iters=30 rand_seed=10

  0%|          | 0/30 [00:00<?, ?it/s]

  3%|▎         | 1/30 [00:44<21:21, 44.18s/it]

  7%|▋         | 2/30 [01:29<20:59, 44.98s/it]

 10%|█         | 3/30 [04:13<44:32, 99.00s/it]

 13%|█▎        | 4/30 [04:54<33:07, 76.45s/it]

 17%|█▋        | 5/30 [05:37<26:49, 64.37s/it]

 20%|██        | 6/30 [06:20<22:45, 56.88s/it]

 23%|██▎       | 7/30 [07:01<19:52, 51.87s/it]

 27%|██▋       | 8/30 [07:45<18:07, 49.42s/it]

 30%|███       | 9/30 [08:27<16:23, 46.85s/it]

 33%|███▎      | 10/30 [09:08<15:03, 45.19s/it]

 37%|███▋      | 11/30 [09:53<14:14, 44.96s/it]

 40%|████      | 12/30 [10:36<13:20, 44.46s/it]

 43%|████▎     | 13/30 [11:24<12:53, 45.49s/it]

 47%|████▋     | 14/30 [12:07<11:55, 44.75s/it]

 50%|█████     | 15/30 [12:51<11:07, 44.49s/it]

 53%|█████▎    | 16/30 [13:35<10:22, 44.50s/it]

 57%|█████▋    | 17/30 [14:19<09:36, 44.38s/it]

 60%|██████    | 18/30 [15:03<08:50, 44.22s/it]

 63%|██████▎   | 19/30 [15:46<08:01, 43.80s/it]

 67%|██████▋   | 20/30 [16:29<07:16, 43.67s/it]

 70%|███████   | 21/30 [17:18<06:47, 45.33s/it]

 73%|███████▎  | 22/30 [18:03<05:59, 44.95s/it]

 77%|███████▋  | 23/30 [18:47<05:12, 44.71s/it]

 80%|████████  | 24/30 [19:39<04:42, 47.03s/it]

 83%|████████▎ | 25/30 [21:00<04:46, 57.20s/it]

 87%|████████▋ | 26/30 [21:56<03:46, 56.71s/it]

 90%|█████████ | 27/30 [22:54<02:51, 57.22s/it]

 93%|█████████▎| 28/30 [24:06<02:03, 61.79s/it]

 97%|█████████▋| 29/30 [24:48<00:55, 55.71s/it]

100%|██████████| 30/30 [25:30<00:00, 51.71s/it]

100%|██████████| 30/30 [25:30<00:00, 51.03s/it]

[LIGER PARAMS] function=quantile_norm rand_seed=10

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/pyliger_env/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:227: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/isolated_labels.py:348: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Skipping epsilon as it has <100 cells
Skipping macrophage as it has <100 cells
Skipping mast as it has <100 cells
Skipping schwann as it has <100 cells
Skipping t_cell as it has <100 cells
Isolated labels CLISI...
isolated labels: no more than 4 batches per label
isolated labels: ['t_cell']

scGraph with Fisher multinomial distance...
Skipped cell type t_cell, due to < 10 cells
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/9 [00:00<?, ?it/s]

 22%|██▏       | 2/9 [00:00<00:00, 11.93it/s]

 44%|████▍     | 4/9 [00:00<00:00,  5.22it/s]

 67%|██████▋   | 6/9 [00:00<00:00,  7.84it/s]

 89%|████████▉ | 8/9 [00:00<00:00,  9.82it/s]

100%|██████████| 9/9 [00:00<00:00,  9.00it/s]

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/sc_graph.py:278: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/kbet.py:296: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.7104023358642712

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7147665865905805

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7096351098304927

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7251083383369786

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7220639785218652

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.7176806861449698

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.7151587948461215

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.7113405081647994

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.7005965872339821

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6975400639137476

optimised clustering against liger_metric_label
optimal cluster resolution: 0.8
optimal score: 0.7251083383369786
BRAS...

seed           10.000000
BAMI            0.725108
CASW            0.651695
SCGRAPHM        0.498447
ISOLISI         0.946913
BRAS            0.700734
KBET            0.664942
CPCR            0.887001
bio_score       0.705541
batch_score     0.750892
joint_score     0.723682
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,ISOLISI,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,1,0.749521,0.641835,0.482737,0.948630,0.723537,0.666964,0.850793,0.705681,0.747098,0.722248
1,2,0.724227,0.656162,0.394569,0.909228,0.731187,0.638978,0.859166,0.671046,0.743110,0.699872
2,3,0.696086,0.624469,0.424694,0.882693,0.691277,0.608915,0.859246,0.656986,0.719813,0.682116
3,4,0.699250,0.634973,0.461559,0.954033,0.748331,0.640884,0.894333,0.687454,0.761183,0.716945
4,5,0.712611,0.651664,0.391117,0.864614,0.733781,0.682429,0.893991,0.655001,0.770067,0.701028
5,6,0.715620,0.649403,0.401541,0.897554,0.727209,0.643906,0.861324,0.666030,0.744146,0.697276
6,7,0.699431,0.624305,0.396261,0.895558,0.732436,0.662243,0.832170,0.653889,0.742283,0.689246
7,8,0.739332,0.649495,0.381866,0.879271,0.720716,0.644559,0.834376,0.662491,0.733217,0.690781
8,9,0.687182,0.620035,0.538368,0.789276,0.734175,0.617278,0.854880,0.658715,0.735444,0.689407
9,10,0.725108,0.651695,0.498447,0.946913,0.700734,0.664942,0.887001,0.705541,0.750892,0.723682

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.714837  0.018971  0.687182  0.749521
CASW         0.640404  0.012751  0.620035  0.656162
SCGRAPHM     0.437116  0.051730  0.381866  0.538368
ISOLISI      0.896777  0.046619  0.789276  0.954033
BRAS         0.724338  0.015957  0.691277  0.748331
KBET         0.647110  0.021585  0.608915  0.682429
CPCR         0.862728  0.021293  0.832170  0.894333
bio_score    0.672283  0.019087  0.653889  0.705681
batch_score  0.744725  0.013434  0.719813  0.770067
joint_score  0.701260  0.014029  0.682116  0.723682