# Scanorama best - mouse_mammary

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

This notebook is intentionally unexecuted.

In [1]:
import gc
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = (
    "/ubc/cs/research/beaver/projects/"
    "Single-cell-integration-metrics"
)
os.environ["R_HOME"] = (
    f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R"
)
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd
import scanorama
import scanpy as sc
import scipy.sparse as sp

from scib.metrics.metrics import metrics

In [2]:
DATASET_NAME = 'mouse_mammary'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'BATCH'
LABEL_KEY = 'celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_NEIGHBORS = 15
N_TOP_HVG = 2000
INTERNAL_DIMRED = 50
BATCH_SIZE = 5000
APPROX = True
UNION = False

EMBED_KEY = "X_scanorama"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "scanorama_metric_batch"
METRIC_LABEL_KEY = "scanorama_metric_label"

assert DATASET_NAME == 'mouse_mammary'
assert BATCH_KEY == 'BATCH'
assert LABEL_KEY == 'celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
        "internal_dimred": INTERNAL_DIMRED,
        "batch_size": BATCH_SIZE,
        "n_top_hvg": N_TOP_HVG,
    },
    name="configuration",
)

dataset                                                mouse_mammary
data_path          /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                      BATCH
label_key                                                   celltype
metrics                     [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                                 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
internal_dimred                                                   50
batch_size                                                      5000
n_top_hvg                                                       2000
Name: configuration, dtype: object

In [3]:
def validate_dataset_contents():
    adata_backed = ad.read_h5ad(DATA_PATH, backed="r")
    try:
        required_keys = (BATCH_KEY, LABEL_KEY)
        missing_keys = [
            key for key in required_keys if key not in adata_backed.obs
        ]
        if missing_keys:
            raise ValueError(
                f"Missing obs keys {missing_keys}. "
                f"Available keys: {list(adata_backed.obs.columns)}"
            )

        obs = adata_backed.obs[[BATCH_KEY, LABEL_KEY]].copy()
        pseudotime = None
        if "TRAJ" in SELECTED_METRICS:
            if "dpt_pseudotime" not in adata_backed.obs:
                raise ValueError(
                    "TRAJ requires adata.obs['dpt_pseudotime']."
                )
            pseudotime = adata_backed.obs["dpt_pseudotime"].copy()

        n_obs = int(adata_backed.n_obs)
        n_vars = int(adata_backed.n_vars)
    finally:
        adata_backed.file.close()

    if obs.isna().any().any():
        raise ValueError(
            "Missing batch/label values: "
            f"{obs.isna().sum().to_dict()}"
        )

    n_batches = int(obs[BATCH_KEY].nunique())
    n_labels = int(obs[LABEL_KEY].nunique())
    if n_batches < 2:
        raise ValueError(
            f"Batch metrics require at least 2 batches; found {n_batches}."
        )

    batch_coverage = obs.groupby(
        LABEL_KEY,
        observed=True,
    )[BATCH_KEY].nunique()
    label_counts = obs.groupby(LABEL_KEY, observed=True).size()

    if "TRAJ" in SELECTED_METRICS:
        finite_pseudotime = pseudotime.dropna()
        if (
            len(finite_pseudotime) < 2
            or finite_pseudotime.nunique() < 2
        ):
            raise ValueError(
                "TRAJ requires at least 2 usable pseudotime values."
            )

    if "ISOLISI" in SELECTED_METRICS:
        min_batch_coverage = int(batch_coverage.min())
        if min_batch_coverage >= n_batches:
            raise ValueError(
                "ISOLISI is enabled, but every label appears in all batches."
            )

    eligible_cpcr_labels = [
        str(label)
        for label in label_counts.index
        if int(label_counts.loc[label]) >= 100
        and int(batch_coverage.loc[label]) >= 2
    ]
    if "CPCR" in SELECTED_METRICS and not eligible_cpcr_labels:
        raise ValueError(
            "CPCR requires a label with at least 100 cells across "
            "at least 2 batches."
        )

    return {
        "n_obs": n_obs,
        "n_vars": n_vars,
        "n_batches": n_batches,
        "n_labels": n_labels,
        "cpcr_eligible_labels": len(eligible_cpcr_labels),
    }


validate_dataset_contents()

{'n_obs': 9288,
 'n_vars': 1222,
 'n_batches': 3,
 'n_labels': 3,
 'cpcr_eligible_labels': 3}

In [4]:
OPTUNA_BEST_SOURCE = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/results/optuna_multi_metrics/scanorama/mouse_mammary/expanded_metrics_v2/scanorama_mouse_mammary_joint_expanded_metrics_v2_best_params.json'
OPTUNA_STUDY_NAME = 'scanorama_mouse_mammary_joint_expanded_metrics_v2'
OPTUNA_BEST_TRIAL = 147
OPTUNA_BEST_VALUE = 0.7157384164779248
OPTUNA_BEST_PARAMS = {'knn': 35, 'sigma': 24.084639679227276, 'alpha': 0.4302063160544961}

assert tuple(OPTUNA_BEST_PARAMS) == ("knn", "sigma", "alpha")
SCANORAMA_PARAMS = dict(OPTUNA_BEST_PARAMS)

pd.Series(
    {
        "source": OPTUNA_BEST_SOURCE,
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **SCANORAMA_PARAMS,
        "batch_size": BATCH_SIZE,
        "approx": APPROX,
        "union": UNION,
        "internal_dimred": INTERNAL_DIMRED,
        "n_top_hvg": N_TOP_HVG,
    },
    name="best_setting",
)

def check_keys(adata):
    missing_keys = [
        key
        for key in (BATCH_KEY, LABEL_KEY)
        if key not in adata.obs
    ]
    if missing_keys:
        raise ValueError(
            f"Missing keys in adata.obs: {missing_keys}. "
            f"Available keys: {list(adata.obs.columns)}"
        )


def ensure_csr(matrix):
    if sp.issparse(matrix):
        return matrix.tocsr()
    return sp.csr_matrix(matrix)


def split_by_batch(adata):
    batches = adata.obs[BATCH_KEY].astype("category")
    batch_names = list(batches.cat.categories)
    parts = []
    index_parts = []

    for batch_name in batch_names:
        indices = np.where(batches.values == batch_name)[0]
        index_parts.append(indices)
        parts.append(adata[indices, :].copy())

    return parts, batch_names, index_parts


def hvg_subset(adata):
    if "highly_variable" not in adata.var:
        sc.pp.highly_variable_genes(
            adata,
            flavor="seurat",
            n_top_genes=N_TOP_HVG,
        )

    hvg_mask = (
        adata.var["highly_variable"]
        .fillna(False)
        .astype(bool)
        .to_numpy()
    )
    if int(hvg_mask.sum()) == 0:
        raise ValueError("No highly variable genes selected.")
    return adata[:, hvg_mask].copy()


def reassemble_scanorama_embedding(parts, index_parts, n_obs):
    embedding_concat = np.concatenate(
        [part.obsm[EMBED_KEY] for part in parts],
        axis=0,
    )
    concat_indices = np.concatenate(index_parts)
    inverse = np.empty(n_obs, dtype=np.int64)
    inverse[concat_indices] = np.arange(n_obs, dtype=np.int64)
    return embedding_concat[inverse, :]


def run_scanorama_setting(adata, seed):
    np.random.seed(seed)
    check_keys(adata)

    adata_work = hvg_subset(adata.copy())
    adata_work.X = ensure_csr(adata_work.X)
    parts, batch_names, index_parts = split_by_batch(adata_work)

    scanorama.integrate_scanpy(
        parts,
        batch_size=BATCH_SIZE,
        verbose=0,
        ds_names=batch_names,
        dimred=INTERNAL_DIMRED,
        approx=APPROX,
        sigma=float(SCANORAMA_PARAMS["sigma"]),
        alpha=float(SCANORAMA_PARAMS["alpha"]),
        knn=int(SCANORAMA_PARAMS["knn"]),
        union=UNION,
        hvg=None,
        seed=int(seed),
    )

    embedding = reassemble_scanorama_embedding(
        parts,
        index_parts,
        n_obs=adata_work.n_obs,
    )
    if embedding.shape[0] != adata_work.n_obs:
        raise ValueError(
            f"Scanorama output shape {embedding.shape} is incompatible "
            f"with n_obs={adata_work.n_obs}."
        )
    if not np.all(np.isfinite(embedding)):
        raise ValueError(
            "Scanorama produced NaN or Inf in X_scanorama."
        )

    adata_int = adata_work.copy()
    adata_int.obsm[EMBED_KEY] = np.asarray(
        embedding,
        dtype=np.float32,
    )
    return adata_int

In [5]:
def metric_value(metric_series, key):
    if key not in metric_series.index:
        raise KeyError(
            f"Metric {key} not found. "
            f"Available metrics: {list(metric_series.index)}"
        )

    value = metric_series[key]
    if isinstance(value, (list, tuple, np.ndarray)):
        values = np.asarray(value, dtype=float)
        if values.size == 0 or not np.all(np.isfinite(values)):
            raise ValueError(
                f"Metric {key} returned non-finite values: {values}"
            )
        return float(np.mean(values))

    value = float(value)
    if not np.isfinite(value):
        raise ValueError(
            f"Metric {key} returned a non-finite value: {value}"
        )
    return value


def compute_joint_metrics(adata_raw, adata_int):
    sc.pp.neighbors(
        adata_int,
        use_rep=EMBED_KEY,
        n_neighbors=N_NEIGHBORS,
        random_state=0,
    )

    metric_key_map = {
        METRIC_BATCH_KEY: BATCH_KEY,
        METRIC_LABEL_KEY: LABEL_KEY,
    }
    for adata_name, adata_obj in (
        ("adata_raw", adata_raw),
        ("adata_int", adata_int),
    ):
        existing_aliases = [
            alias for alias in metric_key_map if alias in adata_obj.obs
        ]
        if existing_aliases:
            raise ValueError(
                f"Reserved metric obs keys already exist in {adata_name}: "
                f"{existing_aliases}"
            )
        for alias, source_key in metric_key_map.items():
            adata_obj.obs[alias] = adata_obj.obs[source_key].copy()

    metric_df = metrics(
        adata=adata_raw,
        adata_int=adata_int,
        batch_key=METRIC_BATCH_KEY,
        label_key=METRIC_LABEL_KEY,
        embed=EMBED_KEY,
        cluster_key=CLUSTER_KEY,
        verbose=False,
        bami_="BAMI" in SELECTED_METRICS,
        casw_="CASW" in SELECTED_METRICS,
        scgraphm_="SCGRAPHM" in SELECTED_METRICS,
        traj_="TRAJ" in SELECTED_METRICS,
        isolisi_="ISOLISI" in SELECTED_METRICS,
        bras_="BRAS" in SELECTED_METRICS,
        kbet_="KBET" in SELECTED_METRICS,
        cpcr_="CPCR" in SELECTED_METRICS,
    )
    metric_series = metric_df.iloc[:, 0]

    result = {
        key: metric_value(metric_series, key)
        for key in SELECTED_METRICS
    }
    bio_score = float(
        np.mean([result[key] for key in SELECTED_BIO_METRICS])
    )
    batch_score = float(
        np.mean([result[key] for key in SELECTED_BATCH_METRICS])
    )
    joint_score = float(0.6 * bio_score + 0.4 * batch_score)

    if not np.all(np.isfinite([bio_score, batch_score, joint_score])):
        raise ValueError(
            "Aggregation produced a non-finite score: "
            f"bio={bio_score}, batch={batch_score}, "
            f"joint={joint_score}"
        )

    result["bio_score"] = bio_score
    result["batch_score"] = batch_score
    result["joint_score"] = joint_score
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_scanorama_setting(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 27.22it/s]

100%|██████████| 3/3 [00:00<00:00, 27.07it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.8665980498144221

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8661326906505988

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7434864638908603

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6996780256150631

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6896837956095347

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6746892390645205

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6522543607317601

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6332567064866548

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6231612064124542

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5839047078666761

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-07-26 15:58:16,631:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8665980498144221
BRAS...

seed           0.000000
BAMI           0.866598
CASW           0.659598
SCGRAPHM       0.999877
BRAS           0.864724
KBET           0.061748
CPCR           0.636119
bio_score      0.842024
batch_score    0.520864
joint_score    0.713560
dtype: float64

===== seed 1 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 38.69it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8655747327614906

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8659050654018836

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7399460099831559

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6987660033828579

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6876868874664026

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6695806626046704

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6462688795114583

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6094866192906913

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6053825671357278

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5756900507953755

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8659050654018836
BRAS...
seed           1.000000
BAMI           0.865905
CASW           0.658847
SCGRAPHM       0.999886
BRAS           0.862012
KBET           0.061870
CPCR           0.629525
bio_score      0.841546
batch_score    0.517802
joint_score    0.712049
dtype: float64

===== seed 2 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 40.97it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8671033233724922

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8675909893244511

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7385329573461774

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.69989859031515

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6896608211148403

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6773606696213327

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6401471601936419

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6206877033180374

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6018175617428115

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6023585817870069

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8675909893244511
BRAS...
seed           2.000000
BAMI           0.867591
CASW           0.660240
SCGRAPHM       0.722062
BRAS           0.869536
KBET           0.066489
CPCR           0.651192
bio_score      0.749964
batch_score    0.529072
joint_score    0.661608
dtype: float64

===== seed 3 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 34.75it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8672212843383625

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8662911748453748

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7524050510531106

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.702453821986673

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6737101608805177

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6723883627946089

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.656321174243397

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6187054092469327

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6153931679973715

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6030848667190576

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8672212843383625
BRAS...
seed           3.000000
BAMI           0.867221
CASW           0.660610
SCGRAPHM       0.722050
BRAS           0.865683
KBET           0.064370
CPCR           0.644794
bio_score      0.749961
batch_score    0.524949
joint_score    0.659956
dtype: float64

===== seed 4 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 27.21it/s]

100%|██████████| 3/3 [00:00<00:00, 27.00it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8741284366313681

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8656491672020865

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7984150136656079

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7350460435790616

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7154431840544734

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6528704286593567

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6482131434263441

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6452199836293698

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6052516788327463

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5772110421528476

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8741284366313681
BRAS...
seed           4.000000
BAMI           0.874128
CASW           0.658691
SCGRAPHM       0.722056
BRAS           0.866138
KBET           0.063870
CPCR           0.645189
bio_score      0.751625
batch_score    0.525065
joint_score    0.661001
dtype: float64

===== seed 5 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 26.88it/s]

100%|██████████| 3/3 [00:00<00:00, 26.67it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8663303709920579

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8662701256961821

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7461728899005555

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7376534312007279

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7025104095101428

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6715918289249411

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6446436385428784

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6188903327063769

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6103968271798377

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5911046929353165

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8663303709920579
BRAS...
seed           5.000000
BAMI           0.866330
CASW           0.659678
SCGRAPHM       0.999851
BRAS           0.861730
KBET           0.062518
CPCR           0.626894
bio_score      0.841953
batch_score    0.517047
joint_score    0.711991
dtype: float64

===== seed 6 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 25.32it/s]

100%|██████████| 3/3 [00:00<00:00, 24.98it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8747849089321503

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8736540653346302

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7420439309611215

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7056135133266497

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6639207168866669

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.645495655095877

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6418085460772346

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6308754991719897

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6150671320876616

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5940417591087752

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8747849089321503
BRAS...
seed           6.000000
BAMI           0.874785
CASW           0.660021
SCGRAPHM       0.999854
BRAS           0.864548
KBET           0.063681
CPCR           0.635195
bio_score      0.844887
batch_score    0.521141
joint_score    0.715388
dtype: float64

===== seed 7 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 41.94it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.867459273713615

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8665349232463496

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.73605766738729

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7205395060516627

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7035034167978813

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6878096772956084

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6727368221459283

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6137577466051111

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6111778217428813

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5873128433122988

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.867459273713615
BRAS...
seed           7.000000
BAMI           0.867459
CASW           0.659981
SCGRAPHM       0.722050
BRAS           0.867737
KBET           0.060053
CPCR           0.648742
bio_score      0.749830
batch_score    0.525511
joint_score    0.660102
dtype: float64

===== seed 8 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 42.01it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8680132893474326

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8645259865594099

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7423831647042167

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6896824180441079

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6463975912490286

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.643353494363908

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6424006647712641

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6345331093555681

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6189652357858917

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.585639131534833

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8680132893474326
BRAS...
seed           8.000000
BAMI           0.868013
CASW           0.659379
SCGRAPHM       0.722064
BRAS           0.861951
KBET           0.071579
CPCR           0.627509
bio_score      0.749819
batch_score    0.520346
joint_score    0.658030
dtype: float64

===== seed 9 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 36.18it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8649473223680595

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8655378676326907

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7377750300611071

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7351188499472054

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6853647765696502

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6486892790830672

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6479951544919272

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6318259973459227

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6132436612888477

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6068332281334208

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8655378676326907
BRAS...
seed           9.000000
BAMI           0.865538
CASW           0.659645
SCGRAPHM       0.722065
BRAS           0.862277
KBET           0.065204
CPCR           0.629569
bio_score      0.749083
batch_score    0.519017
joint_score    0.657056
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.866598,0.659598,0.999877,0.864724,0.061748,0.636119,0.842024,0.520864,0.713560
1,1,0.865905,0.658847,0.999886,0.862012,0.061870,0.629525,0.841546,0.517802,0.712049
2,2,0.867591,0.660240,0.722062,0.869536,0.066489,0.651192,0.749964,0.529072,0.661608
3,3,0.867221,0.660610,0.722050,0.865683,0.064370,0.644794,0.749961,0.524949,0.659956
4,4,0.874128,0.658691,0.722056,0.866138,0.063870,0.645189,0.751625,0.525065,0.661001
5,5,0.866330,0.659678,0.999851,0.861730,0.062518,0.626894,0.841953,0.517047,0.711991
6,6,0.874785,0.660021,0.999854,0.864548,0.063681,0.635195,0.844887,0.521141,0.715388
7,7,0.867459,0.659981,0.722050,0.867737,0.060053,0.648742,0.749830,0.525511,0.660102
8,8,0.868013,0.659379,0.722064,0.861951,0.071579,0.627509,0.749819,0.520346,0.658030
9,9,0.865538,0.659645,0.722065,0.862277,0.065204,0.629569,0.749083,0.519017,0.657056

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.868357  0.003140  0.865538  0.874785
CASW         0.659669  0.000562  0.658691  0.660610
SCGRAPHM     0.833181  0.136098  0.722050  0.999886
BRAS         0.864634  0.002551  0.861730  0.869536
KBET         0.064138  0.003042  0.060053  0.071579
CPCR         0.637473  0.008788  0.626894  0.651192
bio_score    0.787069  0.045355  0.749083  0.844887
batch_score  0.522081  0.003690  0.517047  0.529072
joint_score  0.681074  0.026313  0.657056  0.715388