# Scanorama default - mouse_mammary

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

This notebook is intentionally unexecuted.

In [1]:
import gc
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = (
    "/ubc/cs/research/beaver/projects/"
    "Single-cell-integration-metrics"
)
os.environ["R_HOME"] = (
    f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R"
)
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd
import scanorama
import scanpy as sc
import scipy.sparse as sp

from scib.metrics.metrics import metrics

In [2]:
DATASET_NAME = 'mouse_mammary'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'BATCH'
LABEL_KEY = 'celltype'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_NEIGHBORS = 15
N_TOP_HVG = 2000
INTERNAL_DIMRED = 50
BATCH_SIZE = 5000
APPROX = True
UNION = False

EMBED_KEY = "X_scanorama"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "scanorama_metric_batch"
METRIC_LABEL_KEY = "scanorama_metric_label"

assert DATASET_NAME == 'mouse_mammary'
assert BATCH_KEY == 'BATCH'
assert LABEL_KEY == 'celltype'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
        "internal_dimred": INTERNAL_DIMRED,
        "batch_size": BATCH_SIZE,
        "n_top_hvg": N_TOP_HVG,
    },
    name="configuration",
)

dataset                                                mouse_mammary
data_path          /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                      BATCH
label_key                                                   celltype
metrics                     [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                                 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
internal_dimred                                                   50
batch_size                                                      5000
n_top_hvg                                                       2000
Name: configuration, dtype: object

In [3]:
def validate_dataset_contents():
    adata_backed = ad.read_h5ad(DATA_PATH, backed="r")
    try:
        required_keys = (BATCH_KEY, LABEL_KEY)
        missing_keys = [
            key for key in required_keys if key not in adata_backed.obs
        ]
        if missing_keys:
            raise ValueError(
                f"Missing obs keys {missing_keys}. "
                f"Available keys: {list(adata_backed.obs.columns)}"
            )

        obs = adata_backed.obs[[BATCH_KEY, LABEL_KEY]].copy()
        pseudotime = None
        if "TRAJ" in SELECTED_METRICS:
            if "dpt_pseudotime" not in adata_backed.obs:
                raise ValueError(
                    "TRAJ requires adata.obs['dpt_pseudotime']."
                )
            pseudotime = adata_backed.obs["dpt_pseudotime"].copy()

        n_obs = int(adata_backed.n_obs)
        n_vars = int(adata_backed.n_vars)
    finally:
        adata_backed.file.close()

    if obs.isna().any().any():
        raise ValueError(
            "Missing batch/label values: "
            f"{obs.isna().sum().to_dict()}"
        )

    n_batches = int(obs[BATCH_KEY].nunique())
    n_labels = int(obs[LABEL_KEY].nunique())
    if n_batches < 2:
        raise ValueError(
            f"Batch metrics require at least 2 batches; found {n_batches}."
        )

    batch_coverage = obs.groupby(
        LABEL_KEY,
        observed=True,
    )[BATCH_KEY].nunique()
    label_counts = obs.groupby(LABEL_KEY, observed=True).size()

    if "TRAJ" in SELECTED_METRICS:
        finite_pseudotime = pseudotime.dropna()
        if (
            len(finite_pseudotime) < 2
            or finite_pseudotime.nunique() < 2
        ):
            raise ValueError(
                "TRAJ requires at least 2 usable pseudotime values."
            )

    if "ISOLISI" in SELECTED_METRICS:
        min_batch_coverage = int(batch_coverage.min())
        if min_batch_coverage >= n_batches:
            raise ValueError(
                "ISOLISI is enabled, but every label appears in all batches."
            )

    eligible_cpcr_labels = [
        str(label)
        for label in label_counts.index
        if int(label_counts.loc[label]) >= 100
        and int(batch_coverage.loc[label]) >= 2
    ]
    if "CPCR" in SELECTED_METRICS and not eligible_cpcr_labels:
        raise ValueError(
            "CPCR requires a label with at least 100 cells across "
            "at least 2 batches."
        )

    return {
        "n_obs": n_obs,
        "n_vars": n_vars,
        "n_batches": n_batches,
        "n_labels": n_labels,
        "cpcr_eligible_labels": len(eligible_cpcr_labels),
    }


validate_dataset_contents()

{'n_obs': 9288,
 'n_vars': 1222,
 'n_batches': 3,
 'n_labels': 3,
 'cpcr_eligible_labels': 3}

In [4]:
SCANORAMA_PARAMS = {'knn': 20, 'sigma': 15.0, 'alpha': 0.1}
assert tuple(SCANORAMA_PARAMS) == ("knn", "sigma", "alpha")

pd.Series(
    {
        **SCANORAMA_PARAMS,
        "batch_size": BATCH_SIZE,
        "approx": APPROX,
        "union": UNION,
        "internal_dimred": INTERNAL_DIMRED,
        "n_top_hvg": N_TOP_HVG,
    },
    name="default_setting",
)

def check_keys(adata):
    missing_keys = [
        key
        for key in (BATCH_KEY, LABEL_KEY)
        if key not in adata.obs
    ]
    if missing_keys:
        raise ValueError(
            f"Missing keys in adata.obs: {missing_keys}. "
            f"Available keys: {list(adata.obs.columns)}"
        )


def ensure_csr(matrix):
    if sp.issparse(matrix):
        return matrix.tocsr()
    return sp.csr_matrix(matrix)


def split_by_batch(adata):
    batches = adata.obs[BATCH_KEY].astype("category")
    batch_names = list(batches.cat.categories)
    parts = []
    index_parts = []

    for batch_name in batch_names:
        indices = np.where(batches.values == batch_name)[0]
        index_parts.append(indices)
        parts.append(adata[indices, :].copy())

    return parts, batch_names, index_parts


def hvg_subset(adata):
    if "highly_variable" not in adata.var:
        sc.pp.highly_variable_genes(
            adata,
            flavor="seurat",
            n_top_genes=N_TOP_HVG,
        )

    hvg_mask = (
        adata.var["highly_variable"]
        .fillna(False)
        .astype(bool)
        .to_numpy()
    )
    if int(hvg_mask.sum()) == 0:
        raise ValueError("No highly variable genes selected.")
    return adata[:, hvg_mask].copy()


def reassemble_scanorama_embedding(parts, index_parts, n_obs):
    embedding_concat = np.concatenate(
        [part.obsm[EMBED_KEY] for part in parts],
        axis=0,
    )
    concat_indices = np.concatenate(index_parts)
    inverse = np.empty(n_obs, dtype=np.int64)
    inverse[concat_indices] = np.arange(n_obs, dtype=np.int64)
    return embedding_concat[inverse, :]


def run_scanorama_setting(adata, seed):
    np.random.seed(seed)
    check_keys(adata)

    adata_work = hvg_subset(adata.copy())
    adata_work.X = ensure_csr(adata_work.X)
    parts, batch_names, index_parts = split_by_batch(adata_work)

    scanorama.integrate_scanpy(
        parts,
        batch_size=BATCH_SIZE,
        verbose=0,
        ds_names=batch_names,
        dimred=INTERNAL_DIMRED,
        approx=APPROX,
        sigma=float(SCANORAMA_PARAMS["sigma"]),
        alpha=float(SCANORAMA_PARAMS["alpha"]),
        knn=int(SCANORAMA_PARAMS["knn"]),
        union=UNION,
        hvg=None,
        seed=int(seed),
    )

    embedding = reassemble_scanorama_embedding(
        parts,
        index_parts,
        n_obs=adata_work.n_obs,
    )
    if embedding.shape[0] != adata_work.n_obs:
        raise ValueError(
            f"Scanorama output shape {embedding.shape} is incompatible "
            f"with n_obs={adata_work.n_obs}."
        )
    if not np.all(np.isfinite(embedding)):
        raise ValueError(
            "Scanorama produced NaN or Inf in X_scanorama."
        )

    adata_int = adata_work.copy()
    adata_int.obsm[EMBED_KEY] = np.asarray(
        embedding,
        dtype=np.float32,
    )
    return adata_int

In [5]:
def metric_value(metric_series, key):
    if key not in metric_series.index:
        raise KeyError(
            f"Metric {key} not found. "
            f"Available metrics: {list(metric_series.index)}"
        )

    value = metric_series[key]
    if isinstance(value, (list, tuple, np.ndarray)):
        values = np.asarray(value, dtype=float)
        if values.size == 0 or not np.all(np.isfinite(values)):
            raise ValueError(
                f"Metric {key} returned non-finite values: {values}"
            )
        return float(np.mean(values))

    value = float(value)
    if not np.isfinite(value):
        raise ValueError(
            f"Metric {key} returned a non-finite value: {value}"
        )
    return value


def compute_joint_metrics(adata_raw, adata_int):
    sc.pp.neighbors(
        adata_int,
        use_rep=EMBED_KEY,
        n_neighbors=N_NEIGHBORS,
        random_state=0,
    )

    metric_key_map = {
        METRIC_BATCH_KEY: BATCH_KEY,
        METRIC_LABEL_KEY: LABEL_KEY,
    }
    for adata_name, adata_obj in (
        ("adata_raw", adata_raw),
        ("adata_int", adata_int),
    ):
        existing_aliases = [
            alias for alias in metric_key_map if alias in adata_obj.obs
        ]
        if existing_aliases:
            raise ValueError(
                f"Reserved metric obs keys already exist in {adata_name}: "
                f"{existing_aliases}"
            )
        for alias, source_key in metric_key_map.items():
            adata_obj.obs[alias] = adata_obj.obs[source_key].copy()

    metric_df = metrics(
        adata=adata_raw,
        adata_int=adata_int,
        batch_key=METRIC_BATCH_KEY,
        label_key=METRIC_LABEL_KEY,
        embed=EMBED_KEY,
        cluster_key=CLUSTER_KEY,
        verbose=False,
        bami_="BAMI" in SELECTED_METRICS,
        casw_="CASW" in SELECTED_METRICS,
        scgraphm_="SCGRAPHM" in SELECTED_METRICS,
        traj_="TRAJ" in SELECTED_METRICS,
        isolisi_="ISOLISI" in SELECTED_METRICS,
        bras_="BRAS" in SELECTED_METRICS,
        kbet_="KBET" in SELECTED_METRICS,
        cpcr_="CPCR" in SELECTED_METRICS,
    )
    metric_series = metric_df.iloc[:, 0]

    result = {
        key: metric_value(metric_series, key)
        for key in SELECTED_METRICS
    }
    bio_score = float(
        np.mean([result[key] for key in SELECTED_BIO_METRICS])
    )
    batch_score = float(
        np.mean([result[key] for key in SELECTED_BATCH_METRICS])
    )
    joint_score = float(0.6 * bio_score + 0.4 * batch_score)

    if not np.all(np.isfinite([bio_score, batch_score, joint_score])):
        raise ValueError(
            "Aggregation produced a non-finite score: "
            f"bio={bio_score}, batch={batch_score}, "
            f"joint={joint_score}"
        )

    result["bio_score"] = bio_score
    result["batch_score"] = batch_score
    result["joint_score"] = joint_score
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_scanorama_setting(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 32.27it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.8668838863851854

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8655565376964145

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.791468311098538

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7318904371649811

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.66830571704491

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6704608383358743

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.643406322851903

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6314310324731535

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6230378484328114

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.583191611822455

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-07-26 15:54:20,956:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8668838863851854
BRAS...

seed           0.000000
BAMI           0.866884
CASW           0.658176
SCGRAPHM       0.721897
BRAS           0.837457
KBET           0.050946
CPCR           0.568862
bio_score      0.748986
batch_score    0.485755
joint_score    0.643693
dtype: float64

===== seed 1 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 27.40it/s]

100%|██████████| 3/3 [00:00<00:00, 26.80it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.868353065474347

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7927996513693608

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7941469428756316

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7309202514243773

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6904983151932027

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6685624297180185

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6484305858650498

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6468339720103037

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6345494343599651

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5860726472248949

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.868353065474347
BRAS...
seed           1.000000
BAMI           0.868353
CASW           0.658901
SCGRAPHM       0.721856
BRAS           0.831369
KBET           0.051542
CPCR           0.568475
bio_score      0.749704
batch_score    0.483795
joint_score    0.643340
dtype: float64

===== seed 2 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 41.27it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.866785652058622

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7945064273782915

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7939956519423613

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7321168183689675

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6991002968993987

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6456154987805615

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6453589556355105

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6445219114481487

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6428775428887148

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.584356862057379

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.866785652058622
BRAS...
seed           2.000000
BAMI           0.866786
CASW           0.657798
SCGRAPHM       0.721897
BRAS           0.836501
KBET           0.049742
CPCR           0.567674
bio_score      0.748827
batch_score    0.484639
joint_score    0.643152
dtype: float64

===== seed 3 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 38.06it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8653446176350588

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7917402403879208

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7918929527864454

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7006375681577894

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6858877172166153

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6476459943316298

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6466225715467021

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6457672543025995

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6082451313659362

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.605638773439111

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8653446176350588
BRAS...
seed           3.000000
BAMI           0.865345
CASW           0.659547
SCGRAPHM       0.721852
BRAS           0.832853
KBET           0.053413
CPCR           0.570522
bio_score      0.748914
batch_score    0.485596
joint_score    0.643587
dtype: float64

===== seed 4 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 41.80it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8668012266355843

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8657704473771646

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7924337858560507

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7305650401372272

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.7299748862302937

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6713438573068734

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.64733970217799

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6424723643877899

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6211736550383573

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6044570075599984

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8668012266355843
BRAS...
seed           4.000000
BAMI           0.866801
CASW           0.658833
SCGRAPHM       0.721954
BRAS           0.832159
KBET           0.050485
CPCR           0.575554
bio_score      0.749196
batch_score    0.486066
joint_score    0.643944
dtype: float64

===== seed 5 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 40.53it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8672988439060115

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7930896089959315

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7930992152581579

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7149270416195047

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6921227009303145

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6520041922118937

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6492984336212122

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6328607238842229

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6305274403066732

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6044243787657119

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8672988439060115
BRAS...
seed           5.000000
BAMI           0.867299
CASW           0.658321
SCGRAPHM       0.721997
BRAS           0.829949
KBET           0.049759
CPCR           0.567981
bio_score      0.749206
batch_score    0.482563
joint_score    0.642549
dtype: float64

===== seed 6 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 41.40it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8654085830168458

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.865462264284452

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7909766147165135

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7318648574638397

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6939014974636312

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.633799452663015

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6322441346689764

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6310905107238248

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6282264801472512

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6237135743894325

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.865462264284452
BRAS...
seed           6.000000
BAMI           0.865462
CASW           0.659864
SCGRAPHM       0.721809
BRAS           0.832614
KBET           0.049491
CPCR           0.574039
bio_score      0.749045
batch_score    0.485382
joint_score    0.643580
dtype: float64

===== seed 7 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 36.86it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8680205863178143

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7938905543174576

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7942572970847492

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7141244551750233

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6912694338967953

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6703939577430182

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6472555306802937

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6482112710184939

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6328198557705599

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6073576601769254

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.8680205863178143
BRAS...
seed           7.000000
BAMI           0.868021
CASW           0.659767
SCGRAPHM       0.721813
BRAS           0.833380
KBET           0.049781
CPCR           0.564601
bio_score      0.749867
batch_score    0.482587
joint_score    0.642955
dtype: float64

===== seed 8 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 41.78it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.8664659416738978

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.8664870502202167

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.796678535461384

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.7351791408382372

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.68855993611065

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6631613817808635

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.6423647987783565

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.629831943545456

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6274251335016763

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5989120282589647

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.8664870502202167
BRAS...
seed           8.000000
BAMI           0.866487
CASW           0.658909
SCGRAPHM       0.999817
BRAS           0.831039
KBET           0.050910
CPCR           0.573776
bio_score      0.841738
batch_score    0.485241
joint_score    0.699139
dtype: float64

===== seed 9 =====

After spk: 280 genes
After vis: 280 genes
After wal: 280 genes
Found 280 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Variance contribution increased after integration!
Setting PCR comparison score to 0.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00, 42.84it/s]

kBET...

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.865960702746908

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7919276768824599

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.7925671560915181

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.723717112176402

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6829328733954256

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.6467891320448704

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.645142368733092

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.6435624340412729

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.6300968754335549

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.6179126508360812

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.865960702746908
BRAS...
seed           9.000000
BAMI           0.865961
CASW           0.660150
SCGRAPHM       0.721660
BRAS           0.836385
KBET           0.048258
CPCR           0.568435
bio_score      0.749257
batch_score    0.484359
joint_score    0.643298
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.866884,0.658176,0.721897,0.837457,0.050946,0.568862,0.748986,0.485755,0.643693
1,1,0.868353,0.658901,0.721856,0.831369,0.051542,0.568475,0.749704,0.483795,0.643340
2,2,0.866786,0.657798,0.721897,0.836501,0.049742,0.567674,0.748827,0.484639,0.643152
3,3,0.865345,0.659547,0.721852,0.832853,0.053413,0.570522,0.748914,0.485596,0.643587
4,4,0.866801,0.658833,0.721954,0.832159,0.050485,0.575554,0.749196,0.486066,0.643944
5,5,0.867299,0.658321,0.721997,0.829949,0.049759,0.567981,0.749206,0.482563,0.642549
6,6,0.865462,0.659864,0.721809,0.832614,0.049491,0.574039,0.749045,0.485382,0.643580
7,7,0.868021,0.659767,0.721813,0.833380,0.049781,0.564601,0.749867,0.482587,0.642955
8,8,0.866487,0.658909,0.999817,0.831039,0.050910,0.573776,0.841738,0.485241,0.699139
9,9,0.865961,0.660150,0.721660,0.836385,0.048258,0.568435,0.749257,0.484359,0.643298

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.866740  0.000940  0.865345  0.868353
CASW         0.659027  0.000747  0.657798  0.660150
SCGRAPHM     0.749655  0.083387  0.721660  0.999817
BRAS         0.833371  0.002430  0.829949  0.837457
KBET         0.050433  0.001326  0.048258  0.053413
CPCR         0.569992  0.003262  0.564601  0.575554
bio_score    0.758474  0.027756  0.748827  0.841738
batch_score  0.484598  0.001200  0.482563  0.486066
joint_score  0.648924  0.016743  0.642549  0.699139