# Scanorama best - mouse_regulatory_T

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

This notebook is intentionally unexecuted.

In [1]:
import gc
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = (
    "/ubc/cs/research/beaver/projects/"
    "Single-cell-integration-metrics"
)
os.environ["R_HOME"] = (
    f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R"
)
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd
import scanorama
import scanpy as sc
import scipy.sparse as sp

from scib.metrics.metrics import metrics

In [2]:
DATASET_NAME = 'mouse_regulatory_T'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'method'
LABEL_KEY = 'cell.type'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_NEIGHBORS = 15
N_TOP_HVG = 2000
INTERNAL_DIMRED = 50
BATCH_SIZE = 5000
APPROX = True
UNION = False

EMBED_KEY = "X_scanorama"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "scanorama_metric_batch"
METRIC_LABEL_KEY = "scanorama_metric_label"

assert DATASET_NAME == 'mouse_regulatory_T'
assert BATCH_KEY == 'method'
assert LABEL_KEY == 'cell.type'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
        "internal_dimred": INTERNAL_DIMRED,
        "batch_size": BATCH_SIZE,
        "n_top_hvg": N_TOP_HVG,
    },
    name="configuration",
)

dataset                                           mouse_regulatory_T
data_path          /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                     method
label_key                                                  cell.type
metrics                     [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                                 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
internal_dimred                                                   50
batch_size                                                      5000
n_top_hvg                                                       2000
Name: configuration, dtype: object

In [3]:
def validate_dataset_contents():
    adata_backed = ad.read_h5ad(DATA_PATH, backed="r")
    try:
        required_keys = (BATCH_KEY, LABEL_KEY)
        missing_keys = [
            key for key in required_keys if key not in adata_backed.obs
        ]
        if missing_keys:
            raise ValueError(
                f"Missing obs keys {missing_keys}. "
                f"Available keys: {list(adata_backed.obs.columns)}"
            )

        obs = adata_backed.obs[[BATCH_KEY, LABEL_KEY]].copy()
        pseudotime = None
        if "TRAJ" in SELECTED_METRICS:
            if "dpt_pseudotime" not in adata_backed.obs:
                raise ValueError(
                    "TRAJ requires adata.obs['dpt_pseudotime']."
                )
            pseudotime = adata_backed.obs["dpt_pseudotime"].copy()

        n_obs = int(adata_backed.n_obs)
        n_vars = int(adata_backed.n_vars)
    finally:
        adata_backed.file.close()

    if obs.isna().any().any():
        raise ValueError(
            "Missing batch/label values: "
            f"{obs.isna().sum().to_dict()}"
        )

    n_batches = int(obs[BATCH_KEY].nunique())
    n_labels = int(obs[LABEL_KEY].nunique())
    if n_batches < 2:
        raise ValueError(
            f"Batch metrics require at least 2 batches; found {n_batches}."
        )

    batch_coverage = obs.groupby(
        LABEL_KEY,
        observed=True,
    )[BATCH_KEY].nunique()
    label_counts = obs.groupby(LABEL_KEY, observed=True).size()

    if "TRAJ" in SELECTED_METRICS:
        finite_pseudotime = pseudotime.dropna()
        if (
            len(finite_pseudotime) < 2
            or finite_pseudotime.nunique() < 2
        ):
            raise ValueError(
                "TRAJ requires at least 2 usable pseudotime values."
            )

    if "ISOLISI" in SELECTED_METRICS:
        min_batch_coverage = int(batch_coverage.min())
        if min_batch_coverage >= n_batches:
            raise ValueError(
                "ISOLISI is enabled, but every label appears in all batches."
            )

    eligible_cpcr_labels = [
        str(label)
        for label in label_counts.index
        if int(label_counts.loc[label]) >= 100
        and int(batch_coverage.loc[label]) >= 2
    ]
    if "CPCR" in SELECTED_METRICS and not eligible_cpcr_labels:
        raise ValueError(
            "CPCR requires a label with at least 100 cells across "
            "at least 2 batches."
        )

    return {
        "n_obs": n_obs,
        "n_vars": n_vars,
        "n_batches": n_batches,
        "n_labels": n_labels,
        "cpcr_eligible_labels": len(eligible_cpcr_labels),
    }


validate_dataset_contents()

{'n_obs': 34697,
 'n_vars': 11765,
 'n_batches': 2,
 'n_labels': 3,
 'cpcr_eligible_labels': 2}

In [4]:
OPTUNA_BEST_SOURCE = '/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/results/optuna_multi_metrics/scanorama/mouse_regulatory_T/expanded_metrics_v2/scanorama_mouse_regulatory_T_joint_expanded_metrics_v2_best_params.json'
OPTUNA_STUDY_NAME = 'scanorama_mouse_regulatory_T_joint_expanded_metrics_v2'
OPTUNA_BEST_TRIAL = 91
OPTUNA_BEST_VALUE = 0.7799398096895096
OPTUNA_BEST_PARAMS = {'knn': 11, 'sigma': 30.48395253409884, 'alpha': 0.3479341444740598}

assert tuple(OPTUNA_BEST_PARAMS) == ("knn", "sigma", "alpha")
SCANORAMA_PARAMS = dict(OPTUNA_BEST_PARAMS)

pd.Series(
    {
        "source": OPTUNA_BEST_SOURCE,
        "study": OPTUNA_STUDY_NAME,
        "best_trial": OPTUNA_BEST_TRIAL,
        "best_value": OPTUNA_BEST_VALUE,
        **SCANORAMA_PARAMS,
        "batch_size": BATCH_SIZE,
        "approx": APPROX,
        "union": UNION,
        "internal_dimred": INTERNAL_DIMRED,
        "n_top_hvg": N_TOP_HVG,
    },
    name="best_setting",
)

def check_keys(adata):
    missing_keys = [
        key
        for key in (BATCH_KEY, LABEL_KEY)
        if key not in adata.obs
    ]
    if missing_keys:
        raise ValueError(
            f"Missing keys in adata.obs: {missing_keys}. "
            f"Available keys: {list(adata.obs.columns)}"
        )


def ensure_csr(matrix):
    if sp.issparse(matrix):
        return matrix.tocsr()
    return sp.csr_matrix(matrix)


def split_by_batch(adata):
    batches = adata.obs[BATCH_KEY].astype("category")
    batch_names = list(batches.cat.categories)
    parts = []
    index_parts = []

    for batch_name in batch_names:
        indices = np.where(batches.values == batch_name)[0]
        index_parts.append(indices)
        parts.append(adata[indices, :].copy())

    return parts, batch_names, index_parts


def hvg_subset(adata):
    if "highly_variable" not in adata.var:
        sc.pp.highly_variable_genes(
            adata,
            flavor="seurat",
            n_top_genes=N_TOP_HVG,
        )

    hvg_mask = (
        adata.var["highly_variable"]
        .fillna(False)
        .astype(bool)
        .to_numpy()
    )
    if int(hvg_mask.sum()) == 0:
        raise ValueError("No highly variable genes selected.")
    return adata[:, hvg_mask].copy()


def reassemble_scanorama_embedding(parts, index_parts, n_obs):
    embedding_concat = np.concatenate(
        [part.obsm[EMBED_KEY] for part in parts],
        axis=0,
    )
    concat_indices = np.concatenate(index_parts)
    inverse = np.empty(n_obs, dtype=np.int64)
    inverse[concat_indices] = np.arange(n_obs, dtype=np.int64)
    return embedding_concat[inverse, :]


def run_scanorama_setting(adata, seed):
    np.random.seed(seed)
    check_keys(adata)

    adata_work = hvg_subset(adata.copy())
    adata_work.X = ensure_csr(adata_work.X)
    parts, batch_names, index_parts = split_by_batch(adata_work)

    scanorama.integrate_scanpy(
        parts,
        batch_size=BATCH_SIZE,
        verbose=0,
        ds_names=batch_names,
        dimred=INTERNAL_DIMRED,
        approx=APPROX,
        sigma=float(SCANORAMA_PARAMS["sigma"]),
        alpha=float(SCANORAMA_PARAMS["alpha"]),
        knn=int(SCANORAMA_PARAMS["knn"]),
        union=UNION,
        hvg=None,
        seed=int(seed),
    )

    embedding = reassemble_scanorama_embedding(
        parts,
        index_parts,
        n_obs=adata_work.n_obs,
    )
    if embedding.shape[0] != adata_work.n_obs:
        raise ValueError(
            f"Scanorama output shape {embedding.shape} is incompatible "
            f"with n_obs={adata_work.n_obs}."
        )
    if not np.all(np.isfinite(embedding)):
        raise ValueError(
            "Scanorama produced NaN or Inf in X_scanorama."
        )

    adata_int = adata_work.copy()
    adata_int.obsm[EMBED_KEY] = np.asarray(
        embedding,
        dtype=np.float32,
    )
    return adata_int

In [5]:
def metric_value(metric_series, key):
    if key not in metric_series.index:
        raise KeyError(
            f"Metric {key} not found. "
            f"Available metrics: {list(metric_series.index)}"
        )

    value = metric_series[key]
    if isinstance(value, (list, tuple, np.ndarray)):
        values = np.asarray(value, dtype=float)
        if values.size == 0 or not np.all(np.isfinite(values)):
            raise ValueError(
                f"Metric {key} returned non-finite values: {values}"
            )
        return float(np.mean(values))

    value = float(value)
    if not np.isfinite(value):
        raise ValueError(
            f"Metric {key} returned a non-finite value: {value}"
        )
    return value


def compute_joint_metrics(adata_raw, adata_int):
    sc.pp.neighbors(
        adata_int,
        use_rep=EMBED_KEY,
        n_neighbors=N_NEIGHBORS,
        random_state=0,
    )

    metric_key_map = {
        METRIC_BATCH_KEY: BATCH_KEY,
        METRIC_LABEL_KEY: LABEL_KEY,
    }
    for adata_name, adata_obj in (
        ("adata_raw", adata_raw),
        ("adata_int", adata_int),
    ):
        existing_aliases = [
            alias for alias in metric_key_map if alias in adata_obj.obs
        ]
        if existing_aliases:
            raise ValueError(
                f"Reserved metric obs keys already exist in {adata_name}: "
                f"{existing_aliases}"
            )
        for alias, source_key in metric_key_map.items():
            adata_obj.obs[alias] = adata_obj.obs[source_key].copy()

    metric_df = metrics(
        adata=adata_raw,
        adata_int=adata_int,
        batch_key=METRIC_BATCH_KEY,
        label_key=METRIC_LABEL_KEY,
        embed=EMBED_KEY,
        cluster_key=CLUSTER_KEY,
        verbose=False,
        bami_="BAMI" in SELECTED_METRICS,
        casw_="CASW" in SELECTED_METRICS,
        scgraphm_="SCGRAPHM" in SELECTED_METRICS,
        traj_="TRAJ" in SELECTED_METRICS,
        isolisi_="ISOLISI" in SELECTED_METRICS,
        bras_="BRAS" in SELECTED_METRICS,
        kbet_="KBET" in SELECTED_METRICS,
        cpcr_="CPCR" in SELECTED_METRICS,
    )
    metric_series = metric_df.iloc[:, 0]

    result = {
        key: metric_value(metric_series, key)
        for key in SELECTED_METRICS
    }
    bio_score = float(
        np.mean([result[key] for key in SELECTED_BIO_METRICS])
    )
    batch_score = float(
        np.mean([result[key] for key in SELECTED_BATCH_METRICS])
    )
    joint_score = float(0.6 * bio_score + 0.4 * batch_score)

    if not np.all(np.isfinite([bio_score, batch_score, joint_score])):
        raise ValueError(
            "Aggregation produced a non-finite score: "
            f"bio={bio_score}, batch={batch_score}, "
            f"joint={joint_score}"
        )

    result["bio_score"] = bio_score
    result["batch_score"] = batch_score
    result["joint_score"] = joint_score
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_scanorama_setting(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.88it/s]

100%|██████████| 2/2 [00:00<00:00,  3.54it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.7402183638814444

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6981506323970835

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6564641214481863

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.625691590768396

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5941270274129945

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5432187298196531

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5416385319880359

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5164285678668022

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.506509436442168

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5048308362831695

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-07-26 16:11:50,635:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.7402183638814444
BRAS...

seed           0.000000
BAMI           0.740218
CASW           0.530399
SCGRAPHM       0.993097
BRAS           0.856805
KBET           0.661709
CPCR           0.935464
bio_score      0.754571
batch_score    0.817993
joint_score    0.779940
dtype: float64

===== seed 1 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.96it/s]

100%|██████████| 2/2 [00:00<00:00,  3.73it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6536987081964969

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6444241481460861

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6682014255708699

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6201228266397907

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5917082082278318

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5494525661795802

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5415448317309229

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5379516207239546

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5215581154763652

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5117361789076602

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6682014255708699
BRAS...

seed           1.000000
BAMI           0.668201
CASW           0.530105
SCGRAPHM       0.993166
BRAS           0.857608
KBET           0.666404
CPCR           0.934814
bio_score      0.730491
batch_score    0.819609
joint_score    0.766138
dtype: float64

===== seed 2 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.03it/s]

100%|██████████| 2/2 [00:00<00:00,  3.86it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.608493359274689

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6488637520355907

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.660527031031474

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6445859522358423

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5987330661806244

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5571122866962409

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5342656315215956

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5195023695583212

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5131834632101674

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5094357599126199

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.6
optimal score: 0.660527031031474
BRAS...

seed           2.000000
BAMI           0.660527
CASW           0.530549
SCGRAPHM       0.993138
BRAS           0.856098
KBET           0.648722
CPCR           0.933016
bio_score      0.728071
batch_score    0.812612
joint_score    0.761888
dtype: float64

===== seed 3 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.13it/s]

100%|██████████| 2/2 [00:00<00:00,  4.05it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6525964279702263

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6346667729554943

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6597283880276159

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6149784887194162

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5915712396278295

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5503821358066223

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5224850685154071

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5137257364897575

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.501605752029093

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49755374231808

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6597283880276159
BRAS...

seed           3.000000
BAMI           0.659728
CASW           0.530430
SCGRAPHM       0.993133
BRAS           0.860721
KBET           0.651479
CPCR           0.938369
bio_score      0.727764
batch_score    0.816856
joint_score    0.763401
dtype: float64

===== seed 4 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.10it/s]

100%|██████████| 2/2 [00:00<00:00,  4.00it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6153803873251754

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6778750527285812

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6552193643857087

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6365379516819805

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5927208056036483

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5495464077387726

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5421564161434438

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5373444266963832

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5160261970681607

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5096192453764145

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6778750527285812
BRAS...

seed           4.000000
BAMI           0.677875
CASW           0.530251
SCGRAPHM       0.993172
BRAS           0.855391
KBET           0.663827
CPCR           0.933234
bio_score      0.733766
batch_score    0.817484
joint_score    0.767253
dtype: float64

===== seed 5 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.11it/s]

100%|██████████| 2/2 [00:00<00:00,  4.02it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6548733415382025

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6408074565980676

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6615808694282346

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6046914411234668

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5558257634136647

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5475051358430023

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5267569794391246

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5145803414926198

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.49742634503350186

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4929495964936366

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6615808694282346
BRAS...

seed           5.000000
BAMI           0.661581
CASW           0.530323
SCGRAPHM       0.993130
BRAS           0.850653
KBET           0.658247
CPCR           0.929995
bio_score      0.728345
batch_score    0.812965
joint_score    0.762193
dtype: float64

===== seed 6 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.10it/s]

100%|██████████| 2/2 [00:00<00:00,  3.99it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6463773559261968

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.5697567134645164

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5604808951226916

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6166554820708444

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5924755637569552

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5714686712984348

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.528878731029351

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.511135048822519

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5046214746451235

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.4973787348946686

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6463773559261968
BRAS...

seed           6.000000
BAMI           0.646377
CASW           0.530476
SCGRAPHM       0.993122
BRAS           0.856957
KBET           0.663507
CPCR           0.936177
bio_score      0.723325
batch_score    0.818880
joint_score    0.761547
dtype: float64

===== seed 7 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.05it/s]

100%|██████████| 2/2 [00:00<00:00,  3.91it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.665723126328717

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6766340083368887

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6592531043639841

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6294872451434035

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.59784641975272

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5866038206508581

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5445846122827509

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5217897962492215

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5209219122778476

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5075868521817569

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6766340083368887
BRAS...

seed           7.000000
BAMI           0.676634
CASW           0.530448
SCGRAPHM       0.993076
BRAS           0.846764
KBET           0.643758
CPCR           0.925136
bio_score      0.733386
batch_score    0.805219
joint_score    0.762119
dtype: float64

===== seed 8 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.09it/s]

100%|██████████| 2/2 [00:00<00:00,  3.97it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6491378152199017

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6396171223250844

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6472358330852892

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6323244570686453

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.588193279397736

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5508744133839724

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5267585458288206

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5169515748376853

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5091724683189132

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5048808803754968

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6491378152199017
BRAS...

seed           8.000000
BAMI           0.649138
CASW           0.530134
SCGRAPHM       0.993210
BRAS           0.850835
KBET           0.651395
CPCR           0.927727
bio_score      0.724161
batch_score    0.809986
joint_score    0.758491
dtype: float64

===== seed 9 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.11it/s]

100%|██████████| 2/2 [00:00<00:00,  4.00it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.601063452218974

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6525181272200067

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6513575908064231

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6356187473846601

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.6046909331047344

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.551983205593975

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5417480321462309

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5322012004237537

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5188381927514081

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5078841087323497

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6525181272200067
BRAS...

seed           9.000000
BAMI           0.652518
CASW           0.530515
SCGRAPHM       0.993106
BRAS           0.852617
KBET           0.666011
CPCR           0.929858
bio_score      0.725380
batch_score    0.816162
joint_score    0.761693
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.740218,0.530399,0.993097,0.856805,0.661709,0.935464,0.754571,0.817993,0.779940
1,1,0.668201,0.530105,0.993166,0.857608,0.666404,0.934814,0.730491,0.819609,0.766138
2,2,0.660527,0.530549,0.993138,0.856098,0.648722,0.933016,0.728071,0.812612,0.761888
3,3,0.659728,0.530430,0.993133,0.860721,0.651479,0.938369,0.727764,0.816856,0.763401
4,4,0.677875,0.530251,0.993172,0.855391,0.663827,0.933234,0.733766,0.817484,0.767253
5,5,0.661581,0.530323,0.993130,0.850653,0.658247,0.929995,0.728345,0.812965,0.762193
6,6,0.646377,0.530476,0.993122,0.856957,0.663507,0.936177,0.723325,0.818880,0.761547
7,7,0.676634,0.530448,0.993076,0.846764,0.643758,0.925136,0.733386,0.805219,0.762119
8,8,0.649138,0.530134,0.993210,0.850835,0.651395,0.927727,0.724161,0.809986,0.758491
9,9,0.652518,0.530515,0.993106,0.852617,0.666011,0.929858,0.725380,0.816162,0.761693

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.669280  0.025690  0.646377  0.740218
CASW         0.530363  0.000147  0.530105  0.530549
SCGRAPHM     0.993135  0.000037  0.993076  0.993210
BRAS         0.854445  0.003933  0.846764  0.860721
KBET         0.657506  0.007652  0.643758  0.666404
CPCR         0.932379  0.003912  0.925136  0.938369
bio_score    0.730926  0.008559  0.723325  0.754571
batch_score  0.814777  0.004317  0.805219  0.819609
joint_score  0.764466  0.005660  0.758491  0.779940