# Scanorama default - mouse_regulatory_T

Seeds: `0-9`

Metrics: BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR

This notebook is intentionally unexecuted.

In [1]:
import gc
import os
import sys

os.environ["PYTHONNOUSERSITE"] = "1"
sys.path = [
    path
    for path in sys.path
    if ".local/lib/python3.10/site-packages" not in path
]

PROJECT_ROOT = (
    "/ubc/cs/research/beaver/projects/"
    "Single-cell-integration-metrics"
)
os.environ["R_HOME"] = (
    f"{PROJECT_ROOT}/CondaEnv/harmony_optuna/lib/R"
)
sys.path.insert(0, f"{PROJECT_ROOT}/scib/")

import anndata as ad
import numpy as np
import pandas as pd
import scanorama
import scanpy as sc
import scipy.sparse as sp

from scib.metrics.metrics import metrics

In [2]:
DATASET_NAME = 'mouse_regulatory_T'
DATA_PATH = f"{PROJECT_ROOT}/data/{DATASET_NAME}.h5ad"
BATCH_KEY = 'method'
LABEL_KEY = 'cell.type'

SELECTED_BIO_METRICS = ('BAMI', 'CASW', 'SCGRAPHM')
SELECTED_BATCH_METRICS = ('BRAS', 'KBET', 'CPCR')
SELECTED_METRICS = SELECTED_BIO_METRICS + SELECTED_BATCH_METRICS

N_SEEDS = 10
N_NEIGHBORS = 15
N_TOP_HVG = 2000
INTERNAL_DIMRED = 50
BATCH_SIZE = 5000
APPROX = True
UNION = False

EMBED_KEY = "X_scanorama"
CLUSTER_KEY = "leiden_opt"
METRIC_BATCH_KEY = "scanorama_metric_batch"
METRIC_LABEL_KEY = "scanorama_metric_label"

assert DATASET_NAME == 'mouse_regulatory_T'
assert BATCH_KEY == 'method'
assert LABEL_KEY == 'cell.type'
assert SELECTED_METRICS == ('BAMI', 'CASW', 'SCGRAPHM', 'BRAS', 'KBET', 'CPCR')

pd.Series(
    {
        "dataset": DATASET_NAME,
        "data_path": DATA_PATH,
        "batch_key": BATCH_KEY,
        "label_key": LABEL_KEY,
        "metrics": list(SELECTED_METRICS),
        "seeds": list(range(N_SEEDS)),
        "internal_dimred": INTERNAL_DIMRED,
        "batch_size": BATCH_SIZE,
        "n_top_hvg": N_TOP_HVG,
    },
    name="configuration",
)

dataset                                           mouse_regulatory_T
data_path          /ubc/cs/research/beaver/projects/Single-cell-i...
batch_key                                                     method
label_key                                                  cell.type
metrics                     [BAMI, CASW, SCGRAPHM, BRAS, KBET, CPCR]
seeds                                 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
internal_dimred                                                   50
batch_size                                                      5000
n_top_hvg                                                       2000
Name: configuration, dtype: object

In [3]:
def validate_dataset_contents():
    adata_backed = ad.read_h5ad(DATA_PATH, backed="r")
    try:
        required_keys = (BATCH_KEY, LABEL_KEY)
        missing_keys = [
            key for key in required_keys if key not in adata_backed.obs
        ]
        if missing_keys:
            raise ValueError(
                f"Missing obs keys {missing_keys}. "
                f"Available keys: {list(adata_backed.obs.columns)}"
            )

        obs = adata_backed.obs[[BATCH_KEY, LABEL_KEY]].copy()
        pseudotime = None
        if "TRAJ" in SELECTED_METRICS:
            if "dpt_pseudotime" not in adata_backed.obs:
                raise ValueError(
                    "TRAJ requires adata.obs['dpt_pseudotime']."
                )
            pseudotime = adata_backed.obs["dpt_pseudotime"].copy()

        n_obs = int(adata_backed.n_obs)
        n_vars = int(adata_backed.n_vars)
    finally:
        adata_backed.file.close()

    if obs.isna().any().any():
        raise ValueError(
            "Missing batch/label values: "
            f"{obs.isna().sum().to_dict()}"
        )

    n_batches = int(obs[BATCH_KEY].nunique())
    n_labels = int(obs[LABEL_KEY].nunique())
    if n_batches < 2:
        raise ValueError(
            f"Batch metrics require at least 2 batches; found {n_batches}."
        )

    batch_coverage = obs.groupby(
        LABEL_KEY,
        observed=True,
    )[BATCH_KEY].nunique()
    label_counts = obs.groupby(LABEL_KEY, observed=True).size()

    if "TRAJ" in SELECTED_METRICS:
        finite_pseudotime = pseudotime.dropna()
        if (
            len(finite_pseudotime) < 2
            or finite_pseudotime.nunique() < 2
        ):
            raise ValueError(
                "TRAJ requires at least 2 usable pseudotime values."
            )

    if "ISOLISI" in SELECTED_METRICS:
        min_batch_coverage = int(batch_coverage.min())
        if min_batch_coverage >= n_batches:
            raise ValueError(
                "ISOLISI is enabled, but every label appears in all batches."
            )

    eligible_cpcr_labels = [
        str(label)
        for label in label_counts.index
        if int(label_counts.loc[label]) >= 100
        and int(batch_coverage.loc[label]) >= 2
    ]
    if "CPCR" in SELECTED_METRICS and not eligible_cpcr_labels:
        raise ValueError(
            "CPCR requires a label with at least 100 cells across "
            "at least 2 batches."
        )

    return {
        "n_obs": n_obs,
        "n_vars": n_vars,
        "n_batches": n_batches,
        "n_labels": n_labels,
        "cpcr_eligible_labels": len(eligible_cpcr_labels),
    }


validate_dataset_contents()

{'n_obs': 34697,
 'n_vars': 11765,
 'n_batches': 2,
 'n_labels': 3,
 'cpcr_eligible_labels': 2}

In [4]:
SCANORAMA_PARAMS = {'knn': 20, 'sigma': 15.0, 'alpha': 0.1}
assert tuple(SCANORAMA_PARAMS) == ("knn", "sigma", "alpha")

pd.Series(
    {
        **SCANORAMA_PARAMS,
        "batch_size": BATCH_SIZE,
        "approx": APPROX,
        "union": UNION,
        "internal_dimred": INTERNAL_DIMRED,
        "n_top_hvg": N_TOP_HVG,
    },
    name="default_setting",
)

def check_keys(adata):
    missing_keys = [
        key
        for key in (BATCH_KEY, LABEL_KEY)
        if key not in adata.obs
    ]
    if missing_keys:
        raise ValueError(
            f"Missing keys in adata.obs: {missing_keys}. "
            f"Available keys: {list(adata.obs.columns)}"
        )


def ensure_csr(matrix):
    if sp.issparse(matrix):
        return matrix.tocsr()
    return sp.csr_matrix(matrix)


def split_by_batch(adata):
    batches = adata.obs[BATCH_KEY].astype("category")
    batch_names = list(batches.cat.categories)
    parts = []
    index_parts = []

    for batch_name in batch_names:
        indices = np.where(batches.values == batch_name)[0]
        index_parts.append(indices)
        parts.append(adata[indices, :].copy())

    return parts, batch_names, index_parts


def hvg_subset(adata):
    if "highly_variable" not in adata.var:
        sc.pp.highly_variable_genes(
            adata,
            flavor="seurat",
            n_top_genes=N_TOP_HVG,
        )

    hvg_mask = (
        adata.var["highly_variable"]
        .fillna(False)
        .astype(bool)
        .to_numpy()
    )
    if int(hvg_mask.sum()) == 0:
        raise ValueError("No highly variable genes selected.")
    return adata[:, hvg_mask].copy()


def reassemble_scanorama_embedding(parts, index_parts, n_obs):
    embedding_concat = np.concatenate(
        [part.obsm[EMBED_KEY] for part in parts],
        axis=0,
    )
    concat_indices = np.concatenate(index_parts)
    inverse = np.empty(n_obs, dtype=np.int64)
    inverse[concat_indices] = np.arange(n_obs, dtype=np.int64)
    return embedding_concat[inverse, :]


def run_scanorama_setting(adata, seed):
    np.random.seed(seed)
    check_keys(adata)

    adata_work = hvg_subset(adata.copy())
    adata_work.X = ensure_csr(adata_work.X)
    parts, batch_names, index_parts = split_by_batch(adata_work)

    scanorama.integrate_scanpy(
        parts,
        batch_size=BATCH_SIZE,
        verbose=0,
        ds_names=batch_names,
        dimred=INTERNAL_DIMRED,
        approx=APPROX,
        sigma=float(SCANORAMA_PARAMS["sigma"]),
        alpha=float(SCANORAMA_PARAMS["alpha"]),
        knn=int(SCANORAMA_PARAMS["knn"]),
        union=UNION,
        hvg=None,
        seed=int(seed),
    )

    embedding = reassemble_scanorama_embedding(
        parts,
        index_parts,
        n_obs=adata_work.n_obs,
    )
    if embedding.shape[0] != adata_work.n_obs:
        raise ValueError(
            f"Scanorama output shape {embedding.shape} is incompatible "
            f"with n_obs={adata_work.n_obs}."
        )
    if not np.all(np.isfinite(embedding)):
        raise ValueError(
            "Scanorama produced NaN or Inf in X_scanorama."
        )

    adata_int = adata_work.copy()
    adata_int.obsm[EMBED_KEY] = np.asarray(
        embedding,
        dtype=np.float32,
    )
    return adata_int

In [5]:
def metric_value(metric_series, key):
    if key not in metric_series.index:
        raise KeyError(
            f"Metric {key} not found. "
            f"Available metrics: {list(metric_series.index)}"
        )

    value = metric_series[key]
    if isinstance(value, (list, tuple, np.ndarray)):
        values = np.asarray(value, dtype=float)
        if values.size == 0 or not np.all(np.isfinite(values)):
            raise ValueError(
                f"Metric {key} returned non-finite values: {values}"
            )
        return float(np.mean(values))

    value = float(value)
    if not np.isfinite(value):
        raise ValueError(
            f"Metric {key} returned a non-finite value: {value}"
        )
    return value


def compute_joint_metrics(adata_raw, adata_int):
    sc.pp.neighbors(
        adata_int,
        use_rep=EMBED_KEY,
        n_neighbors=N_NEIGHBORS,
        random_state=0,
    )

    metric_key_map = {
        METRIC_BATCH_KEY: BATCH_KEY,
        METRIC_LABEL_KEY: LABEL_KEY,
    }
    for adata_name, adata_obj in (
        ("adata_raw", adata_raw),
        ("adata_int", adata_int),
    ):
        existing_aliases = [
            alias for alias in metric_key_map if alias in adata_obj.obs
        ]
        if existing_aliases:
            raise ValueError(
                f"Reserved metric obs keys already exist in {adata_name}: "
                f"{existing_aliases}"
            )
        for alias, source_key in metric_key_map.items():
            adata_obj.obs[alias] = adata_obj.obs[source_key].copy()

    metric_df = metrics(
        adata=adata_raw,
        adata_int=adata_int,
        batch_key=METRIC_BATCH_KEY,
        label_key=METRIC_LABEL_KEY,
        embed=EMBED_KEY,
        cluster_key=CLUSTER_KEY,
        verbose=False,
        bami_="BAMI" in SELECTED_METRICS,
        casw_="CASW" in SELECTED_METRICS,
        scgraphm_="SCGRAPHM" in SELECTED_METRICS,
        traj_="TRAJ" in SELECTED_METRICS,
        isolisi_="ISOLISI" in SELECTED_METRICS,
        bras_="BRAS" in SELECTED_METRICS,
        kbet_="KBET" in SELECTED_METRICS,
        cpcr_="CPCR" in SELECTED_METRICS,
    )
    metric_series = metric_df.iloc[:, 0]

    result = {
        key: metric_value(metric_series, key)
        for key in SELECTED_METRICS
    }
    bio_score = float(
        np.mean([result[key] for key in SELECTED_BIO_METRICS])
    )
    batch_score = float(
        np.mean([result[key] for key in SELECTED_BATCH_METRICS])
    )
    joint_score = float(0.6 * bio_score + 0.4 * batch_score)

    if not np.all(np.isfinite([bio_score, batch_score, joint_score])):
        raise ValueError(
            "Aggregation produced a non-finite score: "
            f"bio={bio_score}, batch={batch_score}, "
            f"joint={joint_score}"
        )

    result["bio_score"] = bio_score
    result["batch_score"] = batch_score
    result["joint_score"] = joint_score
    return result

In [6]:
results = []

for seed in range(N_SEEDS):
    print(f"\n===== seed {seed} =====", flush=True)

    adata_raw = ad.read_h5ad(DATA_PATH)
    adata_int = run_scanorama_setting(adata_raw, seed=seed)
    metric_result = compute_joint_metrics(adata_raw, adata_int)

    row = {"seed": seed, **metric_result}
    results.append(row)
    print(pd.Series(row), flush=True)

    del adata_raw, adata_int
    gc.collect()

results_df = pd.DataFrame(results)
results_df

===== seed 0 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.90it/s]

100%|██████████| 2/2 [00:00<00:00,  3.58it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/scib/scib/metrics/clustering.py:105: FutureWarning: In the future, the default backend for leiden will be igraph instead of leidenalg.

 To achieve the future defaults please pass: flavor="igraph" and n_iterations=2.  directed must also be False to work with igraph's implementation.
  cluster_function(adata, resolution=res, key_added=resolution_key, **kwargs)

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/pyximport/pyximport.py:51: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:671: ImportWarning: PyxLoader.exec_module() not found; falling back to load_module()
/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py:15: DeprecationWarning: dep_util is Deprecated. Use functions from setuptools instead.
  from distutils.dep_util import newer, newer_group

resolution: 0.2, bAMI: 0.5872129549294282

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6661851611200721

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6471374394885745

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6173399715319363

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5908791007958474

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5590871407457793

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5394483167080374

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5253026915692186

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5102703224132358

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5119824730585072

<frozen importlib._bootstrap>:914: ImportWarning: PyxImporter.find_spec() not found; falling back to find_module()
WARNING:2026-07-26 16:11:50,399:jax._src.xla_bridge:794: An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6661851611200721
BRAS...

seed           0.000000
BAMI           0.666185
CASW           0.530408
SCGRAPHM       0.993077
BRAS           0.850628
KBET           0.665659
CPCR           0.934629
bio_score      0.729890
batch_score    0.816972
joint_score    0.764723
dtype: float64

===== seed 1 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.08it/s]

100%|██████████| 2/2 [00:00<00:00,  3.94it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6091881214946463

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6584123494198998

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6626206789523709

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6225072625072949

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5991793325435341

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5408436307890006

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5414780267013767

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5278508474791455

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5143161494821405

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5091819211527538

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.6
optimal score: 0.6626206789523709
BRAS...

seed           1.000000
BAMI           0.662621
CASW           0.530099
SCGRAPHM       0.993142
BRAS           0.849692
KBET           0.666999
CPCR           0.932748
bio_score      0.728621
batch_score    0.816480
joint_score    0.763764
dtype: float64

===== seed 2 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.10it/s]

100%|██████████| 2/2 [00:00<00:00,  3.99it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.615226577378373

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6789712862809607

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6600587542636656

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.629886617022106

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5816716823573614

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5411477317475388

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5212459869242504

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5173268542432414

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5139512138681968

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5095038294363093

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6789712862809607
BRAS...

seed           2.000000
BAMI           0.678971
CASW           0.530511
SCGRAPHM       0.993120
BRAS           0.849248
KBET           0.652065
CPCR           0.931324
bio_score      0.734201
batch_score    0.810879
joint_score    0.764872
dtype: float64

===== seed 3 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.13it/s]

100%|██████████| 2/2 [00:00<00:00,  4.04it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6563202594549238

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7020270927432894

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6468510396790935

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6264975762805957

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5554782141695525

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5599032306734752

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5395752809475785

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5236858178088385

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5038418976111355

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.501487369303687

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7020270927432894
BRAS...

seed           3.000000
BAMI           0.702027
CASW           0.530385
SCGRAPHM       0.993109
BRAS           0.851664
KBET           0.655613
CPCR           0.934924
bio_score      0.741840
batch_score    0.814067
joint_score    0.770731
dtype: float64

===== seed 4 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.09it/s]

100%|██████████| 2/2 [00:00<00:00,  3.99it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6610221588464753

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.602726291624577

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6560196208507929

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6056601280506609

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5705623033280469

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5493395448230828

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5336753902515087

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5295142317290765

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5223995332283414

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5103383240730164

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6610221588464753
BRAS...

seed           4.000000
BAMI           0.661022
CASW           0.530253
SCGRAPHM       0.993148
BRAS           0.849389
KBET           0.670869
CPCR           0.933096
bio_score      0.728141
batch_score    0.817785
joint_score    0.763998
dtype: float64

===== seed 5 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.07it/s]

100%|██████████| 2/2 [00:00<00:00,  3.94it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6537651145886061

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6332898265943285

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6522781029403999

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6156434205944692

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5905691511710012

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5551832894604923

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5427445178521391

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5271554040645312

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5066554611153213

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.49757511893155515

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6537651145886061
BRAS...

seed           5.000000
BAMI           0.653765
CASW           0.530277
SCGRAPHM       0.993107
BRAS           0.843283
KBET           0.655384
CPCR           0.926840
bio_score      0.725716
batch_score    0.808502
joint_score    0.758831
dtype: float64

===== seed 6 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.12it/s]

100%|██████████| 2/2 [00:00<00:00,  4.03it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6506980242243221

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.566016308740434

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.5632654068577098

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.5442360610489089

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5351623712551337

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5400689551721

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5319457231821927

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5178390940046644

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5140485870612557

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5064743547307344

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.2
optimal score: 0.6506980242243221
BRAS...

seed           6.000000
BAMI           0.650698
CASW           0.530452
SCGRAPHM       0.993105
BRAS           0.850719
KBET           0.661071
CPCR           0.934575
bio_score      0.724752
batch_score    0.815455
joint_score    0.761033
dtype: float64

===== seed 7 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.08it/s]

100%|██████████| 2/2 [00:00<00:00,  3.95it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6569680945209466

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.7064787668414503

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.656580819502007

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6162215330656285

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5978357445235704

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5530488620480796

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5458567975678108

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5278729709091768

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5187252008500153

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5148081804154754

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.7064787668414503
BRAS...

seed           7.000000
BAMI           0.706479
CASW           0.530468
SCGRAPHM       0.993070
BRAS           0.840453
KBET           0.648660
CPCR           0.924164
bio_score      0.743339
batch_score    0.804426
joint_score    0.767774
dtype: float64

===== seed 8 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  2.12it/s]

100%|██████████| 2/2 [00:00<00:00,  4.03it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6476784979897259

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6526037865876287

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6522449736549979

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6416996539572115

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5847455404114642

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5513933650746243

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5277781255521817

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.51946679495758

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5100828425271698

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5056577151625201

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6526037865876287
BRAS...

seed           8.000000
BAMI           0.652604
CASW           0.530125
SCGRAPHM       0.993187
BRAS           0.843403
KBET           0.650210
CPCR           0.925886
bio_score      0.725305
batch_score    0.806500
joint_score    0.757783
dtype: float64

===== seed 9 =====

After 10x: 1752 genes
After smart-seq2: 1752 genes
Found 1752 genes among all datasets

Cell type silhouette score...

Per cell type PC regression...
Skipping NKT as it has <2 batches.

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

/ubc/cs/research/beaver/projects/Single-cell-integration-metrics/CondaEnv/harmony_optuna/lib/python3.10/site-packages/scanpy/preprocessing/_pca/__init__.py:226: FutureWarning: Argument `use_highly_variable` is deprecated, consider using the mask argument. Use_highly_variable=True can be called through mask_var="highly_variable". Use_highly_variable=False can be called through mask_var=None
  mask_var_param, mask_var = _handle_mask_var(

scGraph with Fisher multinomial distance...
Processing batches using Fisher information metric and pairwise distances

  0%|          | 0/2 [00:00<?, ?it/s]

 50%|█████     | 1/2 [00:00<00:00,  1.99it/s]

100%|██████████| 2/2 [00:00<00:00,  3.79it/s]

kBET...
1 labels consist of a single batch or is too small. Skip.

Balanced AMI...
Cluster for leiden_opt_0.2 with leiden

resolution: 0.2, bAMI: 0.6500241734493687

Cluster for leiden_opt_0.4 with leiden

resolution: 0.4, bAMI: 0.6628653719208277

Cluster for leiden_opt_0.6 with leiden

resolution: 0.6, bAMI: 0.6353319982197398

Cluster for leiden_opt_0.8 with leiden

resolution: 0.8, bAMI: 0.6165270859574695

Cluster for leiden_opt_1.0 with leiden

resolution: 1.0, bAMI: 0.5989991251871393

Cluster for leiden_opt_1.2 with leiden

resolution: 1.2, bAMI: 0.5589055354457317

Cluster for leiden_opt_1.4 with leiden

resolution: 1.4, bAMI: 0.5418108382537077

Cluster for leiden_opt_1.6 with leiden

resolution: 1.6, bAMI: 0.5333585715905822

Cluster for leiden_opt_1.8 with leiden

resolution: 1.8, bAMI: 0.5289911605244283

Cluster for leiden_opt_2.0 with leiden

resolution: 2.0, bAMI: 0.5130353412700158

optimised clustering against scanorama_metric_label
optimal cluster resolution: 0.4
optimal score: 0.6628653719208277
BRAS...

seed           9.000000
BAMI           0.662865
CASW           0.530511
SCGRAPHM       0.993080
BRAS           0.845107
KBET           0.664092
CPCR           0.927692
bio_score      0.728819
batch_score    0.812297
joint_score    0.762210
dtype: float64

,seed,BAMI,CASW,SCGRAPHM,BRAS,KBET,CPCR,bio_score,batch_score,joint_score
0,0,0.666185,0.530408,0.993077,0.850628,0.665659,0.934629,0.729890,0.816972,0.764723
1,1,0.662621,0.530099,0.993142,0.849692,0.666999,0.932748,0.728621,0.816480,0.763764
2,2,0.678971,0.530511,0.993120,0.849248,0.652065,0.931324,0.734201,0.810879,0.764872
3,3,0.702027,0.530385,0.993109,0.851664,0.655613,0.934924,0.741840,0.814067,0.770731
4,4,0.661022,0.530253,0.993148,0.849389,0.670869,0.933096,0.728141,0.817785,0.763998
5,5,0.653765,0.530277,0.993107,0.843283,0.655384,0.926840,0.725716,0.808502,0.758831
6,6,0.650698,0.530452,0.993105,0.850719,0.661071,0.934575,0.724752,0.815455,0.761033
7,7,0.706479,0.530468,0.993070,0.840453,0.648660,0.924164,0.743339,0.804426,0.767774
8,8,0.652604,0.530125,0.993187,0.843403,0.650210,0.925886,0.725305,0.806500,0.757783
9,9,0.662865,0.530511,0.993080,0.845107,0.664092,0.927692,0.728819,0.812297,0.762210

In [7]:
score_columns = [
    *SELECTED_METRICS,
    "bio_score",
    "batch_score",
    "joint_score",
]

summary_df = pd.DataFrame(
    {
        "mean": results_df[score_columns].mean(),
        "std": results_df[score_columns].std(ddof=0),
        "min": results_df[score_columns].min(),
        "max": results_df[score_columns].max(),
    }
)
summary_df

                 mean       std       min       max
BAMI         0.669724  0.018909  0.650698  0.706479
CASW         0.530349  0.000145  0.530099  0.530511
SCGRAPHM     0.993115  0.000034  0.993070  0.993187
BRAS         0.847359  0.003724  0.840453  0.851664
KBET         0.659062  0.007323  0.648660  0.670869
CPCR         0.930588  0.003852  0.924164  0.934924
bio_score    0.731062  0.006318  0.724752  0.743339
batch_score  0.812336  0.004411  0.804426  0.817785
joint_score  0.763572  0.003694  0.757783  0.770731